contributors.csv

contributors.csv: fix email address

---

gui/wxpython/dbmgr/dialogs.py
gui/wxpython/vdigit/wxdigit.py
gui/wxpython/vdigit/wxdisplay.py

https://trac.osgeo.org/grass/ticket/3777

wxGUI/digitizer: fixes for python 3

---

doc/howto_release.txt
include/Make/Docs.make
tools/gitlog2changelog.py

Source: https://github.com/networkupstools/nut/blob/master/tools/gitlog2changelog.py

new gitlog2changelog script and svn2cl cleanup

---

.github/FUNDING.yml

This PR adds a sponsorship button to the repo, pointing to our moneypool.

added .github/FUNDING.yml

---

README.md

... could be more of course, but intended as a start.

Draft intro added

---

scripts/r.in.wms/r.in.wms.py
scripts/r.in.wms/wms_base.py
scripts/r.in.wms/wms_gdal_drv.py

- A http proxy is added only for the download with the GDAL driver
- not for GetCapabilities

r.in.wms: add proxy for GDAL driver

---

locale/po/grassmods_fr.po

contributed by Sylvain Maillard

i18N: sync from Transifex

---

raster/r.out.gdal/r.out.gdal.html

Add BIGTIFF issue to the docs.
Fix https://trac.osgeo.org/grass/ticket/3859

r.out.gdal add bigtiff docs

---

scripts/v.db.addtable/v.db.addtable.py
vector/v.db.connect/main.c
vector/v.voronoi/defs.h
vector/v.voronoi/main.c
vector/v.voronoi/sw_defs.h
vector/v.voronoi/sw_main.c
vector/v.voronoi/v.voronoi.html
vector/v.voronoi/vo_extend.c
vector/v.voronoi/vo_write.c

Incomplete fix for skeletons and voronoi diagrams for areas.
The skeletons are sometimes still a mess, but this is due to numerical instability in v.voronoi.
The voronoi diagrams for areas need more cleaning up, thus this is an incomplete fix.

v.voronoi for areas

---

vector/vectorintro.html

Interestingly, that was never clearly explained...

Tell the users what the default SQL DB backend is

---

AUTHORS
INSTALL
REQUIREMENTS.html
Vagrantfile
doc/howto_release.txt
doc/infrastructure.txt
gui/wxpython/gmodeler/g.gui.gmodeler.html
lib/cdhc/README
tools/vagrant/compile.sh
vector/v.in.ogr/v.in.ogr.html

Continuation of https://trac.osgeo.org/grass/wiki/GitMigration#Aftermathcleanup work

Further svn2git updates

---

docker/Dockerfile_alpine
docker/README_alpine.md

Dockerfile with an Alpine Linux image with GRASS GIS and grass-session.
Based on: https://github.com/zarch/docker-alpine-grass-gis

Minimalistic docker image based on Alpine

---

imagery/i.vi/i.vi.html
imagery/i.vi/main.c
imagery/i.vi/ndwi.c
imagery/i.vi/testsuite/test_vi.py

NDWI (Normalized Difference Water Index) after McFeeters (1996), https://doi.org/10.3390/rs5073544

NDWI index added

---

gui/wxpython/lmgr/menudata.py

https://trac.osgeo.org/grass/ticket/3867

wxGUI: fix typo reported in #3867

---

lib/python/script/task.py

format function should be called on translatable string which is unicode

fix encoding error in https://trac.osgeo.org/grass/ticket/3867

---

gui/wxpython/datacatalog/tree.py

Allows to manipulate multiple selected layers at once.

Data catalog: multiple layer selection

---

docker/Dockerfile_alpine_wxgui

Based on https://github.com/OSGeo/grass/blob/master/docker/Dockerfile_alpine

Alpine docker image with wxGUI

---

display/d.barscale/main.c

font support added, inspired by d.northarrow

d.barscale: font support added

---

scripts/g.extension/g.extension.py

Addresses https://trac.osgeo.org/grass/ticket/3455 for relbranch76

update base_url to current server layout

---

config.guess
config.sub
configure
doc/howto_release.txt

config.guess + config.sub: updated from http://git.savannah.gnu.org/cgit/config.git/plain/
(as per doc/howto_release.txt)

configure update 

---

config.guess
config.sub
configure
doc/howto_release.txt

config.guess + config.sub: updated from http://git.savannah.gnu.org/cgit/config.git/plain/
(as per doc/howto_release.txt)

configure update

---

docker/Dockerfile_alpine
docker/Dockerfile_alpine_wxgui

removed as https://github.com/OSGeo/grass/pull/75 was merged

remove now unneeded Python 3 shebang trick

---

lib/python/pygrass/rpc/base.py

This patch fixes the warning messages of the pygrass rpc server, that warns if the libgis server must be restarted. The warning is only displayed, if the server was terminated abnormally.

Fixed the pygrass rpc server to avoid wrong restart warnings

---

vector/v.patch/main.c

Now the module not only complains, but also provides
some basic info about what is wrong for missing table,
different key column (name), types and number of columns
(which reports, however, still just the numbers, not the actual difference).

v.patch: add details into error messages

---

raster/r.slope.aspect/main.c

r.slope.aspect: Fix directions in comments

---

temporal/t.rast.algebra/t.rast.algebra.html
temporal/temporalintro.html

- refs published by S Gebbert added
- update pip install cmd to Python 3

Refs by S Gebbert added

---

gui/wxpython/mapdisp/main.py

solves:
https://trac.osgeo.org/grass/ticket/3896
https://trac.osgeo.org/grass/ticket/3897
https://trac.osgeo.org/grass/ticket/3898

wxGUI: fix d.mon for py3

---

scripts/i.band/i.band.py

`i.band` is currently only one module which requires numpy for compilation. This PR fixes this issue by lazy import.

i.band: lazy np import

---

gui/wxpython/gui_core/gselect.py
gui/wxpython/gui_core/wrap.py
gui/wxpython/psmap/dialogs.py
gui/wxpython/psmap/frame.py
gui/wxpython/psmap/instructions.py

https://trac.osgeo.org/grass/ticket/3906

g.gui.psmap: fixes for Python3

---

gui/wxpython/gui_core/ghelp.py

Small improvements in wxGUI About window:
* change website url to https
* add link to github (code revision)

wxgui about: add link to github

---

README.md
raster/r.to.vect/lines.c

https://trac.osgeo.org/grass/attachment/ticket/2649/lines.c.patch

r.to.vect: break line when value changes

---

docker/Dockerfile_ubuntu_pdal

Readds the ubuntu based Dockerfile.
@neteler You'll probably need to adapt the build on Dockerhub. It would also be great to get a Dockerhub build for the Debian based image.

Readd the ubuntu based Dockerfile

---

docker/Dockerfile_ubuntu_pdal

Readds the ubuntu based Dockerfile.
@neteler You'll probably need to adapt the build on Dockerhub. It would also be great to get a Dockerhub build for the Debian based image.

Readd ubuntu dockerfile (7.8 releasebranch)

---

docker/Dockerfile_debian_pdal

Add locale

---

gui/wxpython/animation/controller.py
gui/wxpython/gui_core/wrap.py

https://trac.osgeo.org/grass/ticket/3895

wxGUI/animation: fix deprecation warnings

---

raster/r.slope.aspect/main.c

fix -e flag to calculate values at edges

r.slope.aspect

---

imagery/i.vi/main.c

Fixes https://trac.osgeo.org/grass/ticket/3932

i.vi: red band not required and GUI section modified

---

configure
configure.in

check if share/proj/epsg exists only for PROJ < 6

proj 6+ support

---

vector/v.out.ogr/main.c

export datetime attributes as datetime

v.out.ogr: export datetime attributes as datetime

---

singularity/debian/README_debian.md
singularity/debian/singularityfile_debian

Support for singularity container technology (https://wiki.debian.org/singularity)

added singularity file

---

lib/raster/gdal.c

gdal.c: add .so/.dll for GDAL 3.0

---

raster/r.geomorphon/main.c
raster/r.geomorphon/multires.c

r.geomorphon

---

gui/wxpython/dbmgr/base.py
gui/wxpython/gcp/manager.py
gui/wxpython/gis_set.py
gui/wxpython/gmodeler/dialogs.py
gui/wxpython/gui_core/preferences.py
gui/wxpython/gui_core/vselect.py
gui/wxpython/gui_core/widgets.py
gui/wxpython/gui_core/wrap.py
gui/wxpython/iclass/dialogs.py
gui/wxpython/image2target/ii2t_gis_set.py
gui/wxpython/image2target/ii2t_manager.py
gui/wxpython/iscatt/frame.py
gui/wxpython/location_wizard/wizard.py
gui/wxpython/modules/extensions.py
gui/wxpython/photo2image/ip2i_manager.py
gui/wxpython/psmap/dialogs.py
gui/wxpython/vdigit/dialogs.py
gui/wxpython/vnet/dialogs.py
gui/wxpython/vnet/widgets.py

This fixes https://trac.osgeo.org/grass/ticket/3944, also uses wrapper of wx.ListCtrl everywhere

Fix missing checkboxes in ListCtrl

---

lib/python/script/core.py

Removing the 7.0.0 backwards compatibility from run_command()
which was raising exception on error but returning 0 on success.
Adding option to use the standard fatal() error handling
which might be good for use within GRASS GIS code itself.
Adding extensive documentation for the available options
and linking all relevant functions.
Also passing module name explicitly to CalledModuleError
as a parameter.
It also propagates the return code.
Things such as Jupyter Notebooks now don't have a `0` after every (cell ending with) `run_command()`  and thus look cleaner.

pythonlib: return None from run_command()

---

CONTRIBUTING.md
SUBMITTING

I'm not making changes to README at this point and I'm leaving there a legacy SUBMITING file.

Add CONTRIBUTING file with a standard contributor Git how-to

---

Dockerfile

Add missing python3-wxgtk deb package in the Dockerfile.

Add python3-wxgtk deb package in the Dockerfile

---

raster/r.sim/simlib/hydro.c
raster/r.sim/simlib/input.c
raster/r.sim/simlib/output.c
raster/r.sim/simlib/simlib.h
raster/r.sim/simlib/waterglobs.h

This avoids hard coded limitation of 7mil walkers.

r.sim: dynamic allocation of walkers

---

gui/wxpython/core/globalvar.py

Parsing in a separate function with tests.
Redo error messages to make them more robust supporting also 3-digit versions.
This completely replaces #240.

wxGUI/core: account for .post in wxPython 4.0.7.post2

---

rpm/grass-7.8.0-buildroot.diff
rpm/grass.spec

Fedora SPEC file: updated to https://src.fedoraproject.org/rpms/grass

Fedora SPEC file: updated

---

docker/ubuntu/Dockerfile_ubuntu_latest_pdal
docker/ubuntu/README_ubuntu.md

Ubuntu 19:10 offers PROJ 5, GDAL 2.4, PDAL 1.9, no more need to compile in the Dockerfile

docker: image with Ubuntu 19:10

---

doc/projectionintro.html
general/g.proj/g.proj.html
general/g.setproj/g.setproj.html
raster/r.in.lidar/r.in.lidar.html
raster/r.latlong/r.latlong.html
raster/r.proj/r.proj.html
raster3d/r3.in.lidar/r3.in.lidar.html
raster3d/r3.out.netcdf/r3.out.netcdf.html
scripts/m.proj/m.proj.html
temporal/t.rast.export/t.rast.export.html
temporal/t.vect.export/t.vect.export.html
vector/v.in.lidar/v.in.lidar.html
vector/v.out.lidar/v.out.lidar.html
vector/v.proj/v.proj.html

Replacement of outdated links and naming

manual: PROJ related links update

---

lib/vector/Vlib/cats.c
vector/v.buffer/main.c
vector/v.decimate/main.c
vector/v.out.lidar/main.c
vector/v.random/main.c
vector/v.vect.stats/main.c

fix usage of Vect_cats_in_constraint()

fix usage of vector cats in constraint

---

mswindows/crosscompile.sh

- Rename ``--mxe`` option to ``--mxe-path``
- Rename local variables to lowercase
- Add 2020 to copyright

Change local variable names to lowercase

---

lib/python/script/vector.py

Expose h-flag to function in Python Library
Feel free to close the PR without merging if you consider this less relevant

allow to overwrite command history

---

gui/wxpython/gui_core/dialogs.py
lib/python/script/core.py

* fix wx depracated warnings
* d.text depends on region, region needs to match widget size
* close file in grass.script.region_env to avoid Py3 ResourceWarning

several fixes related to font dialog

---

gui/wxpython/animation/nviztask.py
gui/wxpython/animation/provider.py

Broken because of ea51ed82995, color_map needs to be always present.

fix 3D rendering in animation tool

---

raster/r.proj/r.proj.html

nice overview about projections, conversions, transformations, pipeline operator available in the new PROJ library generation

add link to coordinate operations by PROJ library in r.proj

---

vector/v.proj/v.proj.html

nice overview about projections, conversions, transformations, pipeline operator available in the new PROJ library generation

add link to coordinate operations by PROJ library in v.proj

---

doc/projectionintro.html

nice overview about projections, conversions, transformations, pipeline operator available in the new PROJ library generation

add link to coordinate operations by PROJ library in projectionintro

---

Dockerfile

Add missing python3-gdal package required for the add web services layer

Add missing add web services layer required package in the Dockerfile

---

raster/r.slope.aspect/main.c

Fixes wrong title in #319, also sets better color table.

r.slope.aspect: fix title and color table for -n flag

---

raster/r.kappa/prt_mat.c
raster/r.kappa/stats.c

var fix addresses comment in #290

r.kappa: better user msg; fix var

---

lib/init/grass.sh

grass.sh: enforce Python 3

---

scripts/r.blend/testsuite/test_r_blend_quoting.py

Added test script which implements the test suggested in PR #277
Please check, @marisn

testsuite: r.blend quoting test

---

gui/wxpython/dbmgr/base.py
gui/wxpython/dbmgr/dialogs.py
gui/wxpython/dbmgr/vinfo.py
gui/wxpython/gui_core/goutput.py

https://trac.osgeo.org/grass/ticket/4022

Fix dbmgr for Python3

---

scripts/v.rast.stats/testsuite/test_v_rast_stats.py
scripts/v.rast.stats/v.rast.stats.py

should fix #372
Testing right now.

fix position of null cells

---

vector/v.patch/main.c

* v.patch: Fix topology build
* Fix area topology

v.patch: Fix line categories when building topology (#374)

---

scripts/i.pansharpen/i.pansharpen.py

i.pansharpen: grass.decode stdout

---

scripts/g.extension/g.extension.py

See: https://github.com/OSGeo/grass-addons/issues/118 and https://github.com/OSGeo/grass-addons/pull/119

g.extension: dont expand db modul class

---

gui/wxpython/lmgr/layertree.py
gui/wxpython/mapdisp/frame.py
gui/wxpython/mapdisp/test_mapdisp.py
gui/wxpython/wxplot/base.py
gui/wxpython/wxplot/dialogs.py
gui/wxpython/wxplot/histogram.py
gui/wxpython/wxplot/profile.py
gui/wxpython/wxplot/scatter.py

Also fixes closing of wxplot settings dialogs.

wxplot: add giface to write log correctly

---

gui/wxpython/gui_core/ghelp.py

Fix import wx widget class according different wxPython version (classic/phoenix).

Fix wxGUI Graphical Modeler About Dialog import

---

db/drivers/postgres/describe.c

postgres: Assign 1000 to TEXT field length (#412)

---

mswindows/osgeo4w/package.sh
mswindows/osgeo4w/preremove.bat
mswindows/osgeo4w/python-grass.bat.tmpl

Inspired by `python-qgis.bat` to allow GRASS initialization in editors like PyCharm.

add python-grass.bat for Python initialization

---

gui/wxpython/gmodeler/model.py

Fix wxGUI Graphical Modeler decode string

---

gui/wxpython/lmgr/layertree.py

See https://trac.osgeo.org/grass/ticket/3607

Removing map layer crashes wxGUI (trac.osgeo.org/grass/ticket/3607)

---

vector/v.edit/v.edit.html

v.edit: Change -t to -b in the manual

---

vector/v.generalize/v.generalize.html

remove_small was removed in https://lists.osgeo.org/pipermail/grass-commit/2011-January/015843.html

v.generalize: remove_small is no longer available

---

general/g.version/main.c

See https://github.com/OSGeo/grass/pull/325#issuecomment-607553432

g.version: strstr -> strchr

---

vector/v.to.db/main.c

Don't delete support files when writing history!

v.to.db history support files

---

locale/po/grasswxpy_bn.po
locale/po/grasswxpy_cs.po
locale/po/grasswxpy_de.po
locale/po/grasswxpy_el.po
locale/po/grasswxpy_es.po
locale/po/grasswxpy_fi.po
locale/po/grasswxpy_fr.po
locale/po/grasswxpy_hu.po
locale/po/grasswxpy_id_ID.po
locale/po/grasswxpy_it.po
locale/po/grasswxpy_ja.po
locale/po/grasswxpy_ko.po
locale/po/grasswxpy_lv.po
locale/po/grasswxpy_ml.po
locale/po/grasswxpy_pl.po
locale/po/grasswxpy_pt.po
locale/po/grasswxpy_pt_BR.po
locale/po/grasswxpy_ro.po
locale/po/grasswxpy_ru.po
locale/po/grasswxpy_si.po
locale/po/grasswxpy_ta.po
locale/po/grasswxpy_th.po
locale/po/grasswxpy_tr.po
locale/po/grasswxpy_uk.po
locale/po/grasswxpy_vi.po
locale/po/grasswxpy_zh.po
locale/po/grasswxpy_zh_CN.po

- also fix all .po files
Completes #553

NVIZ: Fix a typo (cont'ed)

---

configure
configure.in

Cross-platform version of date -Iseconds in configure

---

.github/workflows/apt.txt
.github/workflows/test_thorough.sh

This adds numpy and other Python packages to GitHub Actions using apt.

Add numpy and other Python pkgs to CI

---

docker/README.md

Version matrix with base image, GRASS GIS, PROJ, GDAL and PDAL versions and docker image size

docker: version matrix added

---

gui/wxpython/mapdisp/frame.py
gui/wxpython/vdigit/toolbars.py

wxGUI mapwin: Fix show/hide vdigit toolbar

---

macosx/ReadMe.md

Just some stylistic updates to the newly converted readme for mac.

Mac ReadMe: stylistic update

---

vector/v.category/main.c

v.category: message fix

---

scripts/r.in.wms/r.in.wms.py

Mention what -c does with what it gets.

r.in.wms: message update

---

gui/wxpython/location_wizard/wizard.py

wxGUI loc wizard: fix title layout, bug introduced in changes for wx 4.1

---

gui/wxpython/web_services/widgets.py

To reproduce:
1. Add some web service map layer via wxGUI Add web service layer dialog
2. Open web service map layer properties dialog (double click on the added web service map layer)

wxGUI WSPropertiesDialog: Fix select layer if the web service map layer properties dialog is open

---

scripts/r.in.wms/wms_cap_parsers.py

Fix bug introduced in the issue #622. Set condition for `ElementTree` initialization by type of capabilities file variable `cap_file` (capabilities file path/capabilities file content string) in the `BaseCapabilitiesTree` class.
Tested with:
-  with default capabilities file to parse
```r.in.wms url="http://geoportal.cuzk.cz/WMTS_ORTOFOTO/WMTService.aspx" layers=orto output=orthophoto srs=3857 format=jpeg driver=WMTS_GRASS style=default```
-  with external capabilities file to parse (capfile option)
```r.in.wms url=http://geoportal.cuzk.cz/WMTS_ORTOFOTO/WMTService.aspx capfile=/home/user/capfile.xml layers=orto output=orthophoto srs=3857 format=jpeg driver=WMTS_GRASS style=default```

r.in.wms BaseCapabilitiesTree: Fix init ElementTree class 

---

lib/gis/aprintf.c

Standard-compliant usage of `va_list`. A `va_list` becomes indeterminate once passed to a function that calls `va_arg()` on it. `ovprintf()` can invalidate `ap` after passing it to `v*printf()`. The previous version of libgis worked on Linux (at least on my system), but not on Windows. This PR manually advances `ap`.

libgis: Advancing va_list manually after calling ovprintf()

---

vector/v.surf.bspline/main.c

Fix oversight in d933668e889a264040ad2f3568994969261de9a3 to switch between the offered methods.

v.surf.bspline: fix method selection

---

lib/python/script/core.py

pythonlib: allow wkt to be also string in create_location()

---

lib/python/script/raster.py

Fix encode string, bug introduced in the issue #737.

python/script/raster.py: Fix encode string

---

scripts/i.pansharpen/i.pansharpen.py

Fix bug in the reopened issue #737.

i.pansharpen: Fix encode string

---

gui/wxpython/datacatalog/tree.py

Merged LocationMapTree and DataCatalogTree into new class DataCatalogTree inheriting from TreeView.

wxGUI datacatalog: merge LocationMapTree and DataCatalogTree

---

gui/wxpython/lmgr/frame.py

wxGUI/frame: The Data tab and Layer tab were swapped so the Data tab is the first tab from the left and the default when the GUI opens.

Make Data tab the default in GUI

---

raster/r.horizon/r.horizon.html

- add explanations for the change in 688d5885557f22c7ea6618dcac3ddfbfc764731a
- related discussion:
- https://lists.osgeo.org/pipermail/grass-user/2018-July/078870.html
- cont'ed: https://lists.osgeo.org/pipermail/grass-user/2018-August/078887.html

r.horizon manual: explain negative values

---

gui/wxpython/datacatalog/tree.py

wxGUI/catalog: do not expand mapset after filtering if was filtered out

---

gui/wxpython/gui_core/widgets.py
gui/wxpython/modules/import_export.py

Improve output map name existence validation for `GdalImportDialog`, `OgrImportDialog`, `DxfImportDialog` class.
Import raster data dialog with the improved validation:

wxGUI ImportDialog: Improve output map name existence validation

---

gui/wxpython/core/treemodel.py

Now all nodes are deleted recursively, avoiding memory leaks.

wxGUI/treemodel: used weakref to fix deleting of nodes

---

gui/wxpython/gui_core/widgets.py

wxGUI/nviz: SetMaskColour causes problems on macos with wx 4.1.0

---

gui/wxpython/core/menutree.py
gui/wxpython/core/treemodel.py
gui/wxpython/datacatalog/tree.py
gui/wxpython/gui_core/query.py
gui/wxpython/gui_core/treeview.py

wxGUI/treemodel: refactor TreeModel to allow more flexible Node classes.

---

vector/v.to.db/main.c

Add `--overwrite` to help and GUI. Addressing #794.

v.to.db: Add --overwrite to help and GUI

---

scripts/v.in.wfs/v.in.wfs.py

This change allows you to set the user name and password. This can be done in files or in environment variables or directly in the options. The changes are made for Python2 and Python3.

v.in.wfs: add options to set user and password

---

gui/wxpython/startup/locdownload.py

Added the natural earth dataset (207MB) to the download list in the startup menu  #509 
Tested on a local installation of GRASS 7.8.

Added global dataset to download location in startup

---

README.md

adds more badges (from https://github.com/OSGeo/grass/actions)

README: more CI status badges added

---

gui/wxpython/gui_core/goutput.py
gui/wxpython/gui_core/prompt.py

wxGUI: avoid flush clipboard if not opened

---

gui/wxpython/lmgr/frame.py

wxGUI/LayerManager: Changed tab order (Modules are third) and Layers renamed to Display.

wxGUI: Changes in Layer Manager tabs order and labels

---

lib/gis/datum.table

add Datum: Reseau Geodesique Francais Guyane 1995
fixes #798
```
GRASS 7.9.dev (nc_spm_08_grass7):~ > g.proj epsg=2972 -p
-PROJ_INFO-------------------------------------------------
name       : RGFG95 / UTM zone 22N
datum      : RGFG95
ellps      : grs80
proj       : utm
zone       : 22
no_defs    : defined
-PROJ_EPSG-------------------------------------------------
epsg       : 2972
-PROJ_UNITS------------------------------------------------
unit       : meter
units      : meters
meters     : 1
```

datum.table: add RGFG95

---

gui/wxpython/mapswipe/frame.py

wxGUI/mapswipe: call dialog Uninit only when dialog was actually created

---

raster/r.cost/r.cost.html

explain resolving multiple directions to the geometrical optimum

r.cost manual: explain multiple directions

---

scripts/v.import/v.import.py

Same fix as for r.import (bug #547) #659
Based on r.import fix by Anna Petrasova 4be261e
Needs backporting to 7.8

v.import: Do not reproject if projections match

---

doc/infrastructure.md

- new hugo server
- CMSMS moved to old
- addons cronjobs
- misc

infrastructure.md: add latest updates

---

locale/po/grasswxpy_lv.po

Backport of #865 using `msgmerge -N --no-wrap ...`

i18n: Translation update of Latvian language

---

gui/wxpython/datacatalog/tree.py
gui/wxpython/startup/guiutils.py

There is already the "Delete mapsets" option in Data Catalog. The same thing should be enabled for locations.

Allow delete on multiple locations in data catalog

---

gui/wxpython/datacatalog/tree.py
lib/python/grassdb/checks.py

pwd.getpwuid works on unix only

pythonlib/grassdb: replace unix only function for file owner name

---

gui/wxpython/animation/dialogs.py

Fix validation of extension of exported file #899. Backport needed.

wxGUI/animation: fix validation of extension of exported file

---

gui/wxpython/animation/controller.py
lib/python/imaging/images2avi.py

Fix bug reported in the issue #835.

wxGUI/animation: fix export output animation file to avi format

---

gui/wxpython/startup/guiutils.py

wxGUI/datacatalog: fix switching mapset between different dbs

---

gui/wxpython/gcp/g.gui.gcp.py
gui/wxpython/image2target/g.gui.image2target.py
gui/wxpython/photo2image/g.gui.photo2image.py
imagery/i.ortho.photo/i.ortho.photo/menu.c
imagery/i.rectify/main.c
vector/v.rectify/main.c

keyword 'geometry' added

---

general/g.mapset/main.c
lib/init/grass.py

Fixes #963 
Again, unfortunately some repetitive code in grass.py. But fix this with variables and more if clauses, would in my opinion overly complicate the code. This may change with addition of tcsh, depending on what the solution will look like.

Add zsh history change

---

scripts/g.extension/g.extension.py

Fix bug reported in the issue #926.

g.extension: fix module launch with compile '-i' or download '-d' flag

---

scripts/g.search.modules/g.search.modules.py
scripts/g.search.modules/testsuite/test_g_search_modules.py

add possibility to list all available modules, supersedes #988

g.search.modules: without keywords, list all modules

---

raster/r.geomorphon/main.c

r.geomorphon: Fix an out-of-bounds read w/multires

---

lib/python/script/core.py

added missing docs, cited from https://github.com/OSGeo/grass/blob/8b9512b8b2fb0531df848fce58619308cbc29b3d/lib/gis/verbose.c#L46

libpython: explain verbosity levels

---

lib/python/script/core.py

...otherwise the list comes in a single line.

python verbosity docs: minor layout fixes

---

vector/v.out.ogr/main.c

Duplicate entry of "output" keyword

Duplicate entry of "output" keyword

---

scripts/g.extension/g.extension.py
tools/mkhtml.py

Fix bug reported in the issue #979.

tools/mkhtml: fix src and src commits url in html addon module manual

---

locale/po/grasslibs_fr.po
locale/po/grassmods_es.po
locale/po/grassmods_fr.po
locale/po/grassmods_it.po
locale/po/grassmods_zh.po
locale/po/grasswxpy_es.po
locale/po/grasswxpy_fr.po
locale/po/grasswxpy_hu.po
locale/po/grasswxpy_it.po

- restored translations from .po history which unexpectedly disappeared from Transifex
- fixed typos in translations

i18N: restore translations

---

gui/wxpython/gui_core/widgets.py
gui/wxpython/modules/import_export.py

In import and reprojection dialog, check all layers by default.

wxGUI/import: check all layers by default

---

gui/wxpython/core/settings.py
gui/wxpython/wxplot/dialogs.py

This PR replaces custom format of wx file with wx.json. If wx.json is not there, looks for and loads wx file.

Using JSON for GUI settings

---

lib/gis/gislib_cmdline_parsing.dox

It looks like you prefer to squash related changes together, so this commit packs plenty of editorial and technical improvements to the document, please review. However, if it would be better to split this into multiple focused updates and to review them one by one, let me know.

gislib/dox: Refine the command line parsing doc.

---

gui/wxpython/gui_core/pyedit.py

**Expected pyedit wxGUI toolbar tools widgets:**

wxGUI/pyedit: add quit toolbar tool

---

raster/r.geomorphon/geom.c

This bugfix solves an issue with my project data, please review, you might want it in the release branches too. I found it whilst working on something else in this plugin, which I would like to mention as well.
There are 6 (so far) commits with code cleanups in my working copy. They would not add value in the release branches, so I am going to open a separate pull request for the cleanups after the bugfix is sorted.
The cleanups prepare the plugin code for a new feature, which is still a work in progress, and which would make sense in the master branch and eventually in the 2021 Q1 release, although unlikely in the release branches. If everything goes well, it should be ready in time for that.
Would that fit with your development plans?

r.geomorphon: Fix shape calculations

---

raster/r.geomorphon/geom.c
raster/r.geomorphon/local_proto.h
raster/r.geomorphon/main.c
raster/r.geomorphon/memory.c
raster/r.geomorphon/multires.c
raster/r.geomorphon/pattern.c

These changes make existing code easier to follow and to work with, please review. It will be great if you do not squash these commits together, as they are quite unrelated to each other, and in one of them the credit goes to another contributor, who is not a developer.
I have a few more cleanup commits ready for a separate pull request later, where it would be fine to squash as you usually do.

r.geomorphon misc cleanups

---

gui/wxpython/lmgr/frame.py
gui/wxpython/xml/toolboxes.xml
gui/wxpython/xml/wxgui_items.xml

wxGUI/xml: update GUI tools toolbox items

---

vector/v.to.rast/v.to.rast.html

- replace Spearfish with North Carolina dataset example

v.to.rast manual: update example to NC dataset

---

lib/python/bandref/reader.py

* relax requirements for band names

libpython: relax requirements for band names

---

scripts/r.pack/r.pack.py
scripts/r.unpack/r.unpack.py

r.pack/r.unpack: fix pack and unpack VRT raster map with tiled raster maps

---

display/d.profile/main.c
gui/wxpython/docs/wxGUI.iscatt.html
gui/wxpython/timeline/g.gui.timeline.py
gui/wxpython/tplot/g.gui.tplot.py

Relevant for https://grass.osgeo.org/grass79/manuals/keywords.html

manual: add 'plot' keyword

---

scripts/g.extension/g.extension.py

g.extension: Fix installation from gitlab repositories

---

raster/r.geomorphon/geom.c
raster/r.geomorphon/local_proto.h
raster/r.geomorphon/main.c
raster/r.geomorphon/memory.c
raster/r.geomorphon/r.geomorphon.html

These should be the last changes before the new feature I've been working on, please review.

r.geomorphon more cleanups

---

raster/r.geomorphon/geom.c
raster/r.geomorphon/local_proto.h
raster/r.geomorphon/main.c
raster/r.geomorphon/memory.c
raster/r.geomorphon/multires.c
raster/r.geomorphon/pattern.c

r.geomorphon: Run grass_indent.sh on the source

---

gui/wxpython/gui_core/menu.py
gui/wxpython/gui_core/pyedit.py

Add recent files history menu.
**Default menu:**
**Expected menu:**

wxGUI/pyedit: add recent files history menu

---

scripts/d.polar/testsuite/test_d_polar.py

- adds a simple test using the NC aspect map
(also handy to test #1107)

d.polar: test added

---

gui/wxpython/core/gcmd.py

This is a preparation for addressing #1047.

wxGUI: add env parameter in gcmd.py RunCommand

---

scripts/g.extension/g.extension.py

Fixes error message:
```
ERROR: Download file from
<https://api.github.com/repos/OSGeo/grass-addons/git/trees/master?recursive=1>,
return status code HTTP Error 403: rate limit exceeded,
```
If 'rate limit is exceeded' warning message will be printed during installation add-on:
```
WARNING: The download of the json file with add-ons paths from the github
server wasn't successful, rate limit exceeded. The previous
downloaded json file will be used if exists.
```
For testing purpose:
1. Open new emulator terminal tab
2. Start `ipython`
3. Run this code
```
import urllib
for i in range(10000):
try:
response = urllib.request.urlopen('https://api.github.com/repos/OSGeo/grass-addons/git/trees/master?recursive=1')
except urllib.error.HTTPError as e:
print(e.code)
print(e.msg)
```
4. Break this …

g.extension: fix 'rate limit exceeded' http error during request json file (add-ons paths) from the official add-ons github server url

---

scripts/r.pack/r.pack.py
scripts/r.unpack/r.unpack.py

r.pack/r.unpack: fix packing/unpacking vrt map if some of tiled rasters doesn't have color table

---

vector/v.db.select/main.c

Run v7 version of the indent script.

v.db.select: Run grass_indent.sh on the source

---

gui/wxpython/psmap/dialogs.py
gui/wxpython/psmap/frame.py
gui/wxpython/psmap/instructions.py
gui/wxpython/psmap/utils.py

wxGUI/psmap: properly isolate region setting from the rest of GUI

---

tools/mkhtml.py

Fixes add-ons [issue](https://github.com/OSGeo/grass-addons/issues/337).

mkhtml: enable path setting for footer html pages (topics.html...) on add-on manual page

---

scripts/d.rast.edit/d.rast.edit.py

Fix launch d.rast.edit wxGUI (py3/wxPy4).

d.rast.edit: fix launch wxGUI (py3/wxPy4)

---

scripts/g.extension/g.extension.py

g.extension: fix get add-on module name on Win platform 

---

config.guess
config.sub

updated from http://git.savannah.gnu.org/cgit/config.git/plain/

config.guess + config.sub: updated

---

tools/mkhtml.py

Fixes GRASS GIS Add-Ons [issue](https://github.com/OSGeo/grass-addons/issues/337) (Keywords: ... lack of ../ in the path).

tools/mkhtml.py: fix keywords html pages paths if add-on html man page strored on the server

---

scripts/g.extension/g.extension.py

g.extension: fix parse PGM variable from Makefile

---

gui/wxpython/gui_core/infobar.py

wxGUI/infobar: fix infobar creation with wxPython 4.1

---

gui/wxpython/datacatalog/catalog.py
gui/wxpython/datacatalog/infomanager.py
gui/wxpython/datacatalog/tree.py

After creating a new location when a user is in demolocation, second Info Bar appears offering a user to import data using Import vector data or Import raster data buttons.
A the same time, when creating a new Location, GRASS switches to the Location that a user created to its PERMANENT mapset.

wxGUI: displaying infobar focused on first-time user (part 2)

---

gui/wxpython/tplot/frame.py
gui/wxpython/tplot/g.gui.tplot.html
gui/wxpython/tplot/g.gui.tplot.py

Add option to show simple regression model line (calculate simple regression model, print calculated formula y = a + b*x, and r-squared parameter). Implements the issue #1197.

wxGUI/tplot: add option to show simple regression model line

---

gui/wxpython/gui_core/ghelp.py

wxGUI/About: remove hardcoded white background for dark mode

---

gui/wxpython/gui_core/prompt.py

wxGUI/prompt: support dark themes

---

gui/wxpython/datacatalog/tree.py

wxGUI/datacatalog: fix #1184

---

gui/wxpython/datacatalog/tree.py
gui/wxpython/lmgr/frame.py
gui/wxpython/startup/guiutils.py

Also show dialog upon switching only after creating new location/mapset.

wxGUI: always switch when creating new location/mapset

---

gui/wxpython/core/treemodel.py
gui/wxpython/datacatalog/catalog.py
gui/wxpython/datacatalog/toolbars.py
gui/wxpython/datacatalog/tree.py
gui/wxpython/gui_core/goutput.py
gui/wxpython/gui_core/menu.py
gui/wxpython/gui_core/treeview.py
gui/wxpython/modules/extensions.py

Remove unused code, filtering functionality moved to treemodel, change search modules layout and behavior, change data catalog's search widget.

wxGUI: module search GUI improved

---

translators.csv

Updated translators.csv file adding Transifex user, some of them are without email address but I'm going to send an announcement in Transifex to add their email address if they are interested to vote.

Updated translators.csv file

---

gui/wxpython/datacatalog/catalog.py
gui/wxpython/datacatalog/tree.py

After creating a new database from Toolbar, the user is presented with the popup with the question if the user wants to continue to create a location. If confirmed, the 'Create new location' menu is opened.

wxGUI datacatalog: process of creating a new database

---

gui/wxpython/gmodeler/g.gui.gmodeler.html
gui/wxpython/startup/locdownload.py

Fix failure to download sample data.

wxGUI: update Slovakia 3D precipitation voxel sample dataset URL

---

.github/workflows/flake8.yml
lib/init/.flake8

This adds Flake8 check for the init grass.py script ignoring all current issues by their type.

CI: Add Flake8 check for grass.py

---

scripts/v.rast.stats/v.rast.stats.py

originally, an error was raised
fix #1257

v.rast.stats: raise a warning when no categories found in raster map

---

scripts/g.bands/testsuite/test_g_bands.py
scripts/i.band/testsuite/test_i_band.py

Fixes outdated tests.
Addresses #1342

testsuite: fix g.bands and i.band test

---

.github/workflows/codeql-analysis.yml

See closed PR ["Activation security analysis with CodeQL"](https://github.com/OSGeo/grass/pull/1188):
> This PR adds Code-QL which is a tool for
> 
> Code scanning alerts
> Automatically detect common vulnerability and coding errors 
> 
> It will run for master branch and protected branches and for MRs into the master branch.
> For more details see https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository
> 
Output can be seen in [fork](https://github.com/mmacata/grass/security/code-scanning?query=tool%3ACodeQL+ref%3Arefs%2Fheads%2Fcodeql). To generate it, `codeql` branch was also activated in codeql-analysis.yml but now removed.

GitHub Action: Completion of security analysis with CodeQL

---

lib/gis/testsuite/test_parser_json.py
scripts/r.fillnulls/testsuite/test_r_fillnulls.py

testsuite: fix libgis/parser_json.c and r.fillnull

---

.github/workflows/black.yml
lib/init/grass.py

An already long file made even longer, but hopefully this will facilitate refactoring.

init: Apply Black to the init script

---

.github/workflows/black.yml
utils/create_python_init_file.py
utils/g.html2man/g.html2man.py
utils/g.html2man/ggroff.py
utils/g.html2man/ghtml.py
utils/g.html2man/rest.py
utils/gitlog2changelog.py
utils/mkhtml.py
utils/mkrest.py
utils/ppmrotate.py
utils/thumbnails.py

This applies Black formatting to Python scripts in utils.

Apply Black to Python utils

---

utils/dep_tree2sql.sh
utils/fix_typos.sh
utils/module_synopsis.sh

A selection of small fixes by Mega-Linter (combination of bash-exec, shellcheck, and esp. shfmt).

utils: Small fixes of Bash util scripts

---

imagery/i.vi/main.c

i.vi: fix the check for the existence of the 'redchan' variable

---

vector/v.colors/main.c
vector/v.colors/make_colors.c
vector/v.colors/scan_z.c
vector/v.colors/v.colors.html

Make #1297 more efficient by supporting rules from stdin.

v.colors: Implement rules from stdin

---

vector/v.colors/local_proto.h
vector/v.colors/main.c
vector/v.colors/read_rgb.c
vector/v.colors/scan_attr.c
vector/v.colors/scan_cats.c
vector/v.colors/scan_z.c
vector/v.colors/v.colors.html
vector/v.colors/write_rgb.c

v.colors: raster= with use=attr

---

scripts/g.bands/g.bands.html
scripts/i.band/i.band.html

adds list of currently supported multispectral sensors to manual

g.bands and i.band manual: explain supported sensors

---

scripts/v.db.join/v.db.join.py

Since SQL is case insensitive, adding a new column to a table needs to use case insensitive
comparison with the existing columns.
Additionally, use fully qualified map name to get the 'found in more than one mapset' message
only once.

v.db.join: Use case insensitive comparison for columns

---

python/grass/pygrass/raster/history.py
python/grass/pygrass/raster/testsuite/test_history.py

Also fix history __repr__ function

pygrass: remove failing test as not useful

---

gui/wxpython/startup/guiutils.py

Previously it imported the data into the current mapset not the new one,
also sets the default region from that data, previously it extended the region which is not
appropriate here.

wxGUI: fix importing data when new location was created

---

gui/wxpython/gui_core/widgets.py

wxGUI: fix for cases when validator is called automatically from wx.Dialog upon closing it with OK

---

scripts/db.in.ogr/db.in.ogr.py

Useful for AUTODETECT_TYPE=YES for CSV files

db.in.ogr: Add gdal_config= and gdal_doo=

---

vector/v.colors/local_proto.h
vector/v.colors/main.c
vector/v.colors/make_colors.c
vector/v.colors/read_rgb.c
vector/v.colors/scan_attr.c
vector/v.colors/scan_cats.c
vector/v.colors/scan_z.c
vector/v.colors/v.colors.html
vector/v.colors/write_rgb.c

Backport #1393 and #1389 (Resolve #1297)

v.colors: Backport #1393 and #1389 (Resolve #1297)

---

.github/workflows/test_thorough.bat
.github/workflows/test_thorough.sh
testsuite/examples/test_framework_GRASS_GIS_with_NC.sh

Moved (due to server failure) from
- http://fatra.cnr.ncsu.edu/data/nc_spm_full_v2alpha2.tar.gz
to
- https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz
in order to get the CI running again.

NC full sample dataset: new URL

---

lib/python/temporal/core.py
lib/temporal/SQL/downgrade_db_3_to_2.sql
lib/temporal/SQL/drop_views.sql
temporal/Makefile
temporal/t.downgrade/Makefile
temporal/t.downgrade/t.downgrade.html
temporal/t.downgrade/t.downgrade.py

fixes #1448 
New module for G78 to downgrade a temporal db from version 3 to 2.

t.downgrade: downgrade a temporal db from version 3 to 2

---

lib/gis/parser.c

If an option expects a number (int or double), but the answer is a string, the parser reports an error about a missing value. This PR adds a test for invalid values to the parser with corresponding error message. I find the current error message complaining about a missing value confusing when a value has been provided (thus not missing), therefore I would like to backport this change to G78.
Simple test in nc_spm_08: `r.grow in=lakes out=lakes_grow radius=twenty`

lib/gis: add test for invalid value to parser

---

vector/v.colors/local_proto.h
vector/v.colors/main.c
vector/v.colors/make_colors.c
vector/v.colors/scan_attr.c
vector/v.colors/scan_cats.c
vector/v.colors/scan_z.c
vector/v.colors/write_rgb.c

v.colors: Fix color inversion

---

gui/wxpython/core/gcmd.py

wxGUI/gcmd: fix read command stdout

---

lib/gis/parser_dependencies.c

parser: Add angle brackets to a single option/flag rule

---

scripts/.flake8
scripts/d.rast.edit/d.rast.edit.py
scripts/g.bands/g.bands.py
scripts/g.extension/g.extension.py
scripts/i.pansharpen/i.pansharpen.py
scripts/r.fillnulls/r.fillnulls.py
scripts/r.import/r.import.py
scripts/r.in.wms/wms_drv.py
scripts/v.dissolve/v.dissolve.py
scripts/v.in.lines/v.in.lines.py
scripts/v.in.mapgen/v.in.mapgen.py

* Remove unused variables.
* Use one previously unused exception for an error message.
* Ignore the unclear cases using per-file-ignores (to be resolved in the future).

scripts: Remove unused vars or ignore in Flake8

---

lib/psdriver/graph_close.c
lib/psdriver/graph_set.c
lib/psdriver/psdriver.h

This PR addresses #1450 by creating a temporary file and renaming it to the final output on closing.

PS Driver: Write data to a tempfile before closing

---

gui/wxpython/.flake8
gui/wxpython/iclass/toolbars.py
gui/wxpython/location_wizard/wizard.py
gui/wxpython/mapswipe/frame.py

Enable Flake8 unused variable warning (F841) mostly by ignoring it for files and directories using per-file-ignores.

wxGUI: Enable unused var warning

---

lib/init/.flake8

Enable resolved warnings. Add underscore as a builtin.

init: Clean up Flake8 config

---

locale/grass_po_stats.py

This applies Black 20.8b1 to po file stats script.
Uses: black --target-version=py36

Apply Black to locale

---

gui/wxpython/core/giface.py
gui/wxpython/lmgr/frame.py
gui/wxpython/lmgr/giface.py
gui/wxpython/lmgr/layertree.py
gui/wxpython/lmgr/workspace.py
gui/wxpython/mapdisp/frame.py
gui/wxpython/vdigit/preferences.py
gui/wxpython/xml/toolboxes.xml
gui/wxpython/xml/wxgui_items.xml

In order to finish the PR #1321, some refactoring needs to take place.
The first change is the allocation of class for workspace management from Layer Manager.
This is the first PR which starts the refactoring to prepare GUI for designing and implementing the Single Layout window option on which (if everything will turned out well) I would like to work this summer within GSoC :-)

wxGUI refactoring: New WorkspaceManager class

---

lib/psdriver/graph_close.c
lib/psdriver/graph_set.c
lib/psdriver/psdriver.h

This PR addresses #1450 by creating a temporary file and renaming it to the final output on closing. (Backport #1451)

PS Driver: Write data to a tempfile before closing (rel78)

---

vector/v.surf.idw/main.c
vector/v.surf.idw/read_sites.c

Indent to prepare for a bug fix

v.surf.idw: indent with indent script

---

raster/r.out.gdal/r.out.gdal.html

- add example how to export COG

r.out.gdal manual: added COG example

---

gui/wxpython/animation/controller.py
gui/wxpython/animation/provider.py

3D animation currently fails due to changes in region handling. Includes fix for Python3 for deleting items in dict.

wxGUI/animation: fix 3D animation

---

gui/wxpython/datacatalog/tree.py

Happens when a lot of maps are removed at once or are being generated too quickly.

wxGUI/datacatalog: fix unresponsive gui if too many maps in current mapset watched with watchdog are changing at once

---

vector/v.net.visibility/main.c

v.net.visibility: fix coordinates parameter

---

CONTRIBUTING.md

Related questions on grass-user suggested that there is a documentation gap. This PR attempts to fill it.
Comments welcome.

CONTRIBUTING.md: intro added for newcomers

---

python/grass/pygrass/modules/interface/module.py
python/grass/pygrass/raster/history.py
python/grass/pygrass/rpc/__init__.py
python/grass/pygrass/vector/abstract.py
python/grass/pygrass/vector/table.py

* Plain try-finally is how re-raising is expressed according to the doc:
'If there is a saved exception it is re-raised at the end of the finally clause.'
* datetime.strptime() produces ValueError.
* Only ImportError for import statement.

pygrass: Remove usage of bare except

---

gui/wxpython/gui_core/prompt.py

List of maps is updated when signal grassdbchanged and mapsetchanged is emitted.

wxGUI/prompt: update autocomplete map list when there is a change in db

---

scripts/g.extension/g.extension.py

Backport of #1565
(due to the `black` formatting differences cherry-picking is no longer possible...)

g.extension: match module files on Windows

---

docker/alpine/Dockerfile_alpine

Replaces #1568 with a better solution by @mmacata, per https://github.com/mundialis/actinia_core/pull/187

Dockerfile_alpine: fix broken pip six installation

---

config.guess
config.sub
configure

Update from
- http://git.savannah.gnu.org/cgit/config.git/plain/config.guess
- http://git.savannah.gnu.org/cgit/config.git/plain/config.sub

configure, config.sub, config.guess: updated

---

config.guess
config.sub

Update from
- http://git.savannah.gnu.org/cgit/config.git/plain/config.guess
- http://git.savannah.gnu.org/cgit/config.git/plain/config.sub
(backport of #1585)

config.sub, config.guess: updated

---

lib/python/docs/src/pygrass_modules.rst
lib/python/gunittest/case.py
lib/python/gunittest/gmodules.py
lib/python/pygrass/modules/interface/module.py
lib/python/pygrass/modules/interface/typedict.py
lib/python/temporal/temporal_vector_algebra.py
temporal/t.rast.accumulate/t.rast.accumulate.py
temporal/t.rast.neighbors/t.rast.neighbors.py

This slightly changes API (hides popen attribute), but is needed for Python3.

Backport #1407 pygrass Module fix

---

docker/alpine/Dockerfile_alpine
docker/alpine/Dockerfile_alpine_latest
docker/debian/Dockerfile_debian_pdal
docker/testdata/test_grass_session.py
docker/ubuntu/Dockerfile_ubuntu_pdal

Workaround for grass-session which requires G8 related updates

Dockerfiles: fix broken grass-session tests

---

docker/alpine/Dockerfile_alpine
docker/debian/Dockerfile_debian_pdal
docker/ubuntu/Dockerfile_ubuntu_pdal

Dockerfiles: remove workaround for grass-session

---

docker/alpine/Dockerfile_alpine
docker/debian/Dockerfile_debian_pdal
docker/ubuntu/Dockerfile_ubuntu_pdal

Dockerfile: fix broken lib link

---

gui/wxpython/lmgr/workspace.py

missing argument added
fixes #1636

wxGUI: SaveToFile() missing 1 required positional argument

---

.github/workflows/apt.txt
.github/workflows/build.sh

add PDAL support to GitHub actions (Ubuntu related)
fixes #1633, needed for #1200

CI: add PDAL support

---

gui/wxpython/core/workspace.py
gui/wxpython/lmgr/workspace.py
gui/wxpython/mapdisp/main.py

I tried to find all occurrences by grep -Irn "anager.Show" and grep -Irn "anager.IsShown", now it should be ok.

wxGUI: Workspace save fails with SbManager has no IsShown

---

gui/wxpython/gui_core/dialogs.py

wxGUI: fix wx flag assertion error in SavedRegion Dialog (#1679)

---

temporal/t.rast.accdetect/testsuite/test_simple.py
temporal/t.rast.accumulate/testsuite/test_accumulation.py
temporal/t.rast.aggregate/testsuite/test_aggregation_absolute.py
temporal/t.rast.aggregate/testsuite/test_aggregation_absolute_parallel.py
temporal/t.rast.aggregate/testsuite/test_aggregation_relative.py
temporal/t.rast.algebra/testsuite/test_raster_algebra.py
temporal/t.rast.algebra/testsuite/test_raster_algebra_granularity.py
temporal/t.rast.algebra/testsuite/test_raster_algebra_granularity_fails.py
temporal/t.rast.contour/testsuite/test_convert.py
temporal/t.rast.export/testsuite/test_rast_export.py
temporal/t.rast.extract/testsuite/test_t_rast_extract.py
temporal/t.rast.gapfill/testsuite/test_gapfill.py
temporal/t.rast.import/testsuite/test_temporal_rast_import.py
temporal/t.rast.neighbors/testsuite/test_neighbors.py
temporal/t.rast.series/testsuite/test_series.py
temporal/t.rast.to.rast3/testsuite/test_strds_to_rast3.py
temporal/t.rast.to.vect/testsuite/test_to_vect.py
temporal/t.rast.univar/testsuite/test_t_rast_univar.py
temporal/t.rast.what/testsuite/test_what.py
temporal/t.rast3d.extract/testsuite/test_t_rast3d_extract.py
temporal/t.rast3d.univar/testsuite/test_t_rast3d_univar.py
temporal/t.remove/t.remove.html
temporal/t.remove/t.remove.py
temporal/t.shift/testsuite/test_shift.py
temporal/t.snap/testsuite/test_snap.py
temporal/t.support/testsuite/test_support_str3ds.py
temporal/t.support/testsuite/test_support_strds.py
temporal/t.support/testsuite/test_support_stvds.py
temporal/t.vect.algebra/testsuite/test_vector_algebra.py
temporal/t.vect.extract/testsuite/test_vect_extract.py

new pull request from previous one #1650

t.remove: new implementation of flags

---

.github/workflows/osgeo4w.yml

osgeo4w-setup-x86_64.exe executable was renamed osgeo4w-setup-x86_64-v1.exe

Fix osgeo4w workflow

---

scripts/.flake8
scripts/g.extension/g.extension.py

Backports all changes to g.extension (excluding `#%` -> `# %`)

g.extension: attempt to backport changes from master

---

raster/r.patch/do_patch.c
raster/r.patch/local_proto.h
raster/r.patch/main.c
raster/r.patch/support.c
raster/r.series/main.c

- Reformat r.series
- Reformat r.patch

misc: fix indentation for r.series and r.patch

---

gui/wxpython/lmgr/frame.py
gui/wxpython/main_window/frame.py

wxGUI: Each layertree has its own display toolbar

---

.flake8
python/grass/pydispatch/dispatcher.py
python/grass/pydispatch/signal.py

* E722 do not use bare 'except' resolved by using Exception.
* E501 line too long resolved by doctest result simplification.

Fix some Flake8 for pydispatch

---

gui/wxpython/gis_set.py
gui/wxpython/gui_core/dialogs.py
gui/wxpython/gui_core/forms.py
gui/wxpython/image2target/ii2t_gis_set.py
gui/wxpython/modules/mcalc_builder.py

Backport of #744.
Fixes #1784.

wxGUI: Remove colouring of standard buttons

---

configure
configure.in

@marisn: as requested and discussed on grass-dev

configure: use pkg-config for FreeType 2

---

.github/FUNDING.yml

change sponsor link to opencollective

---

imagery/i.cluster/i.cluster.html
imagery/i.smap/i.smap.html

This PR re-adds (with minor editions) the example on how to add band references originally in #1866.

add text snippet and how to add band references

---

mswindows/crosscompile.sh

Drop `$version` from filenames.

mswindows: Update crosscompile.sh to 8.0

---

lib/python/ctypes/loader.py
mswindows/GRASS-Installer.nsi.tmpl
mswindows/GRASS-Packager.bat.tmpl
mswindows/Makefile
mswindows/env.bat
mswindows/osgeo4w/env.bat.tmpl
mswindows/osgeo4w/mklibs.sh
mswindows/osgeo4w/package.sh
mswindows/osgeo4w/postinstall.bat

This PR introduces #1880 into release branch 7.8.

Apply patches from OSGeo4W upstreams backported to relbr78

---

gui/wxpython/nviz/tools.py
imagery/i.ortho.photo/lib/orthoref.c

The lintian QA tool reported a spelling errors for 7.8.6-rc3:
* postion -> position

Fix spelling errors.

---

gui/wxpython/nviz/tools.py
imagery/i.ortho.photo/lib/orthoref.c

Fix spelling errors. (backport of #1916)

---

gui/wxpython/lmgr/pyshell.py

wxGUI/lmgr: fix Python Shell 'help()' function and intro text

---

gui/wxpython/core/gconsole.py
gui/wxpython/gui_core/prompt.py

Changed .bash_history to .wxgui_history as per issue #962

Use .wxgui_history as history file for the gui (#962)

---

python/grass/script/setup.py

* Search for install path (GISBASE) no returns the path it found.
* Runtime env setup now accepts any Path-like objects.
* The extra checks before mapset path resolve function call now support tilde for home directory.

grass.script: Fix path resolving in init

---

imagery/i.vi/pvi.c

i.vi: fix PVI formula

---

scripts/i.spectral/i.spectral.html
scripts/i.spectral/i.spectral.py

scripts/i.spectral: show error message if one of the supported monitor isn't running

---

doc/howto_release.md

- various updates from G7.x to G8

howto_release.md: updated for G8

---

python/grass/script/array.py
python/grass/temporal/space_time_datasets.py

Fixes #925. Changes done in addons in https://github.com/OSGeo/grass-addons/pull/622

grass.script.array: remove deprecated read function

---

python/grass/script/setup.py

The documentation example:
~- now works for Python 3~
- has correct and tested setup for mac
- is Black formatted
~- is flake8 validated~

pythonlib: update script.setup docs

---

doc/gui/wxpython/example/frame.py
gui/wxpython/gcp/manager.py
gui/wxpython/gui_core/mapdisp.py
gui/wxpython/iclass/frame.py
gui/wxpython/image2target/ii2t_manager.py
gui/wxpython/mapdisp/frame.py
gui/wxpython/mapdisp/main.py
gui/wxpython/mapswipe/frame.py
gui/wxpython/photo2image/ip2i_manager.py
gui/wxpython/rdigit/g.gui.rdigit.py
gui/wxpython/vdigit/g.gui.vdigit.py

Iconsize should be a parameter of MapPanelBase.

wxGUI: Map display object has no attribute iconsize

---

utils/mkhtml.py

Closes #1837, https://github.com/OSGeo/grass-addons/issues/601. It relates with this [PR](https://github.com/OSGeo/grass-addons/pull/615).

utils/mkhtml.py: fix get and set addon manual page source and history URL link

---

gui/wxpython/animation/frame.py
gui/wxpython/animation/provider.py
gui/wxpython/gmodeler/frame.py
gui/wxpython/gui_core/dialogs.py
gui/wxpython/gui_core/forms.py
gui/wxpython/gui_core/widgets.py
gui/wxpython/gui_core/wrap.py
gui/wxpython/mapswipe/frame.py
gui/wxpython/nviz/tools.py
gui/wxpython/psmap/dialogs.py
gui/wxpython/psmap/frame.py

Addresses #2047, #2048, #2049, also includes other problematic places.
Wait with merging, more fixes are needed.

wxGUI: more Python 3.10 fixes

---

doc/howto_release.md
doc/infrastructure.md
locale/README

- add how to create ChangeLog with GH API for GH release notes
- minor path fixes

howto_release.md: create ChangeLog with GH API

---

gui/wxpython/core/settings.py
gui/wxpython/gui_core/preferences.py
gui/wxpython/main_window/frame.py
gui/wxpython/wxgui.py

This PR adds single window layout to settings, so that it can be easily tested. This can be merged only after #1675 is merged.

wxGUI: add single window to settings

---

locale/Makefile

Resolve #1643.
This PR adds `--from-code=utf-8` option to xgettext.

i18n: xgettext --from-code=utf-8

---

.github/workflows/build_osgeo4w.sh
.github/workflows/osgeo4w.yml
.github/workflows/test_simple.bat
.github/workflows/test_simple.sh
.github/workflows/test_thorough.bat
mswindows/osgeo4w/build_osgeo4w.sh

This brings back CI on MS Windows. It replaces #1873
@HuidaeCho do you have any objections to merge this now, and adress packaging in another PR?

CI for MS Windows: Switch to OSGeo4W V2

---

scripts/g.extension/g.extension.py

scripts/g.extension: fix get get_addons_paths func json_file attribute

---

tools/mkhtml.py

Fix git cherry-pick commit cba6a7aebf339d9c5fa822bf890d7cc759b07e18.

tools/mkhtml.py: fix git cherry-pick commit cba6a7aebf339d9c5fa822bf890d7cc759b07e18

---

utils/mkhtml.py

Fix git cherry-pick commit 223dc8824fbc37333ec3c2e1d3afd0223168e3b4.

utils/mkhtml.py: fix git cherry-pick commit 223dc8824fbc37333ec3c2e1d3afd0223168e3b4

---

utils/mkhtml.py

Fix get core modules commit from local git repository and remote GitHub API server. Bug related with PR #2100.

utils/mkhtml.py: fix get core modules commit from local git repo and remote GitHub API server

---

vector/v.distance/main.c

This is a basic quick-fix for #2126
Tests should be added...

v.distance: relax parser rules

---

vector/v.distance/main.c

v.distance: relax parser rules (#2127)

---

doc/howto_release.md

(would be nice to be able to skip CI as not needed here)

howto_release.md: minor tweaks

---

singularity/debian/singularityfile_debian

Small fixes to singularity file

singularity: Minor fixes of definition file

---

lib/arraystats/class.c

Fix -Wself-assign compiler warnings

---

gui/wxpython/gcp/manager.py
gui/wxpython/image2target/ii2t_manager.py
gui/wxpython/photo2image/ip2i_manager.py

wxGUI: Fix statusbar mode index for GetMode method

---

doc/howto_release.md

howto_release.md: sync to release_branch_8_0

---

mswindows/osgeo4w/package.sh

Fix #2197
Co-authored-by: Helmut Kudrnovsky hellik@web.de

MS Windows packaging: add missing dlls

---

lib/init/grass.py

Consolidate shell starting code in one function

startup: Start shell from start_shell()

---

temporal/t.rast.neighbors/t.rast.neighbors.html
temporal/t.rast.neighbors/t.rast.neighbors.py

transfer semantic label from input to output if existing

t.rast.neighbors: transfer semantic label

---

doc/howto_release.md

sync with 58e5b8e306c58a4c2fa5f2e42b1e5620e992d1a0

howto_release.md: forwardport notes from relbranch80

---

gui/wxpython/gui_core/preferences.py
locale/po/grasswxpy_bn.po
locale/po/grasswxpy_cs.po
locale/po/grasswxpy_de.po
locale/po/grasswxpy_el.po
locale/po/grasswxpy_es.po
locale/po/grasswxpy_fi.po
locale/po/grasswxpy_fr.po
locale/po/grasswxpy_hu.po
locale/po/grasswxpy_id_ID.po
locale/po/grasswxpy_it.po
locale/po/grasswxpy_ja.po
locale/po/grasswxpy_ko.po
locale/po/grasswxpy_lv.po
locale/po/grasswxpy_ml.po
locale/po/grasswxpy_pl.po
locale/po/grasswxpy_pt.po
locale/po/grasswxpy_pt_BR.po
locale/po/grasswxpy_ro.po
locale/po/grasswxpy_ru.po
locale/po/grasswxpy_si.po
locale/po/grasswxpy_ta.po
locale/po/grasswxpy_th.po
locale/po/grasswxpy_tr.po
locale/po/grasswxpy_uk.po
locale/po/grasswxpy_vi.po
locale/po/grasswxpy_zh.po
locale/po/grasswxpy_zh_CN.po

Update string (and translation files) to use official name (see https://proj.org/)

user message: change Proj.4 to PROJ

---

lib/init/grass.html

docs: add config option python_path

---

docker/README.md

- update version numbers
- update image sizes

docker: GRASS GIS docker matrix update

---

lib/imagery/Makefile

 lib/imagery: fix SONAME missing

---

lib/gis/copy_file.c

infp and outfp are not closed if there is an error.
BTW I haven't found, is there a style to apply to the c code?

Fix possible ressource leak in lib/gis/copy_file.c

---

python/grass/pygrass/modules/grid/grid.py
python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py

When width or height or both are not provided, compute the size based on number of process.
Use 1 column x N rows tile schema to make patching faster.

pygrass.GridModule: make tile size optional

---

raster/r.terraflow/fill.cpp
raster/r.terraflow/plateau.cpp
raster/r.terraflow/plateau.h

Fix -Wunused-private-field compiler warning

---

include/Make/Grass.make
lib/raster/Makefile
lib/raster/gdal.c

fixes #1872, reverts 26503976190 ff

grass_raster: remove GDAL_DYNAMIC (fixes #1872, reverts 26503976190 ff)

---

CHANGES
NEWS
SUBMITTING

- SUBMITTING no longer needed; see CONTRIBUTING.md
- simplify CHANGES file

Minor cleanup of CHANGES file

---

INSTALL
README.md
docker/README.md
docker/alpine/Dockerfile
docker/alpine/Dockerfile_alpine_latest
docker/debian/Dockerfile
docker/ubuntu/Dockerfile
general/g.version/g.version.html
lib/init/grass.html
man/sphinx/Makefile
man/sphinx/conf.py
man/sphinx/make.bat
mswindows/crosscompile.sh
python/grass/gunittest/multirunner.py
python/grass/script/setup.py
rpm/grass.spec

Update various mentions of grass80 and grass81 -> grass83

main: Update grass80/grass81 to grass83

---

CHANGES
INSTALL
NEWS
README.md
SUBMITTING
docker/README.md
docker/alpine/Dockerfile
docker/alpine/Dockerfile_alpine_latest
docker/debian/Dockerfile
docker/ubuntu/Dockerfile
general/g.version/g.version.html
lib/init/grass.html
man/sphinx/Makefile
man/sphinx/conf.py
man/sphinx/make.bat
mswindows/crosscompile.sh
python/grass/gunittest/multirunner.py
python/grass/script/setup.py
rpm/grass.spec

Update various mentions of grass80 and grass81 -> grass82

releasebranch_8_2: Update grass80 to grass82

---

.github/workflows/osgeo4w.yml
.github/workflows/pylint.yml
.github/workflows/pytest.yml

Updating the version file fixed the Dockers, but broke Windows CI which was not updated, so fixing that.

version: Additional 8.1 to 8.2 changes

---

python/grass/temporal/abstract_dataset.py
python/grass/temporal/abstract_space_time_dataset.py
python/grass/temporal/aggregation.py
python/grass/temporal/datetime_math.py
python/grass/temporal/list_stds.py
python/grass/temporal/metadata.py
python/grass/temporal/temporal_granularity.py
python/grass/temporal/temporal_vector_algebra.py
python/grass/temporal/testsuite/unittests_temporal_raster_algebra_equal_ts.py
temporal/t.rast.algebra/t.rast.algebra.html
temporal/t.rast.list/tests/t_rast_list_test.py
temporal/t.rast.to.rast3/t.rast.to.rast3.py
temporal/t.rast.what/t.rast.what.py
temporal/t.select/t.select.html
temporal/t.vect.algebra/t.vect.algebra.html
temporal/t.vect.what.strds/test.t.vect.what.strds.sh
temporal/t.vect.what.strds/test.t.vect.what.strds_relative.sh

These are just some changes from my local test of the semi-automated typo fixing script including fixes of some of my recent typos.

temporal: Fix typos in doc and comments

---

man/Makefile
python/libgrass_interface_generator/Makefile

as reported with https://github.com/OSGeo/grass-addons/pull/740.

make: remove __pycache__ directories with distclean

---

lib/raster/auto_mask.c
lib/raster/mask_info.c
raster/r.kappa/mask.c
raster/r.report/maskinfo.c

A whitespace-only change after running grass_indent.sh.

checks: Indent mask-related code

---

doc/howto_release.md
utils/update_version.py

* Tag message is created automatically.
* Version script clarifies meaning of the different messages it produces.
* Commit command for changed version file is easier to edit.
* More details in the tagging and general Git procedure.
* Acknowledge that checks may take some time to run.

contributing: Create tag message, add more details

---

raster/r.kappa/mask.c
raster/r.report/maskinfo.c

The code for showing details about mask is the same in r.kappa and r.report with only minor details unrelated to its function. This removes all the remaining differences such as formatting.

modules: Sync r.kappa and r.report mask reporting code

---

gui/wxpython/gui_core/query.py

wxGUI: Do not show empty raster label/color fields in query dialog

---

locale/po/grasslibs_de.po
locale/po/grasslibs_ko.po
locale/po/grassmods_de.po
locale/po/grasswxpy_es.po
locale/po/grasswxpy_it.po

Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [GRASS GIS/grasslibs](https://weblate.osgeo.org/projects/grass-gis/grasslibs/).
It also includes following components:
* [GRASS GIS/grasswxpy](https://weblate.osgeo.org/projects/grass-gis/grasswxpy/)
* [GRASS GIS/grassmods](https://weblate.osgeo.org/projects/grass-gis/grassmods/)
Current translation status:

Translations update from OSGeo Weblate

---

gui/wxpython/psmap/frame.py

Remove unnecessary HyperlinkDialog widget, related with PR #2419.

wxGUI/psmap: remove unnecessary HyperlinkDialog widget

---

doc/raster/r.example/main.c
doc/vector/v.example/main.c

This indents C code in v.example and r.example using the current indent script.

docs: Indent examples with current style

---

.github/workflows/osgeo4w.yml
mswindows/osgeo4w/build_osgeo4w.sh

CI: introduce setup-msys2@v2 setup action (backport #2508)

---

.github/FUNDING.yml

Sponsorship: tweak openCollective URL

Beautify openCollective link according to GH docs

---

man/build_keywords.py

Fixes https://github.com/OSGeo/grass-addons/issues/791.

man: use relative path for core modules man HTML page

---

general/g.rename/main.c

Fix -Wparentheses warning

---

raster/r.mapcalc/mapcalc.l

Fix -Wunneeded-internal-declaration warning

---

general/g.version/g.version.html

g.version manual: change link to citations

---

gui/wxpython/core/utils.py

wxGUI/modules: fix entering raster map file path by the keyboard inside Import Gdal dialog `FileBrowseButton` widget text field

---

gui/wxpython/lmgr/layertree.py

wxGUI/lmgr: fix launch map layer menu item '3D view properties' in the single window mode

---

gui/wxpython/lmgr/layertree.py

wxGUI/lmgr: hide map layer menu item 'Change opacity level' if 3d view is activated.

---

doc/raster/r.example/main.c
doc/vector/v.example/main.c

Formatting following directories:
- doc

Clang-Format, part 7

---

db/drivers/dbf/table.c
display/d.legend.vect/main.c
display/d.legend/draw.c
raster/r.out.pov/main.c
raster/r.sim/simlib/input.c

Fix '-Wformat-overflow=' compiler warnings

---

lib/display/r_raster.c

lib/display: issue warning on GRASS_NOTIFY command failure

---

gui/wxpython/gui_core/prompt.py

Reimplementation of #2718
According to the simple solution suggested by @petrasovaa in https://github.com/OSGeo/grass/pull/2718#issuecomment-1369200501 (thanks for that, sometimes it is handy to look at the problem from an entirely different perspective).

wxGUI/console: Adding hint to command prompt

---

lib/gis/parser_dependencies.c
raster/r.in.png/main.c
raster/r.terraflow/types.h
raster/r.uslek/prct2tex.c

and a -Wignored-qualifiers warning fix in r.terraflow/types.h.
Fixes partly #2747.

Fix -Wmissing-field-initializers warnings

---

lib/gis/parser_interface.c

libgis: Fix -Wempty-body warning

---

REQUIREMENTS.md

This replaces #2726 and is a followup of #2729 that was just merged.
Closes #2726

Convert REQUIREMENTS.html contents to REQUIREMENTS.md

---

raster/r.horizon/r.horizon.html

small typo fix. should be backported.

r.horizon manual - fix typo

---

lib/gpde/n_arrays_io.c

Fixes usage of Rast3d_fatal_error()

gpde: fix error handing parameters

---

Dockerfile

(sync to #2771)
- Ubuntu docker base image update
- PDAL compilation: WITH_LASZIP=OFF, keep only WITH_LAZPERF=ON
- new versions:
| Base image   | GRASS GIS  | PROJ  | GDAL  | PDAL  | Python | Image size |
|--------------|------------|-------|-------|-------|--------|------------|
| Ubuntu 22.04 | 8.3.dev    | 8.2.1 | 3.4.1 | 2.4.3 | 3.10.6 | 2.92 GB    |
LAZ-perf is enabled in PDAL, hence both LAS and LAZ files can be imported into GRASS GIS.
TODO in a separate PR: reduce image size

docker: update of Ubuntu image

---

.github/workflows/gcc.yml
display/d.labels/do_labels.c
imagery/i.atcorr/geomcond.cpp
include/grass/gis.h
lib/bitmap/bitmap.c
lib/gmath/la.c
lib/nviz/map_obj.c
lib/ogsf/gvl_calc2.c
ps/ps.map/scan_ref.c
vector/v.in.dxf/dxf_to_vect.c

Fix -Wimplicit-fallthrough warnings

---

.github/workflows/docker.yml

This PR hopefully fixes the currently broken docker action:
* selective sync to workflow in `main`
TODO: not sure about the change in line 43

docker: update actions (G78)

---

.github/FUNDING.yml
.github/workflows/ci.yml
.github/workflows/flake8.yml

Actions are upgraded to latest.
The deprecated Ubuntu 18.04 runner was bumped to 22.04.
Yaml files format are now corrected using yamllint.

CI: upgrade actions, runners, yamllint format (7.8)

---

raster/r.neighbors/main.c

r.neighbors: fix integer overflow

---

.github/workflows/README.md
.github/workflows/additional_checks.yml
.github/workflows/black.yml
.github/workflows/build_osgeo4w.sh
.github/workflows/centos.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create_release_draft.yml
.github/workflows/docker.yml
.github/workflows/flake8.yml
.github/workflows/gcc.yml
.github/workflows/osgeo4w.yml
.github/workflows/pylint.yml
.github/workflows/pytest.yml
.github/workflows/ubuntu.yml

- actions are upgraded to latest
- partial sync to respective files in `main`

CI: upgrade actions and runners (8.2)

---

.github/workflows/osgeo4w.yml

Change multiline string type with no need of the somewhat ambiguous use of blank lines as line brake.

CI: simplify Windows setup yaml file

---

gui/wxpython/rlisetup/wizard.py

wxGUI: fix i18n issues in r.li.setup gui

---

temporal/t.rast.algebra/t.rast.algebra.html

t.rast.algebra: improve neighborhood modifier documentation

---

contributors.csv

As requested in <https://lists.osgeo.org/pipermail/grass-dev/2023-March/095891.html>

contributors: edit Ivan Shmakov's email

---

gui/wxpython/iscatt/plots.py
python/grass/pygrass/raster/buffer.py

pygrass: replace deprecated numpy.bool with bool

---

gui/wxpython/datacatalog/tree.py

Manual backport of 549dee56696 from main.

wxGUI: fix exception when switching to mapset (#2994)

---

imagery/i.segment/iseg.h
imagery/i.segment/mean_shift.c
imagery/i.segment/open_files.c
imagery/i.segment/region_growing.c
include/grass/gis.h
lib/dspf/cube_io.c
lib/segment/format.c
lib/vector/Vlib/open_nat.c
lib/vector/Vlib/read_pg.c
lib/vector/Vlib/write.c
lib/vector/Vlib/write_nat.c
lib/vector/Vlib/write_ogr.c
lib/vector/Vlib/write_pg.c
lib/vector/diglib/cindex_rw.c
lib/vector/diglib/head.c
lib/vector/diglib/plus_struct.c
lib/vector/diglib/spindex_rw.c
raster/r.in.bin/main.c
raster/r.stream.extract/close.c
raster/r.stream.extract/do_astar.c
raster/r.stream.extract/init_search.c
raster/r.stream.extract/load.c
raster/r.stream.extract/streams.c
raster/r.stream.extract/thin.c
raster/r.terraflow/grass2str.h
raster/r.terraflow/main.cpp
raster/r.terraflow/stats.cpp
raster/r.terraflow/sweep.cpp
raster/r.watershed/seg/do_astar.c
raster/r.watershed/seg/do_cum.c

Manual backport to 8.2 of #2807, which addresses gettext issues reported with #2806.

Use 'PRId64' from C99, manual backport of #2807 (8.2)

---

doc/howto_release.md
doc/infrastructure.md

- markdown cosmetics and some outdated version numbers updated.
- fix path to helper script
Note: related PRs for the release branches have been created separately (do not backport this PR).
(replaces #2707)

contributing: minor release procedure updates (main)

---

lib/gis/parser_dependencies.c

Add a note to documentation on requirement to finish the list with a NULL item

doc: Document that lists in parser must be NULL terminated

---

gui/wxpython/modules/vclean.py

wxGUI/vclean: fix StaticLine widget parent win

---

doc/notebooks/parallelization_tutorial.ipynb

Jupyter notebook covering intro to parallelization in GRASS. This content could also be turned into manual page.

docs: add notebook tutorial on parallelization

---

doc/python/raster_example_ctypes.py
doc/python/vector_example_ctypes.py

in Python3, it was replaced by input()

doc examples: remove a call of non-existent function raw_input()

---

doc/howto_release.md

- finetuning of instructions after last 8.3.0 release
-  markdown prettified with: `npx prettier --print-width 80 -w doc/howto_release.md`

docs: update howto_release.md (G83)

---

doc/infrastructure.md

- add Weblate, remove Transifex (after migration to OSGeo Weblate)
- fix some leftover G7 -> G8
- major markdown cleanup with `npx prettier --print-width 80 -w  doc/infrastructure.md`

docs: update and cleanup of infrastructure.md

---

gui/wxpython/gmodeler/g_gui_gmodeler_zipcodes_avg_elevation.gxm

the old version was outdated - some features (parameterization, param order) is done in a different way nowadays

wxGUI/gmodeler: update sample model

---

scripts/v.db.join/v.db.join.py

This PR adds exclude_columns= option to exclude certain columns from other table (e.g., cat).

v.db.join: Add exclude_columns= option

---

gui/wxpython/lmgr/layertree.py

wxGUI/lmgr: fix unfocused Layers pane wx.ListCtrl widget row background color

---

raster/r.walk/r.walk.html

Add text to clarify friction map requirements and values.

docs: update friction map info for r.walk.html

---

doc/infrastructure.md

Describe in `infrastructure.md` how the GRASS docker images are created.

docs: add GRASS docker section to infrastructure.md

---

gui/wxpython/core/gcmd.py
gui/wxpython/gui_core/forms.py

wxGUI/history: fix printing module GUI stderr inside wxGUI Console

---

.flake8
gui/wxpython/core/globalvar.py
gui/wxpython/history/browser.py
gui/wxpython/lmgr/frame.py
gui/wxpython/main_window/frame.py

Fixes #3301.
https://github.com/OSGeo/grass/assets/50632337/fd7433ed-bb15-4c78-b84f-85f7295aa808

wxGUI/history: enable run special command e.g. d.rast, d.vect etc., as well as from the wxGUI Console

---

README.md

docs: add openssf Scorecard and Best Practices Badge to README.md

---

configure
configure.ac

Closes https://github.com/OSGeo/grass/issues/3343

configure: fail configuration with missing lex/flex

---

gui/wxpython/gmodeler/frame.py

This PR improves a bit positioning of new shapes added to the model.
Current behaviour:
[Screencast from 2024-01-22 15-28-06.webm](https://github.com/OSGeo/grass/assets/5683186/d906a593-8267-43bb-85bc-759fd3c46074)
New behaviour:
[Screencast from 2024-01-22 15-22-36.webm](https://github.com/OSGeo/grass/assets/5683186/18c67654-637a-49f1-9bfb-a2727759b496)

Graphical Modeler: improve GetNewShapePos()

---

gui/wxpython/core/gconsole.py

Replaces #3373.
Explanation: https://github.com/OSGeo/grass/pull/3373#issuecomment-1908643261

GUI: sync GConsole skipInterface handling with g.parser

---

raster/r.texture/r.texture.html

This PR is an attempt to fill in the missing texture measure explanations.

docs: r.texture manual texture measure explanations

---

raster/r.mapcalc/Makefile

Minor simplification of #3415.

r.mapcalc: simplify Makefile rule

---

gui/wxpython/lmgr/layertree.py

wxGUI/lmgr: allow change group layer opacity level

---

db/drivers/mysql/db.c

Improving (print debug info) PR #3612.

db/drivers/mysql: print debug info for setting MySQL ANSI SQL mode

---

lib/init/grass.html
lib/init/grass.py

Renaming location to project for grass.py with backwards compatibility.

init: renaming location to project for grass.py init script

---

gui/wxpython/history/browser.py
gui/wxpython/history/tree.py

Fixes https://github.com/OSGeo/grass/issues/3713.
(besides that it also fixes the problem from here https://github.com/OSGeo/grass/pull/3712 and makes some mini code improvements).

wxGUI/history: update cross to green check after updating to current region

---

AUTHORS
COPYING
raster/r.carve/README
raster/r.carve/r.carve.html
raster/r.flow/r.flow.html
raster/r.sim/r.sim.sediment/r.sim.sediment.html
raster/r.terraflow/r.terraflow.html
raster/r.watershed/front/r.watershed.html
scripts/r.fillnulls/r.fillnulls.html
vector/v.surf.rst/v.surf.rst.html
vector/v.vol.rst/v.vol.rst.html

Replace www4.ncsu.edu with fatra.cnr.ncsu.edu.

manual: update broken URLs

---

utils/generate_release_notes.py

This extends the API of the release notes generator to check a string (title) provided in command line against the categories provided in utils/release.yml. If there is no match, a message is printed and the process exits with non-zero return code. There is category "other changes", so non-zero may or may not mean a failure.
This does not do the checking, only provides the API to implement it.

contributing: Add API to check PR titles

---

gui/wxpython/mapswipe/frame.py

wxGUI/mapswipe: fix map image flickering if position is changed by sash

---

gui/wxpython/docs/wxgui_sphinx/conf.py
renovate.json5

Currently, pre-commit, when run on all code, some files need to be fixed (ie: trailing whitespace)
This is a prerequisite to having my other PRs working when submitted.

style: Apply missing pre-commit fixes

---

scripts/r.import/r.import.py

no added value in leaving an if clause just to do the same check

r.import: avoid duplicated if check

---

utils/generate_release_notes.py

* Show name, not just username, for new contributors if available and different from the username using GitHub API.
* Fix heading level for What's changed section.
* Add empty Highlights section with a call to fill it.
* Update to the current badge image for Binder badge.

contributing: Refine generated release notes

---

imagery/i.segment/parse_args.c
lib/dspf/cube_io.c

Remove some unused variables, thanks to cppcheck

style: Remove some unused variables

---

gui/wxpython/gmodeler/dialogs.py

* meanwhile, fix the button size to see them in the default pop-up
* fix #3862

wxGUI/gmodeler: fix conflicting flags in 'Create relation' dialog

---

gui/wxpython/gmodeler/panels.py

wxGUI/gmodeler: fix adding data from menu

---

flake.nix

* inherit build dependencies from grass package
* add `dev-help` function

packaging: improve nix development environment

---

.github/workflows/test-nix.yml
flake.nix
package.nix

CI: add nix package build test

---

gui/wxpython/gmodeler/model.py
gui/wxpython/gui_core/forms.py
gui/wxpython/psmap/dialogs.py
gui/wxpython/vnet/vnet_data.py
pyproject.toml

Ruff rules: https://docs.astral.sh/ruff/rules/not-in-test/ and https://docs.astral.sh/ruff/rules/not-is-test/
Combined these two fixes in one PR as they were similar enough

style: Fix not-in-test (E713) and not-is-test (E714)

---

gui/wxpython/core/render.py
gui/wxpython/core/utils.py
gui/wxpython/gmodeler/dialogs.py
gui/wxpython/gmodeler/model.py
gui/wxpython/gui_core/forms.py
gui/wxpython/gui_core/gselect.py
gui/wxpython/lmgr/frame.py
gui/wxpython/main_window/frame.py
gui/wxpython/modules/colorrules.py
gui/wxpython/timeline/frame.py
gui/wxpython/tplot/frame.py
pyproject.toml
python/grass/script/core.py
python/grass/semantic_label/reader.py

Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-map/
Related Pylint rule: [consider-using-generator / R1728](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/consider-using-generator.html)

style: Fix unnecessary-map (C417)

---

gui/wxpython/psmap/instructions.py
pyproject.toml
python/grass/script/task.py
raster/r.solute.transport/example.py

Ruff rule: https://docs.astral.sh/ruff/rules/empty-comment/

style: Fix empty-comment (PLR2044)

---

pyproject.toml
python/grass/imaging/images2swf.py

Ruff rule: https://docs.astral.sh/ruff/rules/f-string-number-format/

style: Fix f-string-number-format (FURB116)

---

raster3d/r3.in.v5d/v5d.c

This pull request removes unused variables identified by cppcheck.

r3.in.v5d: Remove unused variables

---

gui/wxpython/animation/frame.py
gui/wxpython/gmodeler/dialogs.py
gui/wxpython/gmodeler/panels.py
gui/wxpython/gui_core/forms.py
gui/wxpython/gui_core/menu.py
gui/wxpython/gui_core/prompt.py
gui/wxpython/gui_core/widgets.py
gui/wxpython/history/tree.py
gui/wxpython/iclass/frame.py
gui/wxpython/lmgr/frame.py
gui/wxpython/lmgr/layertree.py
gui/wxpython/main_window/frame.py
gui/wxpython/mapdisp/frame.py
gui/wxpython/mapdisp/main.py
gui/wxpython/mapswipe/frame.py
gui/wxpython/rdigit/g.gui.rdigit.py
gui/wxpython/vdigit/g.gui.vdigit.py
pyproject.toml

This reverts commit 0cc7cbf610e889075b8f465eecb0f319737b7456.
Fixes #4124

style: Revert "style: Fixes some unnecessary-lambda (PLW0108) (#3956)"

---

gui/wxpython/gui_core/widgets.py
gui/wxpython/modules/colorrules.py
pyproject.toml
scripts/v.pack/v.pack.py

Ruff rule: https://docs.astral.sh/ruff/rules/useless-import-alias/
3 instances fixed

style: Fix useless-import-alias (PLC0414)

---

gui/wxpython/animation/data.py
gui/wxpython/gmodeler/model.py
gui/wxpython/iscatt/core_c.py
lib/init/grass.py
pyproject.toml
python/grass/pygrass/modules/grid/grid.py
scripts/g.extension/g.extension.py

Ruff rule: https://docs.astral.sh/ruff/rules/extraneous-parentheses/
7 instances fixed

style: Fix extraneous-parentheses (UP034)

---

gui/wxpython/datacatalog/tree.py
gui/wxpython/gmodeler/model.py
pyproject.toml
python/grass/temporal/temporal_algebra.py
python/grass/temporal/temporal_granularity.py
scripts/i.pansharpen/i.pansharpen.py
scripts/r.pack/r.pack.py
temporal/t.unregister/t.unregister.py
vector/v.univar/testsuite/test_v_univar.py

Ruff rule: https://docs.astral.sh/ruff/rules/dict-index-missing-items/
9 instances solved

style: Fix dict-index-missing-items (PLC0206)

---

general/g.region/testsuite/test_g_region.py

following up on https://github.com/OSGeo/grass/pull/3941#issuecomment-2283000362

g.region: fix ruff lint error in tests

---

db/db.describe/main.c

Fix issue reported in https://github.com/OSGeo/grass/pull/4021#issuecomment-2298894298.

db.describe: fix illegal memory access report

---

doc/notebooks/jupyter_tutorial.ipynb

- Clarify using different backends
- Fix icons

grass.jupyter: Clarify InteractiveMap documentation

---

gui/wxpython/gui_core/forms.py

Fixes  #4254 (verbose checkbox behavior). Introduced in f99780c.

GUI: fix verbose checkbox behavior in tool dialogs

---

general/g.version/g.version.html
gui/wxpython/gcp/manager.py
gui/wxpython/image2target/ii2t_manager.py
gui/wxpython/photo2image/ip2i_manager.py
gui/wxpython/vnet/widgets.py

---
#4277
---
just code changed from `ColumnSorterMixin(self, ncols)` to `ColumnSorterMixin.__init__(self, ncols)`

GUI: fix ColumnSorterMixin regression

---

doc/development/rfc/README.md
doc/development/rfc/version_numbering.md

- add list of RFCs with their status
- fix missing RFC number in `version_numbering.md`

docs: add README.md to doc/development/rfc/

---

.flake8
gui/wxpython/gui_core/gselect.py
gui/wxpython/gui_core/preferences.py
gui/wxpython/gui_core/widgets.py

Removed extra `#` to fix the `E266 too many leading '#' for block comment` for all files in `gui_core/`

wxGUI: Fixed E266 - extra '#' for comments in gui_core/

---

gui/wxpython/image2target/g.gui.image2target.py
gui/wxpython/image2target/ii2t_statusbar.py
gui/wxpython/photo2image/g.gui.photo2image.py
gui/wxpython/photo2image/ip2i_statusbar.py

Just to be clear that I did not create these files, I'm removing my name which was copy-pasted into these files while duplicating the code from somewhere else.

style: Remove misleading author info from wxGUI photo and image code

---

gui/wxpython/gmodeler/canvas.py
gui/wxpython/gmodeler/model.py
pyproject.toml

Merges multiple `isinstance` calls with one with a tuple of classes to check against.
Ruff rule: https://docs.astral.sh/ruff/rules/duplicate-isinstance-call/

style: Fix duplicate-isinstance-call (SIM101)

---

imagery/i.atcorr/i.atcorr.html

numbering of first AVIRIS band and bold font for first appearance of sensors names

i.atcorr: update man page to fix numbering of AVIRIS bands and make style consistent

---

.flake8
scripts/v.what.strds/v.what.strds.py

Fixed `E722`, Specified following exceptions
- `FileNotFoundError` incase file is not present
- `CalledModuleError` for GIS exceptions

grass.script: Fixed E722 in v.what.shrds/

---

.flake8
gui/wxpython/vnet/dialogs.py
gui/wxpython/vnet/toolbars.py
gui/wxpython/vnet/vnet_core.py
gui/wxpython/vnet/vnet_data.py
gui/wxpython/vnet/vnet_utils.py
gui/wxpython/vnet/widgets.py

Removed unused variables in F841 as none of them call a constructor.

wxGUI: Fixed F841 in vnet/

---

gui/wxpython/iclass/frame.py
gui/wxpython/mapdisp/frame.py
gui/wxpython/vnet/dialogs.py
gui/wxpython/vnet/vnet_core.py
pyproject.toml
python/grass/temporal/register.py
scripts/i.pansharpen/i.pansharpen.py

Ruff rule: https://docs.astral.sh/ruff/rules/if-else-block-instead-of-dict-get/
Python docs: https://docs.python.org/3/library/stdtypes.html#dict.get
The get method never raises a KeyError.

style: Fix if-else-block-instead-of-dict-get (SIM401)

---

.flake8
gui/wxpython/photo2image/ip2i_manager.py

Replaced `bare except` with a `CalledModuleError` for `gs.RunCommand`
Also removed flake8 errors which have been resolved/not present

wxGUI: FIxed bare except in photo2image/

---

gui/wxpython/wxgui.py

Reverted https://github.com/OSGeo/grass/pull/4542#issuecomment-2438550121

wxGUI: Reverted unused variable fix in wxgui/

---

gui/wxpython/nviz/wxnviz.py

Fixes #4580 introduced in #4567. Imports were from wrong files. There are still some issues with nviz, but that might be due to some other changes I need to investigate.

wxGUI/nviz: fix imports

---

.flake8
scripts/i.pansharpen/i.pansharpen.py

FIxed following:
- Added `CalledModuleError` for `gs.run_command`
- Added `Exception` for `gs.map_calcstart` as I wasn't able to figure what else would be applicable. Maybe `CalledModuleError` as well?

i.pansharpen: Fixed bare except clause 

---

.flake8
scripts/d.frame/d.frame.py

Fixed bare except clause by adding `IndexError` and `ValueError`

d.frame: Fix bare except clause

---

imagery/i.vi/main.c

Addressing request in Issue #4652.

i.vi: Add ndwi color table to output

---

.flake8
gui/wxpython/rdigit/g.gui.rdigit.py

wxGUI: Removed unused variable from rdigit/

---

.flake8
gui/wxpython/iclass/digit.py

Removed `*` imports and specified imports in `iclass/digit.py`

wxGUI: Removed star imports in digit.py

---

ps/ps.map/ps_vlegend.c

This pull request fixes issue identified by Coverity Scan (CID : 1207603, 1207606).

ps.map: Fix Resource Leak issue in ps_vlegend.c

---

gui/wxpython/iscatt/core_c.py

Modules were mapped to wrong libraries. Mapped them correctly as per https://github.com/OSGeo/grass/pull/4427#issuecomment-2471675396

wxGUI: Fixed modules import to correct libraries

---

macosx/ReadMe.md

Commit e67351a4127bf0b40fc485086d9b1ea9170add22 renamed the requirements guide. This PR adjusts sources to changes.

docs: update requirements guide

---

vector/v.mkgrid/v.mkgrid.html

Fixed manual typos and a couple of small changes.

docs: v.mkgrid.html fix manual typos

---

vector/v.net.timetable/v.net.timetable.html

"identificator" changed to "identifier"

docs: v.net.timetable.html fix manual typo

---

.flake8
gui/wxpython/location_wizard/dialogs.py

Removed the variable and called the function constructor directly

wxGUI: Removed unused variable in location_wizard/dialogs.py

---

.flake8
gui/wxpython/mapdisp/statusbar.py

Removed unused variable `e` from statusbar

wxGUI: Removed unused variable in mapdisp/statusbar.py

---

raster/r.resamp.filter/r.resamp.filter.html

Update the manual according to #2569 
Fixes #2569

r.resamp.filter: update manual

---

.flake8
gui/wxpython/iclass/frame.py

Specified imports and removed star imports

wxGUI: Specified imports in iclass/frame.py to fix F403

---

display/d.text/test.py
gui/wxpython/core/debug.py
gui/wxpython/core/gconsole.py
gui/wxpython/core/utils.py
gui/wxpython/mapwin/buffered.py
gui/wxpython/mapwin/graphics.py
gui/wxpython/vdigit/wxdisplay.py
gui/wxpython/vnet/vnet_data.py
gui/wxpython/vnet/widgets.py
pyproject.toml
python/grass/imaging/images2ims.py
python/grass/imaging/images2swf.py
python/grass/temporal/spatial_extent.py
python/grass/temporal/temporal_algebra.py
python/grass/temporal/temporal_raster3d_algebra.py
python/grass/temporal/temporal_raster_algebra.py
temporal/t.rast.accdetect/t.rast.accdetect.py

Pylint rule: https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/chained-comparison.html

style: Fix R1716: Simplify chained comparison between the operands (chained-comparison)

---

gui/wxpython/animation/utils.py
gui/wxpython/gui_core/gselect.py
gui/wxpython/gui_core/menu.py
gui/wxpython/gui_core/toolbars.py
gui/wxpython/iscatt/iscatt_core.py
gui/wxpython/iscatt/toolbars.py
gui/wxpython/lmgr/frame.py
gui/wxpython/main_window/frame.py
gui/wxpython/mapwin/base.py
gui/wxpython/mapwin/buffered.py
gui/wxpython/mapwin/graphics.py
gui/wxpython/nviz/mapwindow.py
gui/wxpython/nviz/tools.py
gui/wxpython/nviz/workspace.py
gui/wxpython/rlisetup/wizard.py
gui/wxpython/timeline/frame.py
gui/wxpython/tplot/frame.py
gui/wxpython/vdigit/wxdigit.py

Analogous to #4907, but for files inside gui/.

gui: Fix typos and formatting of docstring parameters

---

python/grass/benchmark/results.py
python/grass/benchmark/testsuite/test_benchmark.py
python/grass/benchmark/testsuite/test_benchmark_cli.py
python/grass/grassdb/checks.py
python/grass/gunittest/loader.py
python/grass/gunittest/reporters.py
python/grass/imaging/images2gif.py
python/grass/imaging/images2swf.py
python/grass/jupyter/baseseriesmap.py
python/grass/pygrass/modules/grid/grid.py
python/grass/pygrass/modules/grid/split.py
python/grass/pygrass/modules/interface/module.py
python/grass/pygrass/modules/interface/typedict.py
python/grass/pygrass/rpc/__init__.py
python/grass/pygrass/utils.py
python/grass/pygrass/vector/__init__.py
python/grass/pygrass/vector/geometry.py
python/grass/script/core.py
python/grass/script/raster.py
python/grass/script/task.py
python/grass/semantic_label/reader.py
python/grass/temporal/abstract_dataset.py
python/grass/temporal/list_stds.py
python/grass/temporal/register.py
python/grass/temporal/stds_import.py

This PR picks all the refactorings made by the pyrefact tool concerning list and dict comprehensions. They were adjusted to minimize the diff and keep the comments

python: Use comprehensions when initializing lists and dicts

---

raster3d/r3.out.v5d/main.c

This pull request fixes issue identified by Coverity Scan (CID : 1207838)
Used G_free() to fix this issue

r3.out.v5d: Fix Resource Leak issue in main.c

---

.flake8
gui/wxpython/mapdisp/main.py

Added ValueError for string/split operations and IndexError for indexing

wxGUI: Fixed bare except in mapdisp/main.py

---

raster/r.geomorphon/r.geomorphon.html

Rereading my previous commit https://github.com/OSGeo/grass/pull/4831/ , I feel like these changes better reflect the original author's intent and are more concise.

doc: Reword text to be less verbose in r.geomorphon

---

gui/wxpython/animation/data.py
gui/wxpython/animation/dialogs.py
gui/wxpython/dbmgr/vinfo.py
gui/wxpython/gui_core/forms.py
gui/wxpython/gui_core/vselect.py
gui/wxpython/location_wizard/wizard.py
gui/wxpython/mapdisp/frame.py
gui/wxpython/psmap/dialogs.py
gui/wxpython/psmap/instructions.py
gui/wxpython/psmap/utils.py

Standardized `ScriptError` imports across `gui/` to fix #4838

wxGUI: Update 'ScriptError' to be correctly imported from `grass.exceptions`

---

pyproject.toml

Enable new group of rules, handle renamed rules since first configuration, remove fixed rules.

style: Ruff rules maintenance

---

.gitignore

I've added common Python virtual directories (`venv/`, etc..) and `.vscode/` to the .gitignore file.

config: Updated .gitignore paths to ignore python environments and vscode settings

---

scripts/g.manual/g.manual.py

g.manual looks for markdown docs and if it's not there tries the legacy documentation.

g.manual: use new markdown docs

---

docker/alpine/Dockerfile

If my hypothesis in https://github.com/OSGeo/grass/pull/5108#issuecomment-2657686367 is right, this should solve the build failure

docker: Fix git clone path in Dockerfile for gdal-grass

---

.markdownlint.yml
display/d.rast.arrow/d.rast.arrow.md
imagery/i.atcorr/i.atcorr.md
imagery/i.rectify/i.rectify.md
raster/r.in.lidar/r.in.lidar.md
raster/r.in.pdal/r.in.pdal.md
raster/r.in.xyz/r.in.xyz.md
raster/r.series.accumulate/r.series.accumulate.md
raster/r.sim/r.sim.sediment/r.sim.sediment.md
raster/r.stream.extract/r.stream.extract.md
raster/r.terraflow/r.terraflow.md
raster/r.viewshed/r.viewshed.md
raster/r.watershed/front/r.watershed.md
vector/v.rectify/v.rectify.md
vector/v.to.db/v.to.db.md

Fixes remaining no-inline-html, #5148 needs to be merged first and this updated, right now the CI will fail.

docs: fix remaining no-inline-html

---

.markdownlint.yml
display/d.rast.arrow/d.rast.arrow.md
doc/examples/gui/wxpython/g.gui.example.md
doc/gui/wxpython/example/g.gui.example.md
general/g.mapsets/g.mapsets.md
imagery/i.maxlik/i.maxlik.md
imagery/i.segment/i.segment.md
ps/ps.map/ps.map.md
raster/r.horizon/r.horizon.md
raster/r.in.lidar/r.in.lidar.md
raster/r.in.pdal/r.in.pdal.md
raster/r.li/r.li.padcv/r.li.padcv.md
raster3d/r3.flow/r3.flow.md
raster3d/r3.in.lidar/r3.in.lidar.md
scripts/d.to.rast/d.to.rast.md
scripts/r.rgb/r.rgb.md
scripts/v.dissolve/v.dissolve.md
vector/v.buffer/v.buffer.md
vector/v.cluster/v.cluster.md
vector/v.decimate/v.decimate.md
vector/v.lidar.edgedetection/v.lidar.edgedetection.md
vector/v.mkgrid/v.mkgrid.md
vector/v.net.visibility/v.net.visibility.md
vector/v.qcount/v.qcount.md
vector/v.segment/v.segment.md
vector/v.vect.stats/v.vect.stats.md

Using caption if there otherwise the name of the image file.

docs: fix no-alt-text

---

gui/wxpython/gmodeler/panels.py
pyproject.toml

Fixed `SIM115` and subsequently raised `FURB103`

style: SIM115 / FURB103: Replace explicit file open/close with Path.write_text()

---

lib/imagery/Makefile

docs: fix missing image in imageryintro.md

---

gui/wxpython/psmap/utils.py
pyproject.toml

Added specific rule code F401 to the PIL import noqa comment to silence "imported but unused" warning.

wxGUI: Fix PGH004: Add specific rule code F401 to noqa comment

---

lib/manage/do_copy.c

This pull request fixes issue identified by Coverity Scan (CID : 1207901)

lib/manage: Fix Resource Leak Issue in do_copy.c

---

raster/CMakeLists.txt

Build `r.mask.status` also with CMake.

cmake: build 'r.mask.status'

---

raster/r.kappa/main.c
raster/r.kappa/stats.c

This pull request fixes issue identified by Coverity Scan (CID : 1208250)

r.kappa: Copy into fix buffer size issue

---

lib/gis/units.c

Haven't tested but this looks like a bug fix.

lib/gis: fix source typo

---

man/build.py
man/build_rest.py
man/mkdocs/mkdocs.yml

docs: fix typos in man/ directory

---

gui/wxpython/core/utils.py
gui/wxpython/dbmgr/base.py
gui/wxpython/dbmgr/dialogs.py
gui/wxpython/gmodeler/model.py
gui/wxpython/gui_core/dialogs.py
gui/wxpython/gui_core/forms.py
gui/wxpython/gui_core/mapdisp.py
gui/wxpython/gui_core/simplelmgr.py
gui/wxpython/image2target/ii2t_manager.py
gui/wxpython/lmgr/layertree.py
gui/wxpython/main_window/page.py
gui/wxpython/mapdisp/main.py
gui/wxpython/mapwin/buffered.py
gui/wxpython/modules/colorrules.py
gui/wxpython/modules/import_export.py
gui/wxpython/nviz/mapwindow.py
gui/wxpython/nviz/wxnviz.py
gui/wxpython/photo2image/g.gui.photo2image.py
gui/wxpython/psmap/dialogs.py
gui/wxpython/rdigit/g.gui.rdigit.py
gui/wxpython/rlisetup/g.gui.rlisetup.html
gui/wxpython/rlisetup/g.gui.rlisetup.md
gui/wxpython/startup/locdownload.py
gui/wxpython/tplot/frame.py
gui/wxpython/vdigit/g.gui.vdigit.py
gui/wxpython/xml/grass-gxw.dtd

gui: fix typos

---

vector/v.surf.idw/read_sites.c

This pull request fixes issue identified by Coverity Scan (CID : 1207627)
Used `G_free()` to fix this issue.

v.surf.idw: Fix Resource Leak issue in read_sites.c

---

cmake/find_scripts/FindSQLite.cmake
cmake/modules/CheckDependentLibraries.cmake
db/drivers/CMakeLists.txt
general/CMakeLists.txt
include/config.h.cmake.in

Use imported SQLite target, drop custom FindSQLite.

cmake: use of imported SQLite target, drop custom FindSQLite

---

display/d.histogram/bar.c
display/d.histogram/get_stats.c
display/d.histogram/pie.c
display/d.labels/d.labels.html
display/d.labels/d.labels.md
display/d.legend/get_stats.c
display/d.vect/d.vect.html
display/d.vect/d.vect.md
display/displaydrivers.html
display/displaydrivers.md

display: fix typos

---

display/d.vect/shape.c
imagery/i.landsat.toar/landsat_met.c

This pull request fixes issue identified by Coverity Scan (CID : 1207875)
Used `Vect_destroy_field_info()` to fix this issue.

d.vect: Fix resource Leak Issue in shape.c

---

lib/ogsf/gk.c
lib/ogsf/gp2.c
lib/ogsf/gs2.c
lib/ogsf/gs3.c
lib/ogsf/gsd_objs.c
lib/ogsf/gsd_prim.c
lib/ogsf/gsd_surf.c
lib/ogsf/gsd_wire.c
lib/ogsf/gvl.c
lib/ogsf/gvld.c

lib/ogsf: fix typos

---

gui/wxpython/mapdisp/main.py
pyproject.toml

Implements a context manager for file operations. The change ensures proper file handling and cleanup by using a with statement when processing files with fileinput.input().

wxGUI: Fix SIM115 by using context managers for file operations in mapdisp

---

pyproject.toml
scripts/i.pansharpen/i.pansharpen.py

Replaced file input with context manager

i.pansharpen: Fix SIM115 warning by using context manager for file operations

---

gui/wxpython/tplot/g.gui.tplot.md
raster/r.in.lidar/r.in.lidar.md

Addresses #5244.
Some of the images were commented out in the html, so I didn't do anything with them.

doc: fix missing images in md files

---

cmake/modules/CheckDependentLibraries.cmake
lib/CMakeLists.txt

cmake: use of imported TIFF target

---

CMakeLists.txt
cmake/modules/CheckDependentLibraries.cmake
cmake/modules/Configure.cmake
general/CMakeLists.txt
lib/CMakeLists.txt

Use imported X11 and OpenGL targets.

cmake: use of imported X11 and OpenGL targets

---

cmake/modules/CheckDependentLibraries.cmake
lib/gis/CMakeLists.txt
raster/r.mapcalc/CMakeLists.txt

cmake: use of imported Threads target

---

.github/workflows/cmake.yml
cmake/modules/CheckDependentLibraries.cmake
lib/gis/CMakeLists.txt

cmake: use of imported BZip2 target

---

vector/v.category/main.c

Addresses the issue mentioned in  https://github.com/OSGeo/grass/pull/5360#issuecomment-2726553066

v.category: fix uninitialised value "format"

---

lib/ogsf/gs3.c

This pull request fixes issue identified by Coverity Scan (CID : 1208113, 1208114, 1208115, 1208116, 1208117, 1270329, 1270332)

lib/ogsf: Fix Resouce Leak issue in gs3.c

---

cmake/ctypesgen.cmake
lib/init/CMakeLists.txt
python/libgrass_interface_generator/CMakeLists.txt

Fix ctypesgen's generation of GRASS API with CMake builds.

cmake: fix ctypesgen's generation of GRASS API

---

doc/development/github_guide.md
doc/examples/notebooks/hydrology.ipynb
doc/examples/python/m.distance.py
doc/examples/vector/TODO
doc/howto_release.md
doc/vector/TODO

docs: fix typos

---

.github/workflows/macos_install.sh
.github/workflows/ubuntu.yml
raster/r.texture/testsuite/test_rtexture.py
raster/r.texture/testsuite/test_rtexture_parallel.py

Hopefully, this works.
Closes #3796

CI: add '-ffp-contract=off' compiler flag to test runners

---

lib/vector/Vlib/buffer2.c
lib/vector/Vlib/close.c
lib/vector/Vlib/e_intersect.c
lib/vector/Vlib/intersect2.c
lib/vector/Vlib/net_build.c
lib/vector/dglib/BUGS
lib/vector/dglib/dglib.dox
lib/vector/dglib/examples/README
lib/vector/dglib/graph.h
lib/vector/dglib/sp-template.c
lib/vector/dglib/type.h
lib/vector/neta/utils.c
lib/vector/rtree/rect.c
lib/vector/vectorlib_faq.dox
lib/vector/vectorlib_topology.dox
lib/vector/vedit/delete.c

lib/vector: fix typos

---

binder/postBuild
binder/requirements.txt
doc/examples/notebooks/hydrology.ipynb
doc/examples/notebooks/jupyter_example.ipynb
doc/examples/notebooks/jupyter_tutorial.ipynb
doc/examples/notebooks/parallelization_tutorial.ipynb
doc/examples/notebooks/scripting_example.ipynb
doc/examples/notebooks/solar_potential.ipynb
doc/examples/notebooks/temporal.ipynb
doc/examples/notebooks/viewshed_analysis.ipynb

* build with PDAL
* fix and unify session initialization
* temporal notebook: replace with official dataset
* GRASS GIS -> GRASS
https://mybinder.org/v2/gh/petrasovaa/grass/binder-fix?labpath=doc%2Fexamples%2Fnotebooks%2Fjupyter_tutorial.ipynb

doc: enable PDAL in binder and fix and unify init calls

---

imagery/i.topo.corr/testsuite/test_i_topo_corr.py

This PR introduces a test suite for the i.topo.corr GRASS GIS module, focusing on validating various topographic correction methods and ensuring consistency in output values.
**Key updates in this PR include:**
**Functionality:**
- Implementation of regression tests for i.topo.corr, covering cosine, c-factor, and percent correction methods.
- Verification of illumination model statistics to ensure correctness.
- Ensuring that the -s flag preserves the original reflectance range and color rules.
**Test Case Additions:**
- Illumination Model Test: Validates that computed illumination values match expected reference statistics.
- Cosine Method Test: Confirms that cosine-based topographic correction produces expected reflectance values.
- C-Factor Method Test: Checks if the c-factor …

i.topo.corr: Add test file

---

lib/init/grass.py

I extracted this commit from a branch where I was queuing up other changes in the file.
Since the changes weren't related to the rest and made it harder to review, I made a separate uncontroversial PR for merging quickly before the rest.

init: Apply isort to imports

---

raster/r.external/proj.c

r.external: Fix Resource Leak issue in proj.c

---

general/g.remove/main.c

I find it unhelpful that `g.remove` is unspecific with its "file not found" message, e.g.
```bash
g.remove -f type=vector 'pattern=voronoi*'
WARNING: No data base element files found
g.remove -f type=raster,vector 'pattern=map*'
WARNING: No data base element files found
g.remove -f type=raster 'pattern=model*'
WARNING: No data base element files found
g.remove -f type=vector 'pattern=ato*'
WARNING: No data base element files found
```
Running this in scripted (cloud) environments may flood the logs with messages not helpful for debugging.
This PR changes the message to
```bash
g.remove -f type=raster 'pattern=bla*'
No file(s) found for type(s): raster
g.remove -f type=region 'pattern=bla*'
No file(s) found for type(s): region
g.remove -f type=all 'pattern=bla*'
No file(s) found for …
```

g.remove: improve user message to contain more details

---

display/d.histogram/pie.c

This pull request fixes issue identified by Coverity Scan (CID : 1208457)

d.histogram: Fix Uninitialized Variable in pie.c

---

raster/r.out.ascii/tests/test_r_out_ascii.py

**Basic ASCII Test (test_ascii_basic):**
- Verifies correct header information (north, south, east, west, rows, cols)
- Checks proper formatting of raster data (3x3 grid with values 1-3)
**SURFER ASCII Grid Test (test_ascii_surfer):**
- Validates DSAA header and grid specifications
- Ensures correct data representation in SURFER format with specified width flag
**MODFLOW ASCII Array Test (test_ascii_modflow):**
- Checks MODFLOW-specific header format
- Verifies proper data output in MODFLOW array style
**File Output Test (test_file_output)**
- Tests the ability to write ASCII output to a file.
- Validates that the file content matches the expected ASCII output format.
**Precision and Null Value Test (test_precision_null)**
- Tests handling of precision and null value flags during ASCII …

r.out.ascii: added test cases for the module

---

man/Makefile
man/mkdocs/overrides/partials/copyright.html

Added notice of NSF funding to the footer of the Mkdocs documentation addressing issue #5522.

docs: Added NSF funding to docs footer

---

raster/r.to.vect/points.c

This pull request fixes issue identified by Coverity Scan (CID : 1208461, 1208459)

r.to.vect: Fix uninitialized variable issue in points.c

---

imagery/i.eb.eta/testsuite/test_i_eb_eta.py

This PR introduces regression tests for the `i.eb.eta` module. The test suite is designed to validate the correctness, numerical stability, and input sensitivity of the evapotranspiration computation. The tests ensure that the module produces expected results for a variety of input configurations.
- **Basic output test**: Verifies correctness using synthetic inputs and compares output raster statistics to a known reference.
- **Numerical stability test**: Ensures stable results with constant net radiation and temperature gradient; checks correlation with evaporative fraction.
- **Net radiation dependency test**: Validates that ET scales proportionally with varying net radiation while keeping other inputs constant.
- **Evaporative fraction dependency test**: Confirms ET output scales …

i.eb.eta: add test file

---

imagery/i.aster.toar/gain_aster.c

This pull request fixes issue identified by Coverity Scan (CID : 1208463)

i.aster.toar: Fix Uninitialized Variable in gain_aster.c

---

.github/workflows/test_thorough.bat

300/328= 0.914634
See https://github.com/OSGeo/grass/issues/5647#issuecomment-2882930010

CI(OSGeo4W): Temporarily lower gunittest test success threshold

---

flake.lock
package.nix

This PR is syncing Nix packaging with the latest version in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/gr/grass/package.nix) and updates nixpkgs version.
This PR is based on changes in https://github.com/OSGeo/grass/pull/5550 .
Keep packaging up-to-date and get the latest versions of build dependencies.
```
nix build .#grass
./result/bin/grass --version
GRASS 8.5.0dev
...
```

nix: update packaging

---

scripts/d.polar/polar_diagram.eps
scripts/d.polar/ps_defs.eps
scripts/g.extension/g.extension.py
scripts/g.extension/testsuite/test_addons_download.py
scripts/i.pansharpen/i.pansharpen.py
scripts/r.colors.stddev/r.colors.stddev.html
scripts/r.colors.stddev/r.colors.stddev.md
scripts/r.in.wms/wms_cap_parsers.py
scripts/v.dissolve/tests/v_dissolve_aggregate_test.py
scripts/v.dissolve/v_dissolve.ipynb
scripts/v.to.lines/v.to.lines.py

docs: fix typos found via codespell in scripts

---

CONTRIBUTING.md

Changed instances written as 'GRASS GIS' to 'GRASS' in the file CONTRIBUTING.md

docs: Changed instances of 'GRASS GIS'

---

README.md

Updating to match new branding.

docs: Changed GRASS GIS to GRASS

---

python/grass/pygrass/vector/table.py

make it clear where the function gets from in the examples

docs: pygrass.vector.table - add missing get_path imports

---

lib/gpde/gpdelib.dox
lib/gpde/n_arrays_calc.c
lib/gpde/n_geom.c
lib/gpde/n_solute_transport.c

lib/gpde: fix typos

---

general/g.mapsets/g.mapsets.html
general/g.mapsets/g.mapsets.md

g.mapsets: fix typos

---

cmake/modules/DevelUtils.cmake
cmake/modules/build_module.cmake
cmake/modules/get_host_arch.cmake

cmake: fix typos

---

lib/gmath/gmathlib.dox
lib/gmath/la.c
lib/gmath/solvers_direct_cholesky_band.c
lib/gmath/solvers_krylov.c

lib/gmath: Fix typos

---

README.md
docker/README.md

This should make the main README.md more useful and readable. The docker part was moved to docker/README.

doc: revise main README.md

---

scripts/g.extension/g.extension.py

g.extension: fix XML element's Truth checking deprecation

---

python/grass/script/core.py

Points to related functions of the same group/set of functionalities
Renders in nice blue bloxes

docs: Add "see also" boxes with cross-refs in grass.script.core docstrings

---

python/grass/app/data.py
python/grass/experimental/create.py
python/grass/experimental/mapset.py
python/grass/gunittest/case.py
python/grass/gunittest/gmodules.py
python/grass/gunittest/main.py
python/grass/jupyter/setup.py
python/grass/script/core.py
python/grass/script/task.py
python/grass/temporal/abstract_space_time_dataset.py
python/grass/temporal/temporal_algebra.py

This contains some new text, where I was interpreting the code where exceptions were raised, in order to document them.
It might conflict with a pending PR that is still pending to finish the checks to merge. It will need to be updated with the main branch in that case.

docs: Format raised exceptions docstrings and cross-references

---

python/grass/script/tests/utils_test.py
python/grass/script/utils.py

grass.script: KeyValue raise AttributeError when expected

---

general/g.list/tests/conftest.py
general/g.list/tests/g_list_test.py

ref: #5848 
This PR adds a regression test suite for the `g.list` module. These tests are intended to serve as regression checks for upcoming PRs that add JSON support to `g.list`.

g.list: Add test file

---

raster/r.colors.out/r.colors.out.md
raster/r.colors.out/r3.colors.out.md
raster/r.describe/r.describe.md
vector/v.colors.out/v.colors.out.md

Examples for json output in r.describe, r.colors.out, r3.colors.out and v.colors.out.

doc: json examples for r.describe and r/r3/v.colors.out

---

vector/v.lrs/v.lrs.segment/main.c

This pull request fixes issue identified by Coverity Scan (CID : 1207846).
Used Vect_destroy_cats_struct() to fix this issue.

v.lrs.segment: Fix Resource Leak Issue in main.c

---

lib/pngdriver/read_ppm.c

This pull request fixes issue identified by Coverity Scan (CID : 1207220, 1207235)
added a check to fgetc()

lib/pngdriver: Fix unchecked return value in read_ppm.c

---

raster/r.volume/testsuite/test_r_volume.py

ref: #5949 
This PR adds a regression test suite for the `r.volume` module. These tests are intended to serve as regression checks for upcoming PRs that add JSON support to `r.volume`.

r.volume: Add test file

---

python/grass/script/vector.py

This PR uses the CSV output of v.db.select, hopefully fixing #2576.

grass.script.vector_db_select: use v.db.select CSV output for safer parsing

---

raster/r.fill.dir/main.c

This Pull Request fixes issue identified by Coverity Scan (CID : 1208252)
strcpy() changed to G_strlcpy()

r.fill.dir: Fix Copy into Buffer Size issues in main.c

---

raster/r.distance/testsuite/test_distance.py

ref: #6135 
This PR updates the regression test suite for the `r.distance` module by adding and revising test cases to cover all scenarios, ensuring that future changes, particularly the upcoming addition of JSON support, do not break existing behavior.

r.distance: Update existing test cases

---

gui/wxpython/dbmgr/base.py

wxGUI/dbmgr: calculate column statistics for SQL filtered or interactively selected rows

---

gui/wxpython/dbmgr/dialogs.py

wxGUI/dbmgr: fix Edit selected record dialog date column type TextCtrl widget validator/hint

---

vector/v.surf.bspline/main.c

This pull request fixes issue identified by Coverity Scan (CID : 1501263)

v.surf.bspline: Fix Uninitialized Variable Issue in main.c

---

vector/conftest.py
vector/v.edit/tests/v_edit_test.py
vector/v.edit/v.edit.md

Add tests for create, add, delete, addcat, and delcat, but also clarify in the documentation how layer and cats is used with addcat and delcat.

v.edit: Clarify cats and layer use, add tests

---

vector/v.lrs/lib/lrs.c

This pull request fixes issue identified by Coverity Scan ( CID: 1207857, 1588957)

v.lrs: Fix Resource Leak Issue in lrs.c

---

lib/gpde/n_les_assemble.c

This pull request fixes issue identified by Coverity Scan (CID : 1613889, 1613891)

lib/gpde: Fix Resource Leak Issue in n_les_assemble.c

---

raster/r.li/r.li.daemon/list.c

This pull request fixes issue identified by Coverity Scan (CID : 1208197)

r.li.daemon: Fix Dereference before null check issue in list.c

---

raster/r.out.mpeg/main.c
raster/r.out.mpeg/write.c

This pull request fixes issue identified by Coverity Scan (CID : 1207228, 1207257)

r.out.mpeg: Fix unchecked return value from library

---

display/d.histogram/bar.c

This pull request fixes issue identified by Coverity Scan ( CID : 1208256)

d.histogram: Fix Copy Buffer Size issue

---

vector/v.out.ogr/export_areas_fast.c

Address newly detected Coverity Scan CID 1620884 issue.

v.out.ogr: free allocated line_cats structure

---

raster/r.contour/cont.c

This pull request fixes issue identified by Coverity Scan (CID : 1207822)

r.contour: Fix Resource Leak Issue in cont.c

---

lib/vector/Vlib/snap.c

This pull request fixes issue identified by Coverity Scan (CID : 1262580)

lib/vector/Vlib: Fix Unchecked return value from library in snap.c

---

raster/r.geomorphon/pattern.c

This pull request fixes issue identified by Coverity Scan (CID : 1415711, 1415720, 1415732, 1415762)

r.geomorphon: Fix Uninitialized Variable Issue in pattern.c

---

lib/db/dbmi_client/table.c

This pull request fixes issue identified by Coverity Scan (CID : 1208260)

lib: Fix Copy into fixed buffer size issues in table.c

---

doc/jupyter_intro.md

Adding missing import in an example.

doc: missing import in jupyter doc

---

lib/nviz/nviz.c

This pull request fixes issue identified by Coverity Scan (CID : 1208152, 1208153)

lib/nviz: Fix Resource Leak issue in nviz.c

---

db/drivers/ogr/execute.c

This pull request fixes issue identified by Coverity Scan (CID : 1207692, 1207693, 1207694)

db.drivers: Fix Resource Leak Issue in execute.c

---

lib/gis/parser_wps.c

This pull request fixes issue identified by Coverity Scan (CID : 1207420)

lib/gis: Fix Dereference after NULL check issue in parser_wps.c
