OSGeo/grass

- lib/db/dbmi_client/start.c
> dbmi_client_start_driver: check if driver name is null or empty (#2131)

- gui/wxpython/core/gconsole.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/mapdisp.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/statusbar.py
- gui/wxpython/main_window/frame.py
- gui/wxpython/mapdisp/statusbar.py
It moves statusbar Mask widget to the main statusbar. It is also changing the way Mask is updated - now it is updated using signals and method RefreshMask.
> wxGUI: Move SbMask widget to main window statusbar

- vector/v.to.db/main.c
with `option=query`, query columns can not only be columns, but also SQL expressions like count(x) or avg(x). In these cases the check for column type fails, and it is up to the user to first create a new column of the appropriate type for storing results, before running `v.to.db`.
> v.to.db: fix option=query

- scripts/v.import/v.import.html
Substitute 'GDAL needs to be installed to use **v.in.ogr**' with 'GDAL needs to be installed to use **v.import**' in the [v.import](https://grass.osgeo.org/grass78/manuals/v.import.html) documentation.
> Fix typo in v.import documentation

- gui/wxpython/gui_core/mapdisp.py
- gui/wxpython/mapdisp/frame.py
- gui/wxpython/mapdisp/properties.py
- gui/wxpython/mapwin/base.py
This PR creates a new Statusbar page in Map Display settings and move there "Use defined projection checkbox".
> wxGUI: Projection checkbox from Map Display statusbar moved to Map Display Settings

- gui/wxpython/core/render.py
When GUI in single window layout starts it prints "Invalid map size" error to console. It's not helpful and there is no actual problem to deal with.
> wxGUI: remove unnecessary printing of invalid map size

- gui/wxpython/core/gcmd.py
- gui/wxpython/core/gconsole.py
- gui/wxpython/core/gthread.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/nviz/mapwindow.py
Simple replace setDaemon(True) -> daemon = True, see https://github.com/python/cpython/pull/25174
> wxGUI: Thread.setDaemon deprecated with Python 3.10

- python/libgrass_interface_generator/README.md
- python/libgrass_interface_generator/ctypesgen/printer_python/printer.py
Remove unnamed zero bit sized structure members  from ctypesgen generated python files, as they are not supported by Ctypes.
Addresses issue reported in #2073
What I initially thought to be a trivial fix, turned out not being so.
E.g. to be able to evaluate the expression
```
((8 * (sizeof(time_t) - sizeof(c_long))) * (1234 == 4321))
```
, `sizeof`, `time_t` and `c_long` need to be known (imported/defined). This was not possible within ctyepesgen, if we want code for a more general use. All these functions/definitions are known in the generated python file.
My solution was therefore to inject a "self healing" code in the ctypesgen generated python file, removing unneeded and unsupported zero bitsized structure members (and in the process this self healing code is itself removed, think …
> ctypesgen: Remove unnamed zero bit sized structure members

- .github/workflows/additional_checks.yml
This adds an new workflow with one new job which is check of CRLF line endings.
The idea is that this workflow (and job) can by extended to have more steps which are
other simple, custom checks like that (like those in utils or other 3rd party checks which are not proper linters).
The check excludes those where we expect CRLF (Windows specific files) or allow anything, i.e., not check at all (data for tests).
The CRFL check used is a simple action erclu/check-crlf which is used, e.g., in MapServer.
Alternatives seem to be AODocs/check-eol which uses .gitattributes and microsoftgraph/eol-blocker which interacts more with the PR.
> CI: Add check for CRLF line endings

- utils/mkhtml.py
Fixes #2137, #2138. Suggested by https://github.com/OSGeo/grass/issues/2137#issuecomment-1024585007.
Note:
Git repository build: core modules manuals have git commit info
Non Git repository build: some core modules manuals have git commit info and some haven't, due GitHub API server error `urllib.error.HTTPError: HTTP Error 403: rate limit exceeded`
> utils/mkhtml: fix print warning/fatal message during compilation

- raster/r.colors/rules.c
When applying scale and/or offset to `r.colors`, color rules were written out in reverse order. This PR fixes the ordering of color rules.
GRASS itself has no problems with a reverse order of color rules, but `r.colors.out` and subsequent `r.colors.out_sld` create broken output.
> r.colors: fix order of rules

- python/grass/gunittest/main.py
Adds an empty section to the parser when no config file is available and returning the section proxy instead of returning and empty dict which has a different API than the section proxy.
Fixes an issue introduced in #2172 which shows in grass-addons CI.
> grass.gunittest: Fix fail with no config

- gui/wxpython/gcp/mapdisplay.py
- gui/wxpython/gui_core/mapdisp.py
- gui/wxpython/iclass/frame.py
- gui/wxpython/image2target/ii2t_mapdisplay.py
- gui/wxpython/mapdisp/frame.py
- gui/wxpython/mapswipe/frame.py
- gui/wxpython/mapwin/base.py
- gui/wxpython/photo2image/ip2i_mapdisplay.py
This PR moves self.mapWindowProperties to map window base class and connects signal which updates map display statusbar whenever the projection settings in Map Display Settings dialog is toggled.
> wxGUI: update statusbar when projection settings checkbox has been toggled

- python/grass/gunittest/main.py
* Use f-strings for simple string formatting.
* Use with statement for open.
* Simply return from main as in other parts of the function.
* Order imports better.
* Update to new import alias.
> grass.gunittest: Use more Python 3 style code

- python/grass/gunittest/main.py
A configuration file can now be specified explicitly in the command line which is useful for providing custom configuration file, e.g., with more or less tests excluded or with differnt timeout for different platfroms or hardware setups.
Removes a useless return from the config function. Reports OSErrors from the function without traceback.
> grass.gunittest: Add --config parameter

- python/grass/benchmark/runners.py
To avoid bias when other processes are running at the same time
> grass.benchmark: shuffle runs for benchmarking by number of cores

- raster/r.terraflow/sweep.cpp
> Fix -Wunused-const-variable compiler warnings

- contributors.csv
- gui/wxpython/gui_core/ghelp.py
This PR adds a new `orcid` column (https://orcid.org/) to the file for better citation of authors.
For discussion, see https://lists.osgeo.org/pipermail/grass-psc/2022-January/002531.html
I have made a quick round of searches to identify some ORCIDs. Please review.
> contributors.csv: added new ORCID column

- gui/wxpython/gui_core/gselect.py
Replaces pygrass.utils.decode as not needed here, grass.utils.decode was called anyway.
This should prevent that gui crashes when loading C libraries fails, see #2192.
> wxGUI: do not import from pygrass on gui startup

- .github/workflows/flake8.yml
- python/grass/jupyter/testsuite/grassrenderer_test.py
- python/grass/jupyter/testsuite/interactivemap_test.py
- python/grass/script/testsuite/test_start_command_functions.py
- python/grass/script/testsuite/test_start_command_functions_nc.py
grass.jupyter and grass.script tests are almost Flake8 compliant. This fixes the reported issues and removes Python 2 specific check.
A new step in the flake8 job checks explicitly for the files in the two testsuite directories. (There is no way in Flake8 itself to include previosly excluded files which is needed because testsuite directories are ignored in the main .flake8 file and here we need to check them.)
> CI: Add Flake8 check for selected tests

- python/grass/benchmark/runners.py
- python/grass/jupyter/display.py
- python/grass/jupyter/interact_display.py
- python/grass/jupyter/region.py
- python/grass/jupyter/render3d.py
- python/grass/jupyter/setup.py
- python/grass/jupyter/testsuite/grassrenderer_test.py
- python/grass/jupyter/testsuite/interactivemap_test.py
- python/grass/jupyter/testsuite/test_render3d.py
- python/grass/jupyter/utils.py
* Add missing docstrings.
* Reorder imports (with both pylint and isort).
* Use full-word variable names.
* Use f-strings if possible. Here it replaces smart, but hard to decode, dictionary usage in format, by simple, although longer, direct use of the dictionary.
> grass.jupyter: Add docstrings, f-strings, fix var names, imports

- python/grass/benchmark/results.py
Use UTF-8 as encoding for text files (JSON files here) in grass.benchmark result reading and writing. This explicitly specifies an encoding and thus it avoids unspecified-encoding warning from Pylint.
> grass.benchmark: Use UTF-8 for text files

- lib/ogsf/gs3.c
- raster3d/r3.in.v5d/v5d.c
- raster3d/r3.out.v5d/v5d.c
Touching files with PR #2165 triggered CodeQL overflow warnings.
This PR addresses these issues:
- Multiplication result may overflow 'int' before it is converted to 'long'.
- Multiplication result may overflow 'int' before it is converted to 'unsigned long'.
> Fix some code scanning CodeQL overflow warnings

- python/grass/benchmark/results.py
- python/grass/jupyter/display.py
- python/grass/jupyter/render3d.py
Although tempfile.TemporaryDirectory uses weakref.finalize to delete the directory and its documentation does mention deletion during garbage-collection and during interpreter shutdown, the intention in its source code is that a with statement or explicit cleanup call is made because otherwise it generates a warning about implicit deletion. Pylint correctly generates warning suggesting with statement (consider-using-with).
In the future, we may consider implementing context-manager and cleanup method to the render classes, but even with that we need to stretch the existence of the temporary directory beyond one method, so the with statement is not applicable. For now, the classes are using only weakref.finalize which is sufficient for a notebook where the object life time is linked with …
>  grass.jupyter: Use weakref.finalize to manage TemporaryDirectory

- .github/workflows/optional_requirements.txt
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/python_requirements.txt
- gui/wxpython/.pylintrc
- python/.pylintrc
- python/grass/jupyter/display.py
- python/grass/jupyter/render3d.py
This adds Pylint check job in a new workflow. It uses the current latest Pylint and latest Python. It uses Pylint to check for minimal supported Python version.
The check runs only for the grass package and most of its content is ignored. It runs for grass.jupyter and grass.benchmark.
The config file is in the python directory because that's the focus of this PR. (In the future, GUI may have a different config file, e.g., due to different naming conventions. On the other hand, in an ideal case, the whole source code will use this file or even a more strict version of this file in the future.)
The check currently fails even for the targeted files.
> CI: Add Pylint check for selected files

- gui/wxpython/datacatalog/catalog.py
- gui/wxpython/datacatalog/toolbars.py
This is alternative PR to #2076. The main difference is that the search widget is not part of toolbar at all and stretches based on datacatalog width. Applies to all standalone/single/multiple window layouts.
> wxGUI: move datacatalog search below toolbar, make it stretch

- .github/workflows/black.yml
- gui/wxpython/dbmgr/vinfo.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/gui_core/wrap.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/lmgr/layertree.py
- gui/wxpython/photo2image/ip2i_manager.py
- pyproject.toml
- python/grass/gunittest/checkers.py
- python/grass/imaging/images2gif.py
- python/grass/imaging/images2swf.py
- python/grass/script/raster.py
- python/grass/script/raster3d.py
- python/grass/script/utils.py
Black is no longer a beta and has a (more strict) stability policy in place.
Changes are expected to happen over years and with updating Python versions (removing the old ones to be exact).
The changes in formatting are specialized no-spaces style for simple operands of power operator and better formatting of a compex if statement.
Python 3.10 is now among target versions. File which had to be ignored by Black due to a, now fixed, bug in Black is not ignored anymore.
In CI, matrix is used to define variables for versions (as in Pylint workflow and workflows with actual matrix). Workflow's on now specifies branches and tags for push.
> Update to Black 22.1.0

- .github/workflows/pylint.yml
- .pylintrc
This aims at running Pylint on all other files except for python/grass and gui/wxpython. Checking all files in a project is hard to do with Pylint, but pytest pylint plugin can do the job.
Many messages are disabled and complexity and similarity limits are raised. Tests in testsuite directories and some additional directories such as doc or utils are ignored. Files with a lot of issues which are unique to them are ignored explicitly.
> Add Pylint check for the main directory

- python/grass/temporal/abstract_space_time_dataset.py
Do not treat a semantic label as shortcut or band identifier if it contains text. This PR is needed to support semantic labels such as red, green, blue, mask.
> TGIS: fix semantic label

- raster/r.watershed/ram/close_maps.c
- raster/r.watershed/seg/close_maps.c
This PR addresses #2003 by saving 0 accumulated cells as 0, not as null, for the -a flag. It does not change the default behavior without -a.
Its side effect is that cells outside non-null input are also saved as 0 (was null before this PR), which is in fact more consistent with the default output without the -a flag. I think with/without -a, null input cells should produce null output cells (TODO).
> r.watershed: Keep 0 accumulation with -a as 0 as opposed to null

- raster/r.buildvrt/main.c
> r.buildvrt: check if all input maps are NULL-only

- .gunittest.cfg
- raster/r.geomorphon/main.c
- raster/r.geomorphon/r.geomorphon.html
parser rules as they were written before this PR, did not allow to construct a pygrass Module object for `r.geomorphon` in a straightforward fashion. In the testsuite the Module is build and run from a command string, which is not the most common approach when doing scripting. When constructing the Module object "manually", the `profileformat` option cannot be set to "nothing" and thus requires `coordinates` which may not be desired.
This small PR attempts to fix this.
If no `profiledata` output is requested, default values in `proileformat` are disregarded. API should be unchanged.
@infrastation, do you think it is OK this way?
In Pygrass Module, one still has to specify `profiledata=""`, which is not very intuitive... Maybe the default answer for `profiledata`should be removed too. …
> r.geomorphon: combine profile parser rules to allow usage as pygrass module

- python/grass/temporal/mapcalc.py
- temporal/t.rast.mapcalc/t.rast.mapcalc.html
More often than not, transferring the semantic label in `t.rast.mapcalc` from the first input (also used as sampling reference for the time stamp) makes sense. If the semantic label gets lost, an unusable STRDS might be created.
An example is application of a multiplication factor to a STRDS with Landsat or Sentinel bands where semantic labels must be preserved.
> t.rast.mapcalc: transfer semantic label

- mswindows/osgeo4w/package.sh
> MS Windows packaging: add missing dlls from MSYS (#2204)

- gui/wxpython/main_window/frame.py
Before:
After:
The width is the same for both side panels.
> wxGUI Single-Window: Make Tools pane wider after startup

- python/grass/temporal/abstract_space_time_dataset.py
`_update_where_statement_by_semantic_label()` fails if there is more than one `_` in the semantic label. Semantic labels can be arbitrary (within limits regarding special characters).
This PR promotes the transition from band names to semantic labels.
> TGIS: any number of "_" is allowed in semantic labels

- lib/init/grass.py
Add python_path and remove svn_revision as obsolete.
> init: fix help string config options

- vector/v.in.pdal/main.cpp
> Fix -Wunused-lambda-capture compiler warning

- raster/r.slope.aspect/main.c
> Fix -Wtautological-overlap-compare compiler warning

- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
- Base the temporary mapset name on process ID and node name instead of just module name.
- Use more robust legalize_vector_name function instead of just removing dots.
- Allow for underscores in user-provided mapset name prefix (and in processed module name) by using stored prefix to delete temporary mapsets.
- This by allows multiple GridModules to run on one machine (including HPC) from different processes without the need to specify unique mapset prefix.
- The previous code required no underscore in the mapset name, but the documentation did not state that. This removes the requirement and avoid possible removal of mapsets with similar name.
- Documentation now comments on how unique the temporary name is and states when a custom prefix needs to be supplied (multiple GridModules from …
> grass.pygrass: Use unique tmp mapset names GridModule

- .github/workflows/pylint.yml
- include/grass/defs/gis.h
- lib/gis/env.c
- lib/gis/tests/lib_gis_env_test.py
The session file (GISRC file) can be read again (force read) with a double underscore function, but when GISRC environment variable changes, the old file is read because cashed value of GISRC is read. This adds a new function which forces the the update (reading) of the variable regardless of its current value similarly to the file content reading.
This also moves the 'no GISRC' error message to the dedicated reading function (from a function of opening environment/variable/session file).
Adds tests for which combines the use of the new _G__read_gisrc_path_ function and the old _G__read_gisrc_env_ function. The test runs isolated using a process otherwise other which use ctypes tests fail.
Sync LD_LIBRARY_PATH handling in Pylint workflow to pytest workflow. The old LD_LIBRARY_PATH code is …
> libgis: Add function to read or read again GISRC var

- python/grass/script/core.py
- python/grass/script/tests/grass_script_setup_test.py
Even when the global _capture_stderr is set, the functions allow users to not capture stderr (e.g., by using devnull). In these cases, sys.stderr.write fails because stderr is None. An example is grass.script.db.db_connection where db.connect regularly fails during grass.script.setup.finish when there is no database connection. With this fix, the function no longer fails and correctly handles the error state with except CalledModuleError.
The issue with the original code is visible in the code itself: _capture_stderr is used in a condition to set stderr=PIPE, but that's conditional on values in kwargs. However, this second condition is not considered when output stderr value is used later on.
The test function named test_init_finish_global_functions_capture_strerr fails with previous …
> grass.script: Do not print stderr when not captured

- python/grass/jupyter/tests/grass_jupyter_session_test.py
Adds test for init, session, and finish using pytest. Uses temporary script to test automatic (implicit) cleanup with weakref.finalize.
Depends on #2246.
> grass.jupyter: Test init and session

- raster/r.object.geometry/testsuite/r_object_geometry_test.py
If type is not specified in r.in.ascii call, it will try to autodetect it from the values. It seems that in some cases this might fail, see #2264.
> r.object.geometry test: explicitly specify CELL type in r.in.ascii

- imagery/i.atcorr/main.cpp
- imagery/i.atcorr/output.h
- imagery/i.atcorr/transform.cpp
- imagery/i.atcorr/transform.h
- include/grass/defs/ogsf.h
- include/grass/iostream/mm_utils.h
- lib/bitmap/bitmap.c
- lib/bitmap/sparse.c
- lib/calc/xmode.c
- lib/calc/xnmode.c
- lib/gis/make_loc.c
- lib/iostream/mm_utils.cpp
- lib/ogsf/gs3.c
- lib/rst/data/dataquad.c
- lib/vector/dglib/examples/cr_from_a.c
- raster/r.terraflow/fill.cpp
- raster/r.terraflow/sweep.h
- raster/r.terraflow/water.h
- raster/r.viewshed/distribute.cpp
- raster/r.viewshed/distribute.h
- raster/r.viewshed/rbbst.cpp
- raster/r.viewshed/rbbst.h
- raster/r.viewshed/visibility.cpp
- raster/r.viewshed/visibility.h
Some fixes on various error/alert/performance issues spotted by clang and cppcheck (there are others, but I prefer to go step by step and know if it suits you :relaxed: )
> Various fixes

- raster/r.watershed/ram/init_vars.c
- raster/r.watershed/seg/init_vars.c
This PR sets accumulation to null where there is no data in elevation. This behavior is consistent with the disk swap -m flag. It also partly addresses https://github.com/OSGeo/grass/issues/1901 by assigning 0 flow amount to null flow cells.
> r.watershed: Null accumulation outside elevation, 0 flow from null flow

- general/g.region/main.c
This PR adjusts the boundaries to the resolution when only `n=`, `s=`, `w=`, and/or `e=` are used.
> g.region: Apply -a flag for n=, s=, w=, e=

- python/grass/temporal/stds_export.py
Without semantic labels, the meaning of the different exported raster maps is unknown and the output is thus meaningless.
Example: a given raster map could be a mask, a particular spectral band, some combination of bands such as NDVI, neighborhood analysis of a particular spectral band, etc. All of these raster maps have the same spatial and temporal characteristics. The only property that allows to distinguish between these different raster maps is their semantic label.
> TGIS: add semantic label to STRDS export

- temporal/Makefile
- temporal/t.copy/Makefile
- temporal/t.copy/t.copy.html
- temporal/t.copy/t.copy.py
- temporal/t.copy/testsuite/test_t_copy.py
This new module `t.copy` creates a copy of a space-time dataset. It can also copy datasets from a different mapset to the current mapset. Optionally, maps registered in the dataset are also copied. By default, only a new space-time dataset is created.
This PR requires PR #1924 to work properly across mapsets.
> TGIS: new module t.copy

- raster/r.in.pdal/info.cpp
Implementation changes of PDAL 2.4.0 caused compilation error.
Fixes #2275
> r.in.pdal: pass LasHeader::header by const ref

- .github/workflows/build_centos.sh
Older versions of gcc support, but does not default to C++11.
Presently the gcc version in the ci centos build is [4.8.5](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/Standards.html#Standards), which causes build failure with C++11 standard code.
Extract of build log for #2272 formatting with ClangFormat:
```
/__w/grass/grass/dist.x86_64-pc-linux-gnu/include/grass/iostream/empq_impl.h: In member function 'AMI_err em_pqueue<T, Key>::merge_streams(AMI_STREAM<ExtendedEltMergeType<T, Key> >**, short unsigned int, AMI_STREAM<ExtendedEltMergeType<T, Key> >*, long int)':
/__w/grass/grass/dist.x86_64-pc-linux-gnu/include/grass/iostream/empq_impl.h:1385:44: error: '>>' should be '> >' within a nested template argument list
std::vector<ExtendedEltMergeType<T, Key>> in_objects(arity);
^ …
```
> ci/centos:  use C++11 standard compile mode

- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/modules/grid/patch.py
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
When overlap is 0, GridModule will merge computed tiles using r.patch, which is now parallel and therefore it will be faster for large data. If overlap is >= 1, r.patch can't be used, original implementation is used.
> GridModule: use parallel r.patch when overlap=0 to speed up patching tiles

- .github/workflows/black.yml
A new version of Click broke Black. The new version of Black fixes the issue.
See also https://github.com/psf/black/issues/2964
> CI: Update to Black 22.3 with fixed Click

- gui/wxpython/location_wizard/wizard.py
> wxGUI: Fix Location Wizard titles being cut off.

- db/drivers/postgres/create_table.c
- db/drivers/postgres/describe.c
* convert `character varying` without length specifier to `text`, do not truncate to 250 characters
* fix escape sequence in error message
> DB driver PG: convert character varying without length to text

- python/grass/temporal/list_stds.py
- temporal/t.rast.list/t.rast.list.html
- temporal/t.rast.list/t.rast.list.py
- temporal/t.rast.list/tests/conftest.py
- temporal/t.rast.list/tests/t_rast_list_test.py
- temporal/t.rast.list/testsuite/test_t_rast_list.sh
* This adds CSV, JSON, and YAML output and generalizes the other outputs.
* Method is now meant only for different data gathering methods, not for the output formatting. method=cols and method=comma are now obsolete.
* All formatting is avaiable with all methods.
* Most code is shared between the two main branches of code (simple list versus delta/gran methods code).
* Columns can be now specified for any option (previously only for cols/list and partically for comma/line output).
* The change is backwards compatible both on module interface level and on Python API level.
There is no performance penalty for the more general, step-by-step code (at least with smaller data; several tests with _perf_ give all times around 1.7s with the 6 map test).
[Binder …
> t.rast.list: Add CSV, JSON, YAML outputs

- docker/alpine/Dockerfile
- docker/testdata/test_grass_session.py
This PR updates the following items
- use `r.in.pdal` from core (drop outdated addon)
- update `-s` flag to `-g` in Dockerfile and test
- OpenMP support: yes
- grass-session test enabled
- use `grass --tmp-location XY` for `--exec` calls (suggested by @wenzeslaus in https://github.com/OSGeo/grass/pull/2073#pullrequestreview-924640702)
- install `py3-scikit-learn` for `r.learn.ml2` addon
- add @mmacata to list of authors
> alpine/Dockerfile: openMP enabled, PDAL support fixed

- display/d.graph/do_graph.c
`alloc` returns 0 if `num < coors_allocated` since to_alloc is assigned with `coors_allocated`, the condition is always true. So, we can directly assign `to_alloc` with `num + CHUNK`
> display/d.graph: remove useless condition

- aclocal.m4
- configure
Currently, the GDAL-GRASS plugin works only if the directory with GRASS libraries is added to `LD_LIBRARY_PATH`, otherwise GRASS libraries don't find each other. This PR, together with the corresponding [GDAL PR 5503](https://github.com/OSGeo/gdal/pull/5503), avoids the need to set `LD_LIBRARY_PATH` or add an entry to `/etc/ld.so.conf.d/`, instead the GDAL-GRASS plugin works out of the box without further adjustments to the system's paths with libraries in non-standard locations.
The crucial change is in `aclocal.m4`. Running `autoconf` version 2.69 resulted in more changes to `configure` than expected, I am not sure if the added `runstatedir` could cause any harm. My tests succeeded so far.
Failure with:
1. build and install GRASS without this PR
2. build and install the GDAL-GRASS …
> Make: add -rpath to LD_SEARCH_FLAGS

- db/drivers/sqlite/db.c
From https://sqlite.org/faq.html: "file locking is broken on many NFS implementations"
This causes db operations to be extremely slow or not working at all if the GRASS SQLite db is located on a NFS drive.
This PR attempts to solve this issue for affected NFS implementations.
The NFS implementations I have access to are all working fine wrt SQLite, therefore additional testing is needed.
This is not a bug in GRASS, but a bug in certain combinations of SQLite + NFS.
> sqlite driver: support no locking for sqlite over nfs

- .github/workflows/pylint.yml
- python/grass/docs/Makefile
- python/grass/docs/conf.py
- python/grass/docs/src/index.rst
- python/grass/jupyter/__init__.py
- Updates documentation intro to reflect that it will be officially included in v8.2.
- Adds grass.jupyter to the libpython index TOC.
- Reduces depth of the TOC to make it more clear.
- Updates copyright year for generated files.
- Generates API doc for all grass.jupyter.
- Adds Sphix documentation build to Pylint check.
The Pylint check builds the code which Sphinx needs and there is already the pytest-based Pylint check so it could potentially do some pytest-related Sphinx tasks.
The API doc is now generated for all parts of the grass package. This make it possible for the doc to say grass.jupyter rather than just jupyter. This duplicates the generated doc for grass.script and others, but in the future this should replace the per-subpackage generated doc.
> grass.jupyter: Generate API doc for Jupyter package

- python/grass/jupyter/display.py
- python/grass/jupyter/region.py
- python/grass/jupyter/utils.py
> grass.jupyter: automatically determine render image dimensions based on region

- python/grass/jupyter/region.py
- python/grass/jupyter/utils.py
Setting bbox for use_region=True and saved_region was moved to the RegionManager init. Setting target region was refactored into a separate function.
[binder](https://mybinder.org/v2/gh/petrasovaa/grass/fix-folium-extent?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fgrass_jupyter.ipynb)
> grass.jupyter: fix setting bounding box for InteractiveMap for saved_region/use_region

- .github/workflows/create_new_release_draft.yml
In the context of creating and using a core_modules_with_last_commit.json file #2140, after creating and submitting a new release tag to remote repository e.g. `git tag -a 8.2.0 -m "Release 8.2.0"` and `git push origin 8.2.0` a new draft is automatically created with GitHub action workflow "Create new release draft" with attached two files core_modules_with_last_commit.json and core_modules_with_last_commit.patch.
> .github/workflows: automatically create new GitHub release draft

- doc/notebooks/basic_example_grass_jupyter.ipynb
- doc/notebooks/grass_jupyter.ipynb
- doc/notebooks/hydrology.ipynb
- doc/notebooks/solar_potential.ipynb
- doc/notebooks/temporal.ipynb
- python/grass/jupyter/Makefile
- python/grass/jupyter/__init__.py
- python/grass/jupyter/interactivemap.py
- python/grass/jupyter/map.py
- python/grass/jupyter/map3d.py
- python/grass/jupyter/reprojection_renderer.py
- python/grass/jupyter/tests/timeseriesmap_test.py
- python/grass/jupyter/testsuite/map3d_test.py
- python/grass/jupyter/testsuite/map_test.py
- python/grass/jupyter/timeseriesmap.py
Renaming  grass.jupyter classes as discussed in #2283 
- `GrassRenderer` -> `Map`
- `Grass3dRenderer` -> `Map3D`
- `TimeSeries` -> `TimeSeriesMap`
Updated notebooks and changed grass.jupyter filenames to match classes contained.
[Binder](https://mybinder.org/v2/gh/chaedri/grass/renaming?labpath=doc%2Fnotebooks%2Fgrass_jupyter.ipynb)
> jupyter: Rename grass.jupyter classes

- doc/notebooks/temporal.ipynb
- python/grass/jupyter/tests/timeseriesmap_test.py
- python/grass/jupyter/timeseriesmap.py
* Restructure TimeSeriesMap so methods are consistent with other grass.jupyter classes by removing `overlay` and `baselayer` in favor of adding layers to map in order they are called with `__getattr__`  magic.
* Update notebook example
For example:
```
precip_map = gj.TimeSeriesMap(use_region=True)
precip_map.add_raster_series("precip_sum_2010")
precip_map.d_legend(color="black", at=(10,40,2,6)) #Add legend
precip_map.d_vect(map="boundary_county", fill_color="none")
precip_map.d_barscale()
precip_map.show()
precip_map.save("image.gif")
```
[Binder](https://mybinder.org/v2/gh/chaedri/grass/timeseries-restructure?labpath=doc%2Fnotebooks%2Fgrass_jupyter.ipynb)
> Restructure TimeSeriesMap

- python/grass/jupyter/__init__.py
The API page can now be used as a landing page for Jupyter in GRASS GIS.
Links included for notebooks go to GitHub and Binder using the main branch.
> grass.jupyter: Make the API page a landing page

- man/build_html.py
- python/grass/docs/src/index.rst
This PR adds two entries.
Add link to main manual index, "Python" section:
Add `grass.jupyter` to TOC list in libpython page:
> manual: add entries about Jupyter notebook support

- python/grass/jupyter/map.py
- python/grass/jupyter/timeseriesmap.py
https://mybinder.org/v2/gh/petrasovaa/grass/jupyter-play-widget?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Ftemporal.ipynb
> grass.jupyter: add play widget for animation

- gui/wxpython/gui_core/mapdisp.py
Previously, GetPosition returned 0,0 because it was called on a Panel, not Frame.
> wxGUI: fix saving and setting display position in workspace for multiple window layout

- .github/workflows/ubuntu.yml
We don't support Ubuntu 18.04 for 8.0 anymore.
> CI: Remove Ubuntu 18.04 check

- raster/r.stats.quantile/main.c
* sync correctly to r.quantile
* fix segfault
Fixes #2259
> r.stats.quantile: sync to r.quantile

- doc/howto_release.md
This PR removes unneeded steps.
Additionally, version update from G8.0 -> G.8.2 (this file remains identical to that of releasebranch_8_2).
> contributing: Simplify release procedure in howto_release.md

- doc/howto_release.md
- List all assumptions.
- Prep repo before a first update step.
- Create tag locally. GitHub Actions workflow creates the release.
- Unlike the 8.2.0RC1 and the past releases done through GitHub which created lightweight tags, create an annotated tag for more metatada (old tags converted from Subversion are annotated).
- Cover all cases for the version file updates.
- Remove the local copy reset after creation of a tag. There are no changes online which should be updated locally (unlike in the previous approach).
- Use consistent heading levels.
- Add step to publish the release.
> contributing: Make release procedure cleaner and more detailed

- .github/workflows/additional_checks.yml
- .github/workflows/black.yml
- .github/workflows/centos.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/flake8.yml
- .github/workflows/gcc.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/super-linter.yml
- .github/workflows/ubuntu.yml
This limits when workflows are running using the 'on' specification. Workflows now run on pushed to the main branch and the release branches and on pull requests against these branches. They no longer run on tags and feature/fix branches.
Additionally, CodeQL runs only on main and PRs to main. (Was missing for 8.0 branch already anyway.)
> CI: Run workflows on main and release branches, PRs, not tags

- doc/howto_release.md
* Add entry for grass-addons repo update (no new branch only, possibly move to branching howto or consider testing against latest release too).
* Improve heading structure in the last part of the document.
* Notifying packagers manually is no longer part of the procedure. They may follow GitHub or grass-dev/grass-accounce.
> contributing: Add missing addons repo, headings

- .github/workflows/pylint.yml
Compiling the two example C modules was part of the release procedure. This makes it part of the CI.
For now the check is (strangely) in the Pylint workflow because it is documentation and that workflow already does a test build of Sphinx (all three need to build from source first). Other places would be a separate doc generating and checking workflow or adding these to GCC checks to ensure higher quality standard.
> CI: Compile r.example and v.example

- lib/imagery/Makefile
The change implemented in #2269 actually didn't fix the SONAME problem (see issue #2268), at least on Fedora:
```
readelf -d /usr/lib64/grass80/lib/libgrass_imagery.so
Dynamic section at offset 0x16860 contains 31 entries:
Tag        Type                         Name/Value
0x0000000000000001 (NEEDED)             Shared library: [libgrass_gis.8.0.so]
0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
0x0000000000000001 (NEEDED)             Shared library: [libgrass_raster.8.0.so]
0x0000000000000001 (NEEDED)             Shared library: [libgrass_vector.8.0.so]
0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib64/grass80/lib]
0x000000000000000c (INIT)               0x5000
0x000000000000000d …
```
> lib/imagery: fix missing SONAME

- gui/wxpython/xml/toolboxes.xml
> wxGUI: add r.in.wms into ImportRasterData toolbox

- doc/howto_release.md
grass.osgeo.org has been migrated from osgeo7 to faster osgeo8 server.
> howto_release.md: update OSGeo server names

- doc/infrastructure.md
- grasslxd server migrated to osgeo8-grass in OSGeo infrastucture (grass.osgeo.org)
- new jumphost for ssh connections
- update cronjobs_osgeo_lxd repo URL
- mention weblate server for translations
- minor fixes
(PR to be backported to 8.2, 8.0, 7.8)
> infrastructure.md: updates to reflect latest changes

- python/grass/jupyter/map.py
- python/grass/jupyter/testsuite/map_test.py
Map from grass.jupyter can now save PNG images. This is easier than using the filename property and it is consistent with TimeSeriesMap.
> grass.jupyter: Add save PNG method to Map

- lib/cairodriver/graph.c
The original message about failing to initialize a Cairo surface does not include any reason. This adds size and status from Cairo.
```
ERROR: Failed to initialize Cairo surface
```
```
ERROR: Failed to initialize Cairo surface (width: 100000, height: 100000):
invalid value (typically too big) for the size of the input
(surface, pattern, etc.)
```
The result depends on what message is generated by Cairo.
```
> d.mon stop=cairo; d.mon start=cairo width=10000 height=10000 --o; d.rast map=dsm; d.mon stop=cairo
WARNING: File <map.png> already exists and will be overwritten
Output file: /home/vpetras/Projects/grass/code/grass/map.png
100%
> d.mon start=cairo width=100000 height=10000 --o; d.rast map=dsm; d.mon stop=cairo
Current region rows: 1991, cols: 2027
ERROR: G_malloc: unable to allocate …
```
> lib/cairo: Add cairo status to error message

- .github/workflows/osgeo4w.yml
CI is failing for OSGeo4W, it seems due to URL change on the downlad server. This PR updates the download URL for OSGeo4W packages in CI.
> CI: fix download url for OSGeo4W

- vector/v.surf.idw/main.c
v.surf.idw doesn't apply mask properly, it works only when the mask has value 0, not null. So when you create mask with r.mask, v.surf.idw ignores that and interpolates for those values as well.
See also https://trac.osgeo.org/grass/ticket/3677 (not sure why I couldn't reproduce it there.)
> v.surf.idw: fix applying mask

- python/grass/jupyter/interactivemap.py
- python/grass/jupyter/region.py
- python/grass/jupyter/reprojection_renderer.py
- python/grass/jupyter/utils.py
Should address #2369. Now when use_region=True or saved_region, it should reproject the map with the correct resolution. Note that in these cases the resolution is not estimated by r.proj but is estimated by reprojecting the extent and using the same ncols/nrows as in the source region, which might not be the most precise way.
> grass.jupyter: fix resolution handling for InteractiveMap

- gui/wxpython/rlisetup/wizard.py
Fixes #2380. On wxMSW (OS MS Windows), [SetFocus()](https://github.com/OSGeo/grass/blob/main/gui/wxpython/rlisetup/wizard.py#L514) method trigger [EVT_KILL_FOCUS](https://github.com/OSGeo/grass/blob/main/gui/wxpython/rlisetup/wizard.py#L618) event which [handler ](https://github.com/OSGeo/grass/blob/main/gui/wxpython/rlisetup/wizard.py#L640) require allow event processing to continue.
> wxGUI/rlisetup: allow EVT_KILL_FOCUS event handler event processing to continue

- lib/vector/Vlib/intersect.c
- lib/vector/Vlib/intersect2.c
- lib/vector/Vlib/testsuite/test_vlib_intersect.py
- vector/v.profile/testsuite/test_v_profile.py
Initial implementation (by me in 2008 https://trac.osgeo.org/grass/changeset/34306) of Vect_line_get_intersections and Vect_line_get_intersections2 returns just one of intersection points between two lines. This is wrong as per bug #2344 users do expect to get back all intersection points. This PR fixes both functions and adds tests to Vlib, v.profile.
Might be a candidate for a backport.
> Vlib: Return all intersection points from Vect_line_get_intersections

- .github/workflows/additional_checks.yml
- .github/workflows/create_release_draft.yml
* Run the create release workflow for PRs and on branches, too, for testing puproses, but exclude the release-only steps one by one. (Not even expression syntax is not checked when workflow does not run.)
* Upload artifacts always since now it runs for non-release commits as well.
* Fix expression syntax: Use single quotes for a string.
* Run only for selected paths for PRs, run always for selected branches and all tags.
* Don't use tags in the git log release notes test in additional checks because there for tags, this would be the same tag and so no difference (although the workflow now runs only for branches, not tags).
> CI: Add test run for release workflow

- utils/generate_last_commit_file.py
The non-versioned directories give no git log output, but they are harmless, so simply skip these cases in the script for generating last change date and commit hash.
> contributing: Skip non-versioned directories in last commit generator

- .github/workflows/ubuntu.yml
Now using config as the sufficiently unique name. This may be need to be changed in the future to something clearly unique like a new id variable. The name variable has spaces, so avoiding that for now.
> CI: Unique artifact name for Ubuntu tests

- raster/r.patch/do_patch.c
- raster/r.patch/local_proto.h
- raster/r.patch/main.c
Currently with nprocs > 1 and output CELL type, there is a race condition on line https://github.com/OSGeo/grass/blob/main/raster/r.patch/main.c#L218 (and in `do_patch` function as well). This is a quick fix that disables collecting and applying statistics from input for CELL type and nprocs > 1 (effectively activating -s flag).
A proper fix should create an array of the stats structures for each thread and then apply them all in `support` function, this requires more changes.
> r.patch: fix race condition for CELL rasters

- doc/howto_release.md
* Get the tag using Git assuming another person is doing the change, so variables need to be created and update version script gives a different status.
* Move changelog step to the server section because it is needed only for that and the file is needed on the computer.
* Move winGRASS steps into a separate section (copied as is).
* Fix syntax error in the tagging part of the doc.
> contributing: Add separate section for OSGeo server uploads

- .github/workflows/additional_checks.yml
- doc/howto_release.md
- utils/generate_release_notes.py
It is no longer necessary to cd to and from the utils directory. The script now assumes it is in the top directory and utils is a subdirectory with its config files.
> contributing: Remove cd steps, assume utils subdir

- doc/notebooks/README.md
This README.md lists all Jupyter notebooks with their respective titles.
Additionally it is explained how to actually start a Jupyter notebook.
> doc/notebooks: add overview README.md

- scripts/db.univar/db.univar.py
- scripts/db.univar/testsuite/test_db_univar.py
- scripts/v.db.univar/tests/conftest.py
- scripts/v.db.univar/tests/v_db_univar_test.py
- scripts/v.db.univar/testsuite/test_v_db_univar.py
- scripts/v.db.univar/v.db.univar.html
- scripts/v.db.univar/v.db.univar.py
This adds JSON output for db.univar and v.db.univar.
```bash
v.db.univar map=roadsmajor column=SHAPE_LEN format=json -e percentile=80,90,95,99 | jq
```
```json
{
"statistics": {
"n": 355,
"min": 20.359027,
"max": 64177.255429,
"range": 64156.896402,
"mean": 4934.153557109861,
"mean_abs": 4934.153557109861,
"variance": 38328715.30867731,
"stddev": 6191.0189233015035,
"coeff_var": 1.254727655238975,
"sum": 1751624.5127740006,
"first_quartile": 761.180256,
"median": 1601.228177,
"third_quartile": 9527.487778,
"percentiles": [
{
"percentile": 80,
"value": 11737.529039
},
{
"percentile": 90,
"value": 13883.001283
},
{
"percentile": 95,
"value": 14711.484257
},
{
"percentile": 99,
"value": 14943.396283
}
]
}
}
```
The implementation introduces some more duplication (in addition to the existing …
> modules: Add JSON output for db.univar and v.db.univar

- temporal/t.unregister/t.unregister.py
By the try to unregister raster maps from a STRDS an error accured:
```
t.unregister input=test_strds@test_mapest maps=elevation@PERMANENT
Unregister maps
ERROR: Unable to execute sql statement. You have no permission to access
mapset <PERMANENT>, or mapset <PERMANENT> has no temporal database.
Accessible mapsets are: <test_mapset>
```
This changes fixes this bug and you can unregister raster maps from other mapset in the STRDS.
> t.unregister: add support to unregister maps from other mapsets

- gui/wxpython/psmap/frame.py
Rendered preview page doesn't have same zoom as draft page and page isn't centered.
1. Launch wxGUI Cartographic Composer `g.gui.psmap`
2. Maximalize wxGUI Cartographic Composer window
3. Click on the Show preview toolbar tool (green "play button")
4. See rendered preview page
Rendered preview page should be have same zoom as draft page and be centered.
Default:
Expected:
- GRASS GIS version: all
> wxGUI/psmap: fix rendered preview page zoom

- gui/wxpython/dbmgr/base.py
If layer table link exist, no warning message dialog is showed (Attribute table link exists), and Layer `SpinCtrl` widget (on the Manage layers page (tab)) increase value automatically.
2. Switch to Manage layers page (tab)
3. From Table choice widget choose **geology** table
4. Hit Add layer button
7. Layer `SpinCtrl` widget automatically increase value (number 3), no warning message dialog is showed with message Attribute table link exists
If layer table link exist, warning message dialog should be showed, and Layer `SpinCtrl` widget (on the Manage layers page (tab)) value should be not increased too.
**System description (please …
> wxGUI/dbmgr: show warning message dialog if new layer table link exists

- vector/v.what/main.c
- vector/v.what/what.c
- vector/v.what/what.h
This PR adds a new option to select columns to be reported by `v.what`. Default as before are all columns.
This can speed up the module in case of large attribute tables with many columns and can reduce the output to the needed information.
> v.what: new option to select columns

- lib/proj/do_proj.c
- vector/v.proj/main.c
The PJ_AREA has not been properly estimated. As a result, sometimes the wrong PROJ pipeline was chosen, or PROJ failed to find a pipeline at all.
> libproj: fix area bbox for PROJ

- lib/proj/do_proj.c
PROJ likes to have longitudes in the range [-180, 180] which causes problems with geometries crossing the anti-meridian at either -180 or 180, also with the PROJ-specific PJ_AREA object required by PROJ to select the correct PROJ pipeline(s).
Tests with areas crossing the antimeridian and reprojecting these to UTM zone 60 or UTM zone 1 were successful. However, reprojecting back to a latlong location does not work out of the box. The user has to manually add the PROJ `+over` switch to the transformation pipeline, e.g.
```
+proj=pipeline +step +inv +proj=utm +zone=1 +south +ellps=WGS84 +over +step +proj=unitconvert +xy_in=rad +xy_out=deg
```
to successfully reproject an area back from UTM zone 1 to latlong: round trip latlong - > UTM zone -> latlong.
Unfortunately, there is no …
> libproj: fix longtitude estimation for PJ_AREA

- gui/wxpython/gui_core/dialogs.py
- gui/wxpython/gui_core/wrap.py
Deselecting all maps from Image create/edit group dialog is not working.
1. Launc wxGUI
2. From the main window menu choose Imagery -> Develop images and groups -> Create/edit group
3. Select some existed group e.g. nitrogen
4. Check Select all  checkbox widget 
5. Uncheck Select all checkbox widget 
6. See error
```
File
"/usr/lib64/grass83/gui/wxpython/gui_core/dialogs.py", line
987, in OnGSelAll
self.gLayerBox.DeselectAll()
AttributeError
:
'ListBox' object has no attribute 'DeselectAll'
```
Deselecting all maps from Image create/edit group dialog should be work without error.
- Operating …
> wxGUI/gui_core: fix imagery create/edit group dialog deselect all maps

- gui/wxpython/lmgr/giface.py
When no map display is activated GCP Manager doesn't launch.
2. Close all activated map display
3. From the main wxGUI window toolbar launch GCP Manager 
4. See error
```
File "/usr/lib64/grass83/gui/wxpython/lmgr/frame.py", line
737, in OnGCPManager
GCPWizard(self, self._giface)
File "/usr/lib64/grass83/gui/wxpython/gcp/manager.py",
line 164, in __init__
self.mappage = DispMapPage(self.wizard, self)
File "/usr/lib64/grass83/gui/wxpython/gcp/manager.py",
line 833, in __init__
extraItems=self.GetSelectTargetRasterExtraItems(),
File "/usr/lib64/grass83/gui/wxpython/gcp/manager.py",
line 1037, in GetSelectTargetRasterExtraItems
return {self.web_servc_lyrs_root_node_name: …
```
> wxGUI/lmgr: fix launch GCP Manager if not map display is activated

- gui/wxpython/animation/g.gui.animation.html
- gui/wxpython/datacatalog/g.gui.datacatalog.html
- gui/wxpython/dbmgr/g.gui.dbmgr.html
- gui/wxpython/gcp/g.gui.gcp.html
- gui/wxpython/gmodeler/g.gui.gmodeler.html
- gui/wxpython/iclass/g.gui.iclass.html
- gui/wxpython/image2target/g.gui.image2target.html
- gui/wxpython/mapswipe/g.gui.mapswipe.html
- gui/wxpython/photo2image/g.gui.photo2image.html
- gui/wxpython/psmap/g.gui.psmap.html
- gui/wxpython/rdigit/g.gui.rdigit.html
- gui/wxpython/rlisetup/g.gui.rlisetup.html
- gui/wxpython/timeline/g.gui.timeline.html
- gui/wxpython/tplot/g.gui.tplot.html
- gui/wxpython/vdigit/g.gui.vdigit.html
All wxGUI components manual page "GUI index" link redirection is not working.
1. Launch some wxGUI component e.g. `g.gui.psmap --ui`
2. Switch to the Manual page (tab)
4. Go to end of the manual page and click on the "GUI index"
5. Link redirection is not working
GUI index link redirection should be working.
- GRASS GIS version: all
> wxGUI: fix manual page "GUI index" link html file name

- temporal/t.rast.series/t.rast.series.html
- temporal/t.rast.series/t.rast.series.py
This PR enables `t.rast.series` to pass the `n_procs` and `memory` parameters on to `r.series`
> t.rast.series: pass n_procs and memory parameters to r.series

- gui/wxpython/wxplot/base.py
Addresses #2418. Although part of the problem is probably in wxPython, we can avoid it by not using scrollbars, they don't seem to be needed, the plot scales based on the window.
> wxGUI: fix error when starting profile tool

- gui/wxpython/gui_core/vselect.py
When you created new vector map with Select vector feature(s) tool, map is added into Map Display layers tree. If you try delete this map from the Data Catalog Location current Mapset tree, map isn't deleted from the current Map Display layers tree.
2. Display some vector map e.g. `d.vect map=census`
3. From the Map Display layers tree select census vector map
4. From the Map Display Frame toolbars activate Select vector feature(s) tool
5. Select some area(s)
6. Hit Create new map button from the Select vector feature(s) dialog (new vector map is created e.g. **census_selectionW08** and is added into current Map Display layers tree)
7. Reload Data Catalog Location current Mapset tree (if you don't have …
> wxGUI/vselect: fix output fully qualified vector name

- gui/wxpython/psmap/frame.py
Revert back PR #2421.
If Ghostscript program isn't available on the OS MS Windows, error is printed to the stdout.
1. Download and install e.g. [WinGRASS-8.3.dev ](https://wingrass.fsv.cvut.cz/grass83/WinGRASS-8.3.dev-1e0f8882d-131-Setup.exe)
2. If you have installed Ghostscript, uninstall it
3. Launch wxGUI Cartographic Composer `g.gui.psmap`
4. Click on the Show preview toolbar tool (green "play button")
5. See error
```
File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\psmap\frame.py", line 484, in OnCmdDone
im.save(self.imgName, format="PNG")
File "C:\Program Files\GRASS GIS 8.3\Python39\lib\site-packages\PIL\Image.py", line 2117, in save
self._ensure_mutable()
File "C:\Program …
```
> wxGUI/psmap: Ghostscript HyperlinkDialog is needed

- gui/wxpython/main_window/frame.py
When you check checkbox widget Hide 'Tools' tab (wxGUI settings dialog) for single-window mode, wxGUI doesn't launch.
1. Launch wxGUI settings dialog and check checkbox widget Hide 'Tools' tab and Use single-windows mode.
2. Hit Save button
3. Restart wxGUI (close and launch wxGUI)
6. See error
```
File "/home/tomas/.local/lib/python3.9/site-packages/wx/core.py", line 3285, in <lambda>
lambda event: event.callable(*event.args, **event.kw) )
File "/usr/lib64/grass83/gui/wxpython/wxgui.py", line 95, in show_main_gui
mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
File "/usr/lib64/grass83/gui/wxpython/main_window/frame.py", line 164, in __init__ …
```
> wxGUI/settings: fix hiding 'Tools' tab for single-window mode

- gui/wxpython/lmgr/workspace.py
PR #2469 (908c5e23bf8fc23f5a0602dd1cc03cab6bd4ad37) introduced a code that uses English UI strings to identify UI elements. In the case of a translated UI it fails to get element and then proceeds to manipulate with not existing element leading to an assert in C++ wx code.
> wxGUI: do not crash on localized GUIs

- doc/notebooks/scripting_example.ipynb
- lib/gis/tests/lib_gis_env_test.py
- lib/init/grass.html
- python/grass/gunittest/invoker.py
- python/grass/gunittest/multirunner.py
- python/grass/jupyter/setup.py
- python/grass/jupyter/tests/conftest.py
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
- python/grass/script/__init__.py
- python/grass/script/setup.py
- python/grass/script/tests/grass_script_setup_test.py
- scripts/v.db.univar/tests/conftest.py
- temporal/t.rast.list/tests/conftest.py
import grass.script.setup or similar was needed to get access to functions in the setup module. Now the module is imported in the init file which makes it available without an additional import in user code. gs.setup.init() is now an easy and clear way of getting access to the init function.
Most of the code using grass.script.setup was modified to the new style (except for grass.py and imports of specific functions).
Documentation related to the session returned from gs.setup.init updated as gs.setup.finish() call is not even needed when easier session.finish() call is used instead. (Using session.finish() leaves gs.setup.init() call to be the only one from setup for typical session handling code, so the previously required separate import would be for one call only; now there is no …
> grass.script: Make setup available without another import

- .github/workflows/pytest.yml
- pyproject.toml
Now the individual pytest tests are terminated after 300 seconds just like the gunittest ones. New dependency pytest-timeout is needed for testing to use the timeout (or avoid the warning about unused configuration). In the future, individual tests can change the time if needed using the pytest.mark.timeout decorator.
> tests: Add timeout to pytest

- scripts/v.db.addcolumn/v.db.addcolumn.py
* Layer without a table is reported with a specific message instead of the previous message which said there is no connection for the map.
* Message for no connection at all contains name of the map.
> v.db.addcolumn: Add error message for layer without a table

- lib/init/grass.py
Although `grass -ec path/to/mapset`, `-e -c`, and `-c -e` work as expected when creating a new mapset, `-ce` leads to `e` being interpreted as CRS. This is a correct and common behavior which cannot be disabled in argparse. The new error message includes the mapset name and the parsed CRS to cover the `-ce` case while remaining focused on the location versus mapset case.
```bash
$ grass -ce ~/grassdata/nc_spm_08_grass7/test1
```
```
ERROR: No CRS is needed for creating mapset. Did you mean to create a new location?
Exiting...
```
```bash
$ grass -ce ~/grassdata/nc_spm_08_grass7/test1
```
```
ERROR: No CRS is needed for creating mapset <test1>, but <e> was provided as CRS. Did you mean to create a new location?
Exiting...
```
> init: Add mapset and CRS to no CRS needed error

- gui/wxpython/core/gconsole.py
When a module is executed, currently, two states are reported, aborted by the user and finished. This adds a third state, finished, but with non-zero return code. This does not add much because the interpretation is unclear and the error message should be clear from the output above, but it adds some info when debugging strange issues because it prints the return code.
Here are examples for r.mapcalc and g.findfile. r.mapcalc is a typical GRASS module in terms of return codes while g.findfile is using non-zero return code as part of its standard operation.
> wxGUI: Report non-zero return code from modules

- lib/init/grass.py
* If --exec or -e (exit with -c) is used, do not show the 'Starting' message. Only one operation will happen, so no need to emphasize there is a session starting.
* Do not show 'Creating' message for --tmp-location. It is temporary, no need to know it is being created when that's what was requested and it will be deleted at the end.
* Show 'Executing' and 'Execution...finished' messages only in verbose mode. By default, there is no need to echo the command which was received.
* Clarify interface of run_batch_job and fix its documentation. Remove unused env var related code.
> init: Decrease verbosity of --exec

- lib/init/grass.py
- python/grass/script/setup.py
* Remove code duplication between init code in grass.py and grass.script.setup for mapset temporary directory cleaning.
* Simplify the code by using subprocess.DEVNULL instead of os.devnull.
* Change the cleaning message to verbose.
* Document both functions.
> init: Remove duplicate mapset cleaning code, use verbose

- python/grass/gunittest/case.py
- python/grass/script/core.py
- raster/r.in.pdal/testsuite/test_r_in_pdal_binning.py
- raster/r.in.pdal/testsuite/test_r_in_pdal_selection.py
- vector/v.in.pdal/testsuite/test_v_in_pdal_basic.py
- vector/v.in.pdal/testsuite/test_v_in_pdal_filter.py
- Remove shutil.which replacement for Python 2.
- Remove unicode alias for Python 3.
> grass.script.core: Remove which and unicode for Python 2

- lib/init/grass.py
- python/grass/script/setup.py
For SQLite database, VACUUM is used when the session is ending. There is a cost in running the task even when the database is small and no vacuuming is needed. This change adds a check for the size of the database and ignores databases under 100MB.
The message is now only verbose and printed when the task is running.
Unlike the original implementation, the vacuum task is now synchronous so that there is no running GRASS process after the session has ended.
The original implementation comes from Trac ticket 3697 (https://trac.osgeo.org/grass/ticket/3697)
and is best visible in a bulk backport commit 73736 (f790d68470cf8c3eba0de8feb2d6937c4f9c7493).
> init: Use VACUUM for large, modified SQLite files only

- python/grass/jupyter/tests/reprojection_renderer_test.py
- python/grass/jupyter/utils.py
Region in pseudo mercator tmp location could be smaller than it was supposed to because only 2 corners of the region were reprojected. Now it reprojects all 4 corners and gets maximum bbox from them.
> grass.jupyter: fix bbox reprojection for InteractiveMap

- scripts/g.extension/g.extension.py
The URL validation introduced in 45ff0ead5acfbcb574a4326b54538b28821a2aea does not include the original error message details in the user-visible error message. This adds the details and also fixes the formatting which was done on the regular string literal instead of the translated string.
> g.extension: Add details to URL error message

- .github/workflows/osgeo4w.yml
- mswindows/osgeo4w/build_osgeo4w.sh
For using MSYS in CI (esp. github) it is recommended to use [msys2/setup-msys2@v2](https://github.com/msys2/setup-msys2) action. See also: https://www.msys2.org/docs/ci/
This PR introduces that action and should make the build pass again without errors.
Replaces #2468 
Should also speedup the test a few minutes and maybe simplifies to explore other possibilities (e.g. using UCRT)
> CI: introduce setup-msys2@v2 setup action

- lib/gis/parser_script.c
The --script now generates code which complies with Black, Flake8 (except long lines), and Pylint (except line-too-long and unused-variable).
The practice of calling main in sys.exit() and return 0 was removed (usually not needed in this context). Parser call is now in main, so the variables are not global anymore (and thus also follow the right naming practice).
> lib/parser: Apply standards to generated script

- vector/v.to.rast/vect2rast.c
When there are no areas in the vector map, v.to.rast would give warning, 'No areas selected'. However, no areas is a perfectly fine state when converting a vector map with points or lines only, so the warning is misleading.
To cover the case where a user may need to know about the number of areas, a verbose message is now added reporting the number replacing both the warning and a debug message with the number.
> v.to.rast: Use verbose for no area message, not warning

- gui/wxpython/gui_core/dialogs.py
When the last item returned by GetSelections() has been .Delete()'d a new item is selected. The newly selected item is added to GetSelections(). If user selects the last item from a list, looping over GetSelections() output eventually will remove all list items not only ones selected by the user.
This is a workaround by freezing user selection in a list and iterating it in a reverse order as each .Delete() call updates the ListBox and thus changes positions of selected items. Reverse traversal ensures that no selected item gets a new position in the list.
> GUI: wx.ListBox is dynamic – looping over GetSelections() results in removal of all list items

- gui/wxpython/gui_core/mapdisp.py
Fixes setting display size when loading workspace in multi-window mode.
> wxGUI: fix setting display size from workspace in multi-window mode

- gui/wxpython/vdigit/g.gui.vdigit.html
- gui/wxpython/vdigit/mapwindow.py
Vector Digitizer keyboard shortcut for activating point/line tool doesn't work.
1. Launch Vector Digitizer `g.gui.vdigit -c map=vdigit`
2. Press keyboard shortcut Ctrl + P or Ctrl + L
3. See error
```
File
"/usr/lib64/grass83/gui/wxpython/vdigit/mapwindow.py", line
142, in OnKeyDown
event = wx.CommandEvent(winid=self.toolbar.addPoint)
TypeError
:
CommandEvent(): arguments did not match any overloaded call:
overload 1: 'winid' is not a valid keyword argument
overload 2: 'winid' is not a valid keyword argument
```
Vector Digitizer keyboard shortcut for activating point/line tool should be work without error message.
- …
> wxGUI/vdigit: fix keyboard shortcut for activating point/line tool

- gui/wxpython/lmgr/frame.py
- gui/wxpython/main_window/frame.py
With pressing any key is printed error message.
1. Launch Win GRASS GIS wxGUI (single or multi window mode)
2. Click on the main toolbar panel widget to get a focus
3. Press any key e.g. Shift
4. See error
Single window mode error:
```
File "C:\Program Files\GRASS GIS
8.3\gui\wxpython\lmgr\frame.py", line 2243, in OnKeyDown
if event.CtrlDown():
AttributeError
:
'KeyEvent' object has no attribute 'CtrlDown'
```
Multi window mode error:
```
File "C:\Program Files\GRASS GIS
8.3\gui\wxpython\main_window\frame.py", line 2284, in
OnKeyDown
if event.CtrlDown():
AttributeError
:
'KeyEvent' object has no attribute 'CtrlDown'
```
With …
> wxGUI: remove unnecessary key press event handlers

- gui/wxpython/vdigit/g.gui.vdigit.html
- gui/wxpython/vdigit/mapwindow.py
- gui/wxpython/vdigit/toolbars.py
Extend Vector Digitizer tools keyboard shortcuts.
- Digitize new boundary: **Ctrl+B**
- Digitize new centroid: **Ctrl+C**
- Digitize new area: **Ctrl+A**
- Move vertex: **Ctrl+G**
- Add vertex: **Ctrl+V**
- Remove vertex: **Ctrl+X**
- Edit line/boundary: **Ctrl+E**
- Move feature(s): **Ctrl+M.**
- Delete feature(s): **Ctrl+D**
- Delete areas(s): **Ctrl+F**
- Display/update categories: **Ctrl+J**
- Display/update attributes: **Ctrl+K**
- Undo: **Ctrl+Z**
- Redo: **Ctrl+Y**
- Settings: **Ctrl+S**
- Show help: **Ctrl+H**
- Quit digitizing tool: **Ctrl+Q**
> wxGUI/vdigit: extend tools keyboard shortcuts

- tools/mkhtml.py
See related thread in grass-dev ML: https://lists.osgeo.org/pipermail/grass-dev/2022-August/095743.html
> Force mkhtml to use UTF-8

- doc/howto_release.md
The instructions for moving to the next version were missing.
> contributing: Add step for update to next version number

- temporal/t.rast.series/t.rast.series.html
- temporal/t.rast.series/t.rast.series.py
Add the option to set the file_limit (the maximum number of open files allowed for each r.series process), like the same option in t.series.aggregate.
> Add 'file_limit'  option to t.rast.series

- INSTALL
- mswindows/crosscompile.sh
- python/grass/gunittest/multirunner.py
- python/grass/script/setup.py
When the current version is used, it needs to be updated usually every minor release. This reduces how much the current version is used where it is not essential.
* When in variable name, use more general variable name.
* When in comment or doc, use '<version>' or VV when no specific example is needed.
* When a specific version is need for an example, use 3.y.z which is obviously an example.
* When not essential in the context, remove it completely.
> version: Reduce usage of the current version number

- include/Make/HtmlRules.make
- lib/gis/parser_html.c
- utils/mkhtml.py
End of file is being added both in parser and also in mkhtml because it is removed so that documentation can be just appended. This marks the closing tag with a comment so that the right line is removed.
(An ultimate solution is moving to more template-like replacement instead of the current file append.)
> lib/parser: Add missing closing div tag

- lib/init/grass.py
For getting grass version:
grass --version
it is expected to get grass version on standard output, not error output.
> init: print GRASS version to stdout not stderr

- doc/development/rfc/PSC_guidelines.md
- doc/development/rfc/PSC_voting_procedures.md
- doc/development/rfc/language_standards_support.md
- doc/development/rfc/legal_aspects_of_code_contributions.md
- doc/development/rfc/migration_github.md
- utils/release.yml
As discussed during PSC call, let's move the already adopted RFCs to documentation (the same place as in #2357).
Original RFCs: https://trac.osgeo.org/grass/wiki/RFC
@neteler, I didn't update the physical address in the legal aspects RFC, should I update it to whatever we have in COPYING or remove entirely?
> RFC: move adopted RFCs from trac wiki

- gui/wxpython/gui_core/gselect.py
- gui/wxpython/modules/import_export.py
Import PostGIS DB raster via wxGUI Import raster data dialog doesn't work.
2. Export some raster map into GTiff format e.g. `r.out.gdal input=elevation output=/tmp/elevation.tif` and import with `raster2pgsql -I -C -s 3358 /tmp/elevation.tif public.elevation | psql -d <YOUR_DATABASE> -U <YOUR_DATABASE_USER> -h <YOUR_DATABASE_HOST> -p <YOUR_DATABASE_PORT>` to PostGIS DB
3. Set PostGIS DB connection via `db.login` module
4. From the Data catalog toolbar activate Import raster data tool
5. From the Import raster data dialog Source type choose Database RadioButton widget
6. From the Source input Format ComboBox widget choose PostGIS Raster driver
7.  From the Name ComboBox widget choose your database name …
> wxGUI/gui_core: fix import PostGIS DB raster

- utils/grass_indent.sh
The `indent` program used by Grass is not the original BSD one.
On FreeBSD (and other BSD and maybe MacOs) we have to use `gindent` which is the gnu indent.
> MacOS/BSD Use gnu indent

- python/grass/temporal/c_libraries_interface.py
If maps are linked to the GRASS GIS database with `r.external -r` those maps do not have a range file.
When trying to register them in a STRDS, the process fails because no map info is returned at all, meaning no north, south, ... info either. In consequence, NON-NULL constraints of the TGIS DB are violated.
This PR fixes the inconsistency, so I tagged it as a bug and added a backport label. If others feel different about it, please feel free to change the labels.
In case of a missing range file, now None/NULL is returned as range of map values together with a valid spatial extent.
> temporal: dont fail when registering maps with missing range file

- man/build_keywords.py
Implement https://github.com/OSGeo/grass-addons/issues/776.
> man: allow register all addons keywords in main Keywords Index

- gui/wxpython/core/gcmd.py
- gui/wxpython/core/gconsole.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/ghelp.py
- gui/wxpython/rlisetup/frame.py
- lib/init/grass.py
- python/grass/gunittest/multirunner.py
- python/grass/script/utils.py
- utils/mkhtml.py
* fix #2538
* Use `getencoding()` where only encoding is needed; `getlocale()` otherwise
> avoid using deprecated locale.getdefaultlocale()

- lib/init/grass.py
> grass.py: fix missing parameters in gettext.install()

- gui/wxpython/gui_core/forms.py
Fixes #2493. `CheckListCtrlMixin` class is [obsolete](https://docs.wxpython.org/wx.lib.mixins.listctrl.CheckListCtrlMixin.html) and `OnCheckItem` method doesn't work with wxPython 4.1.1 version. Instead of that, an event `wx.EVT_LIST_ITEM_CHECKED`,` wx.EVT_LIST_ITEM_UNCHECKED` is binded to the widget LayersList widget.
> wxGUI/forms: fix LayersList widget binding check/uncheck event method

- general/g.mapsets/main.c
`g.mapsets` module writes to the file `$(g.gisenv get="GISDBASE")/$(g.gisenv get="LOCATION_NAME")/$(g.gisenv get="MAPSET")/SEARCH_PATH` additional empty new line.
1. Lanch GG with **nc_spm_08_grass7** LOCATION and **landsat** MAPSET
2. Run `g.mapsets operation=set mapset=landsat`
3. Check the new line symbol `\n` in the file `cat -e "$(g.gisenv get="GISDBASE")/$(g.gisenv get="LOCATION_NAME")/$(g.gisenv get="MAPSET")/SEARCH_PATH"` and see additional new empty line.
```
GRASS nc_spm_08_grass7/landsat:~ > g.mapsets operation=set mapset=landsat
GRASS nc_spm_08_grass7/landsat:~ > cat -e "$(g.gisenv get="GISDBASE")/$(g.gisenv get="LOCATION_NAME")/$(g.gisenv get="MAPSET")/SEARCH_PATH"
landsat$
$
``` …
> general/g.mapsets: fix write MAPSETs without additional empty new line

- scripts/g.extension/g.extension.py
Here is a suggestion to address #2016
Not sure if it needs to be backported all the way to 7.8 as people with such an old installation, probably do not have more recent Python anyway. So maybe 8.0 is a sufficient milestone.
An alternative implementation would be choose the function later in the code, like:
```
if sys.version_info.major == 3 and sys.version_info.minor < 8:
from distutils.dir_util import copy_tree
```
And then here: https://github.com/OSGeo/grass/blob/82fb7b8e93a8b87f7de827c0b1f98992759ce7a1/scripts/g.extension/g.extension.py#L1582
```
if sys.version_info.major == 3 and sys.version_info.minor < 8:
copy_tree(actual_file, os.path.join(target_dir, file_name))
else:
shutil.copytree(actual_file, os.path.join(target_dir, file_name), dirs_exist_ok=True)
```
> g.extension: use copytree from shutil for py >= 3.8

- REQUIREMENTS.html
- db/drivers/mysql/grass-mesql.html
- general/g.setproj/g.setproj.html
- lib/gis/parser_html.c
- man/build_html.py
- raster/r.li/r.li.html
- utils/mkhtml.py
- utils/module_synopsis.sh
This PR addresses #2589 (SEO problems on mobile devices):
- Google: addresses "Page isn't usable on mobile" - "Viewport not set"
- https://search.google.com/search-console/mobile-usability?resource_id=http%3A%2F%2Fgrass.osgeo.org%2F&hl=en
- see: https://support.google.com/webmasters/answer/9063469#viewport_not_configured
- Bing: addresses "The page is missing meta language information"
- https://www.bing.com/webmasters/seoreports?siteUrl=https%3A%2F%2Fgrass.osgeo.org%2F&ruleId=39
Manual pages generated with this PR applied are validated correctly at https://validator.w3.org/
> SEO and manuals: add viewport and page language

- lib/init/grass.py
Fixes #753 by creating `<mapset>/.sudo_as_admin_successful` when `$HOME/.sudo_as_admin_successful` exists
> init: Fix sudo message on Ubuntu

- gui/wxpython/lmgr/frame.py
- gui/wxpython/main_window/frame.py
- gui/wxpython/mapdisp/frame.py
> wxGUI: set window offset (OS panel) for single/multiple window mode

- .github/workflows/osgeo4w.yml
- .travis/linux.install.sh
- .travis/linux.script.sh
- Vagrantfile
- configure
- configure.ac
- macosx/ReadMe.md
- mswindows/crosscompile.sh
- mswindows/osgeo4w/build_osgeo4w.sh
- mswindows/osgeo4w/package.sh
- rpm/grass.spec
- utils/vagrant/compile.sh
The configuration option wxwidget has been removed
Refs: #2578
> fix: remove unused wxwidgets compilation configuration option

- utils/mkhtml.py
Same date and time format `"%A %b %d %H:%M:%S %Y"` (example Wednesday Oct 05 06:42:36 2022) inside manual page for all use cases:
1. Core modules compiled from Git repository, with date and time retrievied from the last commit.
2. Core modules compiled from tarball without Git repository and without applied official patch core_modules_with_last_commit.patch, with date and time retrievied from the module source directory.
3. Core modules compiled from tarball without Git repository and with applied official patch core_modules_with_last_commit.patch, with date and time retrievied from the core_modules_with_last_commit.json file.
4. Official addons with date and time retrievied from the last commit via GitHub REST API.
5. Unofficial addons with date and time retrievied from the module source …
> utils: fix date and time format retrieved from the module source dir

- Dockerfile
- docker/ubuntu/Dockerfile
- `docker/ubuntu/Dockerfile`
- update to Ubuntu 22.04 base image
- update to latest PDAL (to be compiled since laz-perf missing from Ubuntu)
- update to latest laz-perf
- `Dockerfile`
- sync Dockerfile in main directory to `docker/ubuntu/Dockerfile` (avoids current confusion, fixes #2575)
> docker Ubuntu: update to Ubuntu 22.04, update PDAL and laz-perf

- mswindows/GRASS-Installer.nsi.tmpl
In theory, this should fix [2603](https://github.com/OSGeo/grass/issues/2603). On Windows 10 Professional , the permissions are correct.  Will need to test on Windows 10 Enterprise
> nsis installer changed SID of grass82.py

- man/Makefile
- man/grassdocs.css
- man/hamburger_menu.svg
- man/hamburger_menu_close.svg
- scripts/g.extension/g.extension.py
- utils/mkhtml.py
Module HTML man page use hamburger menu TOC https://github.com/OSGeo/grass/issues/2589#issuecomment-1265416989 for screen width < 1024 px.
> utils: module HTML man page use hamburger menu TOC for screen width < 1024 px

- gui/wxpython/core/utils.py
- gui/wxpython/gui_core/gselect.py
- gui/wxpython/modules/import_export.py
Import PostGIS geometry data via wxGUI Import vector data dialog doesn't work.
2. Set PostGIS connection via `db.login` module
3. From the Data catalog toolbar activate Import vector data tool
4. From the Import vector data dialog Source type choose Database RadioButton widget
5. Format ComboBox widget is not active
Import PostGIS geometry data via wxGUI Import vector data dialog should be work.
- GRASS GIS version: all
- `ogr2ogr --version`: GDAL 3.4.2, released 2022/03/08
```
GRASS nc_basic_spm_grass7/PERMANENT:~ > v.in.ogr -f | grep Postgre
Supported …
```
> wxGUI/modules: fix import PostGIS geometry data

- gui/wxpython/psmap/frame.py
When map preview is rendered and Cartographic Composer frame is closed, error message is printed.
1. Launch wxGUI Cartographic Composer `g.gui.psmap`
2. From the toolbar activate Map frame tool and add raster map e.g. elevation
3. From the toolbar hit Show preview tool
4. From the toolbar hit Show preview tool again
5. Close the Cartographic Composer window
6. See error
```
File "/home/tomas/.local/lib/python3.9/site-
packages/wx/core.py", line 2254, in Notify
self.notify()
File "/home/tomas/.local/lib/python3.9/site-
packages/wx/core.py", line 3410, in Notify
self.result = self.callable(*self.args, **self.kwargs)
File "/usr/lib64/grass83/gui/wxpython/psmap/frame.py",
line 517, in …
```
> wxGUI/psmap: don't set StatusBar widget text when frame is closed

- python/grass/pygrass/modules/grid/grid.py
Python pygrass `GridModule` class instance change LOCATION MAPSET search path.
1. Launch GRASS GIS with **nc_spm_08_grass7** LOCATION and **landsat** MAPSET
2. Launch `g.mapsets operation=set mapset=landsat`
```
GRASS nc_spm_08_grass7/landsat:~ > g.mapsets -p
Accessible mapsets:
landsat
```
4. Launch this Python script
```python
#!/usr/bin/env python3
from grass.pygrass.modules.grid.grid import GridModule
def main():
grd = GridModule("r.slope.aspect",
width=100, height=100, overlap=2,
processes=None, split=False, elevation="elevation", 
slope="slope", aspect="aspect", overwrite=True)
grd.run()
if __name__ == '__main__':
main()
```
5. Check output of `g.mapsets -p`
```
GRASS nc_spm_08_grass7/landsat:~ > g.mapsets -p …
```
> python/grass/pygrass: reset back MAPSET search path after GridModule class instance finish

- gui/wxpython/gui_core/dialogs.py
- gui/wxpython/gui_core/wrap.py
When you check Select all CheckBox widget from Create or edit image group dialog all added raster maps aren't selected.
3. From the menu choose Imagery -> Develop images and groups -> Create/edit group
4. From the Create or edit image group dialog hit Add button widget and add some raster maps
5. From Create or edit image group dialog check Select all CheckBox widget
6. Added raster maps are not selected
or
3. From the Create or edit image group dialog Select existing group or enter name of new group ComboBox widget choose existed image group e.g. nitrogen.
4. From the Create or edit image group dialog hit Add button widget and add some raster maps
5. From Create or edit image group dialog check Select …
> wxGUI/gui_core: fix Create or edit image group dialog Select all CheckBox widget for selecting all items

- gui/wxpython/gui_core/toolbars.py
- gui/wxpython/iscatt/toolbars.py
- gui/wxpython/lmgr/toolbars.py
- gui/wxpython/mapdisp/toolbars.py
- gui/wxpython/psmap/toolbars.py
Fixes the non-standard behavior of top Single-Window GUI toolbars.
**Bug:**
- bigger icons when undocking and docking the toolbar (takes into consideration that one does not drop a toolbar during that process)
after redocking all toolbars were resized
- no toolbar name displayed after undocking
**After fix:**
Now it inherits from AuiToolbar. This approach corresponds to the usage of aui agw library which is used for drawing the main window frame.
After conversion to AuiToolbar:
- sizes of toolbars are still the same
- toolbar name is displayed after undock
Potentially this PR could also fix some other related bugs  (probably different depending on OS) caused by inheriting from the inappropriate wx.Toolbar class.
> wxGUI: Fix behaviour of top Single-Window GUI toolbars

- scripts/g.extension/testsuite/test_addons_download.py
This PR adds test for downloading addons from:
- github
- gitlab
- bitbucket and
- the official addon repository as well as
- for MS Windows
Cause I was not sure if tests that download content from the internet are acceptable I deactivated tests by default. So devs would have to activate them by setting skip to False.
> g.extension: add tests for download from various sources

- gui/wxpython/gui_core/toolbars.py
Current main toolbar tools layout (some tools are hidden): 
Expected main toolbar tools layout:
- Operating System: MS Windows, macOS
- GRASS GIS version: 8.3.dev
Another solution is to set margins after this line: 
https://github.com/OSGeo/grass/blob/c492ae50bcb2f349bd64393ef85624b5b80c9e03/gui/wxpython/gui_core/toolbars.py#L392
```python
if platform.system() in ("Windows", "Darwin"):
self.SetMargins(8, 8)
```
#2568
> wxGUI: fix display of all single window mode main toolbar tools

- gui/wxpython/main_window/frame.py
Fixes #2600.
How to test this PR:
1. Launch wxGUI with single window mode
2. Change and remember visually wxGUI window size and position 
3. Open wxGUI settings via menu Settings -> Preferences
4. On the General page (tab) from the Workspace setting **check Save current windows layout as default**
5. Hit Preferences dialog Save button
6. Close wxGUI
7. Launch wxGUI and check window position and size
If you want to change the wxGUI position and size again, you need to open the wxGUI preferences dialog again and press the Save button again.
> wxGUI: fix setting of user defined window position and size for single window mode

- raster/r.kappa/calc_kappa.c
- raster/r.kappa/prt2csv_mat.c
- raster/r.kappa/testsuite/data/class_1.ascii
- raster/r.kappa/testsuite/data/class_2.ascii
- raster/r.kappa/testsuite/data/ref_1.ascii
- raster/r.kappa/testsuite/data/ref_2.ascii
- raster/r.kappa/testsuite/test_r_kappa.py
r.kappa has some strange design decisions and produces strange or outright wrong output if input data doesn't match its expectations.
This PR fixes:
* printing garbage instead of NA for the first raster category for commision, ommision and kappa values;
* printing raster category values if labels are missing for matrix-only output mode;
> r.kappa: Fix failures, garbage output, fallback to category values

- gui/wxpython/xml/toolboxes.xml
> wxGUI: add r.buildvrt module into DevelopRasterMap toolbox

- db/drivers/ogr/describe.c
- display/d.vect.thematic/main.c
- display/d.vect/opt.c
- imagery/i.eb.soilheatflux/g0.c
- lib/imagery/iscatt_structs.c
- lib/ogsf/gs3.c
- lib/raster3d/getblock.c
- lib/vector/Vlib/build_pg.c
- raster/r.buffer/main.c
- raster/r.fill.stats/main.c
- raster/r.resamp.rst/main.c
- raster3d/r3.in.bin/main.c
- raster3d/r3.in.v5d/v5d.c
- raster3d/r3.out.bin/main.c
- raster3d/r3.out.v5d/v5d.c
- vector/v.normal/main.c
- vector/v.proj/main.c
- vector/v.sample/main.c
- vector/v.to.rast3/main.c
Initially this is a draft, I commented in code to highlight the *sometimes* uninitialised variables.
We need to decide how to address them.
**Affects:**
Modules
- db/drivers/ogr
- d.vect
- d.vect.thematic
- i.eb.soilheatflux
- r.buffer
- r.fill.stats
- r.resamp.rst
- r3.in.bin
- r3.in.v5d
- r3.out.bin
- r3.out.v5d
- v.normal
- v.proj
- v.sample
- v.to.rast3
GRASS Library parts
- lib/imagery
- lib/ogsf
- lib/raster3d
- lib/vector/Vlib
> Fix -Wsometimes-uninitialized compiler warnings

- imagery/i.gensig/means.c
- lib/cdhc/enormp.c
- lib/raster3d/test/test_put_get_value_large_file.c
- lib/rst/interp_float/ressegm2d.c
- lib/rst/interp_float/segmen2d_parallel.c
- lib/vector/Vlib/ascii.c
- lib/vector/Vlib/net_build.c
- lib/vector/neta/path.c
- raster/r.statistics/o_sum.c
- raster/r.stream.extract/streams.c
- vector/v.lrs/v.lrs.label/main.c
- vector/v.net.salesman/main.c
- vector/v.split/main.c
Initially this is a draft, I commented in code to highlight the uninitialised variables.
We need to decide how to address them.
**Affects:**
Modules
- i.gensig
- r.statistics
- r.stream.extract
- v.lrs.label
- v.net.salesman
- v.split
GRASS Library parts
- ~lib/cdhc~
- lib/raster
- lib/raster3d
- lib/rst/interp_float
- lib/vector/neta
- lib/vector/Vlib
> Fix -Wuninitialized compiler warnings

- vector/v.in.ogr/main.c
Before this PR, vector data failed to import if it contained columns in the attribute table that are of a data type that is not supported by GRASS\` s DBMI - like binary data (BLOB). This PR changes the behavior of `v.in.ogr` to drop such columns from import instead of failing to import the data in total.
> v.in.ogr: skip columns with unsupported data type instead of failing to import

- vector/v.surf.rst/main.c
Bug introduced in #1271.
Unrelated, but this PR also disables threading when cross validation or deviation are set, they can't run multi-threaded due to several reasons (e.g. writing to db).
> v.surf.rst: fix cross-validation and prevent running it multi-threaded 

- gui/wxpython/gui_core/toolbars.py
Fixes #2626, seems `__getattr__` [doesn't work in this special case](https://stackoverflow.com/questions/12047847/super-object-not-calling-getattr).
I included a short documentation I forgot to push in #2568.
> wxGUI: BaseToolbar.OnTool needs to be explicitly defined

- utils/g.html2man/ghtml.py
- utils/g.html2man/testsuite/test_ghtml2man.py
> utils/g.html2man: don't show mobile TOC menu JS code on cli man page

- configure
- configure.ac
As reported in #2610, rebuilding the GRASS sources (from the release tarballs) with no changes break the gdal-grass plugins because the `GIS_H_VERSION` value changes.
Non-git builds use the current timestamp in `GRASS_HEADERS_GIT_HASH` which is also used for `GRASS_HEADERS_DATE`.
This PR uses `GRASS_VERSION_NUMBER` for `GRASS_HEADERS_GIT_HASH` as a better value for non-git builds, that value won't change for simple rebuilds of the source tree.
> Use GRASS version for non-git builds.

- aclocal.m4
- configure
- configure.ac
- include/Make/Grass.make
- include/Make/Platform.make.in
- include/Make/Shlib.make
- lib/iostream/Makefile
Up till now linking C++ based libraries (at this point only the **iostream** library) was forced into creating a static library. This PR enables the possibility to create a dynamic library with the new configure flag 'SHLIB_LDX', which could use CXX instead of CC.
`IS_CXX = yes` must be set before including the 'Lib.make' file in the library's Makefile.
(retry of #2611 )
> lib config: create dynamic library of C++ libraries (2nd attempt)

- python/grass/temporal/univar_statistics.py
- temporal/t.rast.univar/t.rast.univar.py
- temporal/t.rast.univar/testsuite/test_t_rast_univar.py
- temporal/t.rast3d.univar/t.rast3d.univar.py
- temporal/t.rast3d.univar/testsuite/test_t_rast3d_univar.py
This PR adds support for multiprocessing to `python/grass/temporal/univar_statistics.py` and ultimately to `t.rast.univar` and `t.rast3d.univar`.
A parallel testcase is added. However, thorough testing would be great!
Fixes #2590
> t.rast.univar/t.rast3d.univar: add support for multiprocessing

- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
`run()` method of the `GridModule` class instance doesn't clean up temporary MAPSETs when exception occurs (input raster map doesn't exists).
1.  Launch GRASS GIS with **nc_spm_08_grass7** LOCATION and **PERMANENT** MAPSET
2.  Launch this Python script
```python
#!/usr/bin/env python3
from grass.pygrass.modules.grid.grid import GridModule
def main():
grd = GridModule("r.slope.aspect",
width=100, height=100, overlap=2,
processes=None, split=False, elevation="non_exist_elevation", 
slope="slope", aspect="aspect", overwrite=True)
grd.run()
if __name__ == '__main__':
main()
```
3. See error
```
GRASS nc_spm_08_grass7/PERMANENT:grass > python /tmp/test.py 
ERROR: Raster map <non_exist_elevation> not found
ERROR: Raster map …
```
> grass.pygrass: GridModule clean up temporary mapsets when exception occurs

- display/d.vect.thematic/local_proto.h
- display/d.vect.thematic/main.c
- imagery/i.segment/mean_shift.c
- imagery/i.segment/region_growing.c
- include/grass/iostream/pqheap.h
- lib/cairodriver/graph.c
- lib/gis/parser_wps.c
- lib/raster3d/cache1.c
- lib/vector/Vlib/write_pg.c
- lib/vector/rtree/split.c
- raster/r.mapcalc/mapcalc.l
Initially this is a draft, I commented in code to highlight the unused functions. We need to decide which ones to keep (in one way or other) and which ones that can be removed.
**Affects:**
- include/grass/iostream
Modules
- d.vect.thematic
- i.segment
- r.mapcalc
GRASS Library parts
- lib/cairodriver
- lib/gis
- lib/raster3d
- lib/vector/rtree
- lib/vector/Vlib
> Fix -Wunused-function compiler warnings

- lib/gmath/la.c
- lib/vector/Vlib/write_pg.c
- raster/r.spread/collect_ori.c
- visualization/ximgview/main.c
> Fix -Wunused-variable warnings

- raster/r.sim/simlib/hydro.c
- raster/r.sun/main.c
> Fix -Wmaybe-uninitialized warnings

- vector/v.in.ogr/main.c
There was a glitch in #2630 that values from skipped but not empty columns of unsupported data types were still tried to insert into the table in the GRASS DB.
This PR skips also to INSERT values from those columns, using the same logic as for the columns themself.
> v.in.ogr: handle skipped, not empty columns

- raster/r.in.pdal/info.cpp
Re-used code from PDAL 2.3:
https://github.com/PDAL/PDAL/blob/2.3.0/io/LasHeader.cpp#L524
Fixes #2638
> r.in.pdal: Fix use of PDAL 2.4 deprecated api

- .github/workflows/additional_checks.yml
- .github/workflows/black.yml
- .github/workflows/centos.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create_release_draft.yml
- .github/workflows/docker.yml
- .github/workflows/flake8.yml
- .github/workflows/gcc.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/super-linter.yml
- .github/workflows/ubuntu.yml
Upgrade CI actions to use GH Actions versions running under Node 16:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- actions/checkout@v2 -> actions/checkout@3
- actions/upload-artifact@v2 -> actions/upload-artifact@3
- actions/setup-python@v2 -> actions/setup-python@4
CodeQL Action v1 currently used will be deprecated and upgrading to v2 is encouraged:
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> ci: upgrade to GH Actions running on Node 16

- raster3d/r3.gwflow/main.c
Fixes usage of Rast3d_fatal_error()
> r3.gwflow: Fix Rast3d_fatal_error() usage

- gui/wxpython/xml/toolboxes.xml
So far, it was impossible to find module `r.path` through GUI. This PR fixes it.
> toolboxes.xml: add r.path

- lib/raster3d/tilewrite.c
> lib/raster3d: fix -Wmisleading-indentation warning

- raster/r.mapcalc/map.c
> r.mapcalc: fix -Wunused-variable compiler warning

- lib/imagery/sigset.c
This addresses following warning message:
> warning: 'fscanf' may overflow; destination buffer in argument 3 has size 1024, but the corresponding specifier may require size 1025
Found working on #2661.
> lib/imagery: fix -Wfortify-source warning

- python/grass/script/core.py
`pipes` is deprecated since Python 3.11 and will be removed in version 3.13.
`pipes.quote()` is deprecated since version 2.7.
> grass.script: replace deprecated use of pipes.quote()

- configure
Last minute changes to configure.ac with #2679 never was generated to configure.
> configure: fix un-synced configure file

- gui/wxpython/gui_core/wrap.py
Fixes #2685 by adding SetRange and SetValue wrapper functions that convert input values to integer first.
> wxGUI: fix calling SpinCtrl.SetRange with floats with newer Python

- raster/r.ros/r.ros.html
- raster/r.spread/r.spread.html
- raster/r.spreadpath/r.spreadpath.html
The script is currently stored in https://grass.osgeo.org/sampledata/.
Fixes #2565
TODO: Also add link to related dataset:
https://grass.osgeo.org/sampledata/fire_grass6data.tar.gz
(which should be updated as well - any volunteer?)
> manual: fix firedemo.sh URL

- .github/workflows/clang-format-check.yml
This adds ClangFormat CI check.
To be merged after:
https://github.com/OSGeo/grass/pull/2272
https://github.com/OSGeo/grass/pull/2709
https://github.com/OSGeo/grass/pull/2710
https://github.com/OSGeo/grass/pull/2711
https://github.com/OSGeo/grass/pull/2712
https://github.com/OSGeo/grass/pull/2713
https://github.com/OSGeo/grass/pull/2714
https://github.com/OSGeo/grass/pull/2715
> CI: add ClangFormat check

- scripts/wxpyimgview/wxpyimgview_gui.py
Fixes `wxpyimgview` failure to run with Python 3.10:
```bash
wxpyimgview image=map.bmp percent=50
File "/dev/grass/dist.aarch64-apple-darwin21.6.0/etc/wxpyimgview_gui.py", line 93, in redraw
self.draw()
File "/dev/grass/dist.aarch64-apple-darwin21.6.0/etc/wxpyimgview_gui.py", line 88, in draw
dc.DrawBitmap(BitmapFromImage(image), x0, y0, False)
TypeError: DC.DrawBitmap(): arguments did not match any overloaded call:
overload 1: argument 2 has unexpected type 'float'
overload 2: argument 2 has unexpected type 'float'
```
Using:
Python 3.10.7 (v3.10.7:6cc6b13308, Sep  5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)]
wxPython 4.2.0 osx-cocoa (phoenix) wxWidgets 3.2.0
> wxpyimgview: explicit conversion to int

- imagery/i.maxlik/main.c
- imagery/i.maxlik/testsuite/test_i_maxlik.py
If any input cell from imagery group is NULL, the result of classification is also NULL. The implementation of original cat restoration (79f950095283fc351ecc83fc54b5cd7271101d21) did not check for this corner case and thus caused an out of bounds value access.
> i.maxlik: fix crash when classification result is NULL

- raster/r.proj/r.proj.html
This PR fixes a typo in the r.proj manual. Corrects lan**zc**os to [lanczos](https://en.wikipedia.org/wiki/Lanczos_resampling).
> r.proj: Fix a typo (lanzcos => lanczos)

- gui/wxpython/gui_core/goutput.py
- gui/wxpython/gui_core/prompt.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/main_window/frame.py
This PR changes the way how the **Log file** button works. In this PR it is renamed to **Export history** because it better reflects what it newly does.
Original behavior (the button Log file is togglable):
1) Press the button Log file in the Console
2) Choose where you want to store executed commands
3) Starting this moment, all executed commands are stored to this file
4) Press the button Log file again and stop storing executed commands to the defined file
New behavior (the button Export History is not togglable):
1) Press the button Export History in the Console
2) Choose where you want to store executed commands
3) Store the whole history of executed commands (content of .wxgui_history file which is a part of a mapset)
All executed command history related to particular mapset …
> wxGUI: Console: Export history of executed commands

- raster/r.terraflow/ccforest.h
- raster/r.terraflow/genericWindow.h
- raster/r.terraflow/sweep.h
Force compiler create constructors and assignment operators, fixes following warnings:
- `-Wclass-memaccess`
- `-Wdeprecated-declaration`
> r.terraflow: use default

- raster/r.viewshed/grass.cpp
Addresses CodeQL warnings on "comparison of narrow type with wide type in loop condition" (`dimensionType`, which is typedef'd to `unsigned short int`, is compared to `int`).
These were previously known CodeQL warnings, but some were triggered again by #2648.
> r.viewshed: fix CodeQL warnings

- imagery/i.ortho.photo/lib/orthophoto.h
- imagery/i.segment/iseg.h
- include/grass/defs/ogsf.h
- lib/ogsf/gpd.c
- lib/ogsf/gs2.c
- raster/r.circle/main.c
- raster/r.surf.area/local_proto.h
- vector/v.to.rast/do_lines.c
Fixes `-Wstringop-overflow=` and `-Warray-parameter=` warnings surfaced with #2730. They are very much interrelated, it is therefore better to handle them in one PR.
> Fix Wstringop-overflow and -Warray-parameter compiler warnings

- lib/vector/diglib/spindex_rw.c
This PR fixes an integer overflow when writing out spatial index files (sidx) larger than 2GB. With the integer overflow, the resultant file size is underestimated, a wrong size for writing out file offsets is used and the spatial index file becomes unreadable. Other potentially large vector files (coordinates, topology, category index) are not affected.
> diglib: fix integer overflow

- lib/vector/diglib/spindex_rw.c
Manual backport of #2735 to G78 to fix integer overflow in diglib (cherry-picking not possible due to reformatted G83+).
> manual backport of #2735

- raster/r.mfilter/execute.c
Addresses a -Wunused-result compiler warning.
> r.mfilter: check return value of write()

- lib/proj/get_proj.c
This PR fixes a compilation error with PROJ < 6.
> libproj: Use PJ_TYPE_BOUND_CRS only if Proj version >= 6

- .github/workflows/gcc.yml
- .github/workflows/ubuntu.yml
This set `-Werror` on Ubuntu test builds and in addition adds build-env-variables print on ubuntu and gcc builds for debugging info.
> CI: set -Werror on ubuntu test builds

- vector/v.in.ogr/main.c
Fix #2738.
Tested. No regression found.
> v.in.ogr: Get layer name without definition initialization

- general/g.region/printwindow.c
- lib/btree2/kdtree.c
- lib/gmath/la.c
- lib/vector/Vlib/box.c
- raster/r.horizon/main.c
- raster/r.in.bin/main.c
- raster/r.in.lidar/info.c
- raster/r.in.pdal/info.cpp
- raster/r.in.xyz/main.c
- raster/r.li/r.li.padrange/padrange.c
- raster/r.out.gdal/main.c
- raster/r.series.accumulate/main.c
- raster/r.series/main.c
- raster/r.univar/r.univar_main.c
- raster/r.univar/r3.univar_main.c
- raster/r.univar/stats.c
- raster3d/r3.in.lidar/info.c
- vector/v.cluster/main.c
- vector/v.distance/distance.c
- vector/v.univar/main.c
- vector/v.voronoi/skeleton.c
- use of `INFINITY` (1/0 = INFINITY) rather than only division by zero (this is supported by gcc and other compilers but not on Windows)
- use of `NAN` (0/0 = NAN) rather than only division by zero
Extracted from WIP PR #289
TODO: not sure about the changes in "raster/r.in.lidar/point_binning.c", taken from #289
> cmake support preparation: use of INFINITY and NAN

- raster3d/r3.in.v5d/main.c
Addresses a `-Wliteral-range` compiler warning, with the message:
> floating-point comparison is always false; constant cannot be represented exactly in type 'float' 
Fixes partly #2747.
> r3.in.v5d: Fix -Wliteral-range compiler warning

- README.md
- docker/ubuntu/wxgui/Dockerfile
The Dockerfile is the same as the default [Dockerfile](https://github.com/OSGeo/grass/blob/main/Dockerfile), extended by configuration allows wxGUI to launch.
Docker base distribution image is GNU/Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish) with
- Python 3.10.6 version
- wxPython 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0 version
How to test it:
```bash
docker build -t grassgis -f docker/ubuntu/wxgui/Dockerfile .
xhost local:$(id -u)
docker run -it --privileged --user=$(id -u):$(id -g) --rm \
--volume="$(pwd)/:/data" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
--env HOME=/data/ --env DISPLAY=$DISPLAY --device="/dev/dri/card0:/dev/dri/card0" \
grassgis grass --gui
```
Default Python 3.10.6 version with wxPython 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5 (python3-wxgtk4.0 …
> Add a Dockerfile that allows building a GRASS GIS Docker image with wxGUI

- visualization/ximgview/main.c
Fixes partly https://github.com/OSGeo/grass/issues/2747.
> ximgview: Fix -Wsometimes-uninitialized warning

- configure
- configure.ac
- include/Make/Platform.make.in
- raster/r.in.pdal/Makefile
- vector/v.in.pdal/Makefile
GRASS configure now fails with PDAL 2.5, see current CI Mac builds. Upstream pdal-config is outdated returning `-std=c++11`, while C++17 is in fact needed.
From https://github.com/PDAL/PDAL/blob/master/RELEASENOTES.txt under "2.4.0":
> A compiler that supports C++17 is now required to build PDAL or include PDAL headers in your code.
This is the least invasive fix for this I could think of, and may be backported too.
> configure: remove pdal cppflags

- raster/r.geomorphon/geom.c
- raster/r.geomorphon/local_proto.h
The warning issued:
> warning: ordered comparison of pointer with integer zero [-Wextra]
referring to `pattern->distance > 0`
In addition changes unused return type int to void for `radial2cartesian()`.
Fixes partly #2747.
> r.geomorphon: fix -Wextra compiler warning

- docker/alpine/Dockerfile
- docker/debian/Dockerfile
- docker/ubuntu/Dockerfile
- docker/ubuntu/wxgui/Dockerfile
Add `r.in.pdal` test for alpine image so that it is executed in GHA.
Additional removement of `r.in.pdal` addon installation in Ubuntu and Debian docker images (replaced in C++ version in #1200).
> Add r.in.pdal test for alpine image

- gui/wxpython/mapdisp/frame.py
- gui/wxpython/mapdisp/toolbars.py
Switch between Vector digitizer and Raster digitizer or Vector digitizer  and 3D view or Raster digitizer and 3D view sets wrong  Map Display combobox option.
2. Display some raster map e.g. `d.rast elevation`
3. Activate Vector digitizer via Map Display combobox widget choose Vector digitizer option
4. Switch to the Raster digitizer via Map Display combobox widget choose Raster digitizer option
5. See Map display combobox widget setted option which is **2D view** instead of the correct option **Raster digitizer**
or 
4. Switch to the 3D view via Map Display combobox widget choose 3D view option
5. See Map display combobox widget setted option which is **2D view** instead of the correct option **3D …
> wxGUI: fix map display combobox option after switching between toolbars

- include/grass/iostream/ami_stream.h
- include/grass/iostream/embuffer.h
- include/grass/iostream/empq_impl.h
- include/grass/iostream/imbuffer.h
- include/grass/iostream/mem_stream.h
- include/grass/iostream/minmaxheap.h
- lib/iostream/ami_stream.cpp
- lib/iostream/rtimer.cpp
- raster/r.in.pdal/main.cpp
- raster/r.terraflow/common.cpp
- raster/r.terraflow/fill.cpp
- raster/r.terraflow/main.cpp
- raster/r.terraflow/nodata.h
- raster/r.terraflow/plateau.h
- raster/r.terraflow/stats.cpp
- raster/r.terraflow/sweep.cpp
- raster/r.terraflow/sweep.h
- raster/r.terraflow/water.cpp
- raster/r.viewshed/main.cpp
- raster/r.watershed/front/main.c
- raster/r.watershed/shed/com_line.c
- raster/r.watershed/shed/print.c
Starting with Xcode 14.2 (and with the SDK following it), usage of sprintf() in C++ code issues a `-Wdeprecated-declarations` warning. This replaces it with the safer snprintf().
Fixes #2766
> Replace sprintf() with snprintf() in C++ code

- .pre-commit-config.yaml
This adds [pre-commit](https://pre-commit.com) hook file, which runs and checks black, flake8 and clang-format on staged files.
```bash
cd grass-source-dir
python -m pip install pre-commit
pre-commit install
git add <modified_files>
git commit
```
This is by far the simplest way to keep the files in a good shape. Also it will save **a lot** of CI builds, with no need for correcting pushed and failed commits.
The black and flake8 part may be backported to 8.2.
> Add pre-commit hook file

- docker/README.md
- docker/ubuntu/Dockerfile
- docker/ubuntu_wxgui/Dockerfile
- Debian docker base image update
- PDAL compilation: WITH_LASZIP=OFF, keep only WITH_LAZPERF=ON
- new versions:
| Base image   | GRASS GIS  | PROJ  | GDAL  | PDAL  | Python | Image size |
|--------------|------------|-------|-------|-------|--------|------------|
| Ubuntu 22.04 | 8.3.dev    | 8.2.1 | 3.4.1 | 2.4.3 | 3.10.6 | 2.92 GB    |
LAZ-perf is enabled in PDAL, hence both LAS and LAZ files can be imported into GRASS GIS.
TODO in a separate PR: reduce image size
> docker: update of Ubuntu image

- lib/temporal/SQL/sqlite3_indexes.sql
- python/grass/temporal/abstract_space_time_dataset.py
This PR implements spatial filtering in the temporal library, in particular the `get_registered_maps` and `get_registered_maps_as_objects` functions.
The API should be unchanged, so that module code using those functions should not be affected.
If the library implementation is acceptable, it can be included in relevant module and library code.
Currently, only maps that are spatially not overlapping / intersecting with a given _spatial_extent_ (e.g. from the computational region) are removed from the results of the functions named above.
If there is a need to support other spatial relations (like _within_ or _contains_) the implementation needs to be modified a bit, and subsequent modificatins of module code may have to use an option (with the allowed spatial relation to the relevant …
> TGIS: add spatial filter to STDS

- renovate.json
- utils/release.yml
Use `CI: ` prefix for pull request titles in order to facilitate the automated creation of release notes.
THis is a followup PR to #2772.
Related docs: https://github.com/renovatebot/renovate/blob/main/docs/usage/semantic-commits.md
> CI: improve PR titles of renovate bot

- vector/v.buffer/main.c
> v.buffer: fix option name in error message (backport)

- .clang-format
- .github/FUNDING.yml
- .github/codeql/codeql-config.yml
- .github/workflows/additional_checks.yml
- .github/workflows/black.yml
- .github/workflows/centos.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create_release_draft.yml
- .github/workflows/docker.yml
- .github/workflows/flake8.yml
- .github/workflows/gcc.yml
- .github/workflows/macos.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/super-linter.yml
- .github/workflows/ubuntu.yml
- .pre-commit-config.yaml
- .travis.yml
- utils/release.yml
This adds yaml linter https://github.com/adrienverge/yamllint ~~and formatter https://github.com/jumanjihouse/pre-commit-hook-yamlfmt~~ to `.pre-commit-config.yaml`.
All .yml files have also been fixed to pass without warning and formatted (for unified standard).
With CI's super-linter testing for yaml files, it is preferable to pre-empt any failures.
> pre-commit: add yaml file lint

- raster/r.horizon/main.c
This is an addition to #2727.
(Funnily, accidentally spotting this piece of code was the reason I started at all with #2727, but at that time I couldn't find where I have seen it originally.)
Fixes partly #2747.
> r.horizon: fix -Wdeprecated-non-prototype warning

- include/grass/iostream/embuffer.h
- include/grass/iostream/imbuffer.h
- include/grass/iostream/replacementHeap.h
- include/grass/iostream/replacementHeapBlock.h
Combining compiler flags `-Wall -Wextra -Werror` produces some `-Werror=type-limits` warnings in addition to the ones fixed in #2756.
> iostream: fix -Werror=type-limits warnings

- gui/wxpython/gmodeler/dialogs.py
- gui/wxpython/gui_core/goutput.py
- gui/wxpython/gui_core/prompt.py
This PR solves two things:
* reduces the number of Console buttons by removing the Clear prompt button
* removes bounding boxes around buttons
* moves buttons to the bottom of the Console pane
Before:
The main problem was that the right part of the button line could be cut off in Single-Window GUI (simply by shrinking the side Console pane):
After:
The suggestion is very similar to the solution in other panes (Tools, Python).
Follows the suggestion in https://github.com/OSGeo/grass/issues/2585#issuecomment-1333143997.
> wxGUI Console: Button reorganization

- gui/wxpython/core/settings.py
- gui/wxpython/gui_core/preferences.py
- gui/wxpython/lmgr/layertree.py
- gui/wxpython/wxgui.py
This is making single window the default (checkbox is checked by default). The settings key has changed, so old settings of layout won't apply. I changed where the option is now, it's the first thing in Appearance tab, so hopefully it should be more visible here.
> wxGUI: make single-window default, put it under Appearance

- imagery/i.segment/iseg.h
- imagery/i.segment/mean_shift.c
- imagery/i.segment/open_files.c
- imagery/i.segment/region_growing.c
- include/grass/gis.h
- lib/dspf/cube_io.c
- lib/segment/format.c
- lib/vector/Vlib/open_nat.c
- lib/vector/Vlib/read_pg.c
- lib/vector/Vlib/write.c
- lib/vector/Vlib/write_nat.c
- lib/vector/Vlib/write_ogr.c
- lib/vector/Vlib/write_pg.c
- lib/vector/diglib/cindex_rw.c
- lib/vector/diglib/head.c
- lib/vector/diglib/plus_struct.c
- lib/vector/diglib/spindex_rw.c
- raster/r.in.bin/main.c
- raster/r.stream.extract/close.c
- raster/r.stream.extract/do_astar.c
- raster/r.stream.extract/init_search.c
- raster/r.stream.extract/load.c
- raster/r.stream.extract/streams.c
- raster/r.stream.extract/thin.c
- raster/r.terraflow/grass2str.h
- raster/r.terraflow/main.cpp
- raster/r.terraflow/stats.cpp
- raster/r.terraflow/sweep.cpp
- raster/r.watershed/seg/do_astar.c
- raster/r.watershed/seg/do_cum.c
Replace the macro `PRI_OFF_T` with the use of `PRId64`, which is a macro defined in the C99 `<inttypes.h>` file.
Fixes #2806
which reports that gettext cannot handle locally defined macros, whereas
https://www.gnu.org/software/gettext/manual/gettext.html#Preparing-Strings :
> The gettext tools and library have special support for these <inttypes.h> macros. You can therefore simply write
> printf (gettext ("The amount is %0" PRId64 "\n"), number);
> The PO file will contain the string "The amount is %0<PRId64>\n". The translators will provide a translation
> containing "%0<PRId64>" as well, and at runtime the gettext function’s result will contain the appropriate
> constant string, "d" or "ld" or "lld".
This was already discussed in: …
> Use 'PRId64' from C99, instead of macro PRI_OFF_T

- imagery/i.evapo.pm/functions.c
Disabled code in i.evapo.pm missed one curly bracket which was confusing GNU indent.
> Fix i.evapo.pm disabled code for smooth indetation

- gui/wxpython/tools/build_modules_xml.py
- lib/init/grass.py
This PR is an extract from #348 (extracted and updated with `black`):
- gui/wxpython/tools/build_modules_xml.py edits:
- https://github.com/OSGeo/grass/pull/348/files#diff-11ca77721b6d009b6537c54be4172efed843021797676258ad1141a6c63e6fd1
- lib/init/grass.py edit:
- https://github.com/OSGeo/grass/pull/348/files#diff-647be4ef599868c33f2f69f0d899f79f0aee8d75d1db74f523268c1ac94cddf7
Not sure if we want these changes but just to avoid to see them lost when closing #348 in favour of #2684.
> startup: catch errors in build_modules_xml.py, grass.py

- Dockerfile
- docker/debian/Dockerfile
- docker/ubuntu/Dockerfile
- docker/ubuntu_wxgui/Dockerfile
debian and ubuntu Dockerfiles:
* enable PROJ CDN support for grids (`PROJ_NETWORK=ON`): see https://proj.org/usage/environmentvars.html#envvar-PROJ_NETWORK
* more cleanup added: `apt-get clean all && rm -rf /var/lib/apt/lists/*`
> docker: enable PROJ_NETWORK=ON and more cleanup

- .github/workflows/macos_gunittest.cfg
- .gunittest.cfg
Test of a known (unfixed) bug which is always failing the CI needs to be disabled in the config file.
> tests: Disable test of core.gcmd.recv_some

- scripts/g.extension.all/g.extension.all.py
- scripts/g.extension/g.extension.py
* Removes imports from six, uses standard Python 3 imports.
* Removes Python <=2.4 ElementTree import.
* Removes future print_function imports.
* Removes six from g.extension and g.extension.all. Leaves the rest as is.
> g.extension: Remove six dependency

- Dockerfile
- docker/alpine/Dockerfile
- docker/alpine/Dockerfile_alpine_latest
- docker/debian/Dockerfile
- docker/ubuntu/Dockerfile
debian and ubuntu Dockerfiles (includes backport of #2822):
* sync `./Dockerfile` to `docker/ubuntu/Dockerfile` (backport of #2820)
* enable PROJ CDN support for grids (`PROJ_NETWORK=ON`): see https://proj.org/usage/environmentvars.html#envvar-PROJ_NETWORK
* more cleanup added: `apt-get clean all && rm -rf /var/lib/apt/lists/*`
alpine Dockerfile:
* Dockerfile linting with https://hadolint.github.io/hadolint/
* remove `libexecinfo` as no longer existing in alpine
* postgresql-dev -> libpq-dev
* Dockerfile_alpine_latest: sync to (alpine) Dockerfile
> docker: selective backport of cleanup and PROJ_NETWORK=ON

- .github/workflows/additional_checks.yml
Sometimes two files in the repo need to be the same. Various Dockerfiles are in docker directory, but having a (the one) Dockerfile in the main directly makes sense, too. A new check enforces that the file in synced with the other copy.
> contributing: Enforce that duplicate files are the same

- vector/v.info/print.c
The error messegage about missing database connection for a given layer does not include vector name which may not be clear when scripting and an undelying function calls v.info.
> v.info: Add vector name to no db connection message

- python/grass/script/task.py
Fixes regression caused by #2827.
> python/script: revert to byte string

- python/grass/jupyter/tests/timeseriesmap_test.py
- python/grass/jupyter/timeseriesmap.py
* API: TimeSeriesMap.save now supports pathlib.Path objects (and strings as before).
* tests: Use tmp_path, not current dir. Files generated by the tests should use tmp_path (or other pytest tmp dir ways), not the current directory.
> grass.jupyter: Support pathlib.Path in TimeSeriesMap.save

- raster3d/r3.out.netcdf/main.c
- raster3d/r3.out.netcdf/r3.out.netcdf.html
r3.out.netcdf creates a netCDF file with attribute history which contains software. This removes the hard-coded software version information and uses the current major version instead for the history text. It uses fairly general macros to encapsulate stringification to avoid complex code needed to use snprintf.
The documentation contains the output, so the version should be there, but I removed it from the examples to avoid the need for updates (making the documentation little less precise).
> r3.out.netcdf: Use current major version in history attribute

- gui/wxpython/core/gconsole.py
- gui/wxpython/gui_core/prompt.py
Fixes #974.
2. On the Layer Manager windows switch to the Console page (tab)
3. Run this command e.g. `db.select sql="SELECT * FROM census WHERE cat < 5"`
4. Find this command (from step no. 3) in the console history up arrow keyboard
5. You got this command  `db.select sql=SELECT * FROM census WHERE cat < 5`, but sql param arg is without quotation marks
6. Check commands history file `tail -n 1 grassdata/nc_basic_spm_grass7/PERMANENT/.bash_history` (adjust path according your nc_basic_spm_grass7 LOCATION PERMANENT mapset path), and you got
`db.select sql=SELECT * FROM census WHERE cat < 10`
7. If you rerun this command from history (step no. 5) in the wxGUI Console you got error message …
> wxGUI/gconsole: fix saving command param arg with quotation marks to history file 

- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/modules/grid/patch.py
- python/grass/pygrass/modules/grid/split.py
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
Should fix #2678. In some cases (when using floating point resolution, e.g. s=0, n=10 w=0, e=10, res=0.1), the borders for patching were not computed correctly. The values were being converted from n, s, e, w to rows and col unnecessarily, this rewrites this to avoid this conversion. The interface that r.mapcalc.tiled uses is kept the same, no changes needed there.
I suggest not to backport this immediately.
> grass.pygrass: fix no-data rows in at tile borders

- raster/r.patch/main.c
Reading rasters in parallel when MASK is active leads to errors, see #2809. This PR disables parallelization when MASK is in use.
> r.patch: disable parallelization when MASK is active

- gui/wxpython/main_window/frame.py
The multi-window layout is/was using just Data which worked well, so this changes the label of the pane/panel to just Data for simplicity and consistency. Now both the top caption and notebook tab/page label (if in a notebook) are Data.
A layout similar to the multi-window interface - all floating panels placed together in one notebook.
Same layout as above. Before this PR, the _Data_ tab would be _Data Catalog_.
Data catalog is under _Data_ tab (unchanged by this PR).
> wxGUI: Change caption of Data Catalog to Data

- raster/r.profile/r.profile.html
This PR fixes some grammatical typos in the r.profile manual.
> r.profile: Fix typos in the manual

- vector/v.random/main.c
GUI passes fully qualified map names as input parameters but SQL drivers do not properly escape passed values thus causing an SQL error on @ symbol.
Fixes #2473
> v.random: use unqualified names in db columns

- raster/r.cost/flag.c
- raster/r.cost/main.c
- raster/r.walk/flag.c
- raster/r.walk/main.c
`r.cost` and `r.walk` do not report correct percentages on the progress of the actual cost analysis for regions larger than INT_MAX (at most 2³¹ - 1) cells. Further on, memory allocation for the flag structure may fail.
Needs to be backported to all maintained GRASS 8 branches.
> r.cost and r.walk: fix integer overflows

- utils/mkhtml.py
At time Travis CI fails in `releasebranch_8_2` with:
```
File "/home/travis/build/OSGeo/grass/dist.x86_64-pc-linux-gnu/utils/mkhtml.py", line 37, in <module>
from six.moves.urllib import request as urlrequest
ModuleNotFoundError: No module named 'six'
```
(Example for a failed Travis run: https://github.com/OSGeo/grass/pull/2843/checks?check_run_id=11475577650)
This PR addresses the removal of `six` in a simple way.
Side note: Travis does not fail in `main` due to PR #2547, see
https://github.com/OSGeo/grass/commit/17fc1d8dfd5f07ac88611d22727dfd0e40cd646f#diff-3e1684c5c5d40b273b6488a9b5a5558f556d2bcf2973ba5106b6125e01aa6959
> Fix Travis: ModuleNotFoundError: No module named 'six' (G 8.2)

- raster/r.in.xyz/support.c
Mirrors fix in 75cb8f6e6fe863913e68418f40a62a58d067217e (#2844)
> r.in.xyz: fix integer overflow

- raster/r.in.pdal/grasslidarfilter.h
- raster/r.in.pdal/info.h
- raster/r.in.pdal/main.cpp
- vector/v.in.pdal/main.cpp
PDAL 2.5.1+ header files included in GRASS causes Clang to issue -Wunknown-pragmas compilation warnings.
> clang: suppress -Wunknown-pragmas warnings from PDAL 2.5.1 code

- raster/r.neighbors/main.c
- raster/r.resamp.filter/main.c
- raster/r.resamp.interp/main.c
Fix integer overflow for regions with more than INT_MAX cells.
A very similar cast to `size_t` is already in `r.series`, but maybe other modules that were recently parallelized also need some attention.
> r.neighbors: fix integer overflow

- .github/workflows/build_centos.sh
- .github/workflows/macos_install.sh
- .travis.yml
- .travis/linux.script.sh
- configure
- configure.ac
- include/grass/config.h.in
- mswindows/osgeo4w/build_osgeo4w.sh
Using pkg-config for PDAL configuration is more future proof solution than #2749.
The pdal-config, which we used so far, is not actively maintained and is considered to be removed: https://github.com/PDAL/PDAL/issues/3979.
Configure flags are simplified:
no more `--with-pdal=/opt/local/bin/pdal-config`
only `--with-pdal` or `--without-pdal`
> configure: use pkg-config for PDAL configuration

- python/grass/pygrass/modules/grid/patch.py
Fixes [#870](https://github.com/OSGeo/grass-addons/issues/870) by bringing back a removed function.
> grass.pygrass: restore removed function and mark it as deprecated

- gui/wxpython/core/workspace.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/workspace.py
- gui/wxpython/main_window/frame.py
The layout of Aui Notebook as well as AuiManager panes is automatically saved into a workspace file.
When a workspace is loaded, the layout for both parts is adapted (rearranged) to its workspace definition.
> wxGUI: Save current Single-Window layout to workspace file

- .github/workflows/additional_checks.yml
- .github/workflows/black.yml
- .github/workflows/centos.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/flake8.yml
- .github/workflows/gcc.yml
- .github/workflows/macos.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/super-linter.yml
- .github/workflows/ubuntu.yml
Enables CI concurrency setting `cancel-in-progress` for most of the workflows.
Liberates a huge amount of CI processing in situations with a lot of added commits "upon" each other, e.g. in pull requests that are in practice WIP.
> CI: add CI concurrency

- python/grass/script/core.py
Currently, the `find_file` function in the grass.script.core lib replaces _rast_ / _raster_ elements with _cell. This PR implements a more comprehensive replacement of element types that are used in the code but do not represent mapset elements in the sense of `g.findfile`.
Also, the message level in the function is changed from verbose to debug as the current message is mostly useful for developers.
The change would remove messages from e.g. `t.register --v` that are rather cryptic for normal users. It is a precondition for #2863
> find_file: translate more legacy elements

- mswindows/osgeo4w/package.sh
as seen in the compilation logs of daily winGRASS builds (https://wingrass.fsv.cvut.cz/grass83/logs/): 
pdal is not available in OSGeo4W due to Mingw64/MSVSC incompatibility 
see also gh CI build recipe (https://github.com/OSGeo/grass/blob/main/mswindows/osgeo4w/build_osgeo4w.sh#L67)
> winGRASS: exclude pdal as compilation dependency

- mswindows/osgeo4w/package.sh
fix #2885 by adapting package.sh
> configure: fix compilation --with-openmp in MS Windows

- python/grass/script/core.py
- python/grass/script/raster.py
- python/grass/script/raster3d.py
The superquiet (--qq) parameter was ignored by the core functions and not supported in others. This adds superquiet=False to all relevant functions.
> grass.script: Fix ignored superquiet (--qq) parameter

- .github/workflows/macos_install.sh
The Clang version for macOS CI build just bumped to 15, which issues -Wdeprecated-non-prototype warnings and failed the build with -Werror. This was expected (https://github.com/OSGeo/grass/issues/2747#issuecomment-1429484028) and the underlying issues are non-trivial, so this PR is a temporary solution.
> CI: do not fail macOS on -Wdeprecated-non-prototype

- general/g.proj/main.c
Addresses warnings with the description:
> warning: embedding a directive within macro arguments has undefined behavior
> g.proj: Fix -Wembedded-directive compiler warnings

- .github/workflows/additional_checks.yml
- .github/workflows/black.yml
- .github/workflows/centos.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/flake8.yml
- .github/workflows/gcc.yml
- .github/workflows/macos.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/super-linter.yml
- .github/workflows/ubuntu.yml
Attempt to fix CI concurrency cancelling on main.
Inspired by https://github.com/OSGeo/grass/pull/2868#issuecomment-1474025571
> CI concurrency

- python/grass/temporal/abstract_map_dataset.py
Currently, `t.register` and the `register` module use the `build_id` function from `AbstractMapDataset`, but at the same time duplicate some of the code from that function. This PR takes the additional functionality the `register` module attaches to the `build_id()` function and moves it into the `AbstractMapDataset.build_id()` function. Then duplicated code can be removed from the register module (see #2863).
The behavior of the `build_id` function remains as it is. So places where it is currently used are not affected by the proposed change. Just one "if-check" is added in those cases.
This PR is a precondition for #2863.
> AbstractMapDataset: add option for mapset check

- gui/wxpython/mapwin/analysis.py
This fixes the problem described in #2832 with GUI Profile tool duplicating first point. Additionally, this improves GUI distance measurement, now it omits printing first zero-length segment (the distance between the first duplicate points).
I suggest to use this PR instead of #2832.
> wxGUI: remove initial duplicate point when creating profile or measuring distance

- docker/alpine/Dockerfile
- docker/alpine/Dockerfile_alpine_latest
(backport of #2909)
This PR adds
- the needed gcc compiler for addons written in C language (g.extension)
- enables PostgreSQL (add header file)
Co-authored-by: @anikaweinmann
> docker/alpine: add C support for g.extension; enable PostgreSQL support (backport)

- docker/alpine/Dockerfile
- docker/alpine/Dockerfile_alpine_latest
This PR add
- the needed gcc compiler for addons written in C language (g.extension)
- enables PostgreSQL (add header file)
Co-authored-by: @anikaweinmann
> docker/alpine: add C support for g.extension; enable PostgreSQL support

- vector/v.extrude/main.c
Currently `v.extrude` requires `height` or `height_column` to be set even when `elevation` is specified:
```sh
v.extrude in=stream1 out=stream3d1 elevation=dem10m --o
ERROR: One of 'height' or 'height_column' parameters must be set
```
```
v.extrude in=stream1 out=stream3d1 elevation=dem10m --o
WARNING: Vector map <stream3d1> already exists and will be overwritten
Extruding features...
100%
Copying attribute table...
Building topology for vector map <stream3d1@test>...
Registering primitives...
v.extrude complete. T: 392.161499 B: 0.000000.
```
```
v.extrude in=stream1 out=stream3d1 --q
ERROR: At least one of the following options is required: <height>, <height_column> and <elevation>
```
> v.extrude: do not require height/height_column if elevation specified

- scripts/g.extension/g.extension.py
- scripts/g.extension/testsuite/test_addons_download.py
If you try install install non exists Add-On, g.extension module fail.
1. Try install some non exists Add-On `g.extension non_exists_addon`
2. See error
```
GRASS world_latlong_wgs84/PERMANENT:~ > g.extension non_exists_addon
Fetching <non_exists_addon> from <https://github.com/OSGeo/grass-addons>
(be patient)...
File "/usr/lib64/grass83/scripts/g.extension", line 2867, in <module>
File "/usr/lib64/grass83/scripts/g.extension", line 2847, in main
install_extension(source=source, url=url, xmlurl=xmlurl, branch=branch)
File "/usr/lib64/grass83/scripts/g.extension", line 1230, in install_extension
) = install_extension_std_platforms(
File …
```
> g.extension: show fatal message if installed Add-On doesn't exists in the repository

- CITATION.cff
This PR suggests the CITATION.cff file for improved citation management (by Zenodo.org etc).
The content is based on the GRASS GIS 8.2.1 record: https://doi.org/10.5281/zenodo.7764250
(backport of #2904)
> CITATION.cff: added formatted citation file (G82)

- CITATION.cff
This PR suggests the CITATION.cff file for improved citation management (by Zenodo.org etc).
The content is based on the GRASS GIS 8.2.1 record: https://doi.org/10.5281/zenodo.7764250
TODO:
- add missing authors relevant for the GRASS 8.2/8.3 releases
- add more ORCID IDs (please verify)
> CITATION.cff: added formatted citation file

- .github/workflows/docker.yml
Currently (e.g. https://github.com/OSGeo/grass/actions/runs/4718450552/jobs/8368064252#step:8:9512) the following warning shows up:
_build and push alpine for branch_
_The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see:_
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR attempts to update it accordingly.
> docker alpine: CI update for `set-output` command

- scripts/g.extension/g.extension.py
The installation of some extension via the g.extension module failed.
1. Try install some extension `g.extension db.join`
2. See error
```
File "/usr/lib64/grass83/scripts/g.extension", line 2876, in <module>
File "/usr/lib64/grass83/scripts/g.extension", line 2856, in main
install_extension(source=source, url=url, xmlurl=xmlurl, branch=branch)
File "/usr/lib64/grass83/scripts/g.extension", line 1239, in install_extension
) = install_extension_std_platforms(
File "/usr/lib64/grass83/scripts/g.extension", line 2000, in install_extension_std_platforms
srcdir = download_source_code(
File "/usr/lib64/grass83/scripts/g.extension", line 1912, in download_source_code …
```
> g.extension: refactor/simplify 'GitAdapter' class '_get_addons_list' method

- scripts/g.extension/g.extension.py
- scripts/g.extension/testsuite/test_addons_download.py
If you try download some extension source code only (-d flag), printed extension directory is not correct (check extension directory path on the To Compile/Install run and Path to the source line)
1. Try download some extension source code only `g.extension -d r.accumulate`
2. Check downloaded extension source code path printed on stderr (line To Compile/Install run and Path to the source code)
```
GRASS nc_basic_spm_grass7/PERMANENT:grass > g.extension -d r.accumulate
WARNING: Extension <r.accumulate> already installed. Re-installing...
Fetching <r.accumulate> from <https://github.com/OSGeo/grass-addons> (be
patient)...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (28/28), done.
remote: …
```
> g.extension: fix printing extension temporary directory to stderr for downloading extension source code only with -d flag

- python/grass/pygrass/vector/__init__.py
PyGRASS currently handles geometries for 3D vector maps as 2D
```sh
v.random out=p3d n=1 -z zmax=1
```
Sample PyGRASS script:
```py
from grass.pygrass.vector import VectorTopo
with VectorTopo('p3d') as vmap:
print('Map 3D?', vmap.is_3D())
for f in vmap.viter('points'):
print('Point 3D?', not f.is2D)
print('Z:', f.z)
```
Output:
```
Map 3D? True
Point 3D? False
Z: None
```
```
Map 3D? True
Point 3D? True
Z: 0.4480268010321531
```
> pygrass: retrieve 3D geometries for 3D vector maps

- python/grass/temporal/temporal_algebra.py
- python/grass/temporal/temporal_raster_base_algebra.py
- python/grass/temporal/temporal_vector_algebra.py
Also fixes some related minor issues.
> t.rast.algebra: do not print when debug is off

- scripts/g.extension/g.extension.py
Installing extension via g.extension module fail.
1. Try to install some extension `g.extension db.join`
2. See error
```
in _get_version
return float(
^^^^^^
ValueError: could not convert string to float: 'Git-143)'
```
Installing extension via g.extension module should work without error message.
- Operating System: macOS
- GRASS GIS version 8.3.dev
To be backported with https://github.com/OSGeo/grass/pull/2895.
> g.extension: fix extracting Git version string

- gui/wxpython/gui_core/prompt.py
Since d657c9a9be sometimes when a tool is opened from GUI console a wxAssertionError appears:
```
wx._core
.
:
C++ assertion "nNew != dynamicEvents.size()" failed at /home
/wxpy/wxPython-4.2.0/ext/wxWidgets/src/common/event.cpp(1930
) in SearchDynamicEventTable():
The above exception was the direct cause of the following
exception:
SystemError
:
<class 'wx._core.ChildFocusEvent'> returned a result with an
error set
```
I don't fully understand why that happens, but I don't think there is anything wrong in our code. Writing the hint after the `OnKillFocus` event is resolved seems to fix the problem.
> wxGUI: fix wxAssertionError when opening tools from console

- python/grass/temporal/c_libraries_interface.py
Addresses #2932.
By default, logging shows only messages of level warning and higher, so info is not printed.
> temporal: do not show empty range file message with default logging level

- .github/FUNDING.yml
Given how Open Collective page is organzied, the page with clear contributing options is contribute which has all the options and nothing else, not the home (index) page for a collective. GitHub support suggests to change the configuration by adding /contribute to make the change.
> contributing: Link Open Collective contribute page

- scripts/g.extension/g.extension.py
- scripts/g.extension/testsuite/test_addons_download.py
Installed extension HTML manual page has wrong source code and history GitHub URL link.
Wrong is `SOURCE_URL` env var value, which is for every official addon https://github.com/OSGeo/grass-addons (correct URL for e.g. db.join addon should be https://github.com/OSGeo/grass-addons/tree/grass8/src/db/db.join):
https://github.com/OSGeo/grass/blob/c0addd9acb44efd181e4c38fe428634e9feb83e7/scripts/g.extension/g.extension.py#L2091
which is used inside mkhtml.py file (line 802)
https://github.com/OSGeo/grass/blob/c0addd9acb44efd181e4c38fe428634e9feb83e7/utils/mkhtml.py#L791-L804
1. Try install some extension e.g. `g.extension db.join` 
2. Check db.join HTML manual page with `$EDITOR $GRASS_ADDON_BASE/docs/html/db.join.html`
3. …
> g.extension: fix addon SOURCE_URL env var value for official GitHub addons

- README.md
Add an auto-generated section listing all contributors with their icons at the bottom of `README.md`.
Make this README.md file less boring :-)
Uses:
https://contrib.rocks/preview?repo=OSGeo%2Fgrass
> README.md: Thanks to all contributors

- raster/r.horizon/main.c
- raster/r.horizon/r.horizon.html
- raster/r.horizon/testsuite/test_r_horizon.py
Enabling negative angles in r.horizon requires more work, the current simple implementation has problems (e.g. flat areas). Also r.sun doesn't work well with negative horizon values. See #2935 for discussion. For now, reverting back to horizon values >= 0 seems best. Note was added to manual page.
> r.horizon: revert back to positive values only

- raster/r.univar/stats.c
- raster/r.univar/testsuite/test_r_univar.py
> r.univar: print only statistics for existing zones

- doc/development/rfc/version_numbering.md
- utils/update_version.md
- utils/update_version.py
This PR is a RFC for a new version numbering system. The main point is not making any distinction between even and odd version numbers. After 8.2.z, 8.3.0 would follow.
Notably, this RFC does not follow the current RFC procedure (if any), but creates a PR as suggested in the past as a possible improvement of the procedure.
Closes #2335.
> RFC: Version Numbering

- .pre-commit-config.yaml
- README.md
markdown-lint: exclude README.md from 033-no-inline-html.md, i.e. allow inline HTML in README.md.
Addresses
https://github.com/OSGeo/grass/pull/2947#issuecomment-1553356145
> pre-commit-config.yaml: exclude README.md from markdown-lint

- docker/README.md
Besides versions, ~~update also link to workflows not to go latest executed actions but to file on the main branch.~~
> Docker: Update 8.3 and 8.4 versions in Docker readme table

- doc/development/README.md
This adds a readme file to doc/development. It contains info which was originally in the main readme, but it misses some info useful for navigating the files under doc/development.
> contributing: Add readme to development doc

- utils/update_version.py
The helper script for udpates of versions suggests a commit message right after the update, but when additional changes need to be done, the message from the script can be lost. This adds a subcommand which can generate the message anytime. The message only makes sense when doing the version update, but the script does not check that. It also does not check (does not know) if the RC was just released. We use different commit message after that, but in that case, the commit happens right after the change from RC to dev, so there is no need to use this subcommand.
> contributing: Add suggest message to version script

- lib/init/grass.py
When running grass with --tmp-mapset, printing a message about mapset creation is not needed. Mapset is created and then deleted just as the user asked.
> init: Do not report creating new mapset for tmp mapset

- rpm/grass.spec
Use the latest grass.spec from Fedora Git repo.
This is forward port of 523fb8059b20807e47dd082d5cc9a55799b66146 from 8.3 release branch (done by cherry-pick).
> pkg: Update to latest grass.spec from Fedora

- .flake8
Flake8 config file does not allow inline comments. Previous versions did not enforce that (which lead to silent errors), but the new versions (v6) do.
Source: https://github.com/PyCQA/flake8/issues/1760
> contributing: Fix syntax in Flake8 config

- python/grass/pygrass/modules/interface/parameter.py
- python/grass/pygrass/modules/interface/testsuite/test_parameter.py
For a parameter value which was out of range from key_desc specified as `0-`, grass.pygrass failed to construct the error message and resulting error message for the exception was:
```
TypeError: must be real number, not NoneType
```
This handles the cases with only min or max specified separately, fixes the error message and uses f-strings. The new message is:
```
ValueError: The Parameter <size> must be higher than 1.0, 0 is out of range.
```
> grass.pygrass: Fix parameter range error reporting

- gui/wxpython/gui_core/vselect.py
Activating wxGUI Select vector feature(s) tool fails.
2. Display some vector map `d.vect geology`
3. Try to activate wxGUI Select vector feature(s) tool
4. See error
```
File "/usr/lib64/grass82/gui/wxpython/mapdisp/frame.py",
line 704, in OnSelect
self.dialogs["vselect"].CreateDialog(createButton=True)
File
"/usr/lib64/grass82/gui/wxpython/gui_core/vselect.py", line
135, in CreateDialog
self._dialog.AddWidget(createMap, proportion=0.1)
File
"/usr/lib64/grass82/gui/wxpython/gui_core/vselect.py", line
83, in AddWidget
self.mainSizer.Add(widget, proportion=proportion, flag=flag)
TypeError
:
Sizer.Add(): arguments did not match any overloaded call:
overload 1: …
```
> wxGUI/vselect: fix BoxSizer widget Add method proportion param arg type

- .flake8
- gui/wxpython/core/watchdog.py
- gui/wxpython/datacatalog/tree.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/statusbar.py
- gui/wxpython/main_window/frame.py
The main wxGUI statusbar MASK button widget is not showed when new MASK map is created.
1. Install Python watchdog library via your distribution package manager or via `pip install watchdog`
2. Remove MASK if exists `r.mask -r`
3. Launch wxGUI
4. Create some MASK e.g. `r.mask elevation`
5. Main wxGUI statusbar MASK button widget is not showed
If new MASK map is created, main wxGUI statusbar MASK button widget should be showed.
- GRASS GIS version: 8.3.dev, 8.2
> wxGUI: fix show MASK statusbar button widget if mask is created

- gui/wxpython/core/watchdog.py
When switching to mapset, we can can encounter this error:
Exception in thread
Thread-4
:
File "/usr/lib/python3.10/threading.py", line 1016, in
_bootstrap_inner
self.run()
File "/home/linduska/.local/lib/python3.10/site-
packages/watchdog/observers/api.py", line 205, in run
self.dispatch_events(self.event_queue)
File "/home/linduska/.local/lib/python3.10/site-
packages/watchdog/observers/api.py", line 381, in
dispatch_events
handler.dispatch(event)
File "/home/linduska/.local/lib/python3.10/site-
packages/watchdog/events.py", line 272, in dispatch
{
File "/home/linduska/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/datacatalog/tree.py", line 179, in
on_modified
gisrc["GISDBASE"], gisrc["LOCATION_NAME"], gisrc["MAPSET"]
KeyError
:
'GISDBASE'
It is related …
> wxGUI: exception in thread when switching to mapset

- gui/wxpython/core/ws.py
```bash
grass -c epsg:4326 test
g.region n=90 s=-90 w=-180 e=180
g.gui
```
Get the following error:
```
GRASS_INFO_ERROR(14353,1): Illegal latitude for North: 112.855
GRASS_INFO_END(14353,1)
File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/gui/scripts/d.wms", line 218, in <module>
File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/gui/scripts/d.wms", line 210, in main
temp_map = wms.GetMap(options, flags)
File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/etc/r.in.wms/wms_base.py", line 229, in GetMap
self._initializeParameters(options, flags)
File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/etc/r.in.wms/wms_base.py", line 129, in _initializeParameters
self.proj_location = grass.read_command("g.proj", …
```
> gui: restrict north/south to 90/-90 and west/east to -180/180

- gui/wxpython/gmodeler/model.py
Note: Black brush is used in dark mode only when exporting model into image:
> Show ModelRelation in white on dark mode

- display/d.rast.arrow/d.rast.arrow.html
- display/d.rast.arrow/main.c
This PR adds the `terraflow` type: (clockwise 2<sup>0</sup> for east to 2<sup>7</sup> for north east; aka, ArcGIS flow directions).
> d.rast.arrow: Support Terraflow (ArcGIS) directions

- lib/bitmap/bitmap.c
map is initinialized but not free'd
> lib/bitmap: Fix a potential memory leak

- gui/wxpython/mapdisp/frame.py
- gui/wxpython/mapswipe/frame.py
Addresses #2973.
Interactive querying of rasters now uses region matching the raster to avoid discrepancies due to using display region.
> wxGUI/query: set region matching the raster for each raster queried

- locale/Makefile
Turns out our C++ code is not translated at all.
> Locale: extract translatable messages also from C++ files

- raster/r.in.pdal/point_binning.c
- raster/r.in.xyz/support.c
Combined backport of #2844 and #2847 to version 8.2.
> r.in.pdal and r.in.xyz: manual backport of #2844 and #2847 (8.2)

- gui/wxpython/gmodeler/dialogs.py
1. Add new tool into model
2. Enter selected GRASS tool in `Command`
3. Press Enter
It fails with
```py
File "/home/landa/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/prompt.py", line 490, in OnKeyPressed
self._runCmd(self.GetCurLine()[0].strip())
File "/home/landa/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/prompt.py", line 138, in _runCmd
self.promptRunCmd.emit(cmd={"cmd": cmd, "cmdString": str(cmdString)})
File "/home/landa/src/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/signal.py", line 233, in emit
File "/home/landa/src/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/dispatcher.py", line 344, in send
response = robustapply.robustApply(
File …
```
> Graphical Modeler: fix command parsing in "add tool" dialog

- scripts/db.dropcolumn/testsuite/test_db_dropcolumn.py
- scripts/db.droptable/testsuite/test_db_droptable.py
- scripts/v.db.addtable/testsuite/test_v_db_addtable.py
- scripts/v.db.dropcolumn/testsuite/test_v_db_dropcolumn.py
- scripts/v.db.droptable/testsuite/test_v_db_droptable.py
- scripts/v.db.renamecolumn/testsuite/test_v_db_renamecolumn.py
`unittest.assertNotRegexMatches()` deprecated in python 3.2, removed in python 3.12
> unittest: fix assertNotRegexMatches() removed from python 3.12

- python/grass/script/testsuite/test_script_raster.py
- python/grass/script/testsuite/test_start_command_functions.py
- python/grass/script/testsuite/test_start_command_functions_nc.py
- raster3d/r3.to.rast/testsuite/test_a_b_coeff.py
- raster3d/r3.to.rast/testsuite/test_integer_rounding.py
- raster3d/r3.to.rast/testsuite/test_nulls.py
- raster3d/r3.to.rast/testsuite/test_small_data.py
`unittest.assertEquals()` deprecated in python 3.2, removed in python 3.12
> grass.gunittest: Fix usage of assertEquals() removed from Python 3.12

- raster/r.patch/testsuite/test_rpatch_artificial.py
Some tests of r.patch were randomly failing. The same problem and solution as in #2265.
> r.patch: ensure r.in.ascii in relevant tests always create CELL

- scripts/g.extension/g.extension.py
> g.extension: if copied files exists do not print warning message

- utils/generate_release_notes.py
Based on the issue reported on Gitter 'there must be an empty line after the section titles to be valid MD.' This adds an extra newline after the headings generated by the script. Some headings are generated by the GitHub API and they don't include the line. GitHub rendering works well for both versions.
> contributing: Add empty line after heading in release notes

- doc/howto_release.md
- doc/infrastructure.md
- partial sync to document version in `main`
- markdown linting fixes
- some outdated version numbers updated
- fix path to helper script
Note: PRs for the other branches will be created separately (do not back-/forward-port this PR).
> contributing: release procedure updates (G83)

- doc/howto_release.md
- doc/infrastructure.md
- partial sync to document version in `main`
- markdown linting fixes
- some outdated version numbers updated
- fix path to helper script
Note: PRs for the other branches will be created separately (do not forward-port this PR).
> contributing: release procedure updates (G82)

- gui/wxpython/core/settings.py
- gui/wxpython/gui_core/preferences.py
- gui/wxpython/main_window/frame.py
Fixes https://github.com/OSGeo/grass/issues/3013
> wxGUI: Default Single-Window size is too small

- gui/wxpython/vdigit/mapwindow.py
- gui/wxpython/vdigit/toolbars.py
The bug could be reproduced by:
1. Starting digitizer
2. Switch to panning
3. Switch to a digitizer tool -> doesn't work
Also g.gui.iclass doesn't work.
The toolbar tools were bound to the ToolbarController.OnTool method, this PR replaces the controller's method in runtime by the specific one in digitizer toolbar. Probably there could be a better solution, but this seems to work and the code is changed minimally.
Unrelated change is removing setting focus, seems to help with using keyboard shortcuts.
> wxGUI/digitizer: fix digitizer - VDigitToolbar.OnTool method was not called

- python/grass/temporal/univar_statistics.py
- temporal/t.rast.univar/t.rast.univar.py
- temporal/t.rast.univar/testsuite/test_t_rast_univar.py
This PR adds support for percentiles to `t.rast.univar`.
> t.rast.univar: Add support for percentiles

- docker/debian/Dockerfile
Needed update after new Debian 12 stable release.
Also update PDAL to v2.5.5.
This fixes the currently broken CI.
> docker: update to Debian 12 and PDAL 2.5.5

- docker/alpine/Dockerfile
In `alpine:3.18` many GDAL drivers were removed from the base package to reduce package size [(see related alpine aports issue here)](https://gitlab.alpinelinux.org/alpine/aports/-/issues/14910). Instead they can be installed individually. A list of all available additional drivers can be found [here](https://pkgs.alpinelinux.org/packages?name=gdal-driver*&branch=v3.18&repo=&arch=x86_64&maintainer=). Few were already removed from 3.15 to 3.17. 
This PR suggests to add the possibly most common ones.
Following a list of which drivers were removed from `gdal-tools` package between `alpine:3.17` and `alpine 3.18` :
```
vector
4   BAG -raster,multidimensional raster,vector- (rw+v): Bathymetry Attributed Grid
5   CAD -raster,vector- (rovs): AutoCAD Driver
8   Carto -vector- (rw+): Carto
15 …
```
> Docker alpine: add additional GDAL driver

- docker/alpine/Dockerfile
To allow backporting of changes in alpine Dockerfile and to make it more easy to update to new versions in the future, this PR suggests to get rid of the hardcoded GRASS GIS versions in the Dockerfile.
> Docker alpine: Get rid of hardcoded GRASS GIS version in Dockerfile

- raster/r.resamp.bspline/main.c
This PR fixes a memory leak in `r.resamp.bspline` that becomes apparent only with larger input raster maps
> r.resamp.bspline: fix memory leak

- doc/development/submitting/submitting.md
A bit more detail on how to use set up Pre-commit.
> contributing: Expand instructions on pre-commit

- gui/wxpython/core/gconsole.py
- gui/wxpython/core/globalvar.py
- gui/wxpython/core/ws.py
- gui/wxpython/nviz/workspace.py
- lib/init/grass.py
- python/grass/gunittest/multirunner.py
- python/grass/imaging/images2swf.py
- python/grass/pygrass/modules/interface/testsuite/test_modules.py
- python/grass/pygrass/raster/testsuite/test_raster_region.py
- python/grass/script/task.py
- python/grass/script/utils.py
- scripts/r.in.wms/wms_cap_parsers.py
- scripts/r.in.wms/wms_drv.py
Hi,
Here's some cleanup of the old python 2 versus 3 logic.
https://github.com/OSGeo/grass/discussions/2055
If you are please with this first batch I can proceed to do the remainder.
> Python: Python2 removal

- gui/wxpython/startup/guiutils.py
When creating new mapset (through data catalog or menu settings), this PR initializes db connection. This would prevent problem in #3078 (although that needs to be fixed separately).
> wxGUI: initialize db connection when creating new mapset

- vector/v.db.select/main.c
- vector/v.db.select/testsuite/test_v_db_select.py
- vector/v.db.select/testsuite/test_v_db_select_json_csv.py
- vector/v.db.select/v.db.select.html
The JSON output now has column names and types under info/columns.
The example in documentation does not include the unclear note about booleans (perhaps a discussion for another place).
A command to reproduce the example output is now included.
Documentation and test of the new functionality are included.
> v.db.select: Add column names and types to JSON

- gui/wxpython/dbmgr/base.py
> wxGUI/dbmgr: fix show attribute table for vector map from another mapset

- scripts/r.drain/r.drain.py
Running r.drain with map@mapset fails. This PR  fixes that and also makes tmp map names safe for parallelization on cluster (include also node in the name).
> r.drain: fix for fully-qualified map names

- gui/wxpython/dbmgr/base.py
When right-clicking on a column header with non-numerical type in attribute table manager, an error appears:
```
"/home/vpetras/Projects/grass/code/grass/dist.x86_64-pc-
linux-gnu/gui/wxpython/dbmgr/base.py", line 522, in
OnColumnMenu
popupMenu.Enable(self.popupId["calculate"], False)
wx._core
.
:
C++ assertion ""item"" failed at /home/wxpy/wxPython-4.1.1/e
xt/wxWidgets/src/common/menucmn.cpp(793) in Enable():
wxMenu::Enable: no such item
```
This PR addresses that. The error probably appears only in the newer versions of wxPython, but I am not sure which one broke it.
> wxGUI/dbmgr: fix showing attribute column menu

- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/layertree.py
- gui/wxpython/main_window/frame.py
Saving web service layer as raster map fail.
1. From the GUI Layers pane toolbar launch Add web service map dialog
2. Hit Add default button
3. Choose OSM-WMS item from the load profiles ComboBox widget
4. Hit Connect button
5. From the tree list of layers choose some layer e.g. OpenStreetMap WMS - by terrestris
6. Hit Add layer button 
7.  From the Layers pane choose added web service layer OpenStreetMap WMS - by terrestris and by right mouse click invoke layer menu and choose Save web service layer menu item
8. See error
```
File "/usr/lib64/grass84/gui/wxpython/lmgr/layertree.py",
line 862, in OnSaveWs
parent=self, layer=mapLayer, giface=self._gifaceForDisplay
AttributeError
: …
```
> wxGUI/lmgr: fix saving web service layer as raster map

- lib/gis/renamed_options
- raster/r.texture/r.texture.html
Fixes example and registers old `prefix` in `lib/gis/renamed_options`.
(was missing in e212c96107110eb9d29f69e03c3ae226a928eefd)
> r.texture manual: fix output parameter in example

- gui/wxpython/timeline/frame.py
Fixes #3082.
https://github.com/kecnry/autofig/issues/45
https://github.com/kecnry/autofig/commit/93e6debb953f5b2afe05f463064d60b9566afa59
> wxGUI/timeline: add _change_geometry() method for Matplotlib version >= 3.4

- raster/r.sun/local_proto.h
- raster/r.sun/main.c
- raster/r.sun/rsunglobals.h
- raster/r.sun/rsunlib.c
This is a partial, manual backport of https://github.com/OSGeo/grass/pull/1405.
The warning is treated as an error by Clang 16+ and the compilation fails.
Considering next 7.8 release likely will be the last, this should be a blocker.
> r.sun: fix -Wimplicit-int warnings

- doc/howto_release.md
> howto_release.md: update wingrass notes

- rpm/grass-pkgconfig.patch
- rpm/grass.spec
Use the latest grass.spec from Fedora Git repo,
https://src.fedoraproject.org/rpms/grass/blob/rawhide/f/grass.spec
Fixes #3114
Co-authored-by: @a-detiste
> pkg: remove support for RHEL6 in grass.spec

- raster/r.sim/simlib/hydro.c
- raster/r.sim/simlib/input.c
Parameter infil_value was ignored, only infil (as a raster) was working.  I also removed an unnecessary test for rain (related to the fixed condition, inf should always be initialized).
Addresses #3106.
> r.sim: fix previously ignored infil_value

- scripts/r.fillnulls/r.fillnulls.html
- scripts/r.fillnulls/r.fillnulls.py
Proceed if no holes present also for `rst` method - now all methods behave the same.
In case no holes are in the current region of the raster input map the map is copied over and no fatal error is issues (same for all methods).
Test case:
```bash
g.region raster=elevation -p
r.fillnulls input=elevation output=test method=bilinear
r.fillnulls input=elevation output=test method=rst
```
Fixes #2986
> r.fillnulls: proceed if no holes present (RST method)

- CITATION.cff
Syntax errors fixed (needed for Zenodo.org auto-upload and also in general).
Validated successfully with [cffconvert](https://github.com/citation-file-format/cffconvert):
```
cffconvert --validate
Citation metadata are valid according to schema version 1.2.0.
```
with
```
cffconvert --version
3.0.0a0
```
> docs: fix syntax of CITATION.cff file

- .github/workflows/docker.yml
This PR simplifies the github workflow for docker build, tag and push.
Due to some tag restructuring and new features of [docker/metadata-action](https://github.com/docker/metadata-action) it now only uses one job and, depending on the trigger action, creates different tags. It will create four different types of tags:
- `latest` for main branch and with ubuntu os
- `{{ branch }}-{{ os }}` for all configured branches, e.g. `releasebranch_8_3-alpine`
- `{{ tag }}-{{ os }}` for all published releases. e.g. `8.3.0-alpine`
- `current-{{ os }}` for a still hard-coded branch, here update to releasebranch_8_3, e.g `current-alpine`
This new naming conforms more with the GRASS GIS naming style of versions. While naming of branches and tags and content of `latest` tag is still the same, it adds …
> docker: CI update and simplification

- raster/r.neighbors/main.c
- raster/r.patch/main.c
- raster/r.resamp.filter/main.c
- raster/r.series/main.c
With the parallelization of various raster modules, a memory option for a new output buffer was introduced. The calculation of the number of buffered rows did not take into account that a potentially large amount of RAM is already used for input data. This PR adjusts the calculation of the number of rows to be buffered for output maps for the modules `r.neighbors`, `r.patch`, `r.resamp.filter`, and `r.series`, avoiding accidental OOM errors. These modules should now use not (much) more than the user-specified amount of RAM.
> parallelized raster modules: fix buffer sizes

- misc/m.nviz.image/surface.c
Create output image with `m.nviz.image elevation_map=elevation perspective=15 output=/tmp/elevation` module fails if  `color_map` param arg is not used.
1. Run `m.nviz.image elevation_map=elevation perspective=15 output=/tmp/elevation` from the emulator terminal
2. See error
```
GRASS nc_spm_08_grass7/PERMANENT:~ > m.nviz.image elevation_map=elevation perspective=15 output=/tmp/elevation
Loading raster map <elevation@PERMANENT>...
100%
Segmentation fault
```
Create output image with `m.nviz.image elevation_map=elevation perspective=15 output=/tmp/elevation` module should work  if  `color_map` param arg is not used.
- Operating …
> m.nviz.image: fix checking if color raster map exists if color_map param arg was used

- gui/wxpython/gui_core/gselect.py
Opening vector digitizer settings dialog while editing vector map fails.
1. Launch Vector Digitizer e.g. `g.gui.vdigit geology`
2. From the Vector Digitizer window main toolbar activate Settings tool
3. See error
```
File "/usr/lib64/grass84/gui/wxpython/vdigit/toolbars.py", line 698, in OnSettings
self.settingsDialog = VDigitSettingsDialog(
File "/usr/lib64/grass84/gui/wxpython/vdigit/preferences.py", line 48, in __init__
self._createAttributesPage(notebook)
File "/usr/lib64/grass84/gui/wxpython/vdigit/preferences.py", line 638, in _createAttributesPage
column.InsertColumns(
File "/usr/lib64/grass84/gui/wxpython/gui_core/gselect.py", line 1176, in InsertColumns
for key, value in …
```
> wxGUI/vdidit: fix opening Vector Digitizer settings dialog while editing vector map

- raster/r.watershed/ram/do_cum.c
- raster/r.watershed/seg/do_cum.c
- raster/r.watershed/testsuite/r_watershed_test.py
The PR #2648 introduced a bug in `r.watershed` such that streams and basins are no longer correctly calculated. This PR fixes calculation of streams and basins in `r.watershed`.
> r.watershed: fix streams and basins

- locale/po/grasslibs_de.po
- locale/po/grasslibs_ru.po
- locale/po/grassmods_de.po
- locale/po/grassmods_ru.po
- locale/po/grasswxpy_de.po
- locale/po/grasswxpy_ru.po
Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [GRASS GIS/grasslibs](https://weblate.osgeo.org/projects/grass-gis/grasslibs/).
It also includes following components:
* [GRASS GIS/grasswxpy](https://weblate.osgeo.org/projects/grass-gis/grasswxpy/)
* [GRASS GIS/grassmods](https://weblate.osgeo.org/projects/grass-gis/grassmods/)
Current translation status:
> Translations update from OSGeo Weblate

- gui/wxpython/dbmgr/base.py
Duplicated column name  be added into table description `TableListCtrl` widget (see screenshot below).
2. Switch to Manage tables page (tab)
3. Add new column with same name as existed col name GEO_NAME
4. You see correct error dialog with message: Column <GEO_NAME> already exists in table <geology>.
7. Duplicated column name is added into table description `TableListCtrl` widget
Duplicated column name shouldn't be added into table description `TableListCtrl` widget
- GRASS GIS version: all
> wxGUI/dbmgr: don't add new duplicated table col into table desc TableListCtrl widget

- gui/wxpython/dbmgr/base.py
Sorting (asc/desc) newly added column values via wxGUI dbmgr doesn't work.
2. Switch to Manage tables page (tab)
3. Add new column e.g. **area** with double precision type
4. Switch to Browse data page (tab)
5. Right mouse click to the **area** column to invoke menu and choose Calculate (only numeric columns) -> Area size
6. Left mouse click on the **area** column to sorting values
7. See error
```
File "/home/tomas/.local/lib/python3.9/site-packages/wx/lib/mixins/listctrl.py", line 129, in __OnColClick
self._colSortFlag[col] = int(not self._colSortFlag[col])
IndexError: list index out of range
```
or
6. Right mouse click to …
> wxGUI/dbmgr: fix sorting newly added column values

- gui/wxpython/animation/controller.py
Exporting an animation overlaid with a custom image fails.
1. Launch animation tool wxGUI `g.gui.animation`
2. Add some raster map(s) for creating animation
3. Activate Export animation tool from the animation window toolbar
4. On the Export animation dialog default Format page (tab) set output directory path for exported animation
5. On the Export animation dialog switch to Decorations page (tab)
6. Try to add some custom image (choose image file path)
7. Hit Export button
8. See error
```python
File
"/usr/lib64/grass84/gui/wxpython/animation/dialogs.py", line
1487, in OnExport
self.doExport.emit(
File
"/usr/lib64/grass84/etc/python/grass/pydispatch/signal.py",
line 233, in emit …
```
> wxGUI/animation: fix exporting an animation overlaid with custom image

- gui/wxpython/psmap/dialogs.py
> wxGUI/psmap: fix close vector map properties dialog after hit OK button

- gui/wxpython/psmap/dialogs.py
Typing the name of the vector map by keyboard inside vector map properties dialog (Map TextCtrl widget) print error message.
1. Launch Cartographic composer GUI `g.gui.psmap`
2. Add map frame with some raster map e.g. elevation
3. Add vector map layer by typing vector map name by keyboards e.g. streams 
4. See error
```
File "/usr/lib64/grass84/gui/wxpython/psmap/dialogs.py",
line 1865, in OnVector
topoInfo = grass.vector_info_topo(map=vmap)
File
"/usr/lib64/grass84/etc/python/grass/script/vector.py", line
185, in vector_info_topo
s = read_command("v.info", flags="t", layer=layer, map=map,
env=env)
File "/usr/lib64/grass84/etc/python/grass/script/core.py",
line 533, in read_command …
```
> wxGUI/psmap: fix vector map properties dialog correct typing the name of the vector map

- gui/wxpython/psmap/dialogs.py
Vector line map props dialog Choose line style (`PenStyleComboBox()` class) widget doesn't drawing items correctly.
2. Add map frame (via activating map frame tool from main toolbar), choose **vector line map** e.g. streams and hit Ok button (important is choose vector line map)
3. Double left mouse click on the square map frame to opening map frame dialog and switch to Vector maps page (tab)
4. On the Vector maps page (tab) hit Properties button to opening vector line e.g. streams map props dialog
5. On the vector line e.g. streams map props dialog switch to Size and style page (tab)
6. On Size and style page (tab) try to change  line style (Choose line style widget)
7. …
> wxGUI/psmap: fix vector line map props dialog PenStyleComboBox widget drawing items

- gui/wxpython/psmap/frame.py
Changing the position of the simple point graphic prints an error message.
1. Launch `g.gui.psmap`
2. Add one simple point graphic
3. Activate Pointer tool from the main toolbar
4. Try to interactively change simple point graphic position
5. See error
```
File "/usr/lib64/grass84/gui/wxpython/psmap/frame.py", line 1605, in MouseActions
File "/usr/lib64/grass84/gui/wxpython/psmap/frame.py", line 1849, in OnLeftUp
self.RecalculatePosition(ids=[self.dragId])
File "/usr/lib64/grass84/gui/wxpython/psmap/frame.py", line 2128, in RecalculatePosition
rect.Offset(
TypeError: Rect.Offset(): arguments did not match any overloaded call:
overload 1: argument 'dx' has …
```
> wxGUI/psmap: fix simple point graphic recalculate position

- scripts/g.extension/g.extension.py
Not all addon module are registered during installation on the OS MS Windows platform.
1. Apply PR #3166 first please
2. Try install one of the addons which name start with two characters **\*db.\*, ps.\*, r3.\*, wx.\*** e.g. `g.extension db.join`
3. Check if installed addon module is registered  `g.extension -a`
Addon module whose  name start with two characters **\*db.\*, ps.\*, r3.\*, wx.\*** should be registered during installation same as others addon module.
```
C:\Users\User>g.extension db.join
Downloading precompiled GRASS Addons <db.join>...
Fetching <db.join> from
<http://wingrass.fsv.cvut.cz/grass84/addons/grass-8.4.0dev/db.join.zip> (be
patient)...
Updating extension modules metadata …
```
> g.extension: fix registration addon with module name start with 2 chars db.*, ps.*, r3.*, wx.* 

- gui/wxpython/iscatt/plots.py
Supervised Classification Tool does not show scatter plots and prints error message.
1. Launch Supervised Classification Tool wxGUI `g.gui.iclass`
2. On the left Plots pane combobox widget choose **Scatter plots** item
3. On the Scatter plots toolbar activate Add scatter plot tool
5. On the Select imagery group dialog from the name of imagery group listbox widget items choose **lsat7_2000**
6. Hit Create/edit group... button widget
7. On the Create or edit image group dialog, type into Select existing subgroup or enter name of new subgroup combobox widget new subgroup name e.g. **test** and select some maps from the list to be part of the new cretaed subgroup **test** (lsat7_2000_10, lsat7_2000_20, lsat7_2000_30, …
> wxGUI/iclass: fix showing scatter plots

- gui/wxpython/image2target/ii2t_manager.py
Showing Map Georectifier and Ground Control Points manager for 3D correction tool settings dialog fails and prints an error message.
1. Launch Map Georectifier and Ground Control Points manager for 3D correction tool window `g.gui.image2target`
2. From the Select source location combobox widget choose nc_spm_08_grass7 location
3. From the Select source mapset combobox widget choose landsat mapset
4. Hit Next > button widget
5. On the next wizard Select image/map group to georectify page choose from the Select group combobox widget lsat7_2000 group
6. On the next wizard Select maps to display for GCP creation page from the Select source map to display combobox widget choose lsat7_2000_10@landsat map
7. Hit Finish button …
> wxGUI/image2target: fix showing Ground Control Points settings dialog

- gui/wxpython/gmodeler/frame.py
Saving the Graphical Modeler current model settings to model file fails and prints an error message if Graphical Modeler window is closed.
1. Launch  Graphical Modeler `g.gui.gmodeler`
2. Add GRASS tool (module) to model e.g. simple module command `db.test test1`
3. Validate model
4. Run model
5. Close Graphical Modeler window by keyboard shortcut Alt + F4 or via toolbar Quit tool
6.  On the confirm save current model settings to model file dialog hit Yes button
7. See error
```
File "/usr/lib64/grass84/gui/wxpython/gmodeler/frame.py", line 373, in OnCloseWindow
self.OnWorkspaceSaveAs()
AttributeError: 'ModelFrame' object has no attribute 'OnWorkspaceSaveAs'
``` …
> wxGUI/gmodeler: fix storing current model settings to model file

- gui/wxpython/gui_core/preferences.py
Setting wxGUI command output font fails and prints an error message.
2. Open GUI settings dialog from main toolbar
4. On the GUI settings dialog switch to Appearance page (tab)
5.  Try to change command output font (Font settings), hit Set font button widget
6.  See error
```
File
"/usr/lib64/grass84/gui/wxpython/gui_core/preferences.py",
line 2042, in OnSetOutputFont
outfont = wx.Font(
TypeError
:
Font(): arguments did not match any overloaded call:
overload 1: too many arguments
overload 2: argument 1 has unexpected type 'float'
overload 3: argument 1 has unexpected type 'float'
overload 4: argument 1 has unexpected type 'float'
overload 5: argument 1 has …
```
> wxGUI/preferences: fix setting command output font

- gui/wxpython/iscatt/plots.py
Activating Supervised Classification Tool window scatter plots pane zoom to scatter plot extend menu item prints an error message.
1. Launch Supervised Classification Tool wxGUI `g.gui.iclass`
2. On the left Plots pane combobox widget choose **Scatter plots** item
3. On the Scatter plots toolbar activate Add scatter plot tool
5. On the Select imagery group dialog from the name of imagery group listbox widget items choose **lsat7_2000**
6. Hit Create/edit group... button widget
7. On the Create or edit image group dialog, type into Select existing subgroup or enter name of new subgroup combobox widget new subgroup name e.g. **test** and select some maps from the list to be part of the new cretaed subgroup **test** …
> wxGUI/iclass: fix zoom to scatter plot extend

- gui/wxpython/main_window/frame.py
Which override base OnClose window close event handler method to prevent prematurely uninitialize manager.
PR https://github.com/wxWidgets/Phoenix/pull/2460
Fixes #2647.
> wxGUI/main_window: add and use custom SingleWindowAuiManager class

- gui/wxpython/iscatt/frame.py
- gui/wxpython/iscatt/plots.py
Supervised Classification Tool  scatter plots pane prints error message when closed.
1. Launch Supervised Classification Tool wxGUI `g.gui.iclass`
2. On the left Plots pane combobox widget choose **Scatter plots** item
3. On the Scatter plots toolbar activate Add scatter plot tool
5. On the Select imagery group dialog from the name of imagery group listbox widget items choose **lsat7_2000**
6. Hit Create/edit group... button widget
7. On the Create or edit image group dialog, type into Select existing subgroup or enter name of new subgroup combobox widget new subgroup name e.g. **test** and select some maps from the list to be part of the new cretaed subgroup **test** (lsat7_2000_10, lsat7_2000_20, lsat7_2000_30, …
> wxGUI/iclass: fix closing scatter plot pane via x button

- gui/wxpython/dbmgr/base.py
The wxGUI Attribute Table Manager adjusts the layer settings even if the settings have not changed while pressing the Modify layer button.
1. Launch Attribute Table Manager e.g. `g.gui.dbmgr geology`
2. On the Attribute Table Manager window switch to the Manage Layers page (tab)
3. On the Manage Layers page (tab) switch to the Modify layer  page (tab)
4. Do not change layer settings
5. Hit Modify layer button
6.  See error
```
File "/usr/lib64/grass84/gui/wxpython/dbmgr/base.py", line 3896, in OnModifyLayer
self.parentDialog.parentDbMgrBase.UpdateDialog(layer=layer)
File "/usr/lib64/grass84/gui/wxpython/dbmgr/manager.py", line 253, in UpdateDialog
DbMgrBase.UpdateDialog(self, …
```
> wxGUI/dbmgr: do not modify layer settings if settings have not changed

- gui/wxpython/nviz/tools.py
With Single Window Mode 3D view mode tools pane (default width) has missing horizontal scrollbar or horizontal and vertical scrollbar also.
1. Launch wxGUI with Single Window Mode
2. Display some raster map e.g. elevation `d.rast elevation`
3. Switch from 2D view to 3D view
4. It is not possible change some 3D view settings on the pages View, Data, Appearance, Analysis, Animation with default pane width due tools panel has missing horizontal or vertical scrollbar **by default**.
3D view settings pages View, Data, Appearance, Analysis, Animation with default pane width should have horizontal or  vertical scrollbar.
A. View page
| Default behavior|Expected behavior| …
> wxGUI/nviz: make tools panel verically and horizontally scrollable for Single Window Mode

- gui/wxpython/gui_core/mapdisp.py
The standalone Vector Digitizer app window doesn't close after you hit "power off" toolbar.
1. Launch wxGUI Vector Digitizer as standalone app  e.g. `g.gui.vdigit map=geology`
2. Quit Vector Digitizer by click on the "power off" toolbar
3. The Vector Digitizer window doesn't close
Standalone Vector Digitizer app window should be closed after you hit "power off" toolbar.
- GRASS GIS version: 8.3.dev, 8.2
> wxGUI/vdigit: fix close frame if Vector Digitizer is run as standalone app g.gui.vdigit

- gui/wxpython/psmap/dialogs.py
Map image element doesn't show preview on the Image settings dialog for adding map image element. 
2. From the main toolbar activate Add map elements tool and choose Image
3. On the Image settings dialog select the directory where the EPS images are stored
4. Choose image from list of loaded images
5. See error
```
File "/usr/lib/python3.10/site-packages/wx/lib/filebrowsebutton.py", line 140, in OnChanged
self.changeCallback(evt)
File "/usr/lib64/grass84/gui/wxpython/psmap/dialogs.py", line 5908, in OnDirChanged
self.OnImageSelectionChanged(None)
File "/usr/lib64/grass84/gui/wxpython/psmap/dialogs.py", line 5958, in OnImageSelectionChanged …
```
> wxGUI/psmap: fix showing image map element preview

- gui/wxpython/mapwin/buffered.py
- gui/wxpython/psmap/frame.py
Map Swipe tool Save display to file tool doesn't work an prints an error message.
1. Launch Map Swipe tool `g.gui.mapswipe`
2. Display some two comparable maps
3. Try activate  Save display to file tool from the main toolbar
4. Save display to file
5. See error
```
File "/usr/lib64/grass84/gui/wxpython/core/gthread.py", line 138, in OnDone
event.ondone(event)
File "/usr/lib64/grass84/gui/wxpython/core/render.py", line 510, in OnRenderDone
self.updateProgress.emit(env=event.userdata["env"], layer=self.layer)
File "/usr/lib64/grass84/etc/python/grass/pydispatch/signal.py", line 233, in emit
File …
```
> wxGUI/mapswipe: fix saving display to file

- gui/wxpython/iscatt/toolbars.py
Activating Supervised Classification Tool window scatter plots pane toolbar tools prints an error message.
1. Launch Supervised Classification Tool wxGUI `g.gui.iclass`
2. On the left Plots pane combobox widget choose **Scatter plots** item
3. On the Scatter plots toolbar activate Add scatter plot tool
5. On the Select imagery group dialog from the name of imagery group listbox widget items choose **lsat7_2000**
6. Hit Create/edit group... button widget
7. On the Create or edit image group dialog, type into Select existing subgroup or enter name of new subgroup combobox widget new subgroup name e.g. **test** and select some maps from the list to be part of the new cretaed subgroup **test** (lsat7_2000_10, …
> wxGUI/iclass: fix activating scatter plot pane toolbar tools

- scripts/g.extension/g.extension.py
Fixes #3077.
Fix installing addons via g.extension module on the OS MS Windows without dependency on Git program.
Gettings official GitHub addons repository branches `g.extension -l` is based on the parsing official GitHub addons repository all branches HTML page URL https://github.com/OSGeo/grass-addons/branches/all/ (request/response) instead of using GitHub REST API due restrictions.
> g.extension: fix installing addons on the OS MS Windows

- gui/wxpython/psmap/frame.py
- gui/wxpython/psmap/g.gui.psmap.html
Wrong error message if Ghostscript gswin32c/gswin64c isn't installed (required for rendering output PDF file) on the OS MS Windows platform
1. Download and install e.g. [WinGRASS-8.3.dev ](https://wingrass.fsv.cvut.cz/grass83/WinGRASS-8.3.dev-c7495e2ef-123-Setup.exe)
1. Launch wxGUI Cartographic Composer `g.gui.psmap`
2. Add Map frame and choose some raster map e.g. elevation
3. Push toolbar Generate PDF output tool
4. See error
If Ghostscript gswin32c/gswin64c isn't installed (required for rendering output PDF file), show correct error message.
- Operating System: MS Windows
- GRASS GIS version: all versions
> wxGUI/psmap: fix show correct error message if Ghostscript isn't installed (required for rendering output PDF file) on the OS MS Windows platform

- gui/wxpython/dbmgr/base.py
When you add new table column or rename existed or delete, Browse data page Simple SQL Query WHERE `ComboBox` widget column names choices doesn't update. Same for SQL Builder frame (**must be opened before added/renamed/deleted table column**) `ListBox` widget table column names choices. Same for Field Calculator (**must be opened before added/renamed/deleted table column**) `ListBox` widget table column names choices.
2. Switch to Manage tables page (tab)
3. Add new column e.g. **test** with double precision type or rename existed column e.g. **PERIMETER -> PERIMETER_NEW** or delete some existed table column e.g. **PERIMETER**
4. Switch to Browse data page …
> wxGUI/dbmgr: update Browse data page Simple SQL Query WHERE ComboBox widget column names choices

- gui/wxpython/dbmgr/base.py
- gui/wxpython/gui_core/widgets.py
Removing map table layer don't work and related layer page (tab) on the Browse data and Manage tables page (tab) aren't deleted too.
2. Switch to Manage layers page (tab)
3. Create new table with name e.g. **test** (right side on the Add layer page (tab))
4. Add new layer with layer number 2, and choose **test** table from table choice widget and hit Add layer button
5. On the Manage layers page (tab) switch to Remove layer page (tab)
6. Choose layer 2 from Layer to remove ComboBox widget choices and hit Remove layer button
7. See error
```
File "/usr/lib64/grass83/gui/wxpython/dbmgr/base.py", line 3815, in OnDeleteLayer …
```
> wxGUI/dbmgr: fix removing map table layer and layer related Browse data and Manage tables page (tab)

- imagery/i.topo.corr/i.topo.corr.html
- raster/r.sunmask/r.sunmask.html
- r.sunmask:
- explain sun angles
- update URLs to NREL
- i.topo.corr: improve angle descriptions
Critical review of angles appreciated.
> manual: r.sunmask and i.topo.corr improvements

- doc/howto_release.md
- finetuning of instructions after last 8.3.0 release 
(note: no backport, will be done in a separate PR, #3197)
> docs: update howto_release.md (main)

- imagery/i.ortho.photo/i.ortho.camera/i.ortho.camera.html
- imagery/i.ortho.photo/i.ortho.elev/i.ortho.elev.html
- imagery/i.ortho.photo/i.ortho.init/i.ortho.init.html
- imagery/i.ortho.photo/i.ortho.rectify/i.ortho.rectify.html
- imagery/i.ortho.photo/i.ortho.target/i.ortho.target.html
- imagery/i.ortho.photo/lib/conz_points.c
Time ago some GRASS GIS 6 modules have been rewritten:
- `i.photo.2target` -> `g.gui.photo2image`
- `i.photo.2image` -> `g.gui.image2target`
This PR updates the references in the manual accordingly.
> manual: i.ortho.* update broken module references

- vector/v.reclass/v.reclass.html
Add a note about the fact that either 'rules' or 'column' option must be specified.
See https://github.com/OSGeo/grass/blob/5cb4e430b5e405bce4ab30e6d20c15222b10815f/vector/v.reclass/main.c#L103-L107.
> Update v.reclass.html: either 'rules' or 'column' option must be specified

- utils/grass_clang_format.sh
- Adopt to the fact the result of `clang-format --version` may look slightly different on various platforms.
- Make sure 'clang-format' version 15 is used (v 16+ results in unwanted changes)
Closes https://github.com/OSGeo/grass/issues/3183
> utils: fix clang-format version check

- .dockerignore
- docker/testdata/test_docker_image.sh
- docker/testdata/test_grass_python.py
- docker/ubuntu/Dockerfile
- docker/ubuntu/README.md
This PR implements multi-stage-builds for _ubuntu_, comparable to how they are set up for _alpine_. It also adds a test script for docker files, that should be usable across different distributions...
Image size is reduced to ~1.6 GB (from > 2GB), while some new features are added and datum grids are removed.
A major change is also that GIS packages now come from `ubuntugis-unstable`, so the image ships more recent versions of GDAL, GEOS. In addition, PDAL does not have to be compiled...
Some dev-packages (e.g. gdal-dev, geos-dev) are kept for addon installation, but they still take quite some space so, I am happy to remove some more, depending on what you consider a good size/functionality trade-off.
Adresses: #776
> docker: implement multi-stage-builds for ubuntu

- .github/workflows/python-code-quality.yml
- Dockerfile
- docker/ubuntu/Dockerfile
Closes https://github.com/OSGeo/grass/issues/3204 
I copied over the ubuntu dockerfile edited in #3170 to the dockerfile in the root of the repo, and added a note at the top for future edits to the file (in both files).
This should allow the additional checks to pass again.
> Docker: Sync main Dockerfile to docker/ubuntu/Dockerfile

- python/grass/script/array.py
numpy.memap needs to be flushed so that grass.script.array.write() method writes correct content to a raster. The problem was found when running on an HPC with fairly large array that was being modified and then written to raster - only portion of it was being written correctly, the rest was empty.
May be worth including in 8.3.1 release.
> grass.script: ensure memmap content is flushed before writing to a raster

- docker/debian/Dockerfile
see /usr/share/lintian/data/fields/obsolete-packages
These transitional packages will be removed in Debian 13 Trixie
> pkg: Debian 12: replace obsolete transitional packages by new ones

- gui/wxpython/core/utils.py
This rewrite tries to avoid an error reported by a user:
While I couldn't understand why exactly this happened (possibly something to do with starting GRASS in temporary project, which might have removed from disk), this function should fail gracefully.
I also documented 'ordered' option and renamed variables for clarity.
> wxGUI: rewrite and document core.utils.ListOfMapsets to not cause GUI crash in certain circumstances

- doc/development/rfc/python_language_support.md
Moved draft RFC from tracwiki:
https://trac.osgeo.org/grass/wiki/RFC/8_LanguageStandardsSupportPython
> RFC: Python Language Support

- doc/gui/wxpython/example/frame.py
* meanwhile, delete an unused variable `statitistics`
> g.gui.example: fix typo in statitistics -> statistics

- python/grass/pygrass/raster/buffer.py
* `np.int0` is a deprecated alias for `np.intp` since `np==1.24`
* fix #3227
> pygrass: replace deprecated np.int0 with np.intp

- utils/mkhtml.py
> utils: fix add HTML module man page Source code section for all module HTML files

- display/d.legend.vect/draw.c
Later test (line 270) uses title width to compute background size regardless of title presence, but original code initialized title_w only when title was set.
This fixes occasional extra wide legend background rectangle.
Identified by valgrind as: Conditional jump or move depends on uninitialised value(s).
> d.legend.vect: Initialize title size

- .pre-commit-config.yaml
Renovate bot commit may contain trailing comments with 1 space from the content. This is caused by Renovate uses 'prettier' for formatting, which has a different default compared to yamllint, and that is not likely to change.
This is completely arbitrary, thus to avoid further linting issues cased by Renovate we can as well adapt to use 1 min-space from content.
Update: I added a commit which prepares pre-commit config for the use of `pre-commit.ci` if we choose do so. This part will otherwise make no difference.
- Skip flake8 for pre-commit.ci, as the '.flake8' file is ignored by pre-commit.ci.
- For some unknown reason the 'clang-format' of pre-commit.ci also formats ipynb files (being json files), but local use of pre-commit does not. Exclude ipynb files from clang-format.
> pre-commit: set min-space to 1 for in-line comments in yaml files

- .github/workflows/python-code-quality.yml
- Dockerfile
- docker/ubuntu/Dockerfile
- locale/transifex/.tx/config
- locale/transifex/transifex_merge_2.sh
Address pre-commit warnings and fixes. A majority of the issues originate from CI bot PRs, but not all.
This emphasises the need to explore the introduction of [pre-commit.ci](https://pre-commit.ci/).
> lint: fix pre-commit warnings/errors

- .github/workflows/pytest.yml
Using pytest-xdist, it is possible to use multiple cores to run pytest, with many multiple options to manage the queue.
Since there isn’t many tests to run with pytest, only 100, the runtime for the complete pytest workflow goes from 532-537 seconds to 439-451 seconds (about 86-93 seconds faster). For each run. The pytest only part passed from 3:24-3:44 to 2:04-2:19.
Caching python packages doesn’t seem to help a lot, since only about 30 seconds is passed on this.
In my Megalinter repo, this had a bigger impact, cutting off ~10mins on our longest workflow, cutting the python tests time in half. (It automatically chose 4 workers for the 2 cores in CI, but a lot of time is idle depending on the linters to spin up)
> Speed up pytest workflow by 1min20 with pytest-xdist

- doc/howto_release.md
Partial sync to `main`, following #2414:
- Add cron job update
- Restructure updates to website and wiki
- Remove Launchpad notes (apparently not used, at least not by the release manager)
- Change of procedure for the mailing list announcements
- Improves precision in the text
Note that there are still differences in the initial `git` sync part: also to be synced?
> contributing: Optimize commands, text in release procedure (G83)

- .github/workflows/periodic_update.yml
Fixes the `Periodic update` workflow's cron settings to run the first Wednesday every month.
This also removes the setting of labels for the update PRs created by the bot.
> CI: fix Periodic update's cron and do not add labels

- lib/gis/renamed_options
This PR fixes the key-value pairs for t.* modules in `etc/renamed_options`. Still, flag renaming is not support yet without #3256.
> parser: Fix key-value pairs for t.* modules in renamed_options

- lib/gis/parser.c
This PR supports flag to flag, flag to option (fatal error), option to flag (fatal error) renaming.
https://github.com/OSGeo/grass/blob/816c25f62cd6723aa956939b157ac1f3da1c8f44/lib/gis/renamed_options#L453-L461
Above lines need a fix (2nd `|` => `:`). Fixed in #3260.
> parser: Support renamed flags (flags/options to options/flags as well)

- raster/r.horizon/main.c
- raster/r.horizon/testsuite/test_r_horizon.py
In point mode, some variables were not set properly, leading to major errors. Whenever it entered https://github.com/OSGeo/grass/blob/main/raster/r.horizon/main.c#L940 condition, it resulted in an error due to global variables `sinangle` and `cosangle` equal to 0. Raster mode was fine, those variables are initialized to proper values.
The fix uses `com_par` function (which was previously unused) with minor modification of its input. It sets those variables (and some others) and can be used in both modes, so now the variables in both modes should be set consistently.
The test computes horizon for an artificial, circular area (circle with z value 0 and 1000 around), so the horizon angles should be close to identical. This test would have previously resulted in zero horizon height …
> r.horizon: fix bug in point mode computation

- scripts/db.dropcolumn/db.dropcolumn.py
This PR supports a more recent sqlite3 command to drop a column within db.dropcolumn.
In sqlite3 [3.35.0, the DROP COLUMN](https://www.sqlite.org/changes.html#version_3_35_0) command was added. This PR makes use of the command if the sqlite3 version is high enough.
Background is a failing `db.in.ogr` command for a CSV file containing many columns:
```bash
GRASS cttest/PERMANENT:~ > db.in.ogr input=migr_emi2_L0.csv output=migr_emi2_L0
File "/usr/local/grass83/scripts/db.in.ogr", line 189, in <module>
main()
File "/usr/local/grass83/scripts/db.in.ogr", line 172, in main
grass.run_command(
File "/usr/local/grass83/etc/python/grass/script/core.py", line 466, in run_command
return handle_errors(returncode, result=None, args=args, kwargs=kwargs) …
```
> db.dropcolumn: Circumvent length limit for sqlite3 SQL STDIN string

- general/g.proj/output.c
- general/g.proj/testsuite/test_g_proj.py
This added minimal test of g.proj -w to see whether it fails on Windows and then I added the fix suggested in https://github.com/OSGeo/grass/issues/1955.
> g.proj: fix wkt output on Windows

- db/drivers/ogr/describe.c
- db/drivers/ogr/execute.c
- db/drivers/ogr/fetch.c
- include/grass/defs/gis.h
- lib/vector/Vlib/field.c
- raster/r.in.gdal/main.c
- vector/v.external/list.c
- vector/v.external/local_proto.h
- vector/v.external/main.c
- vector/v.external/proj.c
- vector/v.in.ogr/geom.c
- vector/v.in.ogr/global.h
- vector/v.in.ogr/main.c
- vector/v.in.ogr/proj.c
- vector/v.out.ogr/attrb.c
- vector/v.out.ogr/create.c
- vector/v.out.ogr/list.c
- vector/v.out.ogr/local_proto.h
- vector/v.out.ogr/main.c
This PR aims to cleanup grass code to remove "dead code" since most modern distribution/packaging have GDAL 3.
Fixes https://github.com/OSGeo/grass/issues/2645
> build: Remove compatibility to GDAL 1 and <2.2

- python/grass/pygrass/modules/interface/parameter.py
- vector/v.to.rast/testsuite/test_v_to_rast.py
Command line interface parser allows parameter (option) values such as 'val' when full value should be 'value'. Parameter class from pygrass does the checking, but does not know about these rules. This addition covers the simple case of val-value which is not much work to implement and maintain. It does not cover more complex cases with underscores and legacy aliases.
The test covers the issue for use=value change in v.to.rast made in #3110.
Strict checking in pygrass is discussed in #3237.
> grass.pygrass: Support shortened parameter values

- vector/v.in.ogr/geom.c
Sometimes there are unclosed polygon rings in input vectors which is a violation of the OGR simple feature specification. `ogrinfo` reports in these cases:
```
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
```
`ogr2ogr -makevalid` fails with
```
ERROR 1: IllegalArgumentException: Points of LinearRing do not form a closed linestring
```
This PR adds a fix by appending the first vertex to the end of an unclosed ring, thus closing it. It seems that this is usually the reason for unclosed rings: someone or some software forgot to append the first vertex as the last vertex.
This fix in `v.in.ogr` is only applied if polygon cleaning is not disabled with the `-c` flag, otherwise `v.in.ogr` will fail with a new …
> v.in.ogr: add fix for unclosed rings

- .github/workflows/pytest.yml
Contributes to https://github.com/OSGeo/grass/issues/3285
This is the second step of my PRs to modernize our Python code. It is the first bullet of #3285.
This PR simply adds Python 3.12 in our pytest workflows, in order to be able to see more warnings and deprecations. I chose this as it is a relatively fast workflow and the impact would be minimal. Of course, full coverage isn't there yet, as it only runs 103 tests, but at least some importing of our modules is done (grass.script and some grass.jupyter packages for now).
This doesn't mean for now that we support Python 3.12, but we should be for the next release, so work must start at some point.
> CI: Add Python 3.12 to pytest's matrix

- utils/release.yml
- Two modules can now be separated with comma (2 modules are quite common, more is probably something else).
- Weblate commit messages now match.
- Packaging actually can use the word packaging.
- Docker can have OS after slash.
- Changes of contributors can now use the plain word contributors.
> contributing: Add more expressions to match release notes groups

- vector/v.in.pdal/testsuite/test_v_in_pdal_basic.py
- vector/v.in.pdal/testsuite/test_v_in_pdal_filter.py
When trying to explore a bit more running unittest-based tests with pytest, discovering tests failed on this since shutils wasn’t imported in the file but used in the condition of `@unittest.skipIf`. Additionally found by a Python linter.
I don’t understand how the two test files could have run correctly and not fail yet with this missing import. Is it actually running in the test suite?
> Missing `shutil` import when used inside `@unittest.skipIf` condition

- python/grass/pygrass/messages/__init__.py
Was fixed in C code in https://github.com/OSGeo/grass/commit/9b61d2e668c82bd32b28aa560d70707b39cd2426
Addresses comment https://github.com/OSGeo/grass/pull/3316#issuecomment-1874837305
> python: Remove Shortening messages in pygrass messages

- vector/v.out.ogr/main.c
Currently, `v.out.ogr` deletes an existing OGR output layer in append+overwrite mode in [L618ff](https://github.com/OSGeo/grass/blob/main/vector/v.out.ogr/main.c#L618). This 
- deletion of an existing OGR output layer in append mode can be disastrous if it already contains valuable information and data that should definitively not be deleted
- causes an error because the layer to be appended has been deleted and can not be found in [L709](https://github.com/OSGeo/grass/blob/main/vector/v.out.ogr/main.c#L709), thus fatal error in [L724](https://github.com/OSGeo/grass/blob/main/vector/v.out.ogr/main.c#L724) 
In are more complex workflow, overwrite might be set to the whole workflow in order to overwrite previous interim GRASS results of an unsuccessful run. Once the processing finishes …
> v.out.ogr: fix append+overwrite mode

- db/drivers/mysql/db.c
The port argument is not a string, but a plain integer.  In the past, compilers ignore such type errors and produced a warning only, but this is changing, so this change also addresses a potential build failure.
Note that I can't really test this, but at least the compiler error is gone. Found as part of:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> Use integer port argument with mysql_real_connect

- gui/wxpython/core/utils.py
- gui/wxpython/history/browser.py
> wxGUI/history: fix execute r/r3.mapcalc module command

- .github/workflows/super-linter.yml
- doc/infrastructure.md
- macosx/ReadMe.md
Super-linter is now in its own organization since April 26th, 2023. This updates the workflow to use newer releases.
> Update super-linter.yml to use super-linter/super-linter

- .github/workflows/verify-success.yml
- imagery/i.evapo.time/i.evapo.time.html
- lib/cdhc/doc/chd_statlib.md
- raster/r.walk/r.walk.html
This addresses pre-commit errors, now passes `SKIP=flake8 pre-commit run --all-files`.
> checks: fix pre-commit errors

- .github/workflows/macos_gunittest.cfg
- .gunittest.cfg
- raster/r.in.gdal/testsuite/test_r_in_gdal.py
This should fix r.in.gdal test. I changed the expected east/west to match the actual imported data, which also matches what gdalinfo reports on the testdata. Why this wasn't the case before, I don't know.
Relevant output from gdalinfo on the test dataset:
```
Files: data/elevation3d.nc
Size is 150, 135
Origin = (630000.000000000000000,228500.000000000000000)
Pixel Size = (100.000000000000000,-100.000000000000000)
Corner Coordinates:
Upper Left  (  630000.000,  228500.000) 
Lower Left  (  630000.000,  215000.000) 
Upper Right (  645000.000,  228500.000) 
Lower Right (  645000.000,  215000.000) 
Center      (  637500.000,  221750.000) 
```
> r.in.gdal: fix and enable test

- .github/workflows/macos_install.sh
- .github/workflows/ubuntu.yml
- imagery/i.landsat.acca/algorithm.c
- lib/gis/strings.c
- lib/imagery/iscatt_core.c
- raster/r.fill.stats/main.c
- raster/r.mapcalc/map.c
Current C language support for GRASS is [C11 with **core** features](https://github.com/OSGeo/grass/blob/main/doc/development/rfc/language_standards_support.md#c-language), which does **not** include Variable Length Arrays (VLA). There are, however, a few places in the code that make use of VLAs. This leads us to either update the support directives; insert conditional code (using `__STDC_NO_VLA__`) ; or replace the use of such code.
Given the limited range of changes to the code, I will with this PR suggest to remove the use of VLA and make the code adhere to the RFC 7.
In addition to the code fixes, the `-Wvla` CFLAG is added to the Mac and Ubuntu CI builds to prevent VLA code to slip in again.
> Replace use of Variable Length Arrays in C code

- lib/imagery/group.c
This PR addresses warnings identified by Cppcheck in the lib/imagery/group.c file:
[duplicateExpression]: Refactored redundant conditions in the color assignment logic for improved code clarity.
[invalidscanf]: Added limits to fscanf to prevent potential crashes with large string inputs.
[variableScope]: Reduced variable scope to address scope warnings.
These modifications aim to enhance code clarity, ensure safer input processing, and resolve scope-related warnings in the imagery library.
Changes Made:
Refactored redundant conditions in color assignment logic.
Added limits to fscanf for safer input processing.
Reduced variable scope to address scope warnings.
Testing:
Manual testing performed to ensure the behavior of group.c functions remains unchanged.
Style check conducted using …
> refactor: imagery library resolve cppcheck warnings

- .github/labeler.yml
A little tune up in three parts:
1.  I noticed in my fork that the docs label was added to every PR. I went and reread very very attentively the docs for the labeler action, and noticed I missed that in the example for exclusion, there was a top level key that wasn’t `any` but `all`. So, inside the `changed-files`, the  results of the options `any-glob-to-any-file`, `any-glob-to-all-files`, `all-globs-to-any-file` and `all-globs-to-all-files` were `OR`-ed together. That is because by default, if `any` or `all` is missing, `any` is used. I expected the results of the individual sections of globs to be `AND`-ed together, ie the behavior of `all`.
2. Since I reread so attentively the docs, I observed that `blabla/**/*` was redundant to `blabla/**`, as a single star matches everything except …
> CI(labeler): Fix RFC exclusion from docs, adjust other globs

- .github/workflows/codeql-analysis.yml
During the last week or so, I explored many options and configuration possibilities to refresh our CodeQL jobs, starting from a new fresh advanced config and porting the new suggested practices one by one. This is the result of the most appropriate possibility.
1. First, the goal was to add a concurrency group for PRs, since even when exploring (for other things) in my fork, sometimes I was waiting on runners because a new push to a PR would not cancel CodeQL analysis like our other workflows.
2. Then, to improve build times, I added the number of jobs to the makeflags like our Ubuntu workflows.
3. ~CodeQL scanning for python doesn't need to have grass built to work. This wasn't the case before when CodeQL was introduced, lots have changed. It seems it is a static analysis, but still …
> CI(CodeQL): Improve run times and add concurrency groups

- gui/wxpython/core/gconsole.py
- gui/wxpython/core/giface.py
- gui/wxpython/gui_core/goutput.py
- gui/wxpython/gui_core/prompt.py
- gui/wxpython/history/browser.py
- gui/wxpython/history/tree.py
- gui/wxpython/lmgr/giface.py
- python/grass/grassdb/history.py
This PR is largely based on https://github.com/OSGeo/grass/pull/3310.
It implements new functionality with a pop-up command menu with an item for deleting commands from the history log and at the same time also makes some necessary changes in API to ensure better code maintenance in the future.
The API logic for the History panel respects the API used for the Data Catalog.
Main changes in API:
- Update signal was divided into two signals - addEntryToHistory and removeEntryFromHistory.
- The main class is the HistoryBrowserTree inheriting from CTreeView (similar logic as in DataCatalogTree)
- The HistoryBrowser class is used mainly for the widget layout
Fixes:
- except for editing the history log file when the command is removed from the tree, it also updates the cmd console buffer
- also …
> wxGUI/history: add pop-up command menu with an item for delete command from history + history tree refactoring

- gui/wxpython/gui_core/preferences.py
Currently saving preferences in Graphical Modeler (same applies to Map Swipe) fails with:
```py
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gmodeler/preferences.py", line 631, in OnSave
PreferencesBaseDialog.OnSave(self, event)
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/preferences.py", line 209, in OnSave
memorymb = self.memorymb.GetValue()
^^^^^^^^^^^^^
AttributeError: 'PreferencesDialog' object has no attribute 'memorymb'
```
The variable `self.memorymb` is defined in `gui._core.preferences.PreferencesDialog`. This PR fixes this bug by moving relevant code from `gui._core.preferences.PreferencesBaseDialog.OnSave()` to a new method `gui._core.preferences.PreferencesBaseDialog.OnSave()` .
> wxGUI/preferences: fix `PreferencesDialog` class `OnSave` method

- db/db.execute/db.execute.html
Although repeating the word `much` creates an undeniable emphasis on the user, I find its added value purely sentimental and consider it a mistake.
> db.execute: fix duplicated word in in docs

- gui/wxpython/gui_core/widgets.py
Module description is not show for first match automatically, only number of matches.
[Screencast from 2024-01-22 15-34-47.webm](https://github.com/OSGeo/grass/assets/5683186/6ae263ee-f158-43cc-8146-de31deecc103)
Module description shown including number of matches:
[Screencast from 2024-01-22 15-49-14.webm](https://github.com/OSGeo/grass/assets/5683186/308ec121-4147-405f-8b69-d475d6bacd06)
> SearchModuleWidget: show module description also for first match

- python/grass/temporal/abstract_space_time_dataset.py
- python/grass/temporal/metadata.py
- python/grass/temporal/temporal_granularity.py
After digging a bit I figured out that the bottleneck and reason for the very slow process for updating STDS metadata (see: #3136) is the _get_registered_maps_as_objects_ function.
Creating a map object takes 1/10 og 1/20 of a second, but with 100k maps that sums up to a quite a bit of time...
This PR is a work around for updating STDS metadata, that avoids using the slow function. But ideally, the function itself (_get_registered_maps_as_objects_) should be improved so it scales to larger STDS... I assume it is initilizing of DB interface that is most time consuming, but I did not investigate more deeply...
> temporal: Update STDS metadata from DB

- python/grass/temporal/stds_import.py
- python/grass/utils/download.py
- scripts/g.extension/g.extension.py
- scripts/r.unpack/r.unpack.py
- scripts/v.unpack/v.unpack.py
Fixed a CodeQL CWE-22 type issue (named Arbitrary file write during tarfile extraction), found when running an extended analysis (instead of only default).
The solution suggested in the alert didn’t seem appropriate (extracting files one by one), but I found that this issue was fixed in Python 3.12 and backported in the versions from 3.8 to 3.11.  The extraction filter chosen is the strictest, since the archives that are supposed to be extracted are purely data, we do not expect any rare or advanced behaviour.
https://docs.python.org/3/library/tarfile.html#extraction-filters
https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall
> python: Add extract filter for tarfile.extractall

- gui/wxpython/core/settings.py
- gui/wxpython/gmodeler/frame.py
- gui/wxpython/gmodeler/g.gui.gmodeler.html
- gui/wxpython/gmodeler/model.py
- gui/wxpython/gmodeler/preferences.py
- gui/wxpython/gui_core/preferences.py
Currently the Graphical Modeler is using GRASS script API (`grass.script.core.run_command()`) when converting model into Python code. This cannot be changed by the user.
This PR adds support for PyGRASS API (`grass.pygrass.modules.Module`). GRASS script package is still default. This can be changed in the settings.
Compare sample model:
1) GRASS script package (default):
```py
from grass.script import run_command
...
run_command("v.rast.stats",
flags='c',
map="zipcodes_wake",
layer="1",
type="point,line,boundary,centroid,area",
raster="elevation",
column_prefix="rst",
method="average",
percentile=90)
...
```
2) and PyGRASS:
```py
from grass.pygrass.modules import Module
...
Module("v.rast.stats",
flags='c',
map="zipcodes_wake",
layer="1",
type=['point', 'line', 'boundary', 'centroid', …
```
> Graphical Modeler: add support for PyGRASS API

- include/Make/Python.make
`-t` was used in Python 2 to warn if a file was mixing spaces and tabs such as a valid syntax would depend on the number of spaces a tab is worth. It doesn’t exist anymore since Python 3.0
https://docs.python.org/2.7/using/cmdline.html#cmdoption-t
https://docs.python.org/3/using/cmdline.html
https://docs.python.org/3.0/using/cmdline.html
> python: Remove Python 2-only `-t` CLI flag in makefile

- display/d.barscale/draw_scale.c
This pull request addresses a code clarity enhancement in the file `graphics.c` where the `yarr` array is utilized to store y-coordinates for drawing polygons. The modification aims to improve the understanding of the code by adjusting the assignment of values to `yarr[2]` based on the parity of the loop index.
Reasons:
Correction for Checkerboard Pattern: In the context of the surrounding code, this adjustment ensures the correct positioning of the checkerboard pattern by modifying the calculation of the y-coordinate.
Code Clarity: The change is made to address the `duplicateExpression` warning flagged by cppcheck and to enhance the clarity of the code.
Coding Standards: Additionally, the modified code adheres to the existing coding standards.
Testing:
Manual testing has been performed …
> refactor: positioning of mixed_checker addressing duplicateExpression warning

- gui/wxpython/core/toolboxes.py
- gui/wxpython/core/utils.py
- gui/wxpython/tools/build_modules_xml.py
- python/grass/gunittest/utils.py
Fixes #3328
I took the approach of setting in the dict, as tools like Pyright complain (rightfully), that `_` isn't a know builtin. It's true, its something a bit more dynamic. That's about what we use for the normal translations in
https://github.com/OSGeo/grass/blob/5e86482fd9ad7f1bdb874e23740e1ca6b0b9b896/python/grass/__init__.py#L19
https://github.com/OSGeo/grass/blob/5e86482fd9ad7f1bdb874e23740e1ca6b0b9b896/python/grass/__init__.py#L97-L101
> python: Replace usages of Python2-only `import __builtin__` with a Python 3 compatible equivalent

- .github/workflows/python-code-quality.yml
Contributes to #3380
HIGH PRIORITY FIX to not fail every job that will run python code quality and fail.
It pins pytest to 7.4.4, the latest release before 8.
> CI: Downgrade pytest for pylint job to allow time to fix breaking changes in pytest 8

- db/db.connect/db.connect.html
it used to say that SQLite is default in GRASS GIS 7, but it is default in any version since GRASS GIS 7
> db.connect: update GRASS version defaults in docs

- gui/wxpython/gmodeler/frame.py
- gui/wxpython/gmodeler/model.py
This PR adds support for space-time datasets in Graphic Modeler.
1. open Graphical Modeler
2. add any temporal module, eg. `t.rast.series`
Current behaviour: no data item for space-time dataset is shown
This PR:
> Graphical Modeler: add support for space-time datasets

- vector/v.in.ogr/geom.c
The PR #3282 introduced a mostly harmless bug where incorrect warnings `WARNING: Closing unclosed inner polygon ring` are issued. Vector import succeeds anyway. This PR fixes this bug.
> v.in.ogr: fix bug from PR #3282

- raster/r.horizon/main.c
Use absolute value for r.horizon print angles < GRASS_EPSILON.
Apple ARM processor results :
https://github.com/OSGeo/grass/blob/76c1ac531f69c80f88de127fb38819123e9e4784/raster/r.horizon/main.c#L846
with a `printangle == -0.`  to which is added 360 in the next lines:
https://github.com/OSGeo/grass/blob/76c1ac531f69c80f88de127fb38819123e9e4784/raster/r.horizon/main.c#L847-L848
Closes  #3397
> r.horizon: use absolute value for angles < GRASS_EPSILON

- gui/wxpython/gui_core/goutput.py
- gui/wxpython/history/browser.py
This PR relocates the Export History button placed at the bottom of the Console pane to the History pane at the top.
Before:
After:
> wxGUI/history: Move Export History button to history pane

- doc/infrastructure.md
Citable source code with DOI: explain GRASS GIS - Zenodo.org integration (https://doi.org/10.5281/zenodo.5176030).
> docs: add Zenodo.org linkage to infrastructure.md

- scripts/v.dissolve/v.dissolve.py
In GRASS 8.4 `v.clip` fails when `clip` map has no table connected. Steps to reproduce in NC location:
```
v.extract input=boundary_county cat=1 output=aoi
v.db.connect aoi -d
v.clip input=geology clip=aoi output=geology_clip --o
```
`v.clip` currently fails with:
```
ERROR: Database connection for map <aoi> is not defined in DB file
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/scripts/v.dissolve", line 686, in <module>
main()
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/scripts/v.dissolve", line 566, in main
aggregate_columns_exist_or_fatal(input_vector, layer, columns_to_aggregate)
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/scripts/v.dissolve", line 265, in aggregate_columns_exist_or_fatal
column_names = …
```
> v.clip: do not fail when clip map has no table connected

- mswindows/GRASS-Installer.nsi.tmpl
After upgrading to NSIS3 on the build server a new problem appear. Installers produced by NSIS version 3.09 (eg. https://grass.osgeo.org/grass83/binary/mswindows/native/WinGRASS-8.3.1-2-Setup.exe or https://wingrass.fsv.cvut.cz/grass84/WinGRASS-8.4.0dev-76c1ac531f-121-Setup.exe) fail to uncompress MSVCRT archive: 
This PR modifies slightly syntax of `untgz` based on examples found in https://github.com/tpn/nsis-untgz/blob/master/examples/example.nsi.
> NSIS3: fix untgz command

- scripts/v.clip/testsuite/test_v_clip.py
This PR extends `v.clip` module by testing inputs with no table attached. It runs on given combinations:
* input (no table) + clip
* input + clip (no table)
* input (no table) + clip (no table)
See related #3416
> v.clip: add test for no table

- .github/labeler.yml
Untested, I am not sure about syntax, please review. Thanks.
> CI labeling: add support for testsuite label

- doc/development/submitting/general.md
- rpm/grass.spec
The first part of the paragraph talks about backporting to all branches in between main and furthest backport. However, the example pushed the idea of backport to the furthest instead. The new example is now only about backporting to the in-between branch while the paragraph addresses the backport in general and packport to the closest branch first.
The new example uses version numbers with the major version 3 because it is only an example, so it does not need to be updated.
> contributing: Align backporting example with text

- configure
- configure.ac
- db/drivers/mysql/driver.c
- db/drivers/mysql/fetch.c
- db/drivers/mysql/listtab.c
Addresses a few compilation warnings with MySQL driver and in addition improves the configuration output.
(This does **not** add the driver to the CI tests; eg. PostgreSQL driver is also not included, thus that would be another issue.)
> db/driver: fix MySQL driver compilation warnings

- .github/workflows/macos.yml
- .github/workflows/macos_dependencies.txt
- .github/workflows/macos_gunittest.cfg
- .github/workflows/macos_install.sh
Replace the macOS runner with the [new ARM64](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) based one.
Two tests are not passing, so I put them on the exclusion list.
This will cut the CI run time with approximately 50 %!
> CI: use macOS ARM-based runner

- vector/v.to.db/global.h
- vector/v.to.db/parse.c
- vector/v.to.db/report.c
v.to.db currently prints column headers only when verbosity level is above _quiet_. Other tools (e.g. _v.db.select_ have a specific flag to print column headers in output. v.to.db should use the same approach, as verbosity level should control user messages, and not the actual data output.
This PR adds a `h-flag` for printing a header. Current behavior is unaltered otherwise.
> v.to.db: add h-flag to write header

- python/grass/script/core.py
- python/grass/script/tests/grass_script_core_location_test.py
* Reduces use of runtime environment in the create_location function (gisenv call removed).
* Reduces scope of gisrc which simplifies cleanup.
* Adds 4 tests for basic creation of the location (project).
> grass.script: Reduce use of env in create_location

- raster/r.horizon/main.c
- raster/r.horizon/testsuite/test_r_horizon.py
Fixes #2582.
E.g. for start=0, end=12, step=5, three rasters are now generated (0, 5, 10) and not only 2 (because 12/5 = 2...) as was the case before. 
Documentation is still valid, the interval is [start, end) as described there. Not sure if this should be backported, it is a bugfix, but it could break things (e.g. in QGIS, see the link in #2582).
This also speeds up the test significantly, there was no need to run r.horizon with full resolution if we are checking only the created raster names.
> r.horizon: address incorrect number of rasters created

- python/grass/script/core.py
- python/grass/script/setup.py
- python/grass/script/tests/grass_script_core_location_test.py
The function create_location now works without a full session. Internally, it sets up a runtime environment to execute tools (modules) without the connection to a location (project) which is sufficient for executing g.proj.
The new test covers the new functionality, but to actually test it, the test needs to run by itself because grass.script.setup.init (still) creates a global session.
> grass.script: Create new location without a session

- lib/raster3d/header.c
- lib/raster3d/window.c
- lib/raster3d/windowio.c
Split read and write functions, using function pointers do not work as the parameters has deviating qualifiers (const vs non-const).
This is a, perhaps preferable, alternative to #2891.
It does introduce some repetitive code, but do not remove the correctly used const qualifiers in the `Rast3d_key_set_double()` and similar functions.
Note: the "write" part of `Rast3d_readWriteWindow()` in `windowio.c` is never used and therefore removed. A write function is easily implemented if needed.
> lib/raster3d: fix -Wdeprecated-non-prototype compiler warnings

- gui/wxpython/core/gconsole.py
- gui/wxpython/core/giface.py
- gui/wxpython/gui_core/goutput.py
- gui/wxpython/gui_core/prompt.py
- gui/wxpython/history/browser.py
- gui/wxpython/history/tree.py
- gui/wxpython/lmgr/giface.py
- python/grass/grassdb/history.py
This PR implements new functionality to the History Browser panel, particularly showing info about a command from history through the new Command Info dialog.
- The history log (.wxgui_history) is newly stored as a JSON file. It is backward compatible with the plain .wxgui_history. But in the case that a user creates a new mapset, a new history file is automatically created as a JSON file.
- This PR further implements a new option in the context menu called "Show Info." "Show Info" displays a small dialog called **Command info** about the respective process stored in the JSON file.
- JSON file stores the following info for each executed command:
1. Execution time
2. Runtime duration
3. Status (In process / Successfully finished/ Failed)
4. If a 2D mask was set
5. Executor login
6. Region …
> wxGUI/history: Create panel displaying info about command

- gui/wxpython/startup/locdownload.py
The dataset belongs to the book
L. Casagrande, P. Cavallini, A. Frigeri, A. Furieri, I. Marchesini, M. Neteler, 2012: _GIS Open Source. GRASS GIS, Quantum GIS e Spatialite_. ISBN 9788857901497. 224 pages, Dario Flaccovio Editore S.r.l.
The dataset URL is now updated to the new download space:
https://grass.osgeo.org/sampledata/grassdata_piemonte_utm32n_wgs84_grass7.tar.gz
(size: 291MB)
Fixes #3292
> wxGUI: fix URL to Piemonte (Italy) dataset

- python/grass/script/setup.py
Removed use of deprecated 'tempfile.mktemp' and replaced it with 'NamedTemporaryFile'.
Deprecated mktemp function returns an arbitrary file name to use for a temporary file. However, the application does not immediately create/open this file.
This introduces an opportunity for an attacker to interfere with the file to be created. [Documentation on tempfile](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp) recommends replacing mktemp with NamedTemporaryFile. By doing this, there is no window between getting the temporary file name and opening it.
Following up on echoix's comment on PR #3436, This was the only instance of `tempfile.mktemp` I found in this project. There are other uses of a function `tmp_path_factory.mktemp` in various conftest files, but that is different in …
> script: Change insecure mktemp to NamedTemporaryFile

- .github/workflows/additional_checks.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/create_release_draft.yml
- .github/workflows/docker.yml
- .github/workflows/gcc.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pytest.yml
- .github/workflows/ubuntu.yml
Update G83 GitHub actions to avoid deprecated nodes (Node.js 16 -> Node.js 20)
> CI: sync GitHub action versions to main branch

- raster/r.horizon/main.c
- raster/r.horizon/testsuite/test_r_horizon.py
Another bug coming from using global variables in r.horizon. Reported by a user, can be reproduced with https://www.datigeo-piem-download.it/static/regp01/DTM5_ICE/RIPRESA_AEREA_ICE_2009_2011_DTM-SDO_CTR_FOGLI50-172-EPSG32632-TIF.zip:
```
r.horizon elevation=DTM5_172 direction=0 step=1 coordinates=350089,4979561 -d file=horizon.csv
```
The bug is that for part of the angles it results in zeros. It comes up when there are nulls at the edge of the raster, test was added.
This bug is not present in #3346, there it was (accidentally) fixed.
> r.horizon: variable needs to be reset for point mode

- utils/mkrest.py
I found a vulnerability in this mkrest.py utilities file, where malformed input in the src_file variable could give an attacker a shell if they escaped the rest of the command. This fix restructures the Popen call to not use shell=True while still retaining the same functionality.
> utils: fixed shell vulnerability in mkrest.py

- .github/workflows/periodic_update.yml
Following the fix in https://github.com/OSGeo/grass/pull/3454, this makes sure it doesn't get reverted at a next update
> CI: Set executable bit on updated config.guess and config.sub files

- python/grass/script/core.py
See original #3457. When running Python script using GRASS Python API in third party environments (like QGIS) on MS Windows for every command triggered by `script.core.Popen` a new window pops up. This can be very frustrating when running multiple GRASS modules in sequence. See short example below:
[Screencast_02_27_2024_11:43:41_AM.webm](https://github.com/OSGeo/grass/assets/5683186/f3722036-9769-47ad-a60f-885a0b67b967)
And if you can really enjoy terminal windows poping-up. Than here is real example of [SMODERP2D](https://github.com/storm-fsv-cvut/smoderp2d) QGIS Plugin :-)
[Screencast_02_27_2024_11:44:43_AM.webm](https://github.com/OSGeo/grass/assets/5683186/a8cee2a2-4711-425b-b8e7-ac8398e80351)
Run script below in QGIS:
```py
import os
import grass.script.setup as gsetup
from …
```
> script.core.Popen: do not show new window on MS Windows

- scripts/db.dropcolumn/db.dropcolumn.py
- scripts/db.in.ogr/db.in.ogr.py
- scripts/v.db.renamecolumn/v.db.renamecolumn.py
Some scripts did not specify database and driver when calling `grass.db_describe()`, causing errors if vector maps use non-standard db connections. This PR queries actual db connection settings for affected modules and passes these to `grass.db_describe()`
> vector: use full db connection settings for db.describe

- python/grass/script/core.py
This makes the _message_, _verbose_ and other functions consistent with other wrappers around _run_command_ family calls. While not needed for multiple-mapset situations and parallelization, it is necessary when calls with messages are used without global environment being set and only a custom (local) environment is available which is the case in grass.script.setup (with #3438).
The PR aims at providing the interface, not updating all use cases (it will be applied for grass.script.setup in #3438).
This does not have any test since the current API does not allow for writing these test. This will be tested indirectly in the future (e.g. by #3438).
While connected to #3438, it is a separate issue more connected to the previous _env_ parameter additions to _run_command_ wrappers, so a …
> grass.script: Provide env parameter in the g.message API

- docker/alpine/Dockerfile
After alpine docker image was updated to alpine 3.19, it uses PEP 668 and cannot use `pip` as is anymore:
```
pip3 install --upgrade pip setuptools
...
#8 3.927 error: externally-managed-environment
#8 3.927 
#8 3.927 × This environment is externally managed
#8 3.927 ╰─> 
#8 3.927     The system-wide python installation should be maintained using the system
#8 3.927     package manager (apk) only.
#8 3.927     
#8 3.927     If the package in question is not packaged already (and hence installable via
#8 3.927     "apk add py3-somepackage"), please consider installing it inside a virtual
#8 3.927     environment, e.g.:
#8 3.927     
#8 3.927     python3 -m venv /path/to/venv
#8 3.927     . /path/to/venv/bin/activate
#8 3.927     pip install mypackage
#8 3.927     
#8 3.927     To exit the …
```
> Docker alpine: Fix for PEP-668

- python/grass/script/core.py
- python/grass/script/tests/grass_script_core_location_test.py
This adds a separate function for setting location (aka title) stored in MYNAME file. It includes tests of this function.
> grass.script: Add separate function for setting location description

- python/grass/exceptions/Makefile
- python/grass/temporal/Makefile
It seems that the makefile in `python/grass/temporal/Makefile` has had some merge conflicts 10 years ago. 
Looking at the history, after the single change that changed the file structure in 2021, there were two commits about 1 month apart in 2014. 
https://github.com/OSGeo/grass/commits/0c83c976b2312e7cb586265a3927a321a1a27d63/lib/python/temporal/Makefile?browsing_rename_history=true&new_path=python/grass/temporal/Makefile&original_branch=main
One where doxygen documentation was changed to sphinx, removing lines in Makefiles and the `*lib.dox` files, commit https://github.com/OSGeo/grass/commit/74221f332eefd309c0ef97b1b2b7a5eaf43c5bd5.
Then, an `temporal_operator` module was added that replaced `temporal_vector_operator` and `temporal_raster_operator` in commit …
> makefile: Remove doxygen from temporal and python/grass/exceptions that is unused

- raster/r.topidx/r.topidx.html
> r.topidx: Update the manual with info about unsupported lat/long locations

- mswindows/osgeo4w/package.sh
This PR replaces https://github.com/OSGeo/grass/pull/3476 (base branch changed from `releasebranch_8_3` to `main`)
> Remove libexpat-1.dll from package.sh 

- .github/workflows/clang-format-check.yml
- .github/workflows/post-pr-reviews.yml
Replaces #3284
Closes #3284
This PR replaces #3284.
It is an adaptation of https://github.com/OSGeo/grass-addons/pull/1038.
This integrates the ideas of #3284, which is to run clang-format way faster, in the 30-second range. It also sets the infrastructure needed to post code suggestions to the PRs of linter fixes. Clang-format is now the first here to have it. It is designed, and planned, to have some of our other tools add code suggestions as fixes to PRs to facilitate completing them and applying small fixes without a full round of feedback from the author.
Here is what I wrote for https://github.com/OSGeo/grass-addons/pull/1038:
> After a hundred iterations or so, I've got a solution that I'm satisfied with. This allows linter formatting in a PR from a forked pull request to do so …
> CI(clang-format): Run faster and post fixes as code suggestions if possible when running on a PR

- .github/workflows/apt.txt
- .github/workflows/build_ubuntu-22.04.sh
Following https://github.com/OSGeo/grass-addons/pull/1040, I'm suggesting to integrate this flag to the bigger Ubuntu builds.
I want to tend towards continuously testing a "full" and "minimal" configuration, to at least know that the optional components remain actually optional (still works without), but that optional components do actually still build. This is one more flag that is being added towards the "full" configuration.
> CI: add libsvm to full Ubuntu builds

- .github/workflows/label.yml
When this workflow was introduced, I suggested we try using the sync-labels option, that removes labels if files that were previously matching filters aren't matching anymore, like when some changes are reverted. We would have the time to refine our label-matching rules after merging. After a couple months of using this action (since end of December/beginning of January), I didn't see as much of pull requests where files were initially changed and were finally reverted and that it would have changed the labels of the PR. However, I saw multiple times PRs where manually added labels were removed, sometimes multiple times after each commit, which is a bit less intuitive. Each time I saw labels removed, I tried to think if an adjustment to the label matching patterns would do the trick, but …
> CI(labeler): Disable sync-labels that removes labels and pin action

- .github/labeler.yml
PRs and issues relating to notebooks (for now only Python, but others exists) sometimes require a different skill set to review or resolve.
This PR configures matching the `notebook` label https://github.com/OSGeo/grass/labels/notebook in PRs with notebooks, as long as for the supporting code in the python/grass/jupyter folder.
By having the matching apply to PRs, a reviewer can filter by a label matching his skills to open PRs waiting to be merged (still in the hundreds)
I already started using that label in issues when triaging.
> CI(labeler): Match notebook label

- display/d.rast.num/main.c
This PR uses #3482 to allow displaying raster numbers for a smaller **display extent** (not computational region) than the suggested 200x200. Do we still want this limitation when `d.rast.arrow` doesn't have any or should we add the same limit to `d.rast.arrow`?
> d.rast.num: Constrain rendering within the current display extent in the wx monitor

- vector/v.patch/main.c
This PR makes patched categories continuous. Without this PR:
```bash
v.random tmp100 npoints=100 seed=100
v.db.addtable tmp100 col="id varchar(20)"
v.db.update tmp100 col=id qcol="'tmp100_' || cat"
v.random tmp10 npoints=10 seed=10
v.db.addtable tmp10 col="id varchar(20)"
v.db.update tmp10 col=id qcol="'tmp10_' || cat"
v.patch tmp100,tmp10 out=tmp110 -e
v.category tmp110 op=report
Layer/table: 1/tmp110
type       count        min        max
point        110          2        112
line           0          0          0
boundary       0          0          0
centroid       0          0          0
area           0          0          0
face           0          0          0
kernel         0          0          0
all          110          2        112 # 2-101, 103-112
```
With this PR: …
> v.patch: Continuous cats with -e

- raster/r.in.gdal/r.in.gdal.html
The example of the import of bioclim data is outdated. The data at WorldClim is now available as geoTIFs. As this is the case for quite a while now, I suggest removing the current example.
> Update r.in.gdal.html: remove outdated example

- raster/r.univar/r.univar_main.c
- raster/r.univar/testsuite/test_r_univar.py
Init max value with smallest possible value, `DBL_MIN` is still a positive value. 
Closes: https://github.com/OSGeo/grass/issues/3497
> r.univar: init max value with smallest possible value

- raster/r.watershed/ram/Gwater.h
- raster/r.watershed/ram/do_astar.c
- raster/r.watershed/ram/do_cum.c
- raster/r.watershed/ram/do_flatarea.c
- raster/r.watershed/ram/init_vars.c
- raster/r.watershed/ram/main.c
- raster/r.watershed/ram/ramseg.c
- raster/r.watershed/ram/ramseg.h
- raster/r.watershed/seg/do_cum.c
This PR fixes an unintended integer overflow by the `int size_array(..., int, int)` function. The new return type of this function is `size_t`, and takes `size_t` nrows and ncols. Before this PR, `r.watershed` was not able to allocate `4 * 43994 * 
49529` (about 8.1 GB) because of this integer overflow.
Failed line:
https://github.com/OSGeo/grass/blob/35123df1a67ba99306bff26ae296fdfa2ca69b92/raster/r.watershed/ram/init_vars.c#L149
Error:
```
SECTION 1a (of 4): Initiating Memory.
Current region rows: 43994, cols: 49529
ERROR: G_malloc: unable to allocate 18446744065248018020 bytes of memory at
raster/r.watershed/ram/init_vars.c:149
WARNING: Subprocess failed with exit code 1
```
Test code:
```c
#include <stdio.h>
int main(){
int nrows = 43994;
int ncols = 49529;
/* expected size */
size_t …
```
> r.watershed: Handle large datasets greater than INT32_MAX in cells

- .github/workflows/test_thorough.bat
Currently, the number of test files on windows is 295, and 238 files pass. That is a little over 80% (80.677966%), and the results at the end of the test runs mention 81% passes.
This PR raises the minimum percent of passing files to the current state, so that we can become more aware of changes in the test suite. It still allows for 2 files to fail before it becomes under 80%: 236/295=0.8, but 235/295=0.796610.
There’s no magic with this PR, since number of test files isn’t a very good measure to determine if a regression has occurred inside an already failing file, but it’s still better than nothing.
> CI(windows): Increase required passing tests percentage to 80%

- .github/workflows/coverity.yml
This PR adds automatic Coverity functionality to the GRASS GIS repository. This action will (should) tell the Synopsys Coverity action to run the scan, with the results being posted on the Coverity Website. The following things will be needed in secrets for the action to work:
* COVERITY_URL: the URL for Coverity
* COVERITY_USER: the Coverity username
* COVERITY_PASSPHRASE: the Coverity passphrase
This action is based off of https://sig-product-docs.synopsys.com/bundle/bridge/page/documentation/c_github-coverity.html and will be worked on with @wenzeslaus
> Add Automated Coverity Scanning

- lib/gis/renamed_options
- vector/v.db.connect/main.c
This PR fixes #3149 by using the standard `--overwrite` flag.
> v.db.connect: Replace -o flag with the standard --overwrite

- gui/wxpython/Makefile
The only file in the wxpython/scripts folder was v.krige.py, and was moved to modules between 7.0.0beta2 and 7.0.0beta3
The changes happened 10 years ago in this commit: https://github.com/OSGeo/grass/commit/8aa2194a424e5cbb82a5c53671a7bdf14bb6d47d
> wxpython: Remove non-existing scripts folder from Makefile

- .github/workflows/create_release_draft.yml
Generates Git derived data files, which are added to release tarballs of both `*.tar.gz` and `tar.xz` formats. Accompanied by `md5` and `sha256` checksum files.
Solves #3430, depends on  #3435.
~~Initially put up as draft, if this agreed upon the [howto_release.md](https://github.com/OSGeo/grass/blob/main/doc/howto_release.md) need to be updated.~~
> CI: update publishing workflow

- raster/r.univar/r.univar_main.c
- raster/r.univar/testsuite/test_r_univar.py
Manual backport of  https://github.com/OSGeo/grass/commit/68ca15d0696a9583f730f8b13ae9d6812a2fde71 from #3512.
> r.univar: init max value with smallest possible value (G8.3)

- .flake8
- python/grass/pygrass/tests/benchmark.py
F401 errors are most often caused by ```__init__.py```, except one. The line ```--per-file-ignores=__init__.py:F401``` has been added to the .flake8 file to ignore ```__init__.py```.
> Fix flake8 F401 imported but unused

- gui/wxpython/location_wizard/wizard.py
Replaces user visible strings in wizard.
> wxGUI: rename location to project for new project wizard

- renovate.json
See docs here: https://docs.renovatebot.com/presets-config/#configbest-practices
Among others, it will pin GitHub Actions to digests (ie: will convert the `@v2` of https://github.com/OSGeo/grass/pull/3532 to the digest we use elsewhere). Same for docker images.
> CI: Use Renovate best-practices preset

- .github/actions/create-upload-suggestions/action.yml
- .github/workflows/clang-format-check.yml
Based on https://github.com/OSGeo/grass-addons/pull/1045
This PR extracts the logic of uploading suggestions into a composite action that can be used multiple times.
Afterwards, the grass-addons repo could use the action defined from here instead of locally, and would stay updated.
Next PR will use this to add posting suggestions from black, without duplicating any code.
> CI(suggestions): Extract uploading of code suggestions with a local composite action

- .github/workflows/post-pr-reviews.yml
- .github/workflows/python-code-quality.yml
Since #3527 is merged, I rebased my implementation of posting code suggestions for Black formatting.
I have implemented a pattern to handle multiple tools in the workflow_run triggered workflow (the one called when a workflow is completed, and that runs with write permissions, and from the context of the default branch->main). 
I wrote the workflow with a whitelisting approach in mind, to only allow continuing on the expected file names, in case the workflow is triggered on a file that wasn’t supposed to.
That’s why it’s not a simple loop, that would execute shell scripts on untrusted inputs/interpolation.
> CI(black): Post black code suggestions as PR review comments

- .github/actions/create-upload-suggestions/action.yml
- .github/workflows/coverity.yml
- .github/workflows/ubuntu.yml
- scripts/v.dissolve/v.dissolve.html
While updating black's version in https://github.com/OSGeo/grass/pull/3545, which changed some pre-commit, I observed that some files didn't respect pre-commit's settings, and were changed when running:
```shell
pre-commit run --all-files
``` 
This PR applies those fixes (extracted from commits made after #3545, but are independent).
> pre-commit: Apply trailing whitespace fixes for all repo

- pyproject.toml
@wenzeslaus has indicated that all use of random generators are not for cryptographic purposes in issue #3553 . Knowing this, these alerts are false positives and can be safely ignored. 
This PR adds in a skip to the bandit configuration in pyproject.toml for rule B311. This rule searches for instances of randomizers used for potential cryptography.
> Update Bandit to ignore secure random warning (Rule B311)

- python/grass/script/core.py
- python/grass/script/tests/grass_script_core_location_test.py
As we begin renaming location to project, it would be nice to have a `create_project()` function that works the same as `create_location`.
This is particularly nice in notebooks because these function work without an active GRASS session so users can use a work flow that I think is very intuitive:
1. `import grass.script` and `grass.jupyter`
2. `create_project()` to make a new project 
3. `gj.init()` to start the session in the new project
This PR also includes additional path support. For example, all the following lines will create a new project:
```
gs.create_project("nags_head", epsg="32119") 
gs.create_project("~/grassdata", name="nags_head", epsg="32119") 
gs.create_project("~/grassdata/nags_head", epsg="32119") # full path to new project
```
> grass.script: add create_project() with same functionality as create_location()

- .github/workflows/coverity.yml
The Coverity Scan GitHub action is failing due to [not being able to find the supported Coverity version](https://github.com/OSGeo/grass/actions/runs/8533866655/job/23377252411#step:3:71). This fix attempts to fix the error by adding in the version of Coverity specified in the Coverity defects dashboard.
> CI: specify coverity version in coverity.yml

- raster/r.univar/r.univar.html
Given #3561 I think it is good to add the note that parallelization does not work (or is disabled) when the mask is set to the modules that allow parallelization.
> r.univar: add note that parallelization is disabled if mask is set

- python/grass/jupyter/setup.py
When running `gj.init(/path/to/project)` in already active session, the paths got all mixed up. Problem was that `mapset_exists` was getting `mapset="/tmp/someting/project_name"` and because of a somewhat unexpected (but documented) behavior of `os.path.join` when merging absolute paths, this end up as an existing directory, while the expectation was it would fail. So this change adds the check that mapset is a name, not a path.
> grass.jupyter: fix reinitializing session

- lib/gis/error.c
- lib/gis/mapset_msc.c
- raster/r.gwflow/main.c
This PR fixes three vulnerabilities/weaknesses found with older scans of Coverity. 
Issue 1208372 in error.c concerns an unbounded read of an environment variable into memory. An attacker could overwrite the environment variable that is accessed by G__home() and exploit it to overflow the buf array.
Issue 1501330 in mapset_msc.c concerns writing into an array that is not null terminated. If the path variable was not null terminated, the write could fill the whole array with data without a null terminator, causing trouble down the line.
Issue 1207344 in raster/r.gwflow/main.c concerns a constant variable guarding dead code. This is not exactly a security vulnerability, but is a code quality issue I was able to easily fix.
> lib raster: fixed security vulnerabilities and weaknesses

- configure
- configure.ac
- include/grass/config.h.in
- raster/r.in.pdal/grassrasterwriter.h
Starting from PDAL 2.7.0 filename is mandatory for Writer class, but there is a NoFileWriter class that maintains old behaviour. https://github.com/PDAL/PDAL/pull/4342
> r.in.pdal: use NoFileWriter class for PDAL > 2.7.0 (fixes #3552)

- raster/r.horizon/main.c
- raster/r.horizon/r.horizon.html
- raster/r.horizon/testsuite/test_r_horizon.py
Distance to the horizon is computed within the algorithm, this only exposes the values with `-l` flag:
```
r.horizon --overwrite elevation=circ step=60 coordinates=637505,221755  -l
```
```
azimuth,horizon_height,horizon_distance
0.000000,0.197017,5010.039920
60.000000,0.196689,5017.220346
120.000000,0.196969,5014.957627
180.000000,0.197017,5010.039920
240.000000,0.196689,5017.220346
300.000000,0.196969,5014.957627
```
or
```
[
{
"x": 637505.000000,
"y": 221755.000000,
"azimuth": [
0.000000,
60.000000,
120.000000,
180.000000,
240.000000,
300.000000
],
"horizon_height": [
0.197017,
0.196689,
0.196969,
0.197017,
0.196689,
0.196969
],
"horizon_distance": [
5010.039920,
5017.220346,
5014.957627,
5010.039920,
5017.220346,
5014.957627
]
}
]
```
> r.horizon: add distance into output

- .github/workflows/coverity.yml
This PR attempts to fix the problems with the previously submitted Coverity Scanning action. Basic building functionality is borrowed from [our ubuntu.yml](https://github.com/OSGeo/grass/blob/2aa98a166d8f50aa1491908401205962fa1d70fb/.github/workflows/ubuntu.yml), and Coverity functionality is borrowed from [PROJ's coverity-scan.yml](https://github.com/OSGeo/PROJ/blob/905c9a6c2da3dc6b7aa2c89d3ab78d9d1a9cd070/.github/workflows/coverity-scan.yml).  
The needed secrets are:
* COVERITY_PASSPHRASE: the token used to submit builds.
> CI: Overhaul Coverity Scan

- raster/r.mfilter/main.c
- raster/r.neighbors/main.c
- raster/r.resamp.filter/main.c
- raster/r.resamp.interp/main.c
- raster/r.series/main.c
- raster/r.sim/r.sim.sediment/main.c
- raster/r.sim/r.sim.water/main.c
- raster/r.slope.aspect/main.c
- raster/r.sun/main.c
- raster/r.univar/r.univar_main.c
- vector/v.surf.rst/main.c
Similarly to #2829, this PR disables parallelization when MASK is active for parallelized tools. Fixes #3560.
> raster: disable parallelization when MASK active

- gui/wxpython/xml/toolboxes.xml
- raster/r.proj/main.c
- vector/v.proj/main.c
This PR continues the renaming effort for these 2 tools. #3130 already renamed the standard option and #3570 did the renaming in html doc.
> v.proj/r.proj: continue renaming location to project

- .github/workflows/coverity.yml
Configure and build for Coverity Scan with debug flag set. Also run `cov-build` directly with `make` as argument.
In addition some style fixes to pass pre-commit.
Attempt to fix (still broken?) Coverity Scan.
> CI: configure Coverity Scan with debug flag

- utils/mkhtml.py
This PR suggests to add a check for an empty addon_path.
The default value is set to `addon_path = None` in [L889](https://github.com/osgeo/grass/blob/main/utils/mkhtml.py#L889) and there are circumstances where it is not overwritten. As far as I see it, this would prevent the code from requesting a wrong path in the [following method](https://github.com/osgeo/grass/blob/main/utils/mkhtml.py#L297) returning the latest commit of the whole addon repository instead of the latest commit for the addon.
Manual page generation here is really new to me so I am not sure about all the different variations in which this script might be called and if I oversee something. Background is that I am using the script to generate manual pages for addons not in the official addon repository and this PR would …
> mkhtml: check for addon_path

- gui/wxpython/animation/controller.py
- gui/wxpython/nviz/animation.py
- gui/wxpython/nviz/mapwindow.py
Fixes #3580.
`wx.Timer` class `Start()` method `milliseconds` param arg should by integer type, [doc](https://docs.wxpython.org/wx.Timer.html#wx.Timer.Start).
> wxGUI: fix animation/nviz animation tool play/record animation

- gui/wxpython/location_wizard/wizard.py
- python/grass/script/core.py
> libpython: fix create new project (location)

- .github/workflows/osgeo4w.yml
Saves at least 10 minutes on compilation, for every run. 
This is the low hanging fruit I was able to quickly fix.
Windows runners (and Linux runners) all use 4 cores for public repos since January when they completed the upgrade of the runners.
I was tracing the builds with an ETW trace (xperf), and analyzing with Windows Performance Analyzer (really cool, even down to the context switches per process and priority if needed). I see that with that, most of the time if compilation uses all of the 4 CPU cores. Using 3 jobs makes the build step last 11min18sec for the run I made. Using 4 jobs is about at 10min-10min30sec. Using 1 job like currently is more than 20 minutes.
It is still 2 times slower than I expected, and I didn’t find an obvious reason for now. I expected to see an IO issue, …
> CI(windows): Set number of cores for compilation

- scripts/r.semantic.label/r.semantic.label.py
- scripts/r.semantic.label/testsuite/test_r_semantic_label.py
> r.semantic.label: fix print raster map semantic label

- mswindows/GRASS-Packager.bat.tmpl
- mswindows/crosscompile.sh
- mswindows/env.bat
- mswindows/osgeo4w/build_osgeo4w.sh
Update Windows builds to use Python 3.12 with [updated OSGeo4W](https://lists.osgeo.org/pipermail/grass-dev/2024-April/096269.html).
Closes: #3596.
> windows: use Python 3.12 with updated OSGeo4W

- general/g.mapsets/list.c
- general/g.mapsets/local_proto.h
Add missing declaration/definition of argument type. 
Log extract:
```
/usr/bin/clang -I/opt/local/include -isystem/opt/local/include -isystem/opt/local/include/libomp -std=c11 -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch arm64 -O0 --debug -Wall -Wextra -Wpedantic -Wno-error=deprecated-non-prototype -D_FORTIFY_SOURCE=3 -Wvla -Wno-error=strict-prototypes -DGL_SILENCE_DEPRECATION   -I/dev/grass/dist.aarch64-apple-darwin23.4.0/include -I/dev/grass/dist.aarch64-apple-darwin23.4.0/include    -DPACKAGE=\""grassmods"\"   -I/dev/grass/dist.aarch64-apple-darwin23.4.0/include -I/dev/grass/dist.aarch64-apple-darwin23.4.0/include -DRELDIR=\"general/g.mapsets\" -o OBJ.aarch64-apple-darwin23.4.0/get_maps.o -c get_maps.c
In file included from get_maps.c:5: …
```
> g.mapsets: add missing declared or defined argument type

- include/grass/defs/vector.h
- lib/vector/Vlib/field.c
Add a missing destructor function to the struct `field_info`.  This enables to free memory, which now is being leaked.
> libvector: add destructor function to the struct field_info

- .github/workflows/coverity.yml
Changed upload process to match the process for Scans for which the scan results (ie the `cov-int` directory) is over 500MB in size.
Also added a step for saving the Scan output as an artifact.
Attempt to fix Coverity Scan.
> CI: configure Coverity Scan for larger scans and artifact

- gui/wxpython/wxplot/profile.py
> wxGUI/wxplot: fix profile plot segmentation points position

- vector/v.in.ogr/main.c
Fixes #3604. Allow create DB table column name with reserved keyword.
> v.in.ogr: fix escape table column name during creating table

- python/grass/temporal/stds_import.py
- temporal/t.rast.import/test.t.rast.import.relative.with.semantic.label.sh
> libpython/temporal: fix t.rast.import module import input tarball file

- db/drivers/mysql/db.c
Which allow to use SQL standard double quotes instead of backticks for escaping column name.
Successfully tested with MySQL DB backend.
[Example](https://github.com/OSGeo/grass/issues/3604#issuecomment-2058805737) for testing purpose.
> db/drivers/mysql: set SQL ANSI_QUOTES MODE

- raster/r.horizon/main.c
This should address this (I think)
```
*** CID 1543994:  Null pointer dereferences  (REVERSE_INULL)
/raster/r.horizon/main.c: 1274 in calculate_raster_mode()
1268             Rast_append_format_history(
1269                 &history,
1270                 "Horizon view from azimuth angle %.2f degrees CCW from East",
1271                 angle * rad2deg);
1272     
1273             Rast_write_history(shad_filename, &history);
>>>     CID 1543994:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "shad_filename" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
1274             if (shad_filename)
1275                 G_free(shad_filename);
1276         }
```
> r.horizon: address coverity scan 'Null pointer dereferences'

- .github/workflows/coverity.yml
Revert Coverity Scan workflow to the simple (one-step) submitting method, with some minor moderations. The multi-step version was not needed nor was the solution to fix the problem we have getting this to work.
I manually submitted the runner build artifact online and it started the analysis. I later tried a second time to submit the same build file now via command line (using the same curl command as in this PR), again successful. So this _should_ work.
I did notice a message online after the first online submission, that the analysis was put in queue with three jobs ahead. I don't know if those jobs were ours, or for the system in total. Anyways, with the two submissions, the daily quota was reached, only in ~16 hrs from now will the next one be permitted. As long as we're working this …
> CI: revert coverity to simple submitting method, temporary disable cron

- .github/workflows/coverity.yml
Now with Coverity Scan runner is working, we can reactivate the cron and remove the artifact upload part.
> CI: reactivate Coverity workflow cron, remove artifact upload

- .github/workflows/coverity.yml
This changes the runner log of Coverity, instead of printing URL encoded version string it now prints a human readable string.
before:
`Submitting Version%3A8.4.0dev%2C%20commit%3bb27c05%2C%20branch%3Amain.`
now:
`Submitting Version:8.4.0dev, commit:bb27c05, branch:main.`
> CI: improve Coverity build log

- gui/wxpython/core/toolboxes.py
This PR does not raise an error when it cannot load metadata from uncompiled modules. Not all modules are always compiled (e.g., `r.in.lidar` is optional `WITH_LIBLAS`)
> GUI: Don't try to load metadata from uncompiled modules and raise an error for menu data

- scripts/v.db.dropcolumn/v.db.dropcolumn.py
Enable to use column name which is reserved DB backend keyword.
> v.db.dropcolumn: fix enclosing column name with SQL standard double quotes

- scripts/v.db.renamecolumn/v.db.renamecolumn.py
Enable to use column name which is reserved DB backend keyword.
> v.db.renamecolumn: fix enclosing column name with SQL standard double quotes

- python/grass/script/testsuite/test_names.py
- scripts/v.db.addcolumn/v.db.addcolumn.py
Enable to use column name which is reserved DB backend keyword.
> v.db.addcolumn: fix enclosing column name with SQL standard double quotes

- db/drivers/odbc/db.c
Which allow to use SQL standard double quotes instead of backticks for escaping column name.
Successfully tested with  ODBC MySQL DB backend connection and with this [data example](https://github.com/OSGeo/grass/issues/3604#issuecomment-2058805737).
> db/drivers/odbc: set ODBC MySQL DB backend SQL ANSI_QUOTES MODE

- db/drivers/odbc/db.c
> db/drivers/odbc: catch and handle return value from setting MySQL SQL ANSI mode

- lib/pngdriver/pngdriver.h
This PR addresses https://github.com/OSGeo/grass/pull/3621#issuecomment-2070202300.
> Define (read|write)_png only #ifdef HAVE_PNG_H

- lib/gmath/fft.c
This PR addresses https://github.com/OSGeo/grass/pull/3621#issuecomment-2069764116 by including only one header for FFTW when there are multiple versions.
> gmath: Include only one header for FFTW

- lib/gis/aprintf.c
This PR simply renames `ap_copy` to `aq`. I just like this name better from the `va_copy` man page ;-).
> libgis: Rename ap_copy to aq for G_aprintf

- binaryInstall.src
- general/g.mkfontcap/main.c
- lib/driver/font2.c
- lib/gis/renamed_options
- mswindows/GRASS-Installer.nsi.tmpl
- mswindows/osgeo4w/postinstall.bat
This PR replaces `-o` with standard `--overwrite` and adds a warning.
> g.mkfontcap: Replace -o with --overwrite; Add a renamed flag warning

- CODE_OF_CONDUCT.md
- README.md
This adds code of conduct ([Contributor Covenant](https://www.contributor-covenant.org/)) v2.1 (latest) and adds a badge to README.md. Reporting is to be done to `grass-coc@osgeo.org` (thanks @neteler).
> contributing: add code of conduct

- python/grass/script/tests/grass_script_core_location_test.py
While not harmful for what is tested, the code was copy-pasted from an unrelated test and is not needed in the given tests because init takes care of initialization in the desired location.
> grass.script: Remove copy-pasted code from tests

- .github/actions/create-upload-suggestions/action.yml
- .github/labeler.yml
- doc/development/submitting/general.md
Fixes some `pre-commit` yamllint and markdownlint errors, which have sneaked in again.
> checks: fix some yamllint and markdownlint errors

- gui/wxpython/gmodeler/panels.py
- python/grass/pygrass/modules/interface/testsuite/test_modules.py
this is a follow to last year huge PR
greetings
> python: remove more six crumbs

- .github/workflows/pytest.yml
To help read CI logs more easily, enabled colored output where possible (in CI only, for pytest workflow).
For pytest itself:
- added verbose output so we can see what test is running
- added colors so error results are WAY easier to read through (it even has syntax highlighting for python code)
- added a short summary of passed/skipped/failed/xfailed tests
- added the display of top durations for the test or the setup (I finally chose to not limit the number of items to output, but to raise the minimum duration for that list to ignore all durations under 0.5 sec instead of the default of 0.005s. 0.5s seems reasonable for what a slow unit test should be in my opinion. We have setup and test steps that take over 9 seconds as we can see from that)
<details><summary>Images</summary>
<p> …
> pytest: Enhance logging output with colors and summary

- SECURITY.md
Fix some security.md linting errors, errors with pre-commit.
> docs: fix security.md linting errors

- .markdownlint.yml
- .pre-commit-config.yaml
- .yamllint
Avoid discrepancy between super-linter and pre-commit settings.
I couldn't find a way to avoid this problem without adding yet another two files in an already cluttered top-level repo, but current situation is not sustainable, so...
> checks: add configuration files for yamllint and markdownlint

- doc/notebooks/jupyter_example.ipynb
- doc/notebooks/jupyter_tutorial.ipynb
- general/g.version/g.version.html
- lib/init/grass.html
- singularity/debian/README_debian.md
8.2 used in examples (no change needed?):
Fix based on updates to 8.3 branch (same text or same style):
> version: Replace references to 8.2

- .github/workflows/codeql-analysis.yml
- .github/workflows/pytest.yml
- .github/workflows/python-code-quality.yml
I’ve known about the mold linker for years now. It is a drop in replacement for Unix linkers, but several times faster. The design goal was to be able to link chromium in the one second range, with speeds approaching `cp`. 
https://github.com/rui314/mold has a graph and table of the performance. Phoronix has multiple articles on the subject, that’s where I first learned about it.
The author is the same that created LLVM’s lld linker at the time, and that is still several times faster than what existed before.
I’ve initially wanted to speed up the
CodeQL c-cpp build, as since this build is profiled, it is already slower than normal builds. It still saves about 30 seconds.
I have chosen to not use the mold linker everywhere, to keep the usual linker in the Ubuntu build where most tests are …
> CI: Use faster mold linker to reduce build time by ≈>30 sec

- gui/wxpython/core/treemodel.py
- gui/wxpython/datacatalog/tree.py
- gui/wxpython/history/tree.py
- python/grass/grassdb/history.py
This PR adds a new node level to the history browser tree which is the part of the new History tab dealing with command history management.
It adds five nodes which are then populated by commands:
Today, Yesterday, This week, Older than week and Missing info.
The hierarchy is as follows:
Missing info is a special node used for situations when history log is in the plain text format (in this case we do not have any info when the command was run).
> wxGUI/history: Add time period branching to history browser tree

- lib/vector/diglib/plus_area.c
- lib/vector/diglib/plus_struct.c
- lib/vector/diglib/spindex.c
Fix some memory leaks in `lib/vector/diglib` exposed by static analysis.
> libvector/diglib: fix memory leaks

- python/grass/script/core.py
The original change in PR #3439 has None instead of env passed to the error function in the fatal function. This passes the env parameter.
> grass.script: Fix missing passing of env parameter

- gui/wxpython/dbmgr/base.py
- gui/wxpython/dbmgr/sqlbuilder.py
Enable to use (show/add/delete/rename/query) column name which is reserved DB backend keyword.
Requires these PR #3631, #3632, #3633  to be applied for proper functionality.
> wxGUI/dbmgr: fix enclosing column name with SQL standard double quotes

- general/g.message/main.c
- general/g.proj/main.c
The g.message does not need any of the session setup and it can be used during a setup process to report standardized messages to the user. This removes the need to have a full session before running g.message. GISRC is still needed, but the data (file) structures for mapset don't need to exist.
The code is combination of what is in g.proj (the 'no init' call and comment) and g.dirseps (memory mode for GISRC). It is also syncing the corresponding lines in g.proj.
> g.message: Do not require full gisinit

- python/grass/script/core.py
For reporting errors the g.message tool is called, so the environment setup is always needed (except when doing XY without errors).
> grass.script: Always use full env in create_project

- python/grass/script/core.py
- python/grass/script/testsuite/test_start_command_functions_nc.py
Given several tools have options `format`, this adds automatic parsing to `parse_command`:
```
>>> data = gs.parse_command("r.what", map='elevation@PERMANENT', coordinates=[641567, 223962], format='json')
[{'easting': 641567, 'northing': 223962, 'site_name': '', 'elevation@PERMANENT': {'value': 75.82444763183594}}]
>>> data = gs.parse_command("v.db.select", map='busroute1@PERMANENT', format='csv')
[{'cat': '1', 'ROUTE': '1'}, {'cat': '2', 'ROUTE': '1'}]
>>> pd.DataFrame(data)
cat ROUTE
0   1     1
1   2     1
```
For csv, I use DictReader, which makes sense only when the csv has a header, but that seems like reasonable assumption, and then it works nicely with pandas.
Option delimiter does not fit well into it conceptually, so I deprecated it. Also, it's now taken into account only when …
> grass.script: Automatically parse JSON and CSV in parse_command

- python/grass/script/setup.py
This makes the grass_path parameter a keyword-only argument (PEP 3102). While this technically breaks the 8.0 API for 8.4, the documentation only shows grass_path as a keyword argument, grass_path is required to be a keyword argument when location and mapset are omitted, and given the automation triggered by grass_path=None, any usage of grass_path is likely limited (the usage would have to be as positional argument to trigger the incompatibility).
Originally posted as [a comment in #3438](https://github.com/OSGeo/grass/pull/3438#discussion_r1591003832):
Worked in 8.0-8.3:
```python
gs.setup.init("~/data/nc_spm/new_highway")
gs.setup.init("~/data/nc_spm/new_highway", grass_path="/opt/grass/bin/grass")
gs.setup.init("~/data", "nc_spm", "new_highway")
gs.setup.init("~/data", "nc_spm", …
```
> grass.script: Make grass_path keyword only in init

- gui/wxpython/history/browser.py
- python/grass/grassdb/history.py
This PR enhances the history command info panel by adding the option for setting the current computational region settings to the one active upon the history command execution.
The original command info has only information about the computational region settings:
The new proposal adds information on whether the current region is equal to the region from the history or not. In the case that the two settings are not equal, the new button "Set as current region" is added:
If settings are equal the panel shows just the info message:
> wxGUI/history: New button for setting current computational region based on executed commands

- python/grass/script/task.py
- python/grass/script/tests/test_script_task.py
`grassTask.get_param()` does not perform full match on string data type, see https://github.com/OSGeo/grass/blob/main/python/grass/script/task.py#L151
This may lead to buggy behaviour as explained below.
Sample code:
```py
from grass.script.task import grassTask
print(grassTask("r.mapcalc.simple").get_param('e')['name'])
```
returns `expression` instead of `e`.
> grassTask.get_param(): full match also for strings

- .github/workflows/osgeo4w.yml
CI builds for the mingw64 env, so actually use it. Otherwise various env vars are missing and PATH is wrong.
Use the shell provided by setup-msys2 instead of calling bash directly, no need to hardcode paths then.
> CI: set the right environment for setup-msys2 and use the provided shell

- utils/mkhtml.py
Current Git (2.45.1) produces strict ISO dates with Z for any time with +00:00 time zone offest. Python prior to 3.11 does not understand these dates. This trunkes the Z in case of ValueError which is what old Python throws. The +00:00 offset is placed in the input string for fromisoformat instead.
> build: Help older Python parse new Git dates

- .github/workflows/python-code-quality.yml
- REQUIREMENTS.md
Python 3.7 is end-of-life. Version 3.8 is in security (fixes) status till 2024-10. Changing version in code quality check (for Pylint) and in requirements file.
Minimum version of Python is now specified as 3.8.
> deps: Set min Python version to 3.8

- .github/workflows/print_versions.sh
* Print first version of Python.
* Print also Git version which we use during build (when available and it is available in the CI).
* Print GRASS versions last because they actually need the build to be successful and this purposefully runs even for failures.
> CI: Print Python version first

- .github/workflows/osgeo4w.yml
This uploads the test report for gunittest tests. It is almost exactly the same step as the Ubuntu workflow, but changes were made for the name of the artifact since no config matrix strategy exists here.
I didn’t find another PR or issue for this. It is different from #1212, that tried to have the compiled grass uploaded as a osgeo4w-compatible package.
> CI(windows): Upload test report artifact

- display/d.mon/render_cmd.py
This PR is another attempt to address https://github.com/OSGeo/grass/issues/3481. It should replace
* #3482
* #3491
* #3492
How it works:
1. `d.mon start=wx0`
2. Run a display module from the terminal
3. `D_open_setup()` from the module spawns the monitor's `render.py` and exits
4. `render.py` touches a temp map file for the wx monitor so the monitor can force rendering non-existing layers; without this empty file, the monitor won't render them (`Layer.IsRendered()` and `RenderMapMgr._checkRenderedSizes()` in `gui/wxpython/core/render.py`)
5. `render.py` doesn't `render()` for the wx monitor because the monitor is watching the `cmd` file and will render any new layers; existing layers won't be re-rendered (`exists` in `GetLayersFromCmdFile()` in `gui/wxpython/mapdisp/main.py`
6. …
> d.mon: Delegate rendering to wx monitors

- lib/temporal/SQL/update_stds_spatial_temporal_extent_template_old.sql
- lib/temporal/SQL/update_str3ds_metadata_template_old.sql
- lib/temporal/SQL/update_strds_metadata_template_old.sql
- lib/temporal/SQL/update_strds_metadata_template_v3.sql
- lib/temporal/SQL/update_stvds_metadata_template_old.sql
- python/grass/temporal/abstract_space_time_dataset.py
This is an attempt to address:
#3466
Not sure how to test with Ubuntu 20.04. It is not part of CI, and I do not have Ubuntu 20.04 at hand right now...
I would appreciate if anyone with Ubuntu 20.04 could run temporal tests with this PR applied...
> temporal: handle SQLite < 3.33

- locale/po/grasswxpy_de.po
Deduplication using
```
MYLANG=de
cd locale/po/
mv grasswxpy_${MYLANG}.po grasswxpy_${MYLANG}.po.BAD
msguniq --use-first grasswxpy_${MYLANG}.po.BAD > grasswxpy_${MYLANG}.po
rm -f grasswxpy_${MYLANG}.po.BAD
```
Fixes #3731
> i18n: deduplicate grasswxpy_de.po

- general/g.mapsets/main.c
- imagery/i.signatures/main.c
- include/grass/gis.h
- lib/gis/parser_standard_options.c
- raster/r.horizon/main.c
- raster/r.kappa/main.c
- raster/r.what/main.c
- vector/v.db.select/main.c
As a part of https://github.com/OSGeo/grass/discussions/3019, JSON format support will be added to multiple modules. By default, modules output in existing plain format. If the format=json option is provided, modules will output in JSON format instead. To avoid duplication of code across several modules, define a standard parser option.
> lib: Add a standard parser option for JSON formatting

- .github/workflows/macos.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/print_versions.sh
This was an exploratory branch I made in my fork to confirm another potential bug in the OSGeo4W packages, ie the nightlies, filed as https://github.com/OSGeo/grass/issues/3739. When filing in my recent bugs reports on Windows, I observed that the libgis_date, libgis_revision, revision, build_date fields don't seem updated, and mention 2024-04-14 or in the 2024-04-13 day (when there were big changes in the build environment). Assuming that this April 14, 2024, is after the changes in configure to use the git dates (https://github.com/OSGeo/grass/pull/3435, March 24, 2024), I expect that these would be up to date.
This PR adds all the flags of g.version to the call in the print_versions.sh file, and makes sure it runs on builds of our three platforms. It shows that the build information …
> CI: Print more version information, for all platforms

- gui/wxpython/history/tree.py
Fixes https://github.com/OSGeo/grass/issues/3726 by removing -d (it's linux only).
> wxGUI/history: Fix date formatting

- locale/Makefile
Add gettext message deduplication to `make update-po` step.
Fixes #3465
> i18n: add deduplication to make update-po

- raster/r.proj/main.c
Addresses #3655
I'm not sure this PR should be accepted. It doesn't look like a lot of other people have run into this issue. It is already documented under the 'Notes' section and this may all be a failure of mine to read the documentation sufficiently. Still, if people think it would be helpful to call out the need to use `-n` under certain situations, this may help.
> r.proj: clarify -n flag use case

- python/grass/jupyter/utils.py
Somehow, this one got forgotten during location to project renaming.
> grass.jupyter: update r.proj call to use project instead of location

- scripts/v.db.join/testsuite/test_v_db_join.py
- scripts/v.db.join/v.db.join.py
Currently, ` v.db.join` fails if all columns to join already exist in the target table, because `v.db.addcolumn` is called with an empty list of columns to create.
This PR addresses the issue, removes Python2 related code along with some refactoring. It also adds a test-suite.
> v.db.join: handle existing columns properly

- general/g.setproj/get_stp.c
This pull request fixes uninitialized variable issues in `general/g.setproj/get_stp.c`.
1. Initialized `reccnt`:
- Issue : The variable `reccnt` was used without being initialized.
- Fix : Initialized `reccnt` to `0` at its declaration.
```change
int record, icode, reccnt = 0, special_case;
```
2. Initialized `STabbr_prev`:
- Issue : The variable `STabbr_prev` was used without being initialized.
- Fix : Initialized `STabbr_prev` to an empty string at its declaration.
```change
char STabbr[50], STabbr_prev[50] = "", COname[50], answer[50], buff[256];
```
> Fixed uninitialized variable issues in get_stp.c

- vector/v.surf.rst/v.surf.rst.html
Update broken example (`r.random` usage and more meaningful threshold).
> manual: correct v.surf.rst example

- raster/r.horizon/main.c
- raster/r.horizon/testsuite/test_r_horizon.py
Given the [discussion](https://github.com/OSGeo/grass/pull/3744#issuecomment-2135488969) about what should be part of JSON output, I changed the behavior to include the distance whether or not the -l flag is used. There is no computational reason not to.
> r.horizon: always include distance output in JSON output

- raster/r.texture/testsuite/test_texture.py
`r.texture` module has thirteen measure functions, but only five are tested. I added tests for all these functions. They are checked by min, max, mean, variance, and cells instead of just ranges of outputs.
> r.texture: update tests

- .github/workflows/python-code-quality.yml
- renovate.json
- renovate.json5
This PR sets up the tools versions in the Python code quality workflow as such that Renovate can pick these up.
It gets rid of the matrix strategy variables and uses global env vars, which is a good thing. The matrix strategy variables had drawbacks that made the code scanning configurations get a new key each time these changed.
On the renovate part, the feature used is the regex custom managers. But some configuration presets exists for that, and allow to use a standardized comment line above to insert many required and optional info to link any dependency to where the update info is. It allows to avoid writing a custom regex, and use a widely used one.
You may also notice the renovate config file uses json5; it simply allows trailing comma (to reduce diff for next change) and add …
> CI(python): Keep tools versions updated with env vars and renovate

- docker/debian/Dockerfile
Renovate has a special [handling of Debian versioning ](https://docs.renovatebot.com/modules/versioning/debian/) and should keep them updated with the digest pinned.
> docker: Use debian:bookworm-slim image, with date suffix instead of debian:stable

- docker/README.md
- docker/alpine/Dockerfile
- docker/alpine/grass_tests.sh
- docker/debian/Dockerfile
- docker/testdata/test_docker_image.sh
- docker/ubuntu_wxgui/Dockerfile
- singularity/debian/singularityfile_debian
Option `--tmp-location` is deprecated, use `--tmp-project` flag instead
> docker: replace --tmp-location with --tmp-project

- Dockerfile
- docker/alpine/Dockerfile
- docker/alpine/README.md
- docker/alpine/grass_tests.sh
- docker/debian/Dockerfile
- docker/debian/README.md
- docker/testdata/test_grass_session.py
- docker/ubuntu/Dockerfile
- docker/ubuntu/README.md
- docker/ubuntu_wxgui/Dockerfile
- docker/ubuntu_wxgui/README.md
- singularity/debian/README_debian.md
- singularity/debian/singularityfile_debian
- Rewrite `testdata/test_grass_session.py`, replacing the `pip install grass-session` approach by native solution (now fully functional).
- Remove unneeded environmental variables from images (setting GISBASE without the rest of variables may be harmful because internal mechanisms use it to determine if there is an existing session or not).
- Update tests for all Dockerfiles.
Co-authored-by: Vaclav Petras <wenzeslaus@gmail.com>
> docker: Use only native Python API, set only necessary variables

- .github/workflows/macos.yml
- .github/workflows/print_versions.sh
- .github/workflows/test_simple.bat
- .github/workflows/test_simple.sh
- .github/workflows/test_thorough.bat
- .github/workflows/test_thorough.sh
Option `--tmp-location` is deprecated, use `--tmp-project` flag instead
> CI: replace --tmp-location with --tmp-project

- docker/debian/Dockerfile
- docker/ubuntu_wxgui/Dockerfile
- renovate.json5
Docker images for debian and ubuntu_wxgui use a build argument to get PDAL and compile it from source.
This PR uses the same pattern as https://github.com/OSGeo/grass/pull/3799 (using https://docs.renovatebot.com/presets-customManagers/#custommanagersdockerfileversions) to keep PDAL versions updated.
> docker: Configure renovate updates for PDAL in Dockerfiles

- utils/release.yml
Add prefixes temporal (a lot of temporal tools are often changed together). Docker and CI et al. can have subcategories or scopes. General style and perf are recognized. unittest (as in Python unittest) is recognized together with pytest. Refactoring is added as reaction to a specific change. utils is based on existing commits which are hard to categorize otherwise.
> contributing: Add more prefixes

- utils/generate_release_notes.py
- utils/git_author_github_name.csv
To match the commits to their GitHub names, we need to translate some of the names and emails to GitHub names. Some of these were missing. Now the script also generates a list of authors who need that update.
There is still some names which are not recognized and we need to have another mechanism to ignore bots, so this is a draft.
> contributing: Add more known authors to release notes

- utils/generate_release_notes.py
- utils/known_bot_names.txt
This hides all changes by recognized bots from release notes. The changes may still be relevant, e.g., change of version of dependency in a Docker image, so they are hidden but discoverable using Markdown details HTML tag.
Additionally, to make the release notes shorter, this shows only 20 items and hides the rest together with the changes from bots. The overflowing changes are printed first, then the ones from bots. Each group is sorted alphabetically.
> contributing: Hide bots from release notes

- Dockerfile
- docker/ubuntu/Dockerfile
Built both on a fresh cloud IDE, and also finishing building the untouched ubuntu_wxgui Dockerfile
This fixes only the failures introduced in https://github.com/OSGeo/grass/commit/9f7ecdc31044b64794f35491093ffb8e336c22b4, but nothing else
> docker: Revert failing cleaning steps in Ubuntu Dockerfile

- utils/generate_release_notes.py
- utils/known_bot_names.txt
Hides bots also in the GitHub API release notes which have slightly different format and the bots don't have the bot suffix.
Also fixes missing check for overflow list, so overflowing items were completely hidden.
> contributing: Hide bots in the GH API output

- Vagrantfile
- utils/vagrant/compile.sh
This PR updates Vagrantfile to use Ubuntu 24.04 LTS.
- unofficial Ubuntu image is used (https://app.vagrantup.com/alvistack/boxes/ubuntu-24.04 which is one of the most popular on [Vagrant Cloud](https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=ubuntu+24.04) and has X Windows system activated) Reason: Canonical no longer publish Vagrant image ([source](https://documentation.ubuntu.com/public-images/en/latest/public-images-explanation/vagrant/))
- PDAL support not included since UbuntuGIS doesn't provide any package for Ubuntu 24.04 yet ([link](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+packages?field.name_filter=pdal&field.status_filter=published&field.series_filter=))
```sh
vagrant up
vagrant ssh -c grass
```
> packaging: Update Vagrantfile to Ubuntu 24.04

- pyproject.toml
The message 'check for execution of untrusted input' is triggered by any use of subprocess regardless of the actual input, so even fixed input triggers it. Bandit issue https://github.com/PyCQA/bandit/issues/333 discusses that this is a common false positive triggered by any usage.
The pattern is common enough in our code to ignore this to avoid clutter and warning fatigue. We already ignore B404 mentioned in the issue above.
> checks: Disable Bandit B603 check for untrusted input

- renovate.json5
Renovate supports updating hooks in pre-commit, but it is still opt-in. This PR opts in for these updates.
The prerequisite work for this PR has been merged, that is that pre-commit doesn’t fail when run on all code-base (#3834) and that when the pre-commit config changes, pre-commit is ran in CI on all files to know if the changes would work on a local computer (#3833).
Once merge, PRs updating pre-commit hooks will start to be filed, and CI will allow us to check that they are compatible
> CI: Enable pre-commit updates by Renovate

- python/grass/temporal/abstract_space_time_dataset.py
This PR adds a `group` option to get_registered_maps.
It is mainly intended for STRDS with imagery data where each granule (unique time stamp) has several bands with different semantic_labels. Planned usage is like this:
```
import grass.temporal as tgis
tgis.init()
strds = strds = tgis.open_old_stds("YOUR_IMAGERY_STRDS@PERMANENT", "raster"))
map_rows = strds.get_registered_maps(group="start_time,end_time", where="start_time > '2024-05-22'", columns="id,semantic_label")
for map_row in map_rows:
print(tuple(map_row))
```
> temporal: add group option to get_registered_maps

- gui/wxpython/location_wizard/wizard.py
- python/grass/docs/src/temporal_framework.rst
- utils/gitlog2changelog.py
`== True` (or `== False`) is not a boolean operator and can lead to wrong results
* `is` is also unnoticeably faster
> style: use `is True` instead of `== True`

- .github/workflows/gcc.yml
Remove tests for old C and C++ standards, aligning with the spirit of _RFC 7: Language Standards Support_.
Using (GNU) C17 and C++17, aligning with GDAL RFC 98 which introduces C++ >= 17 for v3.9.
> CI: Remove build tests for C99, C++11, C++14

- python/grass/benchmark/app.py
- python/grass/benchmark/plots.py
- python/grass/benchmark/results.py
- python/grass/benchmark/runners.py
- python/grass/benchmark/testsuite/test_benchmark.py
- python/grass/benchmark/testsuite/test_benchmark_cli.py
Based on issue #2118, add an argument to `nprocs_plot` function in `plots.py`, so it can plot speedup and efficiency for the parallelization results. It's tested on my fork repository (https://github.com/cyliang368/grass/pull/8#).
> grass.benchmark: Compute speedup and enable plotting speedup/efficiency

- lib/gis/getl.c
- modernize C code in order to simplify code
- do not fail with different newline types (Linux vs Windows vs ...)
This PR attempts to address CI errors like  ([source](https://github.com/OSGeo/grass/actions/runs/9534835086/job/26279820815)):
`ERROR: Cannot open filter file 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\grass8-runneradmin-6736\\tmph6va8xp9'\r\n`
> lib/gis: modernize getl2()

- lib/gis/user_config.c
> Variable 'len' is modified inside assert statement. Assert statements are removed from release builds so the code inside assert statement is not executed. If the code is needed also in release builds, this is a bug.
> lib/gis: user_config.c: Fix CWE 398

- .github/workflows/titles.yml
Uses the utils/generate_release_notes.py "check" argument introduced in #3824.
Runs on pull_request_target (so safer to checkout the python script, as the code isn't from the external pull request), and in addition to the 3 default activity types, it runs on the `edited` activity type. This also means that it runs when the body of the PR is edited, but for now, it only takes 12 seconds to run.
Possible improvements possible include:
* Avoid using checkout and use GitHub API to fetch 2 files (utils/generate_release_notes.py and utils/release.yml)
* Filter out when the activity type is `edited` AND that `${{ github.event.changes.title.from }}` is present (I didn't find obviously what field of any of the contexts available to use for knowing if the activity type is `edited`).
> CI(Titles): Validate PR titles in CI

- doc/howto_release.md
> contributing: Optimize text in release procedure

- lib/cdhc/as177.c
The array r has a maximum index of 6.
Additionally, since j is an int, it can have a negative value. This commit limits the risk of errors when accessing r. Moreover, since r is only used within this function, we remove the j == 1 condition and integrate it directly into the r array.
> lib/cdhc: Cdhc_alnfac, fix bound condition

- utils/generate_release_notes.py
- utils/release.yml
The message now includes the expressions (except the excluded ones typically used only by maintainers) and examples (newly added).
> contributing: Improve message for failing PR title check

- .travis.yml
- .travis/linux.before_install.sh
- .travis/linux.install.sh
- .travis/linux.script.sh
- db/drivers/odbc/describe.c
- db/drivers/odbc/fetch.c
- db/drivers/odbc/listtab.c
Default Python version reported by Travis for 20.04 is 3.7.13. While that's still a supported version for 8.3 release if it would be released now, 2023-06-27 is end of support for 3.7, so it seems safe to not test the main branch with 3.7 at this point.
Ubuntu 22.04 in Travis uses Python 3.10 by default according to the documentation.
> CI: Switch Travis to Ubuntu 22.04 and fix non-prototype in ODBC

- .github/workflows/pytest.yml
- pyproject.toml
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
One probable explanation of some flaky pytest failures is that a small number of tests use more resources since they expect they would be the only module running. Or, for example, testing with multiple number of processes, while already multiple pytest runners are executing tests.
This ended up stalling the other tests, and we regularly encountered failures to different tests files.
The solution here is identifying which tests have this behaviour, and should be run separately from the tests run in parallel, with a single runner. Inspired by pytest’s docs on markers, the `needs_solo_run` marker name was chosen and applied to two tests (10 items). 
The slow marker from pytest’s docs is kept as I intend to mark some tests that are way slower than expected with it.
~~With these two steps …
> CI(pytest): Run tests marked need_solo_run separately

- doc/notebooks/jupyter_example.ipynb
- doc/notebooks/jupyter_tutorial.ipynb
- python/grass/jupyter/interactivemap.py
Previously, users needed to add a layer control to an `InteractiveMap` with `add_layer_control()`.
This PR changes this so that `add_layer_control()` is called when the users calls `InteractiveMap.show()` by default if the user has not already called it.
> grass.jupyter: Add LayerControl to InteractiveMap by default

- raster/r.in.pdal/info.cpp
According to LAS specification, the first return number is 1. Fixes #3827
> r.in.pdal: use 1 based return numbers in LAS info output

- CONTRIBUTING.md
- doc/development/github_guide.md
I moved the Github workflow into a separate file to keep the CONTRIBUTING.md file short and not overwhelming. I removed the link to trac wiki, if there are any pieces relevant for new contributors, they should be moved here. I tried to check that, but this needs review. In _Updating your PR from main_ I changed it from rebase to merge to make things less error prone. The rest of the contributing file needs updates as well, but that's out of scope of this PR.
> contributing: move GitHub workflow docs into separate file

- .gitignore
- flake.lock
- flake.nix
- package.nix
Add couple of Nix files which will allow following:
* Create full development environment using single command
* Run GRASS from any GitHub revision
- Install Nix
[(learn more about this installer)](https://zero-to-nix.com/start/install)
```bash
curl --proto '=https' --tlsv1.2 -sSf \
-L https://install.determinate.systems/nix \
| sh -s -- install
```
- Run following command in source code root directory
```bash
nix develop
```
- Optionally, use `direnv` to activate the environment automatically when
moving to the source code directory
```bash
echo "use flake" > .envrc
direnv allow
```
- Run latest version from `main` branch
```bash
nix run github:OSGeo/grass#grass -- --text
```
- Run version from specific Git branch
```bash
nix run github:OSGeo/grass/<GIT-BRANCH>#grass -- --text
```
- Run …
> packaging: Add Nix files for creating development environment and the package

- vector/v.external/args.c
`    options->layer->required = NO;` is contained just a few rows above
> v.external: delete duplicated layer requirement definition

- .github/workflows/clang-format-check.yml
- .github/workflows/create_release_draft.yml
- .github/workflows/label.yml
- .github/workflows/titles.yml
This week during the code sprint, I observed that some workflows or jobs weren't cancelled when another push/force push to a PR was made. Most of them didn't have a long runtime, and some were tricky as they continued to be queued after a force push.
Also fixes a small issue where clang-format jobs were cancelled on main (supposed to be a protected branch) when multiple jobs of this typed were queued. Suppose three merges to main made extremely close together, and the first set of jobs start normally. The first one, currently executing, continued, but the second was cancelled, and the third was made "pending", waiting for the first to finish. This PR finally makes use of the same known pattern.
> CI: Cancel in progress jobs for other workflows

- display/d.linegraph/main.c
This pull request addresses warning identified by Clang in the `display/d.linegraph/main.c` file.
1. **Null Pointer Check in `qsort`:**
- **Issue:** Null pointer passed to 1st parameter expecting 'nonnull'.
- **Fix:** Added a null pointer check before calling `qsort`.
- Clang warnings:
- `main.c:129:5: warning: Null pointer passed to 1st parameter expecting 'nonnull' [core.NonNullParamChecker]`
> d.linegraph: Fix null pointer issue in qsort call

- display/d.legend.vect/draw.c
This pull request addresses dead store warnings in the **d.legend.vect** module's **draw.c** file.
**Fixed Issues**:
- **Warning:** Value stored to 'symb_name' is never read.
- **Warning:** Value stored to 'label' is never read.
**Changes Made**:
- Commented out the redundant assignment to **symb_name**:
// symb_name = G_store(tokens[1]);
- Commented out the redundant assignment to **label**:
// label = G_malloc(GNAME_MAX);
> d.legend.vect: Fix dead store warnings in draw.c

- .github/workflows/pytest.yml
- .github/workflows/super-linter.yml
- .travis.yml
yamllint in pre-commit fails while yamllint from super-linter doesn't. Adds the config file to the super-linter config, as surprisingly super-linter defaults to .yaml-lint.yml, which wasn't a default known config file name in yamllint in all versions of the docs I looked at, going back to v1.0.0 too.
> CI(super-linter): Specify linter rules path to pick up configuration files

- display/d.linegraph/main.c
This pull request addresses a dead store warning in the `d.linegraph` module's `main.c` file.
**Fixed Issue**:
- **Warning:** Although the value stored to 'err' is used in the enclosing expression, the value is never actually read from 'err'.
**Changes Made**:
- Replaced the assignment and usage of **err** in the following block:
while ((err = fscanf(in[i].fp, "%f", &in[i].value)) != EOF) {
}
**with** 
while (fscanf(in[i].fp, "%f", &in[i].value) != EOF) {
}
> d.linegraph: Fix dead store warning in main.c

- .flake8
- gui/wxpython/iclass/dialogs.py
- gui/wxpython/iscatt/frame.py
- gui/wxpython/lmgr/giface.py
- gui/wxpython/rlisetup/frame.py
- gui/wxpython/rlisetup/wizard.py
- gui/wxpython/timeline/frame.py
- gui/wxpython/tplot/frame.py
- gui/wxpython/vdigit/wxdisplay.py
- gui/wxpython/web_services/widgets.py
The E741 "ambiguous variable name 'l'" is fixed in the gui/wxpython directory. Many of the fixes involved renaming "l" in iterables.
One thing I would like to point out is that [01eb8dd](https://github.com/OSGeo/grass/commit/01eb8dd10b34e4457f27d6c12dc8b253f133a988) returns its self value. Personally, I don't see a problem with changing the name, but I thought it would be best to consult with a developer who is familiar with GRASS GUIs.
> Checks: fix flake8 E741 in gui/wxpython directory

- display/d.histogram/bar.c
This pull request addresses dead store warnings in the d.histogram module's bar.c file
**Issue**
This pull request addresses a warning in bar.c related to the variable draw being assigned a value that is never read.
Removed the redundant assignment draw = NO at line 150.
> d.histogram: Fix dead store warnings in bar.c

- gui/wxpython/core/gcmd.py
- gui/wxpython/dbmgr/base.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/gcp/statusbar.py
- gui/wxpython/gmodeler/canvas.py
- gui/wxpython/gmodeler/panels.py
- gui/wxpython/gui_core/prompt.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/image2target/ii2t_statusbar.py
- gui/wxpython/location_wizard/dialogs.py
- gui/wxpython/modules/colorrules.py
- gui/wxpython/nviz/tools.py
- gui/wxpython/photo2image/ip2i_manager.py
- gui/wxpython/photo2image/ip2i_statusbar.py
- gui/wxpython/vnet/dialogs.py
- python/grass/benchmark/runners.py
- python/grass/imaging/images2swf.py
- python/grass/jupyter/region.py
- python/grass/temporal/temporal_granularity.py
- scripts/d.correlate/d.correlate.py
- scripts/d.rast.edit/d.rast.edit.py
- scripts/d.rast.leg/d.rast.leg.py
- scripts/r.tileset/r.tileset.py
- temporal/t.rast.what/t.rast.what.py
Concerns Pylint rules ["consider-using-min-builtin / R1730"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html) and ["consider-using-max-builtin / R1731"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-max-builtin.html)
Using `ruff check --output-format=concise --select PLR1730 --preview --fix`.
Uses the fixes provided for ruff rule [if-stmt-min-max (PLR1730)](https://docs.astral.sh/ruff/rules/if-stmt-min-max/) to fix part of Pylint's ["consider-using-min-builtin / R1730"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-min-builtin.html) and ["consider-using-max-builtin / …
> style: Fixes if-stmt-min-max (PLR1730)

- python/grass/temporal/abstract_space_time_dataset.py
- python/grass/temporal/list_stds.py
- python/grass/temporal/register.py
- python/grass/temporal/temporal_algebra.py
- python/grass/temporal/temporal_granularity.py
- python/grass/temporal/temporal_raster3d_algebra.py
- python/grass/temporal/temporal_raster_algebra.py
- python/grass/temporal/univar_statistics.py
- temporal/t.info/t.info.py
- temporal/t.rast.export/t.rast.export.py
- temporal/t.rast.gapfill/t.rast.gapfill.py
- temporal/t.rast.list/t.rast.list.py
Concerns Pylint rule ["use-set-for-membership / R6201"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-set-for-membership.html)
Using `ruff check --output-format=concise --select PLR6201 --preview --unsafe-fixes --fix 'temporal/' 'python/grass/temporal'`.
Uses the fixes provided for ruff rule [literal-membership (PLR6201)](https://docs.astral.sh/ruff/rules/literal-membership/) to fix part of Pylint's ["use-set-for-membership / R6201"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-set-for-membership.html). 
The changes are limited to the temporal-related folders to limit the review scope.
> style(temporal): Fixes literal-membership (PLR6201)

- man/build_keywords.py
- python/grass/temporal/extract.py
- python/grass/temporal/mapcalc.py
- raster/r.topidx/arc_to_gridatb.py
- raster/r.topidx/gridatb_to_arc.py
Using  `ruff check --select "PLR1722" --unsafe-fixes --output-format=concise --fix`.
Uses the fixes provided for ruff rule [sys-exit-alias (PLR1722)](https://docs.astral.sh/ruff/rules/sys-exit-alias/) to fix part of Pylint's [consider-using-sys-exit / R1722](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-sys-exit.html).
> style: Fixes sys-exit-alias (PLR1722)

- docker/ubuntu_wxgui/Dockerfile
When building the image, only PROJ 8.2.1 is available, and PDAL 2.7.2 checks for PROJ 9.0+
This is a temporary fix to continue having working Docker builds. Renovate will open a PR to update PDAL again afterwards. But a more substantial fix is needed.
> docker: Downgrade PDAL to 2.7.1 in ubuntu_wxgui

- gui/wxpython/lmgr/frame.py
- gui/wxpython/main_window/frame.py
- man/build_keywords.py
- python/grass/gunittest/reporters.py
- python/libgrass_interface_generator/ctypesgen/expressions.py
- temporal/t.rast.algebra/testsuite/test_raster_algebra_arithmetic.py
Applies the remaining fixes that weren't picked up by `ruff check --select "ISC001" --fix` in order to limit the review scope of https://github.com/OSGeo/grass/pull/3943
> style: Manual fixes for single-line-implicit-string-concatenation violations (ISC001)

- gui/wxpython/rlisetup/wizard.py
- imagery/i.atcorr/create_iwave.py
- python/grass/temporal/spatio_temporal_relationships.py
- scripts/g.extension/g.extension.py
- scripts/r.in.aster/r.in.aster.py
Concerns Pylint rule ["useless-return / R1711"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/useless-return.html)
Using `ruff check --output-format=concise --select PLR1711 --fix`.
Uses the fixes provided for ruff rule [useless-return (PLR1711)](https://docs.astral.sh/ruff/rules/useless-return/) to fix Pylint's ["useless-return / R1711"](https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/useless-return.html).
This one is quite easy to review
> style: Fixes useless-return (PLR1711)

- python/grass/grassdb/manage.py
- scripts/g.extension/testsuite/test_addons_download.py
- scripts/g.extension/testsuite/test_addons_modules.py
Concerns Pylint rule ["pointless-exception-statement / W0133"](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/pointless-exception-statement.html)
Using `ruff check --output-format=concise --select PLW0133 --unsafe-fixes --fix`.
Uses the fixes provided for ruff rule [useless-exception-statement (PLW0133)](https://docs.astral.sh/ruff/rules/useless-exception-statement/) to fix Pylint's ["pointless-exception-statement / W0133"](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/pointless-exception-statement.html).
This one is extremely easy to review. The three exceptions were simply not raised, which doesn't make sense, nor do what was intended.
> style: Fixes useless-exception-statement (PLW0133)

- imagery/i.landsat.acca/main.c
**Fix uninitialized variable issue in i.landsat.acca**
This pull request addresses an issue in **imagery/i.landsat.acca/main.c** where the variable **band[i].name** was uninitialized before being used. The fix involves initializing the first character of band[i].name to '\0' to ensure it is a valid string before passing it to sprintf.
**Changes:**
- Initialize band[i].name before using sprintf to avoid undefined behavior.
> i.landsat.acca: Fix uninitialized variable issue in main.c

- raster/r.texture/benchmark/benchmark_rtexture.py
In between the last time I applied the missing pre-commit violations and the time it was merged, some new violations were introduced in here:
https://github.com/OSGeo/grass/commit/a24714ec1fcca3699d1b1d810c48ed5dac9f0bee#diff-fdcb5f33abc00bc15a934808d3d868490e61db92909e6747a2a635faf2c4df02R20
as the PR changed python files, but the CI wasn't run containing the changes on main that updated the flake8 version or exclusions.
Anyways, here's a missing fix for this:
```python
gitpod /workspace/grass $ flake8 --count --statistics --show-source --jobs=$(nproc) .
./raster/r.texture/benchmark/benchmark_rtexture.py:20:62: E226 missing whitespace around arithmetic operator
benchmark(int(mapsize**0.5), f"r.texture_{int(mapsize/1e6)}M", results)
^
1     E226 missing whitespace around arithmetic …
```
> style: fix missing whitespace between operators

- gui/wxpython/animation/frame.py
- gui/wxpython/gmodeler/dialogs.py
- gui/wxpython/gmodeler/panels.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/menu.py
- gui/wxpython/gui_core/prompt.py
- gui/wxpython/gui_core/widgets.py
- gui/wxpython/history/tree.py
- gui/wxpython/iclass/frame.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/layertree.py
- gui/wxpython/main_window/frame.py
- gui/wxpython/mapdisp/frame.py
- gui/wxpython/mapdisp/main.py
- gui/wxpython/mapswipe/frame.py
- gui/wxpython/rdigit/g.gui.rdigit.py
- gui/wxpython/vdigit/g.gui.vdigit.py
Concerns Pylint rule ["unnecessary-lambda / W0108"](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-lambda.html)
Using `ruff check --output-format=concise --select PLW0108 --preview --fix --unsafe-fixes`.
Didn't apply to cases where it wasn't clear if it was safe.
Uses the fixes provided for ruff rule [unnecessary-lambda (PLW0108)](https://docs.astral.sh/ruff/rules/unnecessary-lambda/#unnecessary-lambda-plw0108) to fix part of Pylint's ["unnecessary-lambda / W0108"](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/unnecessary-lambda.html).
> style: Fixes some unnecessary-lambda (PLW0108)

- raster/r.terraflow/sweep.cpp
**Fix uninitialized variable 'flowpq' in raster/r.terraflow/sweep.cpp**
This pull request addresses an issue in `r.terraflow` where the variable `flowpq` was used without being initialized.
**Changes:**
- Initialize `flowpq` to `nullptr` in the `initializePQ` function to ensure it is properly initialized before use.
This fix resolves the cppcheck warning related to the uninitialized variable.
> raster: Fix uninitialized variable 'flowpq' in raster/r.terraflow/sweep.cpp

- raster/r.profile/Makefile
- raster/r.profile/local_proto.h
- raster/r.profile/main.c
- raster/r.profile/r.profile.html
- raster/r.profile/read_rast.c
- raster/r.profile/testsuite/test_profile_ncspm.py
Use parson to add json output format support to the r.profile module.
The output format is as follows:
```json
[
{
"easting": <float>,
"northing": <float>,
"distance": <float>,
"elevation": <float>,
"red": <int>,
"green": <int>,
"blue": <int>
},
{
"easting": <float>,
"northing": <float>,
"distance": <float>,
"elevation": <float>,
"red": <int>,
"green": <int>,
"blue": <int>
},
...
]
```
Note that the `elevation` field is the name of the input and `red`, `green`, `blue`  fields are only included if the `colors` flag is specified.
> r.profile: add JSON support

- .flake8
- locale/grass_po_stats.py
- python/grass/pygrass/raster/rowio.py
- python/grass/temporal/temporal_algebra.py
- python/grass/temporal/temporal_raster3d_algebra.py
- python/grass/temporal/temporal_raster_algebra.py
- python/grass/temporal/temporal_vector_algebra.py
- scripts/d.rast.leg/d.rast.leg.py
- scripts/db.univar/db.univar.py
- scripts/r.in.wms/wms_cap_parsers.py
Reminder of E741 fixes for the "locale", "python", and "scripts" directories. The majority of fixes involved renaming variable names in iterables. The "noqa: E741" was added to "scripts/d.rast.leg/d.rast.leg.py" since it didn't make sense to change just the "l".
> Checks: fix flake8 E741 remainder

- .github/workflows/post-pr-reviews.yml
- .github/workflows/python-code-quality.yml
- .pre-commit-config.yaml
- pyproject.toml
Ruff is a python linter written in rust, that is extremely fast. https://docs.astral.sh/ruff/
This PR adds ruff configuration to pyproject.toml, enabling all rules that aren't currently failing.
Some rules support fixes, so ruff is added to the python-code-quality workflow with suggestions.
Ruff is also added to pre-commit, with fixes.
I made sure to ignore every rule that was failing, as well as adding some per-file-ignores for some rules where I really didn't want to wait enabling them, or not many files were failing. This way, to fix some new rules, look at an ignored rule, look https://docs.astral.sh/ruff/rules/ to see if fixes are available, and remove the ignored identifier.
```bash
ruff check --fix
ruff check --fix --preview
ruff check --output-format=concise --preview …
```
> checks(ruff): Configure ruff linter

- display/d.labels/main.c
**Description**
This pull request reduces the scope of the `minreg` and `maxreg` variables in the `d.labels/main.c` file.
- Moved the declaration of `minreg` and `maxreg` inside their respective `if` blocks to reduce their scope.
This change addresses the following cppcheck warnings:
- display/d.labels/main.c:31:12: style: The scope of the variable 'minreg' can be reduced. [variableScope]
- display/d.labels/main.c:31:20: style: The scope of the variable 'maxreg' can be reduced. [variableScope]
> d.labels: Reduce scope of minreg and maxreg variables in main.c

- display/d.legend.vect/draw.c
**Description:**
This pull request reduces the scope of the 'bg_w' variable in `d.legend.vect/draw.c`.
- Moved `bg_w` declaration to where it is first used in `d.legend.vect/draw.c`.
This change addresses the following cppcheck warning:
display/d.legend.vect/draw.c:46:26: style: The scope of the variable 'bg_w' can be reduced. [variableScope]
double margin, bg_h, bg_w;
> d.legend.vect: Reduce scope of 'bg_w' variable in draw.c

- lib/gis/parser_interface.c
This pull request fixes an issue in `parser_interface.c` where the variable encoding was used without being initialized. The change initializes encoding to NULL to ensure it is properly set before use.
- Initialize encoding to NULL
> lib: Fix uninitialized variable 'encoding' in parser_interface.c

- .github/workflows/post-pr-reviews.yml
- .github/workflows/python-code-quality.yml
I overlooked the situation where some ruff errors can and cannot be fixed in the same pass. The exit code won’t be 0 if not all files were fixed. This prevented to reach the step where the diff was stored as an artifact to upload suggestions, to post.
So instead of setting the ruff step with `continue-on-errors: true`, which would have shown the step as gray (passing), even when rules without fixes are failing, I set the condition to `if: ${{ !cancelled() }}` as mentioned in the docs for always() https://docs.github.com/en/actions/learn-github-actions/expressions#always
I also spotted a copy-paste typo in the post-pr-reviews workflow, that I had already fixed on another branch but forgot to apply on the one that ended up being a PR.
Finally, I reconsidered my initial position on only …
> CI(ruff): Fine tune posting Ruff suggestions

- imagery/i.segment/mean_shift.c
This pull request fixes an issue in `mean_shift.c` where the struct member `ngbr_rc.next` was used without being initialized. The change initializes `ngbr_rc.next` to `NULL` to ensure it is properly set before use.
- Initialize `ngbr_rc.next` to `NULL` 
This fix resolves the cppcheck warning related to the uninitialized variable.
> i.segment: Fix uninitialized struct member 'ngbr_rc.next' in mean_shift.c

- lib/cdhc/shapiroe.c
This pull request addresses the uninitialized variable issue in shapiroe.c identified by cppcheck. 
**Issues**
shapiroe.c:22:17: error: Uninitialized variable: xs [uninitvar]
b = (mean - xs) * sqrt((double)n / (n - 1.0));
^
shapiroe.c:11:19: note: Assuming condition is false
for (i = 0; i < n; ++i)
^
shapiroe.c:22:17: note: Uninitialized variable: xs
b = (mean - xs) * sqrt((double)n / (n - 1.0));
Initialized xs to the first element of the array x to ensure it is properly set before being used in subsequent calculations.
> lib: Fix uninitialized variable issue in shapiroe.c

- imagery/i.segment/region_growing.c
This pull request fixes an issue in region_growing.c where the struct member Ri was used without being initialized. The change initializes Ri to {0} to ensure all members are properly set before use.
- Initialize Ri to {0}.
This fix resolves the cppcheck warning related to the uninitialized variable.
> i.segment: Fix uninitialized struct member error in region_growing.c

- lib/cdhc/dmax.c
This pull request addresses the following warning identified by clang.
**Issue:**
dmax.c:48:10: warning: Assigned value is garbage or undefined [core.uninitialized.Assign]
y[0] = dp_max;
**Changes made:**
The issue was fixed by initializing the variables `dp`, `dp_max`, `dm`, and `dm_max` to `0.0`. This ensures that the variables have a defined value before they are used in the calculation. The updated part of the code is:
double dp = 0.0, dp_max = 0.0, dm = 0.0, dm_max = 0.0;
To maintain consistency across the code, variables other than dp_max are also initialized.
> lib: Fixed uninitialized variable warning in dmax.c by initializing dp, dp_max, dm, and dm_max to 0.0

- imagery/i.atcorr/create_iwave.py
- pyproject.toml
- python/grass/imaging/images2gif.py
- python/grass/temporal/abstract_map_dataset.py
- python/grass/temporal/c_libraries_interface.py
- python/grass/temporal/temporal_granularity.py
- scripts/g.extension/g.extension.py
Equivalent ruff rule is [useless-expression (B018)](https://docs.astral.sh/ruff/rules/useless-expression/) from flake8-bugbear.
One file contains changes that would've been changed in https://github.com/OSGeo/grass/pull/3886, but that PR has other changes.
> style: Fix pylint pointless-statement (W0104)

- pyproject.toml
- python/grass/gunittest/invoker.py
- utils/generate_last_commit_file.py
- utils/mkhtml.py
- utils/test_generate_last_commit_file.py
Using `ruff check --output-format=concise --preview --select UP022 --unsafe-fixes --fix`
Ruff rule [replace-stdout-stderr (UP022)](https://docs.astral.sh/ruff/rules/replace-stdout-stderr/):
> Why is this bad?[#](https://docs.astral.sh/ruff/rules/replace-stdout-stderr/#why-is-this-bad)
> As of Python 3.7, `subprocess.run` has a `capture_output` keyword argument that can be set to `True` to capture `stdout` and `stderr` outputs. This is equivalent to setting `stdout` and `stderr` to `subprocess.PIPE`, but is more explicit and readable.
> style: Fix replace-stdout-stderr (UP022)

- ps/ps.map/r_colortable.c
This pull request addresses the following warnings identified by cppcheck in `r_colortable.c`:
**Issues:**
r_colortable.c:194:14: error: Uninitialized variable: min [uninitvar]
ct.min = min;
r_colortable.c:195:14: error: Uninitialized variable: max [uninitvar]
ct.max = max;
The variables min, max, and tmpD are now initialized to 0.0 to ensure they have defined values before use. This resolves the warnings about uninitialized variables.
> ps.map: Fix uninitialized variable issues in r_colortable.c

- gui/wxpython/core/globalvar.py
- gui/wxpython/gmodeler/canvas.py
- gui/wxpython/gmodeler/model.py
- gui/wxpython/lmgr/layertree.py
- pyproject.toml
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/modules/interface/flag.py
- python/grass/pygrass/modules/interface/parameter.py
- python/grass/pygrass/modules/interface/testsuite/test_flag.py
- python/grass/pygrass/raster/abstract.py
- python/grass/pygrass/utils.py
- python/grass/pygrass/vector/__init__.py
- python/grass/pygrass/vector/abstract.py
- python/grass/pygrass/vector/geometry.py
- utils/mkhtml.py
Relates to pylint rule simplifiable-if-expression / R1719
Fixed ruff rules: https://docs.astral.sh/ruff/rules/if-expr-with-true-false/ and https://docs.astral.sh/ruff/rules/if-expr-with-false-true/
> style: Fix if-expr-with-true-false (SIM210) and if-expr-with-false-true (SIM211)

- python/grass/jupyter/tests/seriesmap_test.py
- python/grass/jupyter/tests/timeseriesmap_test.py
- temporal/t.rast.list/tests/t_rast_list_test.py
The test fixture `space_time_raster_dataset` used in some pytest tests, including in some of the Jupyter tests, is unexpectedly slow at the setup stage when running in pytest with multiple workers. There might be a deadlock problem, or might just use many processes or threads by itself. 
Since it causes some intermittent timeouts, this PR adds the marker to run them separately, without other tests in parallel. The setup stage is still slow, but I highly expect after my couple tries that it will prevent some more timeouts that were still present after https://github.com/OSGeo/grass/pull/3879.
On the positive side, there's (hopefully) less flaky tests to retry, that can cause delays when there is a lot of activity. On the negative side, since these tests are slow AND that the setup phase of …
> pytest: Mark tests using space_time_raster_dataset as needs_solo_run

- pyproject.toml
- python/grass/pygrass/rpc/base.py
- python/grass/temporal/c_libraries_interface.py
Pylint error: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-not-lazy.html
Ruff rules category: https://docs.astral.sh/ruff/rules/#flake8-logging-format-g
A stack-overflow answer showing the use of the "new" logging format (configured as "new" in my branch for my upcoming pylint 3.x config PR): https://stackoverflow.com/a/59027338
The goal of the python logging module https://docs.python.org/3/howto/logging.html#logging-variable-data is to not create a string already formatted, but let the logging format it. In other ecosystems (at least, I don't know for python), there is a concept called structured logging. A good logging usage would have only the templates …
> style: Fix python logging-related pylint and ruff warnings

- gui/wxpython/core/utils.py
- pyproject.toml
- python/grass/imaging/images2swf.py
- python/grass/temporal/c_libraries_interface.py
- python/grass/temporal/datetime_math.py
Do not catch exception only to raise it again
In one file (gui/wxpython/core/utils.py), there was a backport done in 2010 in https://trac.osgeo.org/grass/changeset/41398/ that was supposed to adapt https://trac.osgeo.org/grass/changeset/41396, but with part of the function extracted, having the try in GetListOfLocations is useless, as it is not really used, and will need to get caught elsewhere.
> style: Fix pylint try-except-raise (W0706)

- gui/wxpython/dbmgr/sqlbuilder.py
- gui/wxpython/iscatt/controllers.py
- gui/wxpython/location_wizard/wizard.py
- gui/wxpython/mapwin/base.py
- pyproject.toml
- python/grass/jupyter/seriesmap.py
- python/grass/jupyter/tests/seriesmap_test.py
- python/grass/jupyter/tests/timeseriesmap_test.py
- python/grass/pygrass/tests/benchmark.py
- python/grass/script/testsuite/test_utils.py
- scripts/v.pack/v.pack.py
When iterating over a dictionary with dict.items() but discarding either the values or the keys, dict.values() or dict.keys() should be used instead
Ruff rule: https://docs.astral.sh/ruff/rules/incorrect-dict-iterator/
> style: Fix incorrect-dict-iterator (PERF102)

- pyproject.toml
This enables the ruff rule multiple-with-statements, as all violations were in test files that specifically tested multiple with statements nested together.
Thus, only the pyproject.toml is changed.
> style: Ignore multiple-with-statements (SIM117) for test files

- gui/wxpython/core/toolboxes.py
- pyproject.toml
- scripts/r.in.wms/wms_cap_parsers.py
Ruff rule: https://docs.astral.sh/ruff/rules/loop-variable-overrides-iterator/
Some loops used `for elem in elem`, so I replaced by `for _elem in elem`.
> style: Fix loop-variable-overrides-iterator (B020)

- raster/r.statistics/o_var.c
This pull request addresses the following warning identified by cppcheck.
**Issue:**
o_var.c:70:16: error: Uninitialized variable: count [uninitvar]
m_var(tab, count, &vari);
**Changes made:**
The issue was fixed by initializing the variable `count` to `0` at the beginning of the `o_var` function. This ensures that the variable has a defined value before it is used in the calculation.
> raster: Fix uninitialized variable issue in o_var.c

- raster3d/r3.info/main.c
This pull request addresses the following warning identified by cppcheck.
**Issue:**
main.c:203:47: error: Uninitialized variable: tmp1 [uninitvar]
"raster_3d", cats_ok ? tmp1 : "??") > 0)
**Changes made:**
The issue was fixed by initializing the variables `tmp1`, `tmp2`, and `tmp3` as empty strings. This ensures that the variables have defined values before they are used in the calculation.
> raster3d: Fix uninitialized variable issue in main.c

- .github/workflows/test-nix.yml
- renovate.json5
Regularly update a Nix lock file to get fresh packages from nixpkgs.
Usage of Renovate discussed in https://github.com/OSGeo/grass/pull/3933 .
> CI: automatic update of nix lock file

- flake.lock
- flake.nix
- package.nix
Nixpkgs is moving to Python 3.12 as a default version. It looks like wxPython doesn't support Python 3.12 yet.
This PR will pin Python version used for GRASS to version 3.11.
We are applying the same fix for [upstream Nixpkgs GRASS package](https://github.com/NixOS/nixpkgs/pull/325731).
This PR also contains updated flake.lock file to the latest version of nixpkgs (using `nix flake update` command).
> nix: pin python version to 3.11

- imagery/i.segment/region_growing.c
This pull request address all the uninitialized variables for c files in imagery folder.
Issues:
region_growing.c:725:17: Uninitialized struct member: ngbr_rc.next [uninitStructMember]
*pngbr_rc = ngbr_rc;
region_growing.c:1077:21: Uninitialized struct member: ngbr_rc.next [uninitStructMember]
*pngbr_rc = ngbr_rc;
region_growing.c:1555:21: Uninitialized struct member: ngbr_rc.next [uninitStructMember]
*pngbr_rc = ngbr_rc;
region_growing.c:1555:21: Uninitialized variable: ngbr_rc.next [uninitvar]
*pngbr_rc = ngbr_rc;
region_growing.c:899:10: Uninitialized variable: pl1 [uninitvar]
pl = pl1 + pl2 - nshared;
region_growing.c:899:16: Uninitialized variable: pl2 [uninitvar]
pl = pl1 + pl2 - nshared;
region_growing.c:916:13: Uninitialized variable: count1 [uninitvar]
count = count1 + count2; …
> i.segment: Fix uninitialized variable issue

- pyproject.toml
- python/grass/pygrass/modules/grid/split.py
Ruff rule: https://docs.astral.sh/ruff/rules/if-expr-min-max/
Only one file affected, when returning a bounding box.
> style: Fix if-expr-min-max (FURB136)

- pyproject.toml
- raster/r.stats.zonal/graphics_for_description.ipynb
Ruff rule: https://docs.astral.sh/ruff/rules/too-many-newlines-at-end-of-file/
Only one file changed, a single python notebook had an empty cell at the end of the document, so removed that cell.
> style: Fix too-many-newlines-at-end-of-file (W391)

- gui/wxpython/datacatalog/tree.py
- lib/init/grass.py
- pyproject.toml
- python/grass/temporal/temporal_algebra.py
- scripts/d.polar/d.polar.py
Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-comprehension-in-call/
The explanations are well written in that page. For example, they show this:
> ### Why is this bad?[#](https://docs.astral.sh/ruff/rules/unnecessary-comprehension-in-call/#why-is-this-bad)
> Many builtin functions (this rule currently covers `any`, `all`, `min`, `max`, and `sum`) take any iterable, including a generator. Constructing a temporary list via list comprehension is unnecessary and wastes memory for large iterables.
> 
> `any` and `all` can also short-circuit iteration, saving a lot of time. The unnecessary comprehension forces a full iteration of the input iterable, giving up the benefits of short-circuiting. For example, compare the performance of `all` with a list comprehension against that of a …
> style: Fix unnecessary-comprehension-in-call (C419)

- doc/NIX.md
Add instructions how to install Nix, use it to create a development environment and install GRASS from git.  
New file is created because this information doesn't fit well enywhere else (I spent some time with @veroandreo trying to find a suitable space).
/cc @veroandreo
> doc: add Nix documentation

- imagery/i.atcorr/main.cpp
**This pull request addresses uninitialized variable issue for all cpp files in imagery**
**Issue:**
i.atcorr/main.cpp:213:16: error: Uninitialized variable: rbitem.ti [uninitvar]
return rbitem;
Initialized the RBitem struct to zero to ensure all members, including nested structures, are properly initialized.
> i.atcorr: Fix uninitialized variable

- man/build_class_graphical.py
- pyproject.toml
Ruff rule: https://docs.astral.sh/ruff/rules/sorted-min-max/
One instance changed. It is calling the element at index 0 of a sorted() call.
The check will now be enabled after this, since all instances are fixed and should stay fixed
> style: Fix sorted-min-max (FURB192)

- gui/wxpython/core/gconsole.py
- gui/wxpython/core/render.py
- gui/wxpython/core/settings.py
- gui/wxpython/core/utils.py
- gui/wxpython/core/watchdog.py
- gui/wxpython/core/workspace.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/gui_core/ghelp.py
- gui/wxpython/image2target/ii2t_gis_set.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/location_wizard/wizard.py
- gui/wxpython/photo2image/ip2i_manager.py
- gui/wxpython/vnet/vnet_data.py
- lib/init/grass.py
- pyproject.toml
- python/grass/grassdb/history.py
- python/grass/pygrass/raster/category.py
- python/grass/script/core.py
- python/grass/script/db.py
- scripts/d.frame/d.frame.py
- scripts/g.extension/g.extension.py
- scripts/i.spectral/i.spectral.py
- scripts/r.pack/r.pack.py
Ruff rule: https://docs.astral.sh/ruff/rules/readlines-in-for/
"It is more convenient and performant to iterate over the file object directly"
In python docs for [io.IOBase.readlines](https://docs.python.org/3/library/io.html#io.IOBase.readlines) 
"Note that it’s already possible to iterate on file objects using `for line in file: ...` without calling file.readlines()."
> style: Fix readlines-in-for (FURB129)

- gui/wxpython/core/gcmd.py
- gui/wxpython/core/utils.py
- gui/wxpython/iclass/frame.py
- gui/wxpython/lmgr/layertree.py
- gui/wxpython/web_services/widgets.py
- pyproject.toml
- python/grass/temporal/spatial_extent.py
- scripts/g.extension/g.extension.py
Ruff rule: https://docs.astral.sh/ruff/rules/yoda-conditions/
> style: Fix yoda-conditions (SIM300)

- gui/wxpython/animation/controller.py
- gui/wxpython/animation/temporal_manager.py
- gui/wxpython/animation/utils.py
- gui/wxpython/core/render.py
- gui/wxpython/core/toolboxes.py
- gui/wxpython/mapwin/buffered.py
- gui/wxpython/psmap/dialogs.py
- lib/init/grass.py
- pyproject.toml
- python/grass/grassdb/history.py
- scripts/g.extension/g.extension.py
I batched some FURB rules that had low occurrences into one PR
- style: Fix reimplemented-starmap (FURB140)
- Ruff rule: https://docs.astral.sh/ruff/rules/reimplemented-starmap/
- style: Fix delete-full-slice (FURB131)
- Ruff rule: https://docs.astral.sh/ruff/rules/delete-full-slice/
- style: Fix unnecessary-enumerate (FURB148)
- Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-enumerate
- style: Fix for-loop-set-mutations (FURB142)
- Ruff rule: https://docs.astral.sh/ruff/rules/for-loop-set-mutations
- style: Fix single-item-membership-test (FURB171)
- Ruff rule: https://docs.astral.sh/ruff/rules/single-item-membership-test
> style: Fix various FURB (small count)

- display/d.text/test.py
- lib/imagery/testsuite/test_imagery_sigsetfile.py
- pyproject.toml
Ruff rule: https://docs.astral.sh/ruff/rules/math-constant/
The rule finds hard-coded constants like pi, tau, e, and replaces it with the constants from `math`.
Two files are affected. One seems unused (a test.py that isn't run as tests), and a test file in imagery. Since the complete test file seemed to use two decimal points, I reverted and added a per-file-ignore. I made it in a separate commit so it would be possible to see what it looks like with the change.
> style: Fix math-constant (FURB152)

- renovate.json5
Configures update groups so simultaneous updates of pre-commit and the tool in CI are updated together. (Especially when the pre-commit mirror repo isn't the same repo as the tool).
Worked in my repo, it autoclosed a duplicated ruff and ruff-pre-commit PR https://github.com/echoix/grass/pull/152 and created this instead: https://github.com/echoix/grass/pull/159
> CI: Configure Renovate update groups

- raster/r.coin/print_coin.c
- raster/r.mapcalc/map3.c
- raster/r.object.geometry/main.c
- raster/r.out.mpeg/main.c
- raster/r.sim/simlib/random.c
- raster/r.spreadpath/path_finder.c
- raster/r.statistics/o_kurt.c
- raster/r.statistics/o_sdev.c
- raster/r.statistics/o_skew.c
The pull request fixes uninitialized variable issue for all C files in raster.
> raster: Fix uninitialized variable issue for C raster modules

- raster/r.li/r.li.html
updated dead URL to fragstat paper by McGarigal et al.
> r.li manual: Update reference to fragstat paper

- raster/r.category/Makefile
- raster/r.category/local_proto.h
- raster/r.category/main.c
- raster/r.category/r.category.html
- raster/r.category/test_rcategory_doctest.txt
The JSON output looks as follows:
```json
[
{
"category": 1,
"description": "trees, very green"
},
{
"category": 2,
"description": "water, very deep"
}
]
```
Note that the format option for this module is named as `output_format` because `format` is being used as the name for another option.
> r.category: add JSON support

- .coveragerc
- .github/workflows/pytest.yml
- .gitignore
- utils/coverage_mapper.py
This PR makes sure all Python files are collected in the code coverage report, even if uncovered.
Because of our special layout, the coverage tool can't map back to files in the repo easily, so special configuration was needed.
In order to collect for files that can't be imported, `include_namespace_packages = True` must be used. It adds about 1 min on report creation.
Also, handling the case of the installed scripts not having the same file name as the code in the repo was really hard to solve, and unsolvable only by configuration. I had to resort to using their API that edits the SQLite database with a custom function that maps paths to a path in the repo.
I also made sure to upload HTML report artifacts, as the python coverage tool can save what test function touched what line, and is …
> pytest: Collect all uncovered Python files in code coverage

- python/grass/gunittest/reporters.py
- python/grass/gunittest/utils.py
This is similar to what `coverage html` does when creating an html report. It adds a .gitignore file with a single star, that ignores all the files in that directory, preventing to show up as added files with git. It’s useful for contributors, preventing to accidentally commit the test report folders.
I limited calling that new function to a single place, the one that is normally used in CI (and me locally). The potential places that this new function be called is right after every time ensure_dir() is called (about 4, but only this one had the effect I expected).
I extracted this from my work to add coverage on gunittest (Ubuntu), that works locally but just now on CI (after 50 back-and-forths).
> tests: Add .gitignore to gunittest testreport folder if not present

- display/d.labels/do_labels.c
This pull request addresses multiple warnings identified by cppcheck related to potential buffer overflow issues.
**Issues:**
1. do_labels.c:87:13: warning: sscanf() without field width limits can crash with huge input data. [invalidscanf]
sscanf(text, "%*s %s", buff);
2. do_labels.c:97:13: warning: sscanf() without field width limits can crash with huge input data. [invalidscanf]
sscanf(text, "%*s %s", buff);
3. do_labels.c:101:13: warning: sscanf() without field width limits can crash with huge input data. [invalidscanf]
sscanf(text, "%*s %s", buff);
4. do_labels.c:105:13: warning: sscanf() without field width limits can crash with huge input data. [invalidscanf]
sscanf(text, "%*s %s", buff);
5. do_labels.c:118:17: warning: sscanf() without field width limits can crash with huge input …
> d.labels: Fix buffer overflow issues in do_labels.c

- configure
- configure.ac
- include/grass/config.h.in
- include/grass/defs/gis.h
- lib/gis/strlcpy.c
From commit message:
> This commit introduces a new G_strlcpy function in lib/gis, inspired by
> G_asprintf. G_strlcpy provides a safer alternative to strcpy and strncpy,
> with consistent behavior across different systems.
> 
> Key points:
> - Implements strlcpy functionality, available natively on BSD systems
> - Portable implementation for non-BSD systems (excluding Linux with libbsd)
> - Based on FreeBSD's implementation:
>   https://github.com/freebsd/freebsd-src/blob/98dd639c94f716858ae29958f484729b1d2fd387/sys/libkern/strlcpy.c#L28
> - Designed to replace unsafe uses of strcpy and strncpy throughout the project
> 
> The function is implemented to use the native strlcpy where available,
> falling back to our portable version on systems without it. This ensures
> optimal performance …
> lib/gis: Add portable G_strlcpy function
