- .github/workflows/python-code-quality.yml
Following @ldesousa’s message for #3903 https://matrix.to/#/!BOjyJgENYOLyXbRKxO%3Agitter.im/%24WJLQLw0paLT9URnQRpv7LutALr-5tJeGuGRt0uu-jns,
this PR runs ruff two times:
1. Without fixing anything, but the GitHub output format so a certain number of annotations will be added to the files (somewhere between 10 or 20, GitHub’s UI limits them). Continue on error is set to true, so the next step (that can fail) will be executed.
2. Applying the fixes, but removing the GitHub output format, using the default output format, so there shouldn’t be duplicate annotations for unfixable issues (unless ruff outputs GitHub annotations by itself when running in GitHub Actions).
Since running ruff takes negligible time, running two times isn’t problematic. 
This would allow to show a bit more explications …
> CI(ruff): Show ruff annotations even for fixes

- lib/vector/Vlib/buffer2.c
The true if-statement only handles buffers with rounded corners. E.g. using `v.buffer` without `-s` on points. GEOS handles buffers with corners.
Building with Clang 18 a compiler warning is issued:
```
buffer2.c:1153:15: error: '||' of a value and its negation always evaluates to true [-Werror,-Wtautological-negation-compare]
1153 |     if (round || (!round)) {
|         ~~~~~~^~~~~~~~~~~
```
which in combination with `-Werror` causes build failure.
(Part of preparation for upgrading dependencies for the macOS CI runner).
> lib/vector: fix always true if-condition in Vect_point_buffer2()

- python/grass/pydispatch/PKG-INFO
- python/grass/pydispatch/__init__.py
- python/grass/pydispatch/dispatcher.py
- python/grass/pydispatch/robustapply.py
- python/grass/pydispatch/saferef.py
Manual combination of latest changes of repo https://github.com/mcfletch/pydispatcher
Once black is applied, the actual diff isn't really big. Their repo layout seemed to have changed a big, but I went and copied the (relevant-only) files one by one. It isn't a very active project, but still.
This is the best approach I could think of that would make our vendored dependency get updated, considering they don't really have (newer) releases, and we have some more files that extend the original code like https://github.com/OSGeo/grass/blob/ff453d215a3244644ef207f2d5d065f680016da0/python/grass/pydispatch/signal.py
> grass.pydispatch: Apply code changes from upstream pydispatcher repo

- imagery/i.ortho.photo/i.ortho.photo/menu.c
This issue was identified by coverity scan (CID: 1415632).
Initially cppcheck was used on imagery folder and all uninitialized variables were resolved but this issue was missed by cppcheck.
Initialized the tosystem array with an empty string (char tosystem[99] = "";).
> i.ortho.photo: Fix uninitialized variable and potential buffer overflow

- raster/r.out.mpeg/main.c
This pull request addresses buffer overflow issues identified by flawfinder in the `main.c` file of the `r.out.mpeg` module. Specifically, the `sprintf` function calls have been replaced with the safer `snprintf` function.
Issues:
main.c:399:  [4] (buffer) sprintf:
Does not check for buffer overflows (CWE-120).
main.c:400:  [4] (buffer) sprintf:
Does not check for buffer overflows (CWE-120).
main.c:401:  [4] (buffer) sprintf:
Does not check for buffer overflows (CWE-120).
Changes:
Replaced `sprintf` with `snprintf` at lines 399, 400, and 401 to prevent potential buffer overflows.
> r.out.mpeg: Fix buffer overflow issues by replacing sprintf with snprintf 

- raster/r.path/main.c
This pull request addresses several potential buffer overflow issues in the r.path module by replacing instances of strcpy with strncpy.
The issue is identified by both Coverity scan (CID :1415799) and by flawfinder
> r.path: Fix buffer overflow check issue

- include/grass/defs/vector.h
- lib/vector/Vlib/geos_to_wktb.c
GEOS 3.12 switched the default setting of the trim option to true. To enable consistent behaviour to `Vect_read_area_to_wkt()` and `Vect_line_to_wkt()` across GEOS versions, they now call new 2nd generation functions, which set this trim option explicitly to false.
Closes: #4117 #4118
> lib/vector: new functions for setting trim of GEOS WKT output

- python/grass/pygrass/raster/rowio.py
Please see the comment [here](https://github.com/OSGeo/grass/pull/3928#discussion_r1685058517).
Initially, the PR was about fixing "ambiguous variable name 'l', but in this case 'l's were also unused so deletion was the initial fix. However, it appears Windows has a "ctypes" issue.
I would like to revert them as they were, but rename "l"s to avoid the E741 (Checks for the use of the characters 'l', 'O', or 'I' as variable names) issue. Since I couldn't figure out what "l" parameters are so I renamed it "l_what" for now. Let me know if you find appropriate variable name. Here is [pygrass.raster package documentation](https://grass.osgeo.org/grass83/manuals/libpython/pygrass.raster.html#module-pygrass.raster.rowio).
However, the flake8 problem in F841 (unused-variable) will be addressed …
> grass.pygrass: remove unused arg in ctypes.CFUNCTYPE

- docker/alpine/Dockerfile
This PR fixes issue raised by https://github.com/OSGeo/grass/pull/3899#issuecomment-2266134209
```py
File "/usr/local/bin/grass", line 2551, in <module>
main()
File "/usr/local/bin/grass", line 2222, in main
find_grass_python_package()
File "/usr/local/bin/grass", line 2207, in find_grass_python_package
raise RuntimeError(
RuntimeError: The grass Python package is missing. Is the installation of GRASS GIS complete?
```
Python package is not found because GISBASE is defined to `/usr/local/grass85` but this path doesn't exists.
> docker: define GISBASE for Alpine

- gui/wxpython/core/giface.py
- gui/wxpython/dbmgr/base.py
- gui/wxpython/dbmgr/dialogs.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/gmodeler/dialogs.py
- gui/wxpython/gmodeler/model.py
- gui/wxpython/gui_core/dialogs.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/widgets.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/iscatt/iscatt_core.py
- gui/wxpython/mapdisp/properties.py
- gui/wxpython/mapswipe/frame.py
- gui/wxpython/mapswipe/toolbars.py
- gui/wxpython/modules/import_export.py
- gui/wxpython/nviz/mapwindow.py
- gui/wxpython/photo2image/ip2i_manager.py
- gui/wxpython/psmap/dialogs.py
- gui/wxpython/psmap/instructions.py
- gui/wxpython/rlisetup/wizard.py
- gui/wxpython/vdigit/dialogs.py
- gui/wxpython/vdigit/preferences.py
- pyproject.toml
- python/grass/pygrass/raster/history.py
- python/grass/pygrass/vector/geometry.py
- python/grass/pygrass/vector/testsuite/test_geometry.py
- python/grass/temporal/abstract_map_dataset.py
- python/grass/temporal/testsuite/unittests_temporal_raster_algebra_spatial_topology.py
Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-placeholder/
Even a docstring is enough to not need a placeholder, as it is a statement.
39 instances fixed.
> style: Fix unnecessary-placeholder (PIE790)

- imagery/i.smap/multialloc.c
**Issue:** Sizeof not portable issue identified by coverity scan
This pull request resolves a sizeof mismatch issue identified by Coverity Scan (CID 1208214) in the memory allocation logic of the multialloc function.
Replaced the use of sizeof(char **) with sizeof(char *) to ensure correct and portable memory allocation.
> i.smap: fix sizeof not portable issue

- imagery/i.aster.toar/main.c
fix: Replace sprintf with snprintf to prevent buffer overflow
- Replaced all occurrences of `sprintf` with `snprintf` to ensure buffer sizes are not exceeded.
- This fixes issues reported by flawfinder related to potential buffer overflows.
Issue:
./main.c:168:  [4] (buffer) sprintf:
Does not check for buffer overflows (CWE-120). Use sprintf_s, snprintf, or
vsnprintf.
> i.aster.toar: Fix buffer overflow check issue

- python/grass/temporal/abstract_space_time_dataset.py
Calling ` get_registered_maps_as_objects` may fail, depending on the arguments provided. This PR backports a fix in how the underlying ` get_registered_maps` method is called.
See also: #3798
> abstract_space_time_dataset: use keyword arguments in calls to get_registered_maps

- display/d.text/test.py
- gui/wxpython/nviz/mapwindow.py
- gui/wxpython/psmap/frame.py
- gui/wxpython/psmap/instructions.py
- gui/wxpython/vdigit/toolbars.py
- gui/wxpython/web_services/widgets.py
- man/build_html.py
- pyproject.toml
- python/grass/gunittest/runner.py
- python/grass/pygrass/modules/grid/grid.py
- scripts/r.in.wms/srs.py
Ruff rule: https://docs.astral.sh/ruff/rules/parenthesize-chained-operators/
14 instances fixed
Some changes are continuations of #4055, like for web_services/widgets.py:
https://github.com/OSGeo/grass/pull/4055/files#diff-609b60828c5ebf25e54baf62e63b945705831a5849bc5d3e5e8e5ba302e11d62
> style: Fix parenthesize-chained-operators (RUF021)

- raster/r.out.mpeg/main.c
- raster/r.out.mpeg/write.c
This pull request addresses a potential buffer overflow issue in the r.out.mpeg module by replacing the strcpy function with strncpy.
The issue is identified by both coverity scan (CID:1415777) and by flawfinder.
> r.out.mpeg: Fix potential buffer overflow issue

- lib/vector/diglib/frmt.c
This pull request addresses the potential buffer overflow issues by replacing all instances of strcpy with G_strlcpy.
> lib/vector: Replaced strcpy with G_strlcpy

- raster/r.in.xyz/main.c
This pull request addresses the uninitialized variable issue identified by Coverity Scan (CID: 1547103). This issue was not detected by cppcheck but was flagged by Coverity Scan.
The variable linesize is used in a division operation. The fix ensures that if linesize is less than 6, it is assigned a value of 6, thus avoiding any potential division by zero errors.
> r.in.xyz: Fix Uninitialized variable in main.c file

- temporal/t.rast.accumulate/t.rast.accumulate.py
Seems like a copy-paste artifact from another module like t.rast.accdetect
See https://github.com/OSGeo/grass/pull/4137#discussion_r1707325256 and the thread
> t.rast.accumulate: Remove check of non-existing `range` option

- doc/notebooks/jupyter_tutorial.ipynb
This PR adds documentation to `jupyter_tutorial.ipynb` for the new features developed during GSoC 2024, providing an overview of their functionality. The documented features include:
1. In `grass.jupyter.InteractiveMap()`: 
- A button for querying data (ℹ️)
- A button for displaying and editing the computational region (◻️)
- A button for drawing simple vector geometries (🖉)
2. Parallelization in `grass.jupyter.TimeSeriesMap()` and `grass.jupyter.SeriesMap()`: 
- Example of adjusting the number of cores and performing parallelization.
> grass.jupyter: Add documentation of InteractiveMap Features and Parallelization in jupyter_tutorial.ipynb

- gui/wxpython/history/tree.py
This PR addresses several interconnected enhancements that have been linked into a single PR:
1. Command Ordering:
Commands are now ordered from newest (at the top) to oldest. Originally, they were not sorted - there was not mechanism for that.
2.  Node Refresh Optimization:
-   Replaces the method` _refreshTree()`, which only refreshed and sorted day nodes, with `_reloadNode()`, which reloads and sorts both day nodes and command nodes.
-   When a node is updated with new information (after a command run finishes), the update is made directly to the node's attributes. Previously, the node was removed and re-added, which caused delay. Refreshing and sorting are now made through new methods in the new `HistoryTreeModel` .
3.  Refactoring:
Necessary refactoring to support the changes in …
> wxGUI/history: Order commands by time and optimize node refresh

- python/grass/temporal/datetime_math.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/bad-chained-comparison.html
It seems that from this commit, https://github.com/OSGeo/grass/commit/e2188758f6cc424d887b397faff247cc396aa6ea, it is simply a typo, forgetting to remove  `> 0` after the find().
There's also a copy pasted comment below that should be adapted
> style: Fix Pylint bad-chained-comparison / W3601

- scripts/v.db.reconnect.all/v.db.reconnect.all.py
- scripts/v.unpack/v.unpack.py
- vector/v.fill.holes/tests/conftest.py
(replaces #4175)
Fixes message
```bash
WARNING: Please update the usage of <v.db.connect>: flag <o> has been
renamed to <--overwrite>
```
> style: use overwrite and not 'o' flag in Python scripts

- gui/wxpython/gui_core/forms.py
- gui/wxpython/rdigit/g.gui.rdigit.py
Fixes #4166, something must have changed in the pydispatch library, it looks like before it ignored if the handler didn't have all the parameters.
> wxGUI: fix mapCreated signal handling

- .github/workflows/macos.yml
Also remove homebrew from `/opt/homebrew`, which is the default location for homebrew on apple arm machines (which currently is the case for our CI runner).
> CI: also remove /opt/homebrew from macOS runner

- raster/r.terraflow/unionFind.h
**Description**
This pull request addresses two issues in `r.terraflow/unionFind.h` related to the use of `realloc` for memory reallocation. The changes ensure that memory is properly handled when `realloc` fails.
**Issues**
```
raster/r.terraflow/unionFind.h:129:9: error: Common realloc mistake: 'parent' nulled but not freed upon failure [memleakOnRealloc]
parent = (T *)realloc(parent, 2 * maxsize * sizeof(T));
^
raster/r.terraflow/unionFind.h:133:9: error: Common realloc mistake: 'rank' nulled but not freed upon failure [memleakOnRealloc]
rank = (T *)realloc(rank, 2 * maxsize * sizeof(T));
```
- Added temporary variables to store the results of `realloc` for `parent` and `rank`.
- Included checks to ensure that `realloc` succeeded before updating the original pointers. …
> r.terraflow: Handle memory reallocation errors gracefully

- utils/grass_clang_format.sh
To keep `./utils/grass_clang_format.sh` shell script in sync with pre-commit configuration, the ClangFormat version is taken from `.pre-commit-config.yaml`.
> utils: sync grass_clang_format script to pre-commit config

- flake.lock
- package.nix
- CI(deps): Lock file maintenance
- nix: fix build by using libxml2 with http support
Related nixpkgs PR:
https://github.com/NixOS/nixpkgs/pull/331118
> nix: fix build by using libxml2 with http support

- raster/r.object.geometry/Makefile
- raster/r.object.geometry/main.c
- raster/r.object.geometry/r.object.geometry.html
- raster/r.object.geometry/testsuite/test_r_object_geometry.py
Use parson to add json support to r.object.geometry. The JSON output looks like as follows:
```json
[
{
"category": 27518,
"area": 54,
"perimeter": 40,
"compact_circle": 1.5355295532059356,
"compact_square": 0.73484692283495345,
"fd": 1.8495247341090328,
"mean_x": 631611.11111111112,
"mean_y": 220648.14814814815
},
{
"category": 27529,
"area": 57,
"perimeter": 36,
"compact_circle": 1.3451172460704992,
"compact_square": 0.83887049280786108,
"fd": 1.772672742164326,
"mean_x": 643460.52631578944,
"mean_y": 217232.45614035087
},
{
"category": 27605,
"area": 9,
"perimeter": 16,
"compact_circle": 1.5045055561273502,
"compact_square": 0.75,
"fd": 2.5235914062700342,
"mean_x": 640916.66666666663,
"mean_y": 226527.77777777778
},
{
"category": 27608,
"area": 17,
"perimeter": 24,
"compact_circle": …
```
> r.object.geometry: add json support

- scripts/g.download.location/g.download.location.html
- scripts/g.download.location/g.download.location.py
To be less obscure in case the target location directory already exists:
```
ERROR: Location named <nc_spm_full_v2alpha2> already exists, download
canceled
```
this PR improves the error message to include the path:
```
g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz path=$HOME
ERROR: Location named <nc_spm_full_v2alpha2> already exists in
</home/mneteler/nc_spm_full_v2alpha2>, download canceled
```
This is esp. relevant for scripted usage when the command isn't invoked directly by the user.
In addition, section  of **EXAMPLES** added.
> g.download.location: Print target path in error message

- gui/wxpython/core/gconsole.py
imp library was dropped in Python 3.12, it's only used in one place in gui and I fixed it based on [Python documentation](https://docs.python.org/3/whatsnew/3.12.html#imp). I tested it.
> gui: replace python imp library with importlib for python 3.12

- gui/wxpython/datacatalog/infomanager.py
The startup message for first-time users refers to the old Locations. This should be changed to Projects to match the new naming used in 8.4+.
> startup: Change Location to Project in first-time user messages

- .github/workflows/macos.yml
- .github/workflows/test_thorough.bat
- .github/workflows/test_thorough.sh
- scripts/Makefile
- scripts/g.download.location/g.download.location.html
- scripts/g.download.location/g.download.location.py
- scripts/g.download.project/Makefile
- scripts/g.download.project/g.download.project.html
- scripts/g.download.project/g.download.project.py
To continue with the location to project renaming, this PR is renaming g.download.location to g.download.project. For backwards compatibility I left g.download.location that calls g.download.project.
My suggestion is to add a warning to g.download.location in/after 8.5 and remove it completely for GRASS 9.
> g.download.project: rename g.download.location

- .github/workflows/macos.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pytest.yml
- .github/workflows/ubuntu.yml
Enables to print all occurrences of warnings, and shows all warnings.
Addresses the additional idea expressed in #4203 of showing other warnings.
> CI(python): Enable printing of all Python warnings with PYTHONWARNINGS

- .github/workflows/pytest.yml
Also replace Python 3.8 by Python 3.9 to keep 3 versions tested.
Closes #4203
> CI(pytest): Run pytest tests with Python 3.13

- raster/r.out.png/main.c
This patch fixes two issues:
1. In one of the code paths, we are calling fclose on a file pointer which could potentially be NULL. Doing that would lead to undefined behavior. Check if a file pointer is NULL before closing it.
2. If we call fclose on same file pointer twice, in the second instance we could be closing file descriptor allocated to some other file, which typically happens to a freed descriptor.
This issue was found by using cppcheck tool.
2. Tool used in finding this error: cppcheck
Tool's output after applying the patch
3. Reproduction rate: 100%, reproducible every time.
4. Architecture: Not specific to any underlying architecture.
> r.out.png: fix consecutive fclose calls on same pointer

- .github/workflows/macos_install.sh
- include/grass/la.h
- lib/db/sqlp/sqlp.l
- raster/r.report/global.h
- raster/r.report/prt_json.c
Address `-Wstrict-prototypes` warnings and make CI macOS runner fail in new cases.
> lib: fix missing prototypes

- .flake8
- python/grass/temporal/abstract_space_time_dataset.py
- python/grass/temporal/datetime_math.py
- python/grass/temporal/open_stds.py
- python/grass/temporal/temporal_algebra.py
- python/grass/temporal/temporal_granularity.py
- python/grass/temporal/temporal_raster_base_algebra.py
- python/grass/temporal/temporal_vector_algebra.py
The following are fixes for Flake8 F841 (local variable assigned to but never used) in the python/grass/temporal directory.
In order to fix the F841 problem I deleted unused variable assignments, but I left the module declarations alone since the module itself assigns global or class variables. In this way, I was able to maintain the existing code structure while fixing the Flake8 issues. However, please check that any module declarations are unnecessary.
> Checks: fix Flake8 F841 (local variable assigned to but never used) in python/grass/temporal

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .markdownlint.yml
Based on discussion in #4197, I used the [questions-answers](https://github.com/stevemao/github-issue-templates/blob/master/questions-answers/PULL_REQUEST_TEMPLATE.md) template with small modifications.
I would like to keep the second level of headings to not have too giant font, but that interferes with the markdownlint [style](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md041.md), @echoix any opinion?
> contributing: add PR template

- lib/init/grass.py
I explicitly don't want readfile and writefile to be changed in the same PR.
I don't see any coverage (pytest from here, nor gunittest from my fork (too slow to be used allways)), that runs into the init script. So the approach is to leave it for some time before changing.
The readfile function is only used inside that file, 10 references, in functions like `create_gisrc()`, `set_mapset()`, `load_env()`, `csh_startup()`, `sh_like_startup()`, `classic_parser()`.
If it were to have an impact, we should see it easily. 
I seriously don't think there are any difference, as Pathlib's `read_text()` function is really simple to understand, so I'm including it here for reference when reviewing my similar PRs:
> ```python
>     def read_text(self, encoding=None, errors=None, newline=None):
> …
```
> init: Use pathlib Path.read_text for readfile in the main executable

- python/grass/temporal/core.py
Reads the whole file using a context manager internally.
It is fixing ResourceWarnings, some [SIM115](https://docs.astral.sh/ruff/rules/open-file-with-context-handler/) and some [PTH118](https://docs.astral.sh/ruff/rules/os-path-join/).
In the spirit of https://github.com/OSGeo/grass/pull/4224#discussion_r1731736845, this is a small, easy to review change.
Except for the changes in upgrade_temporal_database, and the else (postgresql instead of sqlite) at the end of create_temporal_database(), changes are covered at least 3 times by each pytest version, and unknown number of times with gunittest. Pytest tests touching these are:
```
python/grass/jupyter/tests/seriesmap_test.py::test_default_init|setup
python/grass/jupyter/tests/timeseriesmap_test.py::test_collect_layers|setup …
```
> grass.temporal.core: Replace open file + read with pathlib.Path's read_text()

- gui/wxpython/history/tree.py
When running a command in a new mapset with no prior history, I was getting a traceback, and similarly when removing command from history when there was a single command. This was introduced in 02e45e93a when trying to avoid calling complete tree refresh every time.
> wxGUI: fix adding and removing from history for new mapset

- gui/wxpython/startup/locdownload.py
Update link to latest natural earth sample dataset, see #4172 and https://github.com/OSGeo/grass-website/issues/454
@neteler, not sure if this is the only place to change the URL, and if I have done it correctly, but to give it a start
> wxGUI: Update link to the Natural Earth sample dataset

- python/grass/jupyter/interactivemap.py
The users input wasn't getting checked here causing the query to fail if the user defined the `width` parameter as a string.
The code below would render the map and fail when the query_vector tried to return.
```
m = gj.InteractiveMap(width="500", map_backend="ipyleaflet")
```
> grass.jupyter: Ensure width and height in InteractiveMap are integers 

- raster3d/r3.showdspf/main_ogl.c
In the current execution, when we face an error while trying to open a database file, as part of error log we are dereferencing a NULL file pointer (which is returend when we try to open a file and error out). Ideally we should be printing the name of the database file rather than the file pointer. This fixes the problem of null pointer dereference.
Output from cppcheck tool:
Output from cppcheck with the fix applied:
3. Architecture: Not specific to any underlying architecture.
> r3.showdspf: fix null pointer dereference when opening database file

- raster3d/r3.showdspf/get_color_ogl.c
color2 pointer is not initialized and it is assigned a value depending on a conditional.
```
for (curr = 1; ctable[curr].color[0] >= 0; curr++) {
cat2 = ctable[curr].data;
color2 = ctable[curr].color;
if (cat2 > cat) {
delta = (cat - cat1) / (cat2 - cat1);
color[0] = delta * color2[0] + (1 - delta) * color1[0];
color[1] = delta * color2[1] + (1 - delta) * color1[1];
color[2] = delta * color2[2] + (1 - delta) * color1[2];
return;
}
cat1 = cat2;
color1 = color2;
```
Potentially, in an execution path if conditional fails and we do not enter the for loop above, we would be accessing an uninitialized pointer after this loop, whose behavior is undefined. Initialize the pointer to NULL to avoid this.
This issue was found by using cppcheck tool.
1. Machine used: Virtual …
> r3.showdspf: fix accessing uninitialized pointer

- lib/init/grass.py
Paired PR of https://github.com/OSGeo/grass/pull/4234. https://github.com/OSGeo/grass/pull/4234 should be merged, then solving the upcoming merge conflict as both PRs added the pathlib import, then this PR can be considered to merge. I want to make sure that we could catch differences in new/old behaviour, that wouldn't be possible if we changed the input and output functions at the same time.
Like https://github.com/OSGeo/grass/pull/4234, this file isn't visible in my code coverage at the moment.
The `writefile()` function is used 4 times, all in the same file.
> init: Use pathlib Path.write_text for writefile in the main executable

- python/grass/temporal/stds_import.py
Similar changes for stds_export are not in this PR by purpose. During the weekend, I had made a mistake in stds_export somewhere and didn't find it, but the mismatch in lengths of init file vs list file in stds_import, that wasn't touched yet. That's why I insist so much on separating input/output in different PRs.
<details><summary>Details on a failing test saved because stds_import and stds_export weren't changed together</summary>
<p>
</p>
</details> 
In the spirit of https://github.com/OSGeo/grass/pull/4224#discussion_r1731736845, this is only fixes the part where a context manager can be avoided.
See PR description of https://github.com/OSGeo/grass/pull/4234 for an illustration of the implementation of read_text() and write_text()
> grass.temporal.stds_import: Use pathlib Path.read_text and Path.write_text for proj string

- vector/v.external.out/list.c
Currently, if 'HAVE_OGR' macro is defined, as part of execution, we sort all formats by name using qsort. But, array containing all formats is assigned based on a conditional and if the conditional fails, it can be NULL.
Behavior of qsort when a NULL array is provided is undefined. To avoid getting into that situation, check if the array is NULL before performing qsort on it.
This issue was found by using cppcheck tool.
3. Should only be valid, when 'HAVE_OGR' flag is specified as part of the compilation process.
4. Output from cppcheck prior to fix
After the fix
> v.external.out: Check for valid array before passing it to qsort

- lib/display/cnversions.c
[display lib], along with minor debug message whitespace tweaks
Display pixels or raster region rows,cols are likely be on the order of 500, while projected map units are often in the millions, so pixels/meter factor can end up as a very small number. This patch edits an unused in the production code debug helper function to not round that division into a confusing 0.0, as well as some whitespace tweaks to make it more readable.
> lib/display: D_show_conversions() %.1f to %g where values likely to be smaller than 0.0

- docker/ubuntu_wxgui/Dockerfile
Add `libgtk-3-dev` to address:
```
...
checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
```
For the usage, also install `python3-wxgtk4.0`.
> docker: fix missing libraries in ubuntu wxgui Dockerfile

- imagery/i.topo.corr/main.c
- lib/gis/color_rules.c
- lib/gis/parser.c
- lib/gis/parser_wps.c
- lib/gis/snprintf.c
- lib/gis/timestamp.c
- lib/imagery/loc_info.c
- lib/init/clean_temp.c
- lib/temporal/lib/default_name.c
- raster/r.colors/edit_colors.c
- raster/r.external/main.c
- raster/r.geomorphon/main.c
- raster/r.geomorphon/profile.c
- raster/r.in.gdal/main.c
- raster/r.in.pdal/main.cpp
- raster/r.reclass/reclass.c
- raster/r.sim/simlib/output.c
- raster3d/r3.in.ascii/main.c
- raster3d/r3.out.ascii/main.c
- raster3d/r3.out.bin/main.c
- raster3d/r3.out.netcdf/main.c
- vector/v.what.rast3/main.c
Beginning with UCRT in Visual Studio 2015 and Windows 10, the behaviour of `snprintf()` (and `vsnprintf()`) is now C99 standard conformant ([source](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=msvc-140#remarks)).
Thus, the output is now always null-terminated. The justification for an internal fix for that is no longer needed.
I should add that the code base is already using snprintf() in a number of places.
> lib: deprecate G_snprintf() and replace with C99 snprintf()

- .flake8
- gui/wxpython/dbmgr/base.py
- gui/wxpython/dbmgr/dialogs.py
- gui/wxpython/dbmgr/sqlbuilder.py
- gui/wxpython/dbmgr/vinfo.py
Flake8 F841 (local variable assigned to but never used) fixes in the `gui/wxpython/dbmgr` directory. 
- [Bug] Fix currently ignored Flake8 warnings [#1522](https://github.com/OSGeo/grass/issues/1522)
The GUI worked fine when I briefly tested it.
Removed unused variables and lines to fix F841.
> checks: Flake8 F841 fixes in the wxpython directory part 2

- ps/ps.map/ps_header.c
Currently, `cats_ok` variable is only set when `do_raster` is true in post script structure. Variable can be filled with any value as it it uninitiazlied which can lead to unpredictable behavior. Set the value to 0 indicating error by default.
3. Output from cppcheck prior to fix:
After the fix:
> ps.map: Initialize variable before using it in conditional

- .flake8
- scripts/r.semantic.label/r.semantic.label.py
- scripts/v.import/v.import.py
- scripts/v.report/v.report.py
- scripts/v.unpack/v.unpack.py
Flake8 F841 (local variable assigned to but never used) fixes in the `scripts` directory.
- [Bug] Fix currently ignored Flake8 warnings [#1522](https://github.com/OSGeo/grass/issues/1522)
**v.semantic.label**
Removed unused `as e` from `except`.  I don’t see this type of fix cause any issues. However, I tested with testsuit and all passed. 
**v.import**
Removed unused `tgtsrs` value assignment and left `gs.read_command("g.proj", flags="j", quiet=True)`.
With the GUI, I tried importing the data/all_types.gpkg and data/all_types_wgs84.gpkg files and encountered no errors. 
Testsuit `test_import_gpkg_wgs84` failed for `self.assertVectorFitsRegionInfo`. I don't see how this …
> checks: Flake8 F841 fixes in the scripts directory part 2

- raster/r.out.png/main.c
This patch continues the work from 917ba58. It's a good practice to immediately reset the file pointer once we do fclose on it, as it prevents using/closing descriptor allocated to another file in the future execution paths.
> r.out.png: reset file pointer to NULL after fclose

- python/grass/temporal/stds_export.py
This PR is the stds_export counterpart of #4236.
> grass.temporal.stds_export: Use pathlib Path.read_text and Path.write_text

- .flake8
- scripts/d.polar/d.polar.py
- scripts/r.in.wms/wms_cap_parsers.py
- scripts/r.in.wms/wms_gdal_drv.py
Flake8 F841 (local variable assigned to but never used) fixes in the `scripts` directory, specifically, `d.polar` and `r.in.wms`.
- [Bug] Fix currently ignored Flake8 warnings [#1522](https://github.com/OSGeo/grass/issues/1522)
- **d.polar**: Tested with *test_d_polar.py* and all passed.
- **r.in.wms**: Since this tool doesn't have gunittest, I tested with GUI entered parameters following. Test was successful.
```r.in.wms url="https://tiles.maps.eox.at/wms?" layers=s2cloudless output=sentinel2 format=png```
Delete unused variables and entire variable declarations.
[pre-defined …
> checks: flake8 F841 (local variable assigned to but never used) fixes in scripts directory part 1

- vector/v.external/list.c
Currently, if 'HAVE_OGR' macro is defined, as part of execution, we order all formats by name using qsort. But, list containing all formats is assigned based on a conditional and if the conditional fails, it can be NULL.
Behavior of qsort is undefined when a NULL ptr is passed as array argument. To avoid getting into that situation, check if the array is NULL before performing qsort on it.
3. Should only be valid, when 'HAVE_OGR' flag is specified as part of the compilation process.
4. Output from cppcheck prior to fix:
After the fix:
> v.external: Check for valid list before passing to qsort

- raster/r.univar/r.univar_main.c
With MASK openmp parallelization can crash. The check for MASK was not in the right place.
> r.univar: fix MASK check with nprocs > 1

- vector/v.out.ogr/list.c
Currently, filling list with GDAL driver names is based on a conditional and if the conditional fails, the list can be NULL.
We pass this list to qsort to sort the names, but behavior of qsort with a NULL array is undefined. To avoid getting into this situation, check if the array is NULL before performing qsort on it.
3. Output from cppcheck prior to fix
After the fix
> v.out.ogr: Check for valid array before passing to qsort

- vector/v.vol.rst/user2.c
`skip_point` structure is not initialized when declared.
1. Only when `cv` is true, `skip_point` contents are filled and the structure is used.
2. cppcheck raised the issue when `cv` is false. Technically, we don't need `skip_point` in such cases and not initializing it won't affect the execution. Nevertheless, it's a good practice to initialize structure contents at the time of declaration.
3. Output from cppcheck prior to fix
After the fix:
> v.vol.rst: Initialize structure contents before passing it around

- vector/v.generalize/smoothing.c
Currently, in `head` which is a `POINT_LIST` structure, we are only initializing the next pointer to NULL, but data present in the point substructure is not initialized which implies that it would be filled with random data. To avoid such scenario, initialize point coordinates to zero.
3. Output from cppcheck prior to fix
After the fix
> v.generalize: Initialize all of structure contents before using it

- temporal/t.rast.accumulate/t.rast.accumulate.py
The printing looks like a leftover from some debugging, I believe it can be safely removed.
> t.rast.accumulate: remove printing

- .flake8
- utils/gitlog2changelog.py
This PR fixes the flake8 error in `utils/gitlog2changelog.py`. It addresses the E712 and E722 errors which are related to bare except clauses. I have put in Exception as blanket statement. If need be, I can also detail particular errors which might be related. I haven't yet because this might also miss out on some exceptions which are not detailed.
> CI: Resolve flake8 issues in utils directory

- .flake8
- lib/init/grass.py
This pull request addresses several Flake8 warnings and improves exception handling in the GRASS GIS initialization script. The changes focus on removing unused variables and replacing bare except clauses with more specific exception handling.
1. Removed unused 'e' variables in exception handling for locale errors.
2. Improved exception handling when reading the VERSIONNUMBER file.
In the locale setting section, removed `as e` from two `except locale.Error` clauses where the error variable was not being used.
```python
except locale.Error as e:
except locale.Error:
> CI: Update .flake8 configuration and fix flake8 errors in lib/init/grass.py

- db/drivers/sqlite/db.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1501211).
> lib/db: Fix copy into fixed size buffer issue in SQLite driver

- .flake8
- temporal/t.rast.what/t.rast.what.py
- temporal/t.vect.algebra/t.vect.algebra.py
Flake8 F841 (local variable assigned to but never used) fixes in the `temporal` directory.  Two declarations of unused functions were deleted.  
- [Bug] Fix currently ignored Flake8 warnings [#1522](https://github.com/OSGeo/grass/issues/1522)
I've tested them with the gunittest tool in the tool folder.
Two declarations of unused functions were deleted.  
I was initially instructed to use 'Checks' for the PR title, however, if any cases need to be changed, please let me know since it isn't listed in `release.yml`.
> Checks: flake8 F841 (local variable assigned to but never used) fixes in the temporal directory

- .flake8
- man/build_check.py
- man/build_check_rest.py
- man/build_class.py
- man/build_class_rest.py
- man/build_full_index.py
- man/build_full_index_rest.py
- man/build_index.py
- man/build_index_rest.py
- man/build_keywords.py
- man/build_topics.py
- utils/gitlog2changelog.py
This PR addresses several linter errors related to wildcard imports and improves overall code quality in multiple Python scripts within the project. The main focus was on resolving F403 and F405 errors, which are related to the use of wildcard imports and potential undefined names.
- Replaced wildcard import with specific imports from `build_html`.
- Removed bare except clauses with Exception keyword
1. **Resolving linter errors**: The primary motivation was to address F403 and F405 errors. These errors indicate potential issues with undefined names due to wildcard imports.
2. Where applicable, string formatting was updated to use f-strings, which are more readable and efficient in Python 3.
These changes do not alter the functionality of the scripts. They purely focus on code quality …
> CI: Fix Flake8 linter errors in man/ directory

- doc/development/style_guide.md
This PR adds relevant info from https://trac.osgeo.org/grass/wiki/Submitting/C as mentioned [here](https://github.com/OSGeo/grass/pull/4307#discussion_r1756980867). I left out some subsections from it, because I was not sure whether they are relevant, for example [note about void functions](https://trac.osgeo.org/grass/wiki/Submitting/C#Void).
I also added missing info about the python addon template and header.
> contributing: update style guide for C

- ps/ps.map/do_scalebar.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1208259).
> ps.map: Fix copy into fixed size buffer issue in do_scalebar.c file

- configure
- configure.ac
- include/grass/config.h.in
- include/grass/defs/gis.h
- lib/gis/strlcat.c
Add wrapper function for [`strlcat()`](https://pubs.opengroup.org/onlinepubs/9799919799/functions/strlcat.html), using system function if available, otherwise uses implementation by Todd C. Miller originated from https://github.com/openbsd/src/blob/e291b8af02e5c2b53d7ddb1f0c9c0fd608b97d45/lib/libc/string/strlcat.c.
`G_strlcat()` is a safer alternative to `strcat()`.
(See also https://www.openbsd.org/papers/strlcpy-paper.pdf).
strlcpy and strlcat are added to [GNU C Library version 2.38](https://lists.gnu.org/archive/html/info-gnu/2023-07/msg00010.html).
> lib/gis: Add portable G_strlcat function

- vector/v.in.dwg/main.c
Currently, one instance of sprintf has same variable as parameter and destination in sprintf. This scneario leads to undefined behavior in C.
```
sprintf(buf, _("%s Cannot open %s"), buf, path);
```
Modify the code to:
1. Write initial error string using snprintf() onto the buffer. Using snprintf() makes sure that we stay within the buffer size and avoid overflow errors.
2. Use snprintf() again to write another error string at the end of previous error string in the same buffer. We again use snprintf() to make sure we are not overflowing the buffer with data.
Prior to fix:
After fix:
3. Architecture: Not specific to …
> v.in.dwg: Avoid using same variable as parameter and destination in sprintf

- lib/linkm/test/try.c
- lib/linkm/test/try2.c
Some of the internal functions had `int` return type, but they were not returning anything and the places where these functions are called were also not expecting anything from the function.
To, simplify such cases, change the function return type to 'void'.
This issue was found using cppcheck tool. It's a low-priority one, since it's in the tests and the functions affected are internal test functions.
3. Output from cppcheck prior to fix
Output from cppcheck after the fix
> lib/linkm: Change non-returning internal function types to void

- .github/workflows/osgeo4w.yml
While investigating for #4323, I saw that the macOS builds used the `-pipe` flag on CFLAGS and CXXFLAGS.
I searched a little on this subject, and it is a quite old flag that was once popular when storage wasn't as fast as it now is and memory was limited. It essentially tells gcc or clang to use pipes instead of temporary files, so it might use a bit more memory. https://stackoverflow.com/questions/1512933/when-should-i-use-gccs-pipe-option https://wiki.gentoo.org/wiki/GCC_optimization#How_are_they_used.3F https://wiki.gentoo.org/wiki/GCC_optimization#-pipe
Knowing that on Windows, the IO is way worse than on Linux (at least for the machines available on the runners, they don't necessarily have the same specs), and that the preprocessing step is a lot slower, I thought it might be worth …
> CI(OSGeo4W): Add -pipe to CFLAGS and CXXFLAGS to reduce build time

- raster/r.viewshed/viewshed.cpp
This was reported by cppcheck tool. Technically, we are not using the member in the struct variable in any of the subsequent functions, but it's a good practice to initialize all the struct members whenever possible.
Initial errors from cppcheck tool:
After applying the patch:
3. Architecture: Not specific to any underlying architecture.
Testing done:
Ran the complete `test_r_viewshed.py` gunittest from the testsuite and it was successful.
> r.viewshed: initialize struct member before using struct

- imagery/i.rectify/main.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1208277).
The variable len is used to match the clang format check
The build was successful after the make process
> i.rectify: Fix copy into fixed size buffer issue in main.c of i.rectify module

- imagery/i.segment/mean_shift.c
This pull request addresses the issue identified by coverity scan (CID : 1415633).
The variable hspec is getting overwritten and only last assigned value is being updated.
To resolve this, the redundant assignments have been commented out rather than removing completely.
> i.segment: Move unused variable value into a code comment

- lib/gis/gislib.dox
Add and remove documentation on [String_Manipulation_Functions](https://grass.osgeo.org/programming8/gislib.html#String_Manipulation_Functions).
> docs: update Programmer's Manual's GIS lib (string) section

- pyproject.toml
- temporal/t.rast.univar/testsuite/test_t_rast_univar.py
- temporal/t.rast3d.univar/testsuite/test_t_rast3d_univar.py
Resolves some ResourceWarnings, and also ruff SIM115.
> t.rast.univar: Use pathlib Path.read_text to open test outputs in t.rast.univar and t.rast3d.univar

- lib/gis/strlcat.c
- lib/gis/strlcpy.c
Make local implementations of strlcpy() and strlcat() optimizable by using restrict type qualifier, while keeping public API for G_strlcat and G_strlcpy available to C++ code and having identical prototype and declaration.
Currently the prototypes look like:
```c
size_t G_strlcat(char *, const char *, size_t);
```
but declared as:
```c
size_t G_strlcat(char *restrict dst, const char *restrict src, size_t dsize) { ...}
```
which the compilers seem to accept, but was probably not the best choice.
> lib/gis: match prototype with declaration for G_strlcat and G_strlcpy

- .github/actions/create-upload-suggestions/action.yml
- .github/workflows/additional_checks.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create_release_draft.yml
- .github/workflows/docker.yml
- .github/workflows/macos.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/periodic_update.yml
- .github/workflows/ubuntu.yml
Both `clang-format-check.yml` and `macos.yml` fail in `releasebranch_8_4`.
This PR aims at syncing a minimum of the GHA in G84 to the `main` branch to keep it alive for future G84 releases.
> CI: selective update of GitHub actions in G84

- python/grass/gunittest/loader.py
Refactored the function fnmatch_exclude_with_base in grass.gunittest.loader in order to work across platforms, including Windows.
I tried multiple approaches and researched a bit, and the first really working solution was the custom `fnmatch_ex` function that pytest uses, since pathlib's `Path.match()` doesn't work properly and doesn't behave like `Path.glob()` concerning `**`s. 
https://github.com/pytest-dev/pytest/blob/9515dfa58a144f3644fd29b256113d723c9c1955/src/_pytest/pathlib.py#L414-L447
```python
def fnmatch_ex(pattern: str, path: str | os.PathLike[str]) -> bool:
"""A port of FNMatcher from py.path.common which works with PurePath() instances.
The difference between this algorithm and PurePath.match() is that the
latter matches "**" glob expressions for each part of the path, while …
```
> grass.gunittest: Fix parsing exclusion from config file on Windows

- .flake8
- gui/wxpython/gcp/g.gui.gcp.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/gcp/mapdisplay.py
- gui/wxpython/gui_core/dialogs.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/goutput.py
- gui/wxpython/gui_core/gselect.py
- gui/wxpython/gui_core/menu.py
- gui/wxpython/gui_core/preferences.py
- gui/wxpython/gui_core/prompt.py
- gui/wxpython/gui_core/pystc.py
- gui/wxpython/gui_core/treeview.py
- gui/wxpython/gui_core/widgets.py
Flake8 F841 (local variable assigned to but never used) fixes in the `gui/wxpython/gpc` and `gui/wxpython/gui_core` directory.
- [Bug] Fix currently ignored Flake8 warnings https://github.com/OSGeo/grass/issues/1522
**g.gui.gpc**: Briefly tested using GUI and worked fine
**gui_core**:  N/A 
- Removed unused variables and lines to fix F841.
- Replaced `# pylint: disable=W0612` with `# noqa: F841` in `gui_core/treeview.py`. Please let me know if you want to keep "# pylint". It looks a little odd, but adding `# noqa:` to the end of code doesn't work. It must be the first line with multiline, like below.
```python
n111 = tree.AppendNode(  # noqa: F841
parent=n11, …
```
> checks: Flake8 F841 fixes in the wxpython directory part 3

- pyproject.toml
- python/grass/gunittest/case.py
- python/grass/gunittest/multireport.py
- python/grass/gunittest/reporters.py
Fixes all SIM115 issues in gunittest, except for two where I couldn't find a way to address with enough confidence for use in our own testing (one is not resolvable with context managers, as the opened file descriptor is assigned to the class in one function, and expected to be closed by another call at the end of the execution).
Only in two functions I had to resort to indent the most of the function since there were usages of the file descriptor throughout the function, and was used inside and outside a loop.
Otherwise, I tried to keep the amount of lines needing an indentation to a minimum, by moving down the variables needing to be within the `with` closer to that construct (in other words, placing variables assignments out the `with` further up, that ends up being understood by git …
> grass.gunittest: Fix SIM115 using context managers to open files

- .github/workflows/test_thorough.bat
Following #4324, that now has the excluded tests be properly excluded on Windows like they are on Linux, this increases the success threshold for gunittest tests on Windows to 86%. Even if we see 87%, it is 86.xx%, so not greater than or equal to 87%.
> CI(OSGeo4W): Update min-success to 86% for gunittest on Windows

- INSTALL.md
- doc/development/README.md
- doc/development/style_guide.md
- move Programmer's manual creation from `doc/development/README.md` to `INSTALL.md`.
- update URLs and wording
- list guides in `doc/development/README.md`
> docs: move Programmer's manual creation to INSTALL.md

- configure
- configure.ac
Fix for bug in configuration of BLAS/LAPACK as revealed by Docker failures.
The problem was caused by a typo of the variable names `with_blas` and `with_lapack`.
In addition: improve handling of configuration with LAPACK without BLAS
> configure: fix default variable name for blas and lapack

- .github/workflows/macos.yml
This PR finally enables caching of micromamba environments for CI runs.
It uses the example of in README that adds the date to the cache key prefix. https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#caching
I’ve been using this on and off (without an extra key prefix) since this winter when doing repetitive CI-only work, since macOS was the fastest to finish running all tests due to the very fast cores on Apple Silicon.
With environment caching, on cache hit the setup-micromamba usually finishes in 18 seconds, instead of 2min+, so compilation starts way before Ubuntu runners even can finish installing through apt.
Why I never did the PR before: I was hoping better caching possibilities from the setup-micromamba action, but it never really improved. The way they offer to …
> CI(macOS): Cache micromamba environment on same week

- pyproject.toml
- scripts/g.extension/g.extension.py
As mentioned in https://github.com/OSGeo/grass/pull/4291#issuecomment-2359894484, the minimum supported Python version of the main branch is 3.9 for a while now, but we still had Black configured to restrict itself to Python 3.8 support.
This PR removes 3.8 from the list of target versions, and adds 3.13, that is going to be released in 12 days (Oct 1, 2024).
This allows Black to use language syntax not available in 3.8, like line breaks in parenthesized `with` context managers.
> style: Bump Black's target Python versions for Python 3.9 minimum

- gui/wxpython/core/toolboxes.py
- gui/wxpython/psmap/instructions.py
- lib/init/grass.py
- man/build_class_graphical.py
- pyproject.toml
- utils/generate_release_notes.py
- utils/gitlog2changelog.py
Ruff rule: https://docs.astral.sh/ruff/rules/multiple-starts-ends-with/
Python docs: https://docs.python.org/3/library/stdtypes.html#str.startswith (no "introduced in" about the tuple of values to check against)
> style: Call `startswith` or `endswith` once with a `tuple` (PIE810)

- gui/wxpython/history/tree.py
After left double mouse click on the wxGUI history tab tree cmd node.
Special cmds are:
```
r"^d\..*|^r[3]?\.mapcalc$|^i.group$|^r.import$|^r.external$|^r.external.out$|"
r"^v.import$|^v.external$|^v.external.out$"
```
Fixes #4321.
> wxGUI/history: fix the run of a special cmds only once

- .github/workflows/osgeo4w.yml
Lately I’ve been working to get pytest running on Windows too. I end up needing some more changes to make it work, however using directly the same script that OSGeo4W uses brings me closer. The changes I would need would be reduced by having some common install options (including the OSGeo4W root) refactored out. I will also need #4121 in a near future too. And I find installation a bit long too. 
So, I ended up creating an action similar to other setup-* actions, that easily allow to instal and configure a software or language. I longly thought out the pros and cons of having the action inside this repo or as a separate repo. I wrote to @wenzeslaus too during that.
I finally settled on creating a clean version of the action in a separate repo, for a couple reasons:
* It has a value for …
> CI(OSGeo4W): Use setup-OSGeo4W action to parametrize install options

- .flake8
- doc/python/m.distance.py
- doc/python/raster_example_ctypes.py
- doc/python/vector_example_ctypes.py
This PR fixes the flake8 error in `doc/python`. It addresses mainly `F403`, `F405` and `E501`. These are mostly related to wild card imports and `max-line-length` errors. I haven't fixed `F401` in `dialogs.py` yet as that will require more comprehensive changes
> doc: Fix Flake8 issues in example files

- general/g.proj/input.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1501203).
strcpy is replaced with G_strlcpy.
The build was successful after the make process
> g.proj: Fix copy into fixed size buffer issue in input.c file

- .github/workflows/macos_gunittest.cfg
- .gunittest.cfg
In preparation for my PR extending the tests on Windows, I explored to see what tests were actually failing and could be enabled. Turns out some of them can be enabled on Linux too, since macOS has its own configuration file.
EDIT: I also did the same process for macOS (enable all then exclude still failing tests).
My other PR is almost ready, but I extracted these unrelated changes here.
This PR only removes some excluded test, and CI still passes.
> tests: Re-enable passing tests from .gunittest.cfg exclusion list

- python/grass/temporal/metadata.py
Fixes #4182 (t.info fails for single registered raster). I tried to work with the current design, although it might have been just easier to revert 7df1a7e, the method inheritance doesn't work very well there.
Besides the reported error, `STDSMetadataBase.print_info()` was also failing. I tested it with the currently deactivated doctests (there are issue running the doctests unrelated to this).
> grass.temporal: fix regression in printing metadata

- temporal/t.connect/testsuite/test_distr_tgis_db_raster.py
- temporal/t.connect/testsuite/test_distr_tgis_db_raster3d.py
- temporal/t.connect/testsuite/test_distr_tgis_db_vector.py
- temporal/t.rast.series/testsuite/test_series.py
Followup of #4328 that had outdated CI when merged, and my message was sent seconds after it was merged.
The PR fixed tests relating to t.info printing info to the shell.
> grass.temporal: Remove expected failures for tests fixed by #4328

- .flake8
- locale/grass_po_stats.py
This PR addresses the PEP8 style error `E722` by specifying the exception type in the `except` clause within the `writejson` function in `grass_po_stats.py`. Additionally, it confirms that no other common `flake8` errors (`E122`, `E128`, `E231`, `E401`) are present in the codebase
- **Specified Exception Type:**
- Changed the bare `except:` to `except OSError:` to catch only OS-related exceptions.
- **Exception Handling:**
- Specifying `OSError` in the `except` clause is appropriate because `os.remove()` can raise various OS-related exceptions such as `FileNotFoundError` or `PermissionError`. This avoids catching unintended exceptions and adheres to PEP8 guidelines.
> CI: Fix PEP8 E722 Error and Confirm No Other Common flake8 Errors in locale/

- ps/ps.map/ps_vpoints.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207906)
Used existing function ```Vect_destroy_cats_struct()```  to fix the memory leak issue.
> ps.map: Fix Resource leak issue in ps_vpoints.c 

- python/grass/jupyter/tests/grass_jupyter_session_test.py
The interpolated path strings aren't escaped when evaluated, so using a raw string allows C:\Users to not have an invalid \U escape sequence.
> grass.jupyter: Fix session tests on Windows

- .flake8
- gui/wxpython/core/gconsole.py
- gui/wxpython/core/render.py
- gui/wxpython/core/settings.py
- gui/wxpython/core/toolboxes.py
- gui/wxpython/core/utils.py
- gui/wxpython/core/workspace.py
This PR addresses the PEP8 style error `E722` by specifying exception types in all bare `except` clauses found throughout the codebase. By replacing bare `except:` statements with specific exception types, we improve code clarity, prevent unintended exception handling, and adhere to PEP8 guidelines.
---
1. **Replaced bare `except:` with `except Exception:` where appropriate.**
- **Affected Code Blocks:**
```python
if len(command) == 1 and not skipInterface:
try:
task = gtask.parse_interface(command[0])
except Exception:
task = None
2. **Replaced bare `except:` with specific exceptions to catch only expected errors.**
- **Changed to `except OSError:` when handling OS-related exceptions.**
```python
try:
self.locs = os.listdir(os.path.join(os.environ["GISBASE"], "locale")) …
> checks: Replace bare except (Flake8 E722) in wxGUI/core

- Dockerfile
- docker/alpine/Dockerfile
- docker/debian/Dockerfile
- docker/ubuntu/Dockerfile
- docker/ubuntu_wxgui/Dockerfile
Package lists were unsorted, and I got tricked when adding liblapacke-dev and sorting the list thinking it was sorted (almost but not). Being unsorted makes finding a package harder. To prove this point, `zlib1g-dev` was listed twice in the same list because it was unsorted.
I simply used the sort lines feature of my IDE, VSCode, that is case-sensitive.
> docker: Sort package lists and configure options in Dockerfiles

- python/grass/jupyter/testsuite/interactivemap_test.py
This should fix the InteractiveMap tests failing in https://github.com/OSGeo/grass/actions/runs/11005106346/job/30557221444?pr=4372
> grass.jupyter: fix interactivemap tests

- .flake8
- gui/wxpython/datacatalog/tree.py
This PR addresses the `E731` linting issue in `tree.py` by replacing a lambda expression with a named function. The change ensures that the code adheres to PEP 8 guidelines, which recommend using a `def` statement instead of assigning a lambda expression.
- Defined a new function `_callback` to replace the lambda expression.
- Updated the code to use the `_callback` function.
- Just recreated `lambda` function with a normal `def` function as specified in the `flake8`
> wxGUI/datacatalog: Replace lambda expression with named Function to fix E731

- vector/v.vol.rst/user1.c
This pull request addresses resource leak issue identified by coverity scan (CID: 1207918)
used ```Vect_destroy_field_info(Fi);``` to free the memory allocated by variable Fi
> v.vol.rst: Fix Resource Leak issue in user1.c file

- .flake8
- gui/wxpython/dbmgr/dialogs.py
This PR is more of a suggestion since I thought this would be a better way to handle this instead of a `try-except` block. It modifies the `GetSQLString` method in the `DisplayAttributesDialog` class to improve how it retrieves values from widgets. The changes make the code more robust and explicit in handling different widget types.
- Replace bare `except` clause with explicit checks for `GetValue()` and `GetLabel()` methods
- Add error handling for widgets that have neither method
The original code used a bare `except` clause to handle potential `AttributeError`s when trying to call `GetValue()` or `GetLabel()` on widgets. This approach was not robust and could potentially hide unexpected errors. The new implementation explicitly checks for the presence of these methods and raises an …
> wxGUI: Refactored try-except block to be more robust in dialogs.py

- .flake8
- gui/wxpython/dbmgr/base.py
- gui/wxpython/dbmgr/manager.py
- gui/wxpython/dbmgr/sqlbuilder.py
This pull request addresses the `E722 do not use bare 'except'` warnings in the codebase by specifying the exception types to be caught. This improves the code quality and makes the exception handling more explicit and clear.
1. **File: `base.py`**
- **Line 211:**
- Changed to catch `ValueError` when `index` method fails to find the specified element.
- **Line 964:**
- Changed to catch `KeyError` when accessing a dictionary key that does not exist.
- Changed to catch `Exception` when writing to the log to handle any unexpected errors.
- **Line 1643:**
- Changed to catch `ValueError` when converting a string to an integer fails.
- **Line 1675:**
- Changed to catch `ValueError` and `KeyError` when converting values and accessing dictionary keys.
- **Line 3812:**
- Changed to catch …
> wxGUI: Fix E722 Warnings by Specifying Exception Types in dbmgr/

- .flake8
- gui/wxpython/docs/wxgui_sphinx/conf.py
Fixed `E402` error in `gui/wxpython/docs/wxgui_sphinx` - moved import module to the top
> checks: Fix E402 Flake8 in for wxGUI Sphinx doc

- gui/wxpython/iclass/g.gui.iclass.html
[g.gui.class](https://grass.osgeo.org/grass85/manuals/g.gui.iclass.html) allows for importing training areas from vector layers. However, it is not clear from the manual that some specific columns are desirable ('cat', 'class', 'color'). This PR addresses this issue by adding a clarification.
> g.gui.iclass: Add explanation of expected format for vector layers 

- gui/wxpython/animation/dialogs.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/gcp/mapdisplay.py
- gui/wxpython/gui_core/vselect.py
- gui/wxpython/iclass/frame.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/image2target/ii2t_mapdisplay.py
- gui/wxpython/iscatt/plots.py
- gui/wxpython/mapdisp/frame.py
- gui/wxpython/nviz/mapwindow.py
- gui/wxpython/nviz/wxnviz.py
- gui/wxpython/photo2image/ip2i_manager.py
- gui/wxpython/photo2image/ip2i_mapdisplay.py
- gui/wxpython/psmap/frame.py
- gui/wxpython/rdigit/dialogs.py
- gui/wxpython/vdigit/wxdigit.py
- gui/wxpython/vnet/widgets.py
- lib/init/grass.py
- man/build_keywords.py
- pyproject.toml
- python/grass/gunittest/case.py
- python/grass/pygrass/modules/interface/parameter.py
- python/grass/temporal/spatial_extent.py
- scripts/g.extension.all/g.extension.all.py
- scripts/r.semantic.label/testsuite/test_r_semantic_label.py
- utils/mkhtml.py
Ruff rule: https://docs.astral.sh/ruff/rules/negate-equal-op/
> style: Fix negate-equal-op (SIM201)

- gui/wxpython/core/watchdog.py
- gui/wxpython/gui_core/preferences.py
- imagery/i.gensig/testsuite/test_i_gensig.py
- lib/imagery/testsuite/test_imagery_sigfile.py
- lib/imagery/testsuite/test_imagery_sigsetfile.py
- pyproject.toml
- python/grass/app/data.py
- python/grass/grassdb/checks.py
Ruff rule: https://docs.astral.sh/ruff/rules/os-stat/
> style: Fix os-stat (PTH116) by replacing os.stat() calls with pathlib

- gui/wxpython/animation/dialogs.py
- gui/wxpython/datacatalog/catalog.py
- gui/wxpython/gmodeler/panels.py
- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/gselect.py
- gui/wxpython/gui_core/pyedit.py
- gui/wxpython/image2target/ii2t_gis_set.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/workspace.py
- gui/wxpython/location_wizard/wizard.py
- gui/wxpython/main_window/frame.py
- gui/wxpython/modules/colorrules.py
- gui/wxpython/modules/import_export.py
- gui/wxpython/nviz/tools.py
- gui/wxpython/psmap/dialogs.py
- gui/wxpython/tplot/frame.py
- gui/wxpython/wxplot/profile.py
- lib/init/grass.py
- locale/grass_po_stats.py
- pyproject.toml
- python/grass/grassdb/checks.py
- python/grass/pygrass/tests/benchmark.py
- python/grass/script/core.py
- python/grass/script/utils.py
- python/grass/temporal/stds_export.py
- python/grass/temporal/stds_import.py
- scripts/r.pack/r.pack.py
- scripts/v.pack/v.pack.py
- utils/mkhtml.py
Ruff rule: https://docs.astral.sh/ruff/rules/os-getcwd/
When unable to confirm a Path would be accepted, I wrapped `Path.cwd()` with `str()`, so the variable would remain a string. When I had to add an import, I placed it such that it tends to what isort would do, but without changing other imports around it.
> style: Fix os-getcwd (PTH109) by replacing `os.getcwd()` calls with `Path.cwd()`

- gui/wxpython/animation/controller.py
- gui/wxpython/core/gcmd.py
- gui/wxpython/iscatt/plots.py
- gui/wxpython/mapwin/decorations.py
- gui/wxpython/vdigit/wxdisplay.py
- gui/wxpython/vnet/dialogs.py
- gui/wxpython/vnet/vnet_core.py
- pyproject.toml
- python/grass/script/utils.py
- python/grass/temporal/temporal_algebra.py
- utils/gitlog2changelog.py
Ruff rule: https://docs.astral.sh/ruff/rules/if-with-same-arms/
> style: Fix if-with-same-arms (SIM114)

- gui/wxpython/animation/temporal_manager.py
- gui/wxpython/gui_core/ghelp.py
- gui/wxpython/mapwin/buffered.py
- gui/wxpython/psmap/dialogs.py
- gui/wxpython/timeline/frame.py
- gui/wxpython/tplot/frame.py
- man/build_full_index.py
- pyproject.toml
- python/grass/imaging/images2ims.py
- scripts/g.search.modules/g.search.modules.py
- scripts/v.report/v.report.py
- utils/g.html2man/rest.py
Ruff rule: https://docs.astral.sh/ruff/rules/reimplemented-operator/
Replaced lambdas with `operator.itemgetter()` or `operator.add()`. These are implemented more efficiently in C and have a Python fallback. An answer on Stcak Overflow shows how sorted() and min() with a key using itemgetter can be 10-15% or 20-60% faster (on Python 3.6).
I couldn't get a definitive answer, but some articles I've read explain that these functions, like itemgetter, can be pickable (requirement for being usable in multiprocessing on Windows/macOS and for Python 3.14), while lambdas are not (as the functions are pickled by name, and lambdas are anonymous and have the same name).
> style: Fix reimplemented-operator (FURB118)

- lib/external/shapelib/README.md
- lib/external/shapelib/dbfopen.c
- lib/external/shapelib/safileio.c
- lib/external/shapelib/shapefil.h
- lib/external/shapelib/shapefil_private.h
- lib/external/shapelib/shpopen.c
Sync external library `shapelib` with upstream shapelib 1.6.0 and GDAL 3.9.2.
> lib/shapelib: sync upstream with shapelib 1.6.0 and GDAL 3.9.2

- gui/wxpython/psmap/instructions.py
- man/build_class_graphical.py
- man/build_manual_gallery.py
- pyproject.toml
- python/grass/pygrass/gis/region.py
- python/grass/pygrass/raster/history.py
- python/grass/pygrass/vector/table.py
- python/grass/script/task.py
- scripts/g.search.modules/g.search.modules.py
Fixes Ruff rule reimplemented-builtin (SIM110): https://docs.astral.sh/ruff/rules/reimplemented-builtin/
> style: Use `any` or `all` instead of `for` loop (SIM110)

- vector/v.transform/main.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1208239).
strcpy is replaced with G_strlcpy.
> v.transform: Fix Copy into fix Buffer size issue

- .flake8
- gui/wxpython/iscatt/controllers.py
- gui/wxpython/iscatt/frame.py
Specified `except` clause Exceptions to fix `E722` in `iscatt\`
> wxGUI: Fixed E722: bare 'except' in iscatt/

- .flake8
- gui/wxpython/iscatt/core_c.py
Fixed all `F405` and `F403` by explicitly importing all the functions. I had to import `ctypes` separately as well since explicit import of `ctypes.c_void_p` wasn't working for some reason. Also updated `ctypes.POINTER` to `POINTER` since its being imported.
> wxGUI: Fix F405 error by explicitly importing required modules in iscatt/

- .flake8
- gui/wxpython/iscatt/core_c.py
Fixed `F841` in `iscatt/core_c.py`. Printed the error message and removed an unused variable. I'll be pushing `F841` in small PRs since they can be relatively complex to review.
> wxGUI: Fixed F841 is iscatt/core_c.py

- gui/wxpython/iscatt/dialogs.py
- gui/wxpython/iscatt/frame.py
Deleted 3 instances of local variable which were not used to fix `F841`. Please review if `regionSizer` is being used or not - I deleted it since it had no further use in the fucntion and did not affect any other functions, being a local variable
> wxGUI: Fixed F841 in dialogs.py, frame.py

- vector/v.colors/scan_attr.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207685)
Used existing function Vect_destroy_field_info() to fix the memory leak issue.
> v.colors: Fix resource leak issue in scan_attr.c file

- raster/r.fill.dir/filldir.c
- vector/v.transform/main.c
This pull request addresses an issue identified by Coverity Scan (CID: 1207239), where the return value of the lseek function is not checked.
> r.fill.dir: Fix unchecked return value in filldir.c

- raster/r.thin/io.c
This pull request addresses an issue identified by Coverity Scan (CID: 1207261), where the return value of the lseek function is not checked.
> r.thin: Fix unchecked return value in io.c

- .flake8
- gui/wxpython/iscatt/controllers.py
- gui/wxpython/iscatt/plots.py
Fixed remaining `F841` in `iscatt/`. I made sure to only remove local variables so that it doesn't break any dependencies.
> wxGUI: Fixed F841 in iscatt/

- .flake8
- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/layertree.py
- gui/wxpython/lmgr/workspace.py
`addLayer` function is reqd hence I just removed variable assignment but kept the function definition. Logged error messages for the other cases. Additionally fixed `E266` - removed additional `#` from comments.
> wxGUI: Fixed F841 and E266 in lmgr/

- pyproject.toml
- python/grass/experimental/tests/grass_script_mapset_session_test.py
- python/grass/jupyter/tests/reprojection_renderer_test.py
- python/grass/pygrass/modules/tests/grass_pygrass_grid_test.py
- python/grass/script/tests/grass_script_setup_test.py
- temporal/t.rast.list/tests/t_rast_list_test.py
Only 10 issues were remaining to enable checking all available ruff rules of the `PT` category.
This PR fixes 3 types of issues, and removes unneeded exclusions, as there were no longer issues there.
The only remaining ignores per file are found in `"*/testsuite/**.py" = ["PT009", "PT027"]` and `"python/grass/gunittest/case.py" = ["PT009"]`. The first one is because we use unittest-style asserts in our gunittest tests, obviously, and the grass.gunittest.case detects our custom assertions like if they were tests (and not following pytest style assertions), which isn't desirable.
That brings us to having all rules of the `PT` category being addressed.
> style: Fix all remaining `PT` flake8-pytest-style issues

- pyproject.toml
- python/grass/pydispatch/robustapply.py
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/modules/interface/env.py
- utils/g.html2man/ghtml.py
Rewrites unnecessary `list` comprehension as a `dict` comprehensions.
Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-list-comprehension-dict/
> style: Fix unnecessary-list-comprehension-dict (C404)

- general/g.remove/testsuite/test_g_remove.py
- gui/wxpython/core/workspace.py
- gui/wxpython/gui_core/gselect.py
- gui/wxpython/gui_core/menu.py
- gui/wxpython/lmgr/frame.py
- gui/wxpython/main_window/frame.py
- gui/wxpython/mapdisp/statusbar.py
- gui/wxpython/vdigit/wxdisplay.py
- pyproject.toml
- python/grass/experimental/tests/grass_script_tmp_mapset_session_test.py
- scripts/d.polar/d.polar.py
- scripts/i.oif/i.oif.py
- scripts/i.pansharpen/i.pansharpen.py
- scripts/i.tasscap/i.tasscap.py
- scripts/v.report/v.report.py
As 0 is the default start value, it can be safely omitted.
Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-range-start/
> style: Fix unnecessary-range-start (PIE808)

- gui/wxpython/lmgr/giface.py
- gui/wxpython/timeline/frame.py
- gui/wxpython/tplot/frame.py
- gui/wxpython/web_services/widgets.py
- pyproject.toml
- python/grass/imaging/images2gif.py
- python/grass/imaging/images2swf.py
- python/grass/pygrass/gis/__init__.py
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/vector/basic.py
- python/grass/pygrass/vector/table.py
- python/grass/pygrass/vector/testsuite/test_table.py
- scripts/i.oif/i.oif.py
Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-comprehension/
> style: Fix unnecessary-comprehension (C416) 

- vector/v.reclass/reclass.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207621, 1207624, 1207622)
Used existing function Vect_destroy_cats_struct(), Vect_destroy_line_struct() to fix the memory leak issue.
> v.reclass: Fix Resource Leak issue in reclass.c

- vector/v.rectify/main.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1208240).
strcpy is replaced with G_strlcpy.
> v.rectify: Fix Copy into fix Buffer size issue

- gui/wxpython/core/giface.py
- gui/wxpython/core/gthread.py
- gui/wxpython/core/layerlist.py
- gui/wxpython/mapwin/analysis.py
- gui/wxpython/mapwin/base.py
- gui/wxpython/modules/import_export.py
- pyproject.toml
- python/grass/imaging/images2swf.py
- python/grass/pygrass/vector/geometry.py
Ruff rule: https://docs.astral.sh/ruff/rules/unnecessary-paren-on-raise-exception/
It is only possible to omit the parentheses if the exception is a class, not a function call (so it would be an exception object). In this PR, all cases were classes.
> style: Fix unnecessary-paren-on-raise-exception (RSE102)

- vector/v.to.db/update.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207709, 1207710)
Used existing function Vect_destroy_field_info() to fix the memory leak issue.
> v.to.db: Fix resource Leak issue in update.c

- raster/r.in.lidar/main.c
- raster/r.in.pdal/main.cpp
- raster/r.in.xyz/main.c
- raster3d/r3.in.lidar/main.c
If a structure is not initialized, it may contain random data. Avoid that by initializing it.
> raster/raster3d: Initialize Cell_head structure contents before using it in r3.in.lidar, r.in.lidar, r.in.pdal, r.in.xyz

- .flake8
- imagery/i.atcorr/create_iwave.py
Just fixed unused `b` since its not required when len=1
> tools: FIxed unused variable in imagery/

- .flake8
- doc/gui/wxpython/example/dialogs.py
`dialogs.py` has an instance of `F401` error for unused import of `grass` library. However as mentioned in the comment and post discussion with @wenzeslaus I decided it would be better to ignore this error for now in case it breaks any underlying dependencies regarding `gettext.install()`
> doc: Ignore F401 in dialogs.py

- gui/wxpython/modules/colorrules.py
Made following modifications to fix `F841`
- Directly called `RunCommand` instead of using a variable
- Printed the error message `e`
- Removed local variable `type` which was unused
> wxGUI: FIxed F841 in colorrules.py

- imagery/i.ortho.photo/lib/find_init.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207903).
Replaced the direct return of G_find_file with a variable (file_exists) to store the result before freeing memory.
> i.ortho.photo: Fix Resource Leak in find_init.c

- lib/vector/Vlib/color_read.c
This pull request resolves a buffer overflow issue detected by Coverity Scan (CID 1208238).
sprintf is replaced with snprintf
> lib/vector/Vlib: Fix copy into buffer size issue in color_read.c

- raster/r.terraflow/fill.cpp
- raster/r.terraflow/genericWindow.cpp
- raster/r.terraflow/sweep.cpp
- raster/r.terraflow/weightWindow.cpp
With GCC and -Werror=pedantic, the r.terraflow C++ code produces errors because extra semicolons are present after some function definitions. This removes the semincolons and I no longer get 'error: extra ;'.
> checks: Remove extra semicolons in r.terraflow

- vector/v.colors/read_rgb.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207628)
Used existing function Vect_destroy_field_info() to fix the memory leak issue.
> v.colors: Fix Resource Leak issue in read_rgb.c

- vector/v.to.db/areas.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207638)
Used existing function Vect_destroy_cats_struct() to fix the memory leak issue.
> v.to.db: Fix Resource Leak issue in areas.c

- display/d.vect/attr.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1207623, 1207625, 1207626)
Used existing function Vect_destroy_line_struct(), Vect_destroy_cats_struct(), Vect_destroy_field_info() to fix the memory leak issue.
> d.vect: Fix Resource Leak issue in attr.c

- raster/r.carve/enforce_ds.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1208024, 1208023)
Used existing function Vect_destroy_line_struct(), Vect_destroy_cats_struct() to fix the memory leak issue.
> r.carve: Fix resource leak issue in enforce_ds.c

- gui/wxpython/lmgr/giface.py
Fixes https://github.com/OSGeo/grass/issues/4485#issuecomment-2407124541
The RecursionError is probably caused by https://github.com/OSGeo/grass/pull/4453, where one of these RecursionErrors was caught in tests, and fixed in a commit in that PR (https://github.com/OSGeo/grass/pull/4453/commits/f7874f63477585d2d936b71fbaac119740abb49c). The exact reason causing the failure wasn't known, so fixing the method `mapsets` that might have been called elsewhere was the correct thing. There wasn't the same pattern in the PR to be fixed.
However, with that comment, it is now clear that it is calling `list()` inside `__len__()` of that same object that is problematic. After reading a bit, the list constructor gets the length or the length hint (when available) as an optimization to allocate memory. …
> gui: Solve a recursion error in gui/wxpython/lmgr/giface.py

- lib/raster/mask_info.c
- raster/r.mask.status/main.c
Fixes two new issues reported by Coverity Scan:
- Handles case of unsuccessful creation of json string
- Silences false positive issue for string copy operation to buffer of size GMAPSET_MAX from G_mapset()
> r.mask.status: fix null pointer dereference and false positive string overflow

- pyproject.toml
Ruff rule PT004 is deprecated, so doesn't run with --preview flag, but still appears without the --preview flag. Since the only error won't be fixed, ignore that rule for the time being.
This means that PR https://github.com/OSGeo/grass/pull/4452 was incomplete in a sense
See https://github.com/astral-sh/ruff/pull/12837 and https://github.com/astral-sh/ruff/issues/8796
> style: Ignore deprecated PT004 rule

- vector/v.net.timetable/main.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1208053, 1208054)
Used existing function Vect_destroy_line_struct(), Vect_destroy_list() to fix the memory leak issue.
> v.net.timetable: Fix Resource Leak issue in main.c

- vector/v.kernel/main.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1208031, 1208032, 1208033)
Used existing function Vect_destroy_line_struct(), Vect_destroy_boxlist() to fix the memory leak issue.
> v.kernel: Fix resource Leak issue in main.c

- lib/vector/Vlib/geos.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1208050, 1208051, 1208052)
Used G_free for fixing resource leak
> lib/vector/Vlib: Fix Resource leak issue in geos.c

- testsuite/raster/raster_md5test.sh
Enables the test `testsuite/raster/raster_md5test.sh` to work with either `md5sum` or `md5`.
(Includes fixes for shellcheck warnings).
> tests: enable use of md5 bin for checksum in raster_md5test.sh

- lib/vector/Vlib/open.c
- python/grass/pygrass/vector/abstract.py
When a vector with topology is opened in update mode, but nothing is changed, topology info (topo, cidx, sidx) is not written out. This PR fixes this.
I am not sure if this is a bug or an enhancement.
> lib/vector/Vlib: always write out topo files in update mode

- .github/workflows/milestones.yml
Addresses https://github.com/OSGeo/grass/pull/4398#issuecomment-2379676744
This PR assigns a milestone when a PR is closed if none is set, using `pull_request_target` trigger with `closed` activity type. It uses up an API call to know if the PR has a milestone set (limit is 5000 per hour when authenticated). If I used the info from the github event context, the information is populated when the job is queued, and will maybe not represent the state once it will run, and will keep the old state if a rerun is made. I tried to use the gh cli instead of their javascript action's ecosystem so steps could be reproduced locally too using the same gh cli calls.
If there are no milestones for that PR, then it uses a second API call to fetch the include/VERSION file at the ref of the merged result …
> CI: Assign milestone on merged PRs

- imagery/i.segment/i.segment.html
- imagery/i.segment/iseg.h
- ps/ps.map/r_instructions.c
- raster/r.resamp.interp/r.resamp.interp.html
- raster/r.topidx/r.topidx.html
Again, use lowercase mask and other wording instead of MASK when talking about masking, similar to #4401 and #4495.
It also adjusts the wording in r.topidx and i.segment.
> doc: Use lowercase for mask

- raster/r.in.gridatb/file_io.c
The pull request addresses the issue identified by coverity scan (CID: 1208191)
fp = fopen(file, "r");
The fopen might fail in that case it will already be null.
> r.in.gridatb: Dereference before null check

- gui/wxpython/nviz/mapwindow.py
Fixed unused variables in `mapwindow.py`
- removed `dc` and `ret` and directly called the contructors
> wxGUI: Fixed F841 in mapwindow.py

- gui/wxpython/lmgr/frame.py
- gui/wxpython/lmgr/layertree.py
Added `TypeError` in `except` clause wherever `GetLayerInfo` is used.
> wxGUI: Added TypeError to lmgr/

- .flake8
- gui/wxpython/modules/histogram.py
- gui/wxpython/modules/import_export.py
- gui/wxpython/modules/mapsets_picker.py
Fixed all F841 errors in modules/
- removed `point`, `ext` and `geometry` variable which were not being used
- called the `App()` constructor directly
- One issue that popped up was while running `pre-commit` on `import_export.py`, This error constantly popped up in `ruff` checks
```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1
gui/wxpython/modules/import_export.py:615:30: F823 Local variable `_` referenced before assignment
|
614 |         if not data:
615 |             GMessage(message=_("No layers selected. Operation canceled."), parent=self)
|                              ^ F823
616 |             return
|
Found 1 error.
```
I didn't find a fix for it currently so I just referenced the `_` locally in the function
> wxGUI: Fixed F841 in modules/

- gui/wxpython/lmgr/workspace.py
This should fix #3222 and a duplicate #4491. It tries to first find the translated version of File menu, if it fails, it looks for untranslated version. I could replicate #4491 and this fixes it, GUI starts again.
> GUI: fix crashing due to File menu translation issues

- .flake8
- gui/wxpython/nviz/tools.py
Removed unused variables and called constructors directly where applicable
> wxGUI: Fixed F841 in tools.py

- .flake8
- gui/wxpython/psmap/dialogs.py
- gui/wxpython/psmap/frame.py
- gui/wxpython/psmap/instructions.py
Following changes were made to fix F405 in `psmap/`
- removed `* imports`
- ran `isort` to sort all the imports
- `cmp` function was not working post doing explicit import with the error `gui/wxpython/psmap/dialogs.py:4127:47: F821 undefined name 'cmp'` - On looking more at this, I found this was removed in python3 and required an explicit comparison function. Hence I defined an explicit comparison function and referenced that instead.
> wxGUI: Fixed F405 in psmap/

- flake.nix
Fix locales in nix provided development environment.
Closes: #4503
> nix: Fix locales in development environment

- gui/wxpython/gmodeler/g.gui.gmodeler.html
- imagery/imageryintro.html
This PR adds an overview text to `imagery/imageryintro.html` including a link to addons to not start this intro text without context.
(aside, addons URL fix in `g.gui.gmodeler.html`)
> docs: add intro text to imageryintro.html

- gui/wxpython/location_wizard/wizard.py
- lib/init/helptext.html
As epsg.io is partially outdated (see [source](https://github.com/maptiler/epsg.io/issues/171) and related) and PROJ is our engine anyway, this PR switches the references in the GUI to https://spatialreference.org.
> GUI: EPSG code source: replace epsg.io with spatialreference.org

- imagery/i.atcorr/computations.cpp
In `trunca()`, under 2 if conditionals (`if rumu[1] > 0.8 and rmu[1] > 0.94`), k and kk values are set to `-1` respectively. When these values are used to access an array, it leads to out of bound access, which is undefined behavior in c++.
Similarly in `os()` and `iso()`, if `taup < h[i]` for all values, iplane would still be `-1` and we would be accessing an array with this as an index, which is undefined behavior.
In both cases, to avoid that, set that index to zero.
> i.atcorr: fix out of bound access in trunca, os and iso

- .flake8
- python/grass/gunittest/invoker.py
Fixed `E721` by using `isinstance()` for type checks instead of `==`
Also I went through some entries on `.flake8` which were in the file but weren't detected on the running the `flake8` check on there so I removed those as well
> docs: Fixed E721 in gunittest/

- .flake8
- gui/wxpython/nviz/tools.py
Removed leading `#` to fix E266
> wxGUI: Fixed E266 in nviz/

- gui/wxpython/mapswipe/frame.py
- pyproject.toml
- python/grass/pygrass/modules/interface/testsuite/test_modules.py
- python/grass/script/tests/test_script_task.py
- raster/r.basins.fill/testsuite/testrbf.py
- raster/r.series/testsuite/test_r_series.py
- raster/r.terraflow/testsuite/test_r_terraflow.py
- raster/r.to.vect/testsuite/test_r_to_vect.py
- raster/r.viewshed/testsuite/test_r_viewshed.py
- scripts/r.import/testsuite/test_r_import.py
- scripts/r.reclass.area/testsuite/testrra.py
- scripts/v.import/testsuite/test_v_import.py
- vector/v.extract/testsuite/test_v_extract.py
- vector/v.net/testsuite/test_v_net.py
- vector/v.random/testsuite/test_v_random.py
- vector/v.select/testsuite/test_v_select.py
- vector/v.to.3d/testsuite/test_vto3d.py
This PR initially wanted to enable and fix N804, but some similar issues could be solved at once.
So, this PR enables pep8-naming (N) rules with ruff.
Rules already respected:
- dunder-function-name (N807)
- constant-imported-as-non-constant (N811)
- camelcase-imported-as-acronym (N817)
Fixed rules:
- invalid-first-argument-name-for-class-method (N804) -> 2 instances
- Ruff rule: https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-class-method/
- Two files had class methods that didn't use `cls` as their first argument when they should have been
- **Can be autofixed for further errors in the future**
- invalid-first-argument-name-for-method (N805) -> 16 instances
- Counterpart of the previous N804, but for classes not using `self` as the first argument when they should
- …
> style: Enable checking for pep8-naming (N) rules with ruff, fix N804, N805 and N813

- gui/wxpython/gmodeler/model.py
- pyproject.toml
- python/grass/script/raster.py
Ruff rule: https://docs.astral.sh/ruff/rules/multi-value-repeated-key-literal/
Pylint : https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/duplicate-key.html
Two instances fixed.
Just to prove that a repeated key in a dict is the same as the last one, I tested it out in a simple example, in IPython:
```python
gitpod /workspace/grass (main) $ ipython
Python 3.12.6 (main, Sep  9 2024, 10:33:54) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]:     aa =   {
...:                     "pos": "posvalue",
...:                     "size": "sizevalue",
...:                     "text": "textvalue1",
...:                     "id": 42,
...:                     "text": "textvalue2", …
```
> style: Fix multi-value-repeated-key-literal (F601) (Pylint W0109)

- gui/wxpython/psmap/dialogs.py
- gui/wxpython/psmap/frame.py
- pyproject.toml
- python/grass/temporal/univar_statistics.py
- raster/r.basins.fill/testsuite/testrbf.py
- raster/r.in.ascii/testsuite/test_r_in_ascii.py
- raster/r.proj/testsuite/test_rproj.py
- raster/r.reclass/testsuite/test_r_reclass.py
- raster/r.tile/testsuite/testrt.py
- raster/r.what/testsuite/testrw.py
- scripts/r.reclass.area/testsuite/testrra.py
- vector/v.extract/testsuite/test_v_extract.py
- vector/v.vect.stats/testsuite/test_vect_stats.py
This PR enables checking of remaining rules in the E category. It fixes simple issues, E101, E231, E265 and E266.
- [mixed-spaces-and-tabs (E101)](https://docs.astral.sh/ruff/rules/mixed-spaces-and-tabs/): 8 file headings (in tests) copied the license text with some tab at the beginning, then continued with spaces.
- [missing-whitespace (E231)](https://docs.astral.sh/ruff/rules/missing-whitespace/): 2 similar instances in the same file didn't have the formatting of the `.replace()` arguments formatted, as it was inside an f-string.
- [no-space-after-block-comment (E265)](https://docs.astral.sh/ruff/rules/no-space-after-block-comment/): Ignored file that https://github.com/OSGeo/grass/pull/4550 is solving.
- [multiple-leading-hashes-for-block-comment …
> style: Enable checking for E ruff rules from pycodestyle, fixing simple issues

- doc/python/raster_example_ctypes.py
- doc/python/vector_example_ctypes.py
- lib/init/grass.py
- man/build_html.py
- temporal/t.info/t.info.py
- temporal/t.list/t.list.py
- temporal/t.rast.accdetect/t.rast.accdetect.py
- temporal/t.rast.accumulate/t.rast.accumulate.py
- temporal/t.rast.aggregate/t.rast.aggregate.py
- temporal/t.rast.to.rast3/t.rast.to.rast3.py
- temporal/t.rast.what/t.rast.what.py
- temporal/t.rename/t.rename.py
- temporal/t.topology/t.topology.py
- temporal/t.unregister/t.unregister.py
- temporal/t.vect.observe.strds/t.vect.observe.strds.py
- temporal/t.vect.what.strds/t.vect.what.strds.py
- utils/g.html2man/ggroff.py
- utils/mkrest.py
- utils/ppmrotate.py
- utils/update_version.py
Ruff rule: https://docs.astral.sh/ruff/rules/if-else-block-instead-of-if-exp
Since the amount of changes for SIM108 are quite large, (more than 330), I've decided to split the fixes in more than 1 PR. I kept `scripts/*`, `python/*` and `gui/*` in other PRs.
To avoid conflicts, I didn't commit the modified `pyproject.toml`, nor extra typing annotations that I used to help guiding and validating these fixes.
> style: Fix if-else-block-instead-of-if-exp (SIM108) (part 1)

- .flake8
- gui/wxpython/modules/colorrules.py
- gui/wxpython/modules/histogram.py
- gui/wxpython/modules/import_export.py
- gui/wxpython/modules/mcalc_builder.py
Added specific errors to remove `bare except` clauses. I put a catch all `Exception` block where I thought there could be many possible `Exceptions`
> wxGUI: Fixed E722 in modules/

- .flake8
- temporal/t.rast.what/t.rast.what.py
Removed commented out concerning E265, E266
> temporal: Fixed E265/E266 in t.rast.what/

- .flake8
- gui/wxpython/nviz/wxnviz.py
Fixed `F405` by specifying imports in `nviz/`
> wxGUI: Fixed F405 in nviz/

- .flake8
- gui/wxpython/photo2image/g.gui.photo2image.py
- gui/wxpython/photo2image/ip2i_manager.py
- gui/wxpython/photo2image/ip2i_mapdisplay.py
Following changes made to fix `F841` in `photo2image/`
- Directly called contructors `GCPWizard` and `wx.BusyInfo`
- Removed `point`, `reload_target` and `diff` which were not being used
> wxGUI: Fixed F841 in photo2image/

- db/drivers/mysql/db.c
- db/drivers/postgres/db.c
- db/drivers/postgres/listdb.c
- include/grass/defs/dbmi.h
- lib/db/dbmi_base/connect.c
- lib/db/dbmi_base/login.c
- lib/vector/Vlib/open_pg.c
- vector/v.external/dsn.c
- vector/v.in.ogr/dsn.c
- vector/v.out.ogr/dsn.c
`db_get_login()` is deprecated in 7.8.0 release with da399c52637ee5c81228459fa374a114c8fef06c. Change its function signature and implementation to match that of the currently preferred `db_get_login2()`.
Modify `db_get_login2()` to internally call `db_get_login()` function call. In the future major version, `db_get_login2()` would be removed to have only one method to get login details for simplicity.
> lib/db: remove deprecated implementation of db_get_login() and replace it with that of db_get_login2()

- db/db.login/main.c
- include/grass/defs/dbmi.h
- lib/db/dbmi_base/login.c
In a similar vein to that of #4302, `db_set_login()` is deprecated in 7.8.0 release with da399c5. Change its function signature and implementation to match that of currently preferred `db_set_login2()`.
Modify `db_set_login2()` to internally call `db_set_login()` function call. In the future major version, `db_set_login()` would be removed to have only one method to set login details for simplicity.
> lib/db: remove deprecated implementation of db_set_login() and replace it with that of db_set_login2()

- .flake8
- gui/wxpython/psmap/dialogs.py
- gui/wxpython/psmap/frame.py
- gui/wxpython/psmap/instructions.py
Following updates were made:
- remove `e` and `n` from all instances
- Added error message for `e`
- removed `if` clause as variables are unused and default to `except`
- adjusted `wx.BusyInfo`
> wxGUI: Fixed F841 in psmap/

- .flake8
- scripts/r.in.srtm/r.in.srtm.py
Following Exceptions added
- `zipfile.BadFIle` and `zipfile.LArgeFile` for file related errors. and `PermissionError` incase it does not have enough permission to be accessed
- In second, since `gs` module is used, I added `CalledModuleError`, I can also do a generic `Exception` here if required
> r.in.srtm: Fix exception handling and add specific error types

- imagery/i.segment/i.segment.html
The text of the man page did not reflect the actual parameter name 'radius'. Also added more SEE ALSO references to acknowledge the existence of a series of support modules.
> i.segment.html: parameter names and links to other modules

- raster/r.his/testsuite/test_r_his.py
Added regression test for r.his.
There was no testing for r.his.
Locally tested with ```python <path>/raster/r.his/testsuite/test_r_his.py```
> tests: Add regression test for r.his

- .flake8
- scripts/r.fillnulls/r.fillnulls.py
Removed bare except clauses as per this:
- `CalledModuleError` for `gs.command`
- Simple `Exception` since all others were list `remove` command
> r.fillnulls: Removed bare except from r.fillnulls

- include/grass/iostream/replacementHeap.h
- include/grass/iostream/replacementHeapBlock.h
In C++20, repeating template parameter names with the name of the class is no longer allowed as it is redundant (https://cplusplus.github.io/CWG/issues/2237.html). The new code is valid also in C++17, but the old code is not accepted in C++20.
> lib/iostream: Remove redundant template parameters

- display/d.vect/attr.c
- lib/vector/Vlib/copy.c
This pull request addresses resource leak issue identified by coverity scan (CID : 1208071)
Used existing function Vect_destroy_field_info() to fix the memory leak issue.
> lib/vector/Vlib: Fix Resource Leak issue in copy.c

- raster/r.in.poly/poly2rast.c
This pull request fixes issued identified by coverity scan (CID : 1207593)
**Changes made:**
- Added fclose(ifd);  in the error handling block when stat < 0.
- Added fclose(ifd); at the end of the function to ensure the file is closed before returning.
> r.in.poly: Fix Resource Leak issue in poly2rast.c

- lib/gis/copy_dir.c
This pull request fixes issue identified by Coverity Scan (CID : 1207596)
Added closedir(dirp); inside the if condition to close the directory pointer in case of errors.
> lib/gis: Fix resource leak issue in copy_dir.c

- raster/r.watershed/seg/close_maps.c
This pull request fixes resource leak issue identified by Coverity Scan (CID : 1207607)
- Freed afbuf in the asp_flag block: Added G_free(afbuf); after Rast_close(fd); to ensure afbuf is released after its final usage.
- in addition to afbuf; cbuf (allocated using Rast_allocate_c_buf()) is also freed to prevent memory leaks.
> r.watershed: Fix Resource Leak issue in close_maps.c

- .flake8
- scripts/v.import/v.import.py
Added `ImportError` onto bare except clause
> v.import: Fixed E722 bare except

- .flake8
- scripts/v.unpack/v.unpack.py
Added `tarFile.Errors` for tarfile operations in the code
Also updated `.flake8`
> v.unpack: Fixed bare 'except'

- lib/ogsf/gvl2.c
This pull request addresses the issue identified by coverity scan (CID: 1207416)
- Added else block where gvl might be null.
- Used G_debug with level 2 which is moderate as it is already aware that it is accessing null volume structure through the message
- Thought behind using G_debug was to print some additional logs instead of just G_warning. (Open to change to normal G_warning or any other level in G_debug)
> lib/ogsf: Dereference after null check in gvl2.c

- .flake8
- scripts/v.report/v.report.py
used `isinstance()` instead of `==` for type checks
> v.report: Updated instance checks

- include/grass/defs/raster.h
- lib/raster/mask_info.c
- raster/r.mask.status/main.c
- raster/r.mask.status/r.mask.status.html
- raster/r.mask.status/tests/r_mask_status_test.py
For both active and inactive raster mask, show the name of the raster which is used (or would be used) for the mask. This will allow tools like r.mask or GUI to do lower-level operations with or around mask without a need to know about defaults or user mechanism to change the name.
I'm repurposing the existing 'name' (full_name) key which is now always set (as opposed to being null when no mask is present) as the 'present' boolean key already has the information on the mask presence. I'm renaming full_name to name because that creates a simpler interface (which is whole point of outputting full name as opposed to two keys to get name and mapset).
> r.mask.status: Always output name of the mask

- .flake8
- scripts/db.out.ogr/db.out.ogr.py
Fixed `841` by removing unused `table`
> db.out.ogr: Removed unused variable

- .flake8
- scripts/r.in.wms/srs.py
- scripts/r.in.wms/wms_drv.py
- scripts/r.in.wms/wms_gdal_drv.py
Added `ImportError`, `ValueError`, and `IndexError`
Also fixed `E402` by shifitng import to top
> r.in.wms: Removed bare 'except' and repositioned imports

- scripts/r.in.wms/wms_drv.py
Replace `arrayrange` with `arange` in line with `np`
> r.in.wms: Replace long-deprecated `np.arrayrange` alias with `np.arange`

- python/grass/script/core.py
- python/grass/script/db.py
- python/grass/script/raster.py
- python/grass/script/raster3d.py
- python/grass/script/vector.py
While the message functions (fatal, warning, message, info, debug, verbose, percent) have env parameter, grass.script was not consistently passing the env parameter to these functions. This fixes all the clear cases in functions which themselves have env (but does not touch any which don't have it where the fix needs to be more complex).
These functions can now be called and produce these messages even for non-global sessions.
> grass.script: Pass environment to message functions

- lib/vector/Vlib/break_polygons.c
This pull request fixes issue identified by Coverity scan (CID: 1207832).
- Each call to open(filename, O_RDWR | O_CREAT | O_EXCL, 0600) now checks if the file descriptor (fd or xpntfd) was successfully created.
- If file creation fails, G_fatal_error() is invoked, and the temporary filename is freed before the function exits.
- If xpntfd creation fails, it also cleans up by destroying the RTree and closing fd.
- Also there is a check for remove(filename). I have used G_warning over there to print message. Not sure whether to use G_fatal or G_warning.
> lib/vector/Vlib: Fix Resource Leak issue in break_polygons.c

- vector/v.delaunay/in_out.c
This pull request fixes issue identified by Coverity Scan (CID: 1207851,1207849).
Used existing function Vect_destroy_line_struct(), Vect_destroy_cats_struct() to fix the memory leak issue.
> v.delaunay: Fix Resource Leak issue in in_out.c

- lib/ogsf/gsd_img_tif.c
This pull request fixes issue identified by Coverity Scan (CID : 1207908)
> lib/ogsf: Fix resource leak issue in gsd_img_tif.c

- raster/r.viewshed/grass.cpp
Partially reverts commit 9ad98566af4142d517df43fd017ef41b5ab2003f, which addressed -Wunused-but-set-variable warnings. The unused code is here commented out, to preserve context of original intent of author.
Closes #4584.
> r.viewshed: address -Wunused-value warnings

- lib/ogsf/gsd_surf.c
In a lot of places, `(255 << 24)` which causes integer overflow and positive number gets converted to negative number. We were then assigning this to an unsigned integer in multiple places, which does conversion in a different way.
For example: If we do `unsigned int x = -20`, `UINT_MAX + 1 - 20` is assigned to x.
I do not think that's what is intended when we do with `ktrans = (255 << 24)`. Fix instances of that, by using an `unsigned int literal` over `int literal`.
> lib/ogsf: fix possible overflow errors in gsd_surf.c

- lib/ogsf/gvld.c
This is similar to https://github.com/OSGeo/grass/pull/4635.
We were doing `(255 << 24)` which causes integer overflow and positive number gets converted to negative number. We were then assigning this to an unsigned integer in multiple places, which does conversion in a different way.
For example: If we do unsigned int x = -20, `UINT_MAX + 1 - 20` is assigned to x.
I do not think that's what is intended when we do
`ktrans = (255 << 24)`. Fix instances of that, by using an unsigned int literal over int literal.
> lib/ogsf: fix possible overflow errors in gvld.c

- lib/ogsf/gsd_wire.c
This is in a vein similar to https://github.com/OSGeo/grass/pull/4635.
In a code, we were doing `(255 << 24)` which causes integer overflow and positive number gets converted to negative number. We were then assigning this to an unsigned integer in multiple places, which does conversion in a different way.
For example: If we do `unsigned int x = -20`, `UINT_MAX + 1 - 20` is assigned to x.
I do not think that's what is intended when we do with `ktrans = (255 << 24)`. Fix instances of that, by using an `unsigned int literal` over `int literal`.
> lib/ogsf: fix possible overflow errors in gsd_wire.c

- vector/v.info/local_proto.h
- vector/v.info/main.c
- vector/v.info/print.c
- vector/v.info/testsuite/test_vinfo.py
Use parson to add json support to v.info for columns. The JSON output looks like as follows:
```json
{
"columns": [
{
"name": "cat",
"sql_type": "INTEGER",
"is_number": true
},
{
"name": "MAJORRDS_",
"sql_type": "DOUBLE PRECISION",
"is_number": true
},
{
"name": "ROAD_NAME",
"sql_type": "CHARACTER",
"is_number": false
},
{
"name": "MULTILANE",
"sql_type": "CHARACTER",
"is_number": false
},
{
"name": "PROPYEAR",
"sql_type": "INTEGER",
"is_number": true
},
{
"name": "OBJECTID",
"sql_type": "INTEGER",
"is_number": true
},
{
"name": "SHAPE_LEN",
"sql_type": "DOUBLE PRECISION",
"is_number": true
}
]
}
```
fixes: https://github.com/OSGeo/grass/issues/4218
> v.info: add json output for columns

- gui/wxpython/core/gconsole.py
- gui/wxpython/core/gthread.py
Fixes #4651.  vars() acts like locals() and there have been some changes:
https://docs.python.org/3/whatsnew/3.13.html#whatsnew313-locals-semantics
> GUI: fix for Python3.13

- python/grass/utils/download.py
> python/grass/utils: fix checking server response content type/dispostion header to allow to download ZIP file.

- imagery/i.albedo/i.albedo.html
- raster/r.li/r.li.html
This PR removes the unneeded header of the `r.li.html` metapage.
Additionally:
- minor style fix in `i.albedo.html`
> docs: i.albedo and r.li manual HTML fixes

- raster/r.kappa/mask.c
- raster/r.report/maskinfo.c
Use Rast_mask_status in r.report code which reports about raster mask including categories of underlying reclassified raster (if any).
This also makes the same change in the r.kappa code which uses the same mask report code as r.report.
> r.report: Work with any mask name (also for r.kappa)

- raster/r.random.cells/init.c
- raster/r.random.surface/init.c
- raster/r.surf.contour/main.c
Use Rast_mask_status instead of hardcoded name MASK for r.surf.contour, r.random.cells, and r.random.surface. Raster mask if present, is loaded in a special way in these tools. After this change, the name of the mask is retrieved from the library (that's the important part) and the library is at the same time used to test the presence of the mask (as opposed to testing presence of raster directly, but that's just more convenient).
The code in r.random.surface switching the if and else branches to make it easier to write and more consistent with the other two.
> raster: Work with any mask name (r.surf.contour, r.random.cells, r.random.surface)

- raster/r.volume/main.c
- raster/r.volume/r.volume.html
Avoid hardcoded MASK by using the Rast_mask_status function. The rest of the logic stays the same so mask
is read just as the plain raster map is read.
Documentation is updated to use 'raster mask' instead of 'MASK'.
> r.volume: Work with any mask name

- raster/r.to.vect/areas_io.c
This pull request fixes issue identified by coverity scan (CID : 1207812).
Existing function Vect_destroy_line_struct() is used.
> r.to.vect: Fix Resource Leak issue in areas_io.c

- .github/workflows/create_release_draft.yml
Extracting the tarball will with this create a containing directory named 'grass-x.y.z', where x, y, z stands for major, minor, micro/patch version.
Previously, the tarball created by CI was extracted to a directory named 'grass', which was a regression to accustomed and expected behaviour.
> CI: create versioned directory name of extracted tarball

- lib/gis/file_name.c
When execution takes else path, pname, a pointer, is set to point to a local variable array which has limited scope. This same pointer is accessed outside of the block containing the local variable, essentially creating a scenario where we are accessing memory outside its score, which is undefined behavior.
Move the variable array out of the loop, so that it has the same scope as pname.
This was found using cppcheck static analysis tool.
> lib/gis: Fix out of scope memory access error in file_name function call

- .flake8
- python/grass/temporal/temporal_topology_dataset_connector.py
Added `KeyError` for values no present in the dictionary
> temporal: Fixed bare 'except' PEP8 error

- raster3d/r3.out.v5d/binio.c
Fix regression introduced by 8dced26.
Reported by Coverity Scan CID 1565401.
> r3.out.v5d: fix broken LITTLE ifdef-else macro in read_float4()

- .flake8
- python/grass/temporal/temporal_raster_base_algebra.py
Added `AttributeError` as a possible exception on `.get_id()`. Possible `TypeError` if `map_i` can be of wrong type
> temporal: Fix bare 'except' in temporal_raster_base_algebra

- imagery/i.topo.corr/main.c
This pull request fixes issue identified by Coverity Scan (CID: 1208241)
> i.topo.corr: Fix Copy into fix Buffer size issue

- raster/r.mfilter/getfilt.c
This pull request fixes issue identified by Coverity Scan (CID:1207590).
Used fclose() to fix this issue.
> r.mfilter: Fix resource leak issue in getfilt.c

- lib/vector/Vlib/remove_duplicates.c
This pull request fixes issue identified by Coverity Scan (CID : 1207797, 1207793, 1207795).
Used existing functions Vect_destroy_line_struct(), Vect_destroy_cats_struct(), Vect_destroy_boxlist().
> lib/vector/Vlib: Fix resource leak issue in remove_duplicates.c

- scripts/r.grow/testsuite/test_grow.py
This PR introduces a new set of tests for the `r.grow` module. These tests focus on specific growth and shrink behaviors, customized metrics, and handling non-standard values. Below is a summary comparing the existing tests with the new ones.
**Comparison of New and Existing Tests**
1. Existing Tests:
- Maps Used: Primarily focuses on predefined maps (`lakes`, `elevation`).
- Growth and Shrink Operations: Simple tests for basic `r.grow` usage, with specific scenarios like growing (radius=10) and shrinking (radius=-10).
- Shrink Test without NULLs: Tests shrinking for a map without NULL values and verifies the output range using `r.describe`.
2. New Tests Added:
- Small Test Map: Uses a 10x10 region `test_map` with a centered 3x3 block for verification of growth patterns.
- Growth with …
> r.grow: added test file for r.grow module

- .flake8
- gui/wxpython/tplot/frame.py
Following changes
- 'y' variable removed
- `AttributeError`, `TypeError` and `ValueError` added
> wxGUI: Fixed unused variable and bare 'except' in frame.py

- .flake8
- gui/wxpython/rlisetup/sampling_frame.py
- gui/wxpython/rlisetup/wizard.py
Removed following errors:
- removed unused variable `item` from `sampling_frame.py`
- added `AttributeError` incase object is `None` in `wizard.py`
> wxGUI: Removed PEP8 errors from rlisetup/

- lib/gis/lz4.c
- lib/gis/lz4.h
Sync lz4 library with the upstream version v 1.10.0.
This has fixes simplifying and making the library robust in multiple areas.
This also fixes the initial null pointer arithmetic error found by cppcheck, which prompted syncing with the upstream library for new fixes and updates.
> lib/gis: Update lz4 library to latest upstream version (v1.10.0)

- raster/r.in.poly/r.in.poly.html
- raster/r.surf.idw/r.surf.idw.html
- temporal/t.vect.univar/t.vect.univar.html
This small PR fixes
- HTML id attributes
- a `href` typo
> docs: fix broken HTML

- .flake8
- gui/wxpython/wxplot/base.py
- gui/wxpython/wxplot/histogram.py
- gui/wxpython/wxplot/profile.py
Following PEP8 errors were fixed in `wxplot/`
- profile.py:253 - Replaced bare except with `except IndexError` when handling list.pop() failure
- profile.py:489 - Added specific exceptions `(ValueError, TypeError, KeyError)` for NumPy statistical calculations
- base.py:207 - Added `CalledModuleError` catch for GRASS raster info parsing failures
- base.py:273 - Added `(IndexError, CalledModuleError)` catch for raster pair info parsing and index access
- histogram.py - Added `Exception` as I could not find any specific exceptions which maybe applicable
> wxGUI: Fixed PEP8 errors in wxplot/

- .flake8
- python/grass/pygrass/tests/benchmark.py
> tests: replaced module imports to the top

- .travis.yml
_**TL;DR:** I resigned myself to use the pyenv available on the Travis runner to set the global python version to 3.10, already installed in the image._
-------
I don't understand why or how Travis does this. Without any announcements, github repo activity, community forum post, docs update or nothing, in the last image update yesterday, the default python version went from python 3.10.2 (https://app.travis-ci.com/github/OSGeo/grass/jobs/628247792#L121) with gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, to Python 3.7.17 (https://app.travis-ci.com/github/OSGeo/grass/jobs/628271965#L119). Python 3.10 is supposed to be the default version from ubuntu jammy's apt repos, so something is going on with how they create their images, or don't control enough.
Complicated by the fact that the …
> CI(Travis): Set python version to 3.10 through pyenv global

- man/build_md.py
At time the GRASS GIS main compilation with addons with `cron_grass_preview_build_binaries.sh` is broken:
https://grass.osgeo.org/grass85/binary/linux/snapshot/build.log.txt
```
...
Parsing <v.what.strds.timestamp>... SUCCESS
Parsing <wx.metadata>... FAILED
Parsing <wx.mwprecip>... FAILED
Parsing <wx.stream>... FAILED
Parsing <wx.wms>... FAILED
+ cp /home/neteler/.grass8/addons/modules.xml /var/www/code_and_data/addons/grass8/modules.xml
+ export ARCH
+ export ARCH_DISTDIR=/home/neteler/src//main/dist.x86_64-pc-linux-gnu
+ export GISBASE=/home/neteler/src//main/dist.x86_64-pc-linux-gnu
+ export VERSION_NUMBER=8.5
+ python3 /home/neteler/src//main/man/build_keywords.py /var/www/code_and_data/grass85/manuals/ /var/www/code_and_data/grass85/manuals/addons/ …
```
> man: fix KeyError: 'MDDIR' in man/build_md.py

- lib/vector/Vlib/dbcolumns.c
A local array was used to store column name and column type for each column, and a pointer to this local array was stored and accessed outside its scope, which can cause undefined behavior.
To avoid this, use memory from heap to store this information so that it's accessible outside where its defined and free this memory at the end to avoid memory leaks.
This issue was found using cppcheck static analysis tool.
> lib/vector/Vlib: Fix out-of-scope memory access

- vector/v.in.ascii/points.c
This pull request fixes issues identified by Coverity Scan (CID : 1207778, 1207779, 1207780)
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct(), G_free()
> v.in.ascii: Fix Resource Leak issue in points.c

- vector/v.univar/main.c
This pull request fixes issue identified by coverity scan (CID : 1207787, 1207788)
Used Vect_destroy_line_struct() to fix this issue.
> v.univar: Fix Resource Leak issue in main.c

- vector/v.net/arcs.c
This pull request fixes issue identified by Coverity Scan (CID : 1207755)
Used Vect_destroy_line_struct() to fix this issue.
> v.net: Fix Resource Leak issue in arcs.c

- lib/gis/parser_rest_md.c
This PR updates the Markdown support in the parser for the manual in terms of
- converting keywords to lowercase in manual pages so that e.g. `dist.x86_64-pc-linux-gnu/docs/mkdocs/site/keywords.html#modis` works
- replacing of `.html` with `.md` in certain cases
> lib/gis: markdown parser lowercase and extension fixes

- include/Make/DB.make
This PR fixes https://github.com/OSGeo/grass/pull/4740#issuecomment-2493971349
Note that links remain broken if GRASS is not built with specific driver support. See broken MySQL links in https://grass.osgeo.org/grass84/manuals/databaseintro.html#creating-a-database. This issue should be addressed by separated PR or at least reported as GitHub issue.
> make: Update DB.make for markdown support

- db/databaseintro.html
- doc/projectionintro.html
- gui/Makefile
- gui/wxguiintro.html
- gui/wxpython/docs/wxGUI.html
- imagery/imageryintro.html
- man/build_html.py
- man/build_md.py
- man/build_rest.py
- man/mkdocs/mkdocs.yml
- raster/rasterintro.html
- raster3d/raster3dintro.html
- temporal/temporalintro.html
- vector/vectorintro.html
While the Graphical User Interface is important it lacked an own "landing page" which also appears in the markdown sidebar.
This PR adds a wxGUI introduction page.
New menu entry:
New page:
New menu entry:
New page:
Notes:
- the content may still be improved. Scope is not to replicate wxGUI.html but to give a general overview which was missing so far.
- the missing caps in the MD page first heading is a general issue which affects all "meta" pages (to be fixed in a new PR).
> docs: add Intro: Graphical User Interface

- vector/v.buffer/v.buffer.html
Something to consider: is the following commented part still relevant? If not it could perhaps be deleted, if yes it could perhaps be made a visible part of the manual. There is another reference to the GRASS buffer, so perhaps it is still worth keeping it as a note or comment near the end?
```
```
> docs: v.buffer.html minor edits

- .flake8
- python/grass/pygrass/raster/category.py
Used `isinstance()` instead of `==` for type instance checks
> raster: Fixed PEP8 - E721 for category.py

- raster/r.water.outlet/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1208243)
> r.water.outlet: Fix Copy into buffer size issue

- raster/r.in.pdal/info.cpp
> r.in.pdal: use different variable name to avoid confusion

- configure
- configure.ac
- include/grass/config.h.in
- raster/r.in.pdal/grassrasterwriter.h
with a simple version check in the code to speed up configure process
As discussed in the https://github.com/OSGeo/grass/pull/4750
> r.in.pdal: replace HAVE_PDAL_NOFILENAMEWRITER configure definition

- vector/v.build.polylines/walk.c
This pull request fixes issue identified by Coverity Scan (CID : 1207763)
Used Vect_destroy_cats_struct() to fix the issue.
> v.build.polylines: Fix Resource Leak issue in walk.c

- .flake8
- gui/wxpython/startup/locdownload.py
Fixed following errors:
- Removed `try-except` for `E722` since except module didn't perform any specific error handling
- Added `noqa` for `F401` since `set_gui_path()` might be required to import the modules
> wxGUI: Fixed PEP8 error in startup/

- vector/v.out.dxf/main.c
This pull request fixes issue identified by coverity scan (CID : 1207804, 1207805)
Vect_destroy_line_struct(), Vect_destroy_cats_struct() are used to fix these issues
> v.out.dxf: Fix Resource Leak issue in main.c

- .cppcheck-suppressions
For past few months, I have been working on sorting errors thrown by `cppcheck` static analysis tool into true positives and false positives manually and fixing the true positives. I believe I was able to fix all the issues arising from the tool.
The file added as part of this PR contains information on false positives and some true positives (for which pull requests are opened and are in discussion. #4702, #4638, #4500, #4499). For false positives which are not obvious, I have added explanations on why there tagged as such.
Once this file is added to the project, we can work on a CI action which takes this suppression file and runs `cppcheck` on any new changes to the project, thus finding new issues if there are any.
Sample way to run using the suppressions file is: `cppcheck …
> check: Add supression file for false positives and pending fixes for cppcheck tool

- lib/gis/debug.c
lib/gis: Refactor va_list usage in debug module
va_list() macro initializes va_list structure before it's usage,
and each va_list() call has to be accompanied by corresponding
va_end() macro call on the same va_list structure.
By having these macros directly before and after the va_list
structure usage, reduces the number of places we need to keep
track of whether the va_list structure was properly inintialized
or closed.
> lib/gis: Refactor va_list usage in debug module

- imagery/i.pca/main.c
This pull request fixes issue identified by coverity scan (CID : 1207830, 1207835, 1207833, 1207834, 1207836, 1207837)
G_free() is used.
> i.pca: Fix Resource Leak issue

- lib/raster3d/index.c
This pull request fixes issue identified by coverity scan (CID : 1207806)
Used Rast3d_free() to fix the issue.
> lib/raster3d: Fix Resource Leak issue

- lib/gpde/n_arrays_io.c
This pull request fixes issue identified by Coverity Scan (CID: 1207769, 1207770, 1207771)
> lib/gpde: Fix Resource Leak issue in n_arrays_io.c

- display/d.histogram/pie.c
This pull request fixes issue identified by Coverity Scan (CID : 1208334)
> d.histogram: Fix Copy into buffer size issue

- vector/v.to.db/query.c
This pull request fixes issue identified by coverity scan (CID : 1207656, 1207657, 1207658)
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct(), Vect_destroy_field_info().
> v.to.db: Fix Resource Leak issue in query.c

- scripts/v.in.wfs/v.in.wfs.py
i suppose that as the same was printed and debug-messaged, it should be just debug message
* also, change the debug message to b more understandable
> v.in.wfs: remove an extra print copying a debug message

- gui/wxpython/gmodeler/canvas.py
it brings performance improvement and more readable code
> CQ: replace a loop by a list comprehension in gmodeler.canvas

- gui/wxpython/gmodeler/canvas.py
no need to run the same `if` condition twice when the interluding one could be inserted in
> CQ: optimise if conditions in gmodeler.canvas

- raster/r.out.gdal/attr.c
This PR solves an old TODO by writing both labels and colors to a raster attribute table (RAT) with `r.out.gdal -t`.
Newer QGIS versions can now also read raster attribute tables and will use the labels and/or colors listed in a RAT.
Test with
```
g.region -p rast=landcover_1m
r.out.gdal in=landcover_1m out=landcover_1m.tif format=GTiff createopt="COMPRESS=DEFLATE" -t
gdalino landcover_1m.tif
```
in the NC sample dataset.
> r.out.gdal: raster attribute table export enhancement

- .flake8
- python/grass/pygrass/raster/__init__.py
Added to `noqa` for this flake8 to preserve module load order
> raster: Fixed E402 by adding `noqa` exception

- raster/r.clump/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1208242)
> r.clump: Fix Copy Buffer Size Issue

- raster/r.stats/cell_stats.c
This pull request fixes issue identified by Coverity Scan (CID : 1207663)
> r.stats: Fix Resource Leak Issue

- ps/ps.map/ps_vlines.c
This pull request fixes issue identified by Coverity Scan (CID: 1207641, 1207642, 1207643)
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct() to fix this issue.
> ps.map: Fix Resource Leak issue in ps_vlines.c

- vector/v.net/report.c
This pull request fixes issue identified by Coverity Scan (CID: 1207652,1207653)
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct() to fix this issue.
> v.net: Fix Resource Leak issue in report.c

- lib/raster/put_title.c
This pull request fixes issue identified by Coverity Scan (CID: 1207660)
used remove() to fix this issue.
> lib/raster: Fix Resource Leak issue in put_title.c

- .dockerignore
For docker alpine build, this fix prevents the following error during GRASS GIS configure step:
`checking for GRASS GIS headers commit date... fatal: bad object HEAD 2024-12-10T08:46:00+00:00`
With this fix it correctly returns:
`checking for GRASS GIS headers commit date... 2024-11-29T10:01:48+00:00`
> docker: Do not ignore certain git folder for docker build

- scripts/v.in.wfs/v.in.wfs.py
the current one said that the downloaded XML cannot be found (not really what was going on) - this one reports the meaningful content of the service exception report instead
> v.in.wfs: improve error message for ServiceException

- .flake8
- gui/wxpython/mapwin/graphics.py
Replace bare except with specific exception handling (wx.PyDeadObjectError, KeyError) to handle cases where the PDC object is destroyed or ID doesn't exist.
> wxGUI: Fix bare except in graphics.py

- locale/po/grassmods_es.po
Fix wrong message translation in `v.distance`:
"distancia máxima --> distancia mínima"
Fixes #4855
> i18n: fix translation sentence in po/grassmods_es.po

- pyproject.toml
- python/grass/temporal/testsuite/test_temporal_doctests.py
All files except one were using `import grass.temporal as tgis` naming convention.
This PR fixes the only file not using this pattern, and adds `tgis` as the expected alias for importing `grass.temporal`.
> style: Define `import grass.temporal as tgis` as an import convention

- python/grass/temporal/gui_support.py
Relates to #4838.
In all of our python library code (mostly under grass.script), `ScriptError` is used from an import of `grass.exceptions`, instead of relying on that it might be imported through grass.script.
This PR uses an explicit import of grass.exceptions.
See all usages of `ScriptError` in the following screenshot (collapsed the results in gui/ subfolder)
> temporal: Use ScriptError from grass.exceptions in grass.temporal.gui_support

- python/grass/temporal/datetime_math.py
`grass.temporal.datetime_math.datetime_to_grass_datetime_string()` checks for `None`, and handles the case where it is `None`, so the `dt` argument can safely be `None`.
This fixes some pylance type checking errors in `_pretifyTimeLabels()`  of gui/wxpython/animation/temporal_manager.py, which rightfully detected that the result of `tgis.string_to_datetime(start)` can be either `datetime` or `None` and that `None` wouldn't be accepted into `datetime_to_grass_datetime_string()`.
> temporal: Adjust typing annotation for `datetime_to_grass_datetime_string()`

- python/grass/temporal/testsuite/unittests_temporal_raster_algebra.py
Fixes the following Pylance error: Method declaration "test_temporal_select" is obscured by a declaration of the same name
Two tests one right after the other had the same name.
The difference between the two tests with the same name are:
```diff
def test_temporal_select(self) -> None:
"""Testing the temporal select operator."""
tra = tgis.TemporalRasterAlgebraParser(run=True, debug=True)
-        tra.parse(expression="R = A : A", basename="r", overwrite=True)
+        tra.parse(expression="R = A : D", basename="r", overwrite=True)
D = tgis.open_old_stds("R", type="strds")
D.select()
-        self.assertEqual(D.metadata.get_number_of_maps(), 4)
-        self.assertEqual(D.metadata.get_min_min(), 1)
+        self.assertEqual(D.metadata.get_number_of_maps(), 2)
+ …
```
> temporal: Rename duplicate test name in unittests_temporal_raster_algebra.py

- lib/display/tran_colr.c
This pull request fixes issue identified by Coverity Scan (CID : 1208305)
Also rearranged the headers alphabetically.
> lib/display: Fix Copy Buffer Size issue in tran_colr.c

- .flake8
- gui/wxpython/vdigit/mapwindow.py
- gui/wxpython/vdigit/preferences.py
- gui/wxpython/vdigit/toolbars.py
- gui/wxpython/vdigit/wxdigit.py
- gui/wxpython/vdigit/wxdisplay.py
FIxed 'F841' by removing unused variables in `vdigit\`
> wxGUI: Removed unused variables in vdigit/

- raster/r.statistics/o_adev.c
This pull request fixes issue identified by Coverity Scan (CID: 1207914)
> r.statistics: Fix Resource Leak issue in o_adev.c

- lib/rst/interp_float/segmen2d.c
This pull request fixes issue identified by Coverity Scan (CID : 1207919)
> lib/rst/interp_float: Fix Resource Leak issue in segmen2d.c

- python/grass/temporal/c_libraries_interface.py
There were warnings that functions were stored in a list that expected ints, and that ints weren't callable. Adjust typing so we can catch if a function added doesn't have the same signature in the future.
> temporal: Tune typing of functions list in c_libraries_interface

- gui/wxpython/psmap/utils.py
Current code didn't handle the case where angle is 0, nor if out of range. For example, calling with an angle of 375.7 will try to compute the width and height on variables not set yet.
Adding fmod (https://docs.python.org/3/library/math.html#math.fmod, better suited for floats than the modulo operator), will help the case of 360 degrees, that will become 0 degrees, and return the width and height directly. Technically the angle could be bigger than 360 and still handled correctly, but, contrary to the modulo operator, the mathematical definition used by fmod means that a negative angle will (could) return a negative angle, that isn't handled in the previous code, nor this small improvement. Something close to https://numpy.org/doc/stable/reference/generated/numpy.unwrap.html could help …
> gui: Fix possibly unbound variables in psmap.utils.BBoxAfterRotation

- gui/wxpython/core/menutree.py
Fixes format-string-without-interpolation / W1310.
Pylint rule: https://pylint.pycqa.org/en/latest/user_guide/messages/warning/format-string-without-interpolation.html
No other violation was found with pylint 3.3.2 (that I'm setting up)
> gui: Fix using formatting for a string that does not have any interpolated variables in core.menutree

- gui/wxpython/psmap/utils.py
- python/grass/script/core.py
Fully type check and annotate convertRGB() and the grass.script.core.parse_color() functions
The psmap.utils.convertRGB is in fact two separate functions, that takes two different kinds of inputs and outputs the other kind. It is correctly represented with an overload.
All places where grass.script.core.parse_color() was used were checked, and it was only here. The generator inside the tuple constructor was changed to a fixed size tuple literal, in order to have simpler signature than `tuple[float, float, float] | tuple[float, ...] | None`, where the `tuple[float, ...]` is for tuples of float of unknown length, which had an impact on static analysis in convertRGB.
I needed to wait for #4873 to be merged to avoid conflicts, they were successive commits in my pylint 3 working branch.
> gui: Fix possibly indexing None in psmap.utils.convertRGB

- utils/release.yml
There isn't a lot a flexibility in the allowed titles for GUI PRs. the prefix wxGUI is not adapted for everything, so allow convential-commits -styled scopes on gui PRs, like other of our categories.
Edit: I also expect us to have PRs for MkDocs specifically soon, so added them as recognized in the docs category
> utils: Allow scopes for gui PR titles

- python/grass/script/utils.py
This small PR adds some type annotations to some functions (that weren't in classes).
With the `from __future__ import annotations`,  the annotations are stringified, so aren't parsed at runtime. (It also allows the `|` for unions to support a common syntax between our supported versions.
The extra imports only happen when type checking. Type checkers set `TYPE_CHECKING` to true, and they bundle the typeshed stdlib for some common useful definitions
> grass.script.utils: Add type hints to some functions

- general/g.tempfile/g.tempfile.html
- imagery/i.ortho.photo/i.ortho.transform/i.ortho.transform.html
- imagery/imageryintro.html
- raster3d/r3.to.rast/r3.to.rast.html
- scripts/db.in.ogr/db.in.ogr.html
- scripts/r.mapcalc.simple/r.mapcalc.simple.html
- vector/v.edit/v.edit.html
Improve CSV import example with GDAL related column type autodetection (suggested by @cmbarton).
Fixes #4674 (see also related issue #4593).
Additionally:
- minor HTML fixes in some manual pages
> manual: db.in.ogr add column type detection for CSV

- .flake8
- python/grass/pydispatch/saferef.py
wrt to #1809 
This PR updates the  `__cmp__` method in `saferef.py` to be compatible with Python 3. Comparison methods `__eq__`
and `__lt__` are implemented to maintain the same functionality without requiring changes elsewhere in the code.
**Changes:**
- Added `__eq__` method for equality comparison.
- Added `__lt__` method for less-than comparison.
- The `__cmp__` method now uses the rich comparison methods for its logic.
This shouldn't change overall behavior of `saferef` class.
> lib: Replaced __cmp__ method with compensating methods for Python3 functionality

- pyproject.toml
- python/grass/gunittest/checkers.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/error/unsupported-membership-test.html
> style: Fix E1135: Value 'b_keys' doesn't support membership test (unsupported-membership-test)

- pyproject.toml
- python/grass/gunittest/reporters.py
Pylint rule: https://pylint.pycqa.org/en/latest/user_guide/messages/convention/unidiomatic-typecheck.html
> style: Fix C0123: Use isinstance() rather than type() for a typecheck (unidiomatic-typecheck)

- gui/wxpython/gui_core/forms.py
- gui/wxpython/modules/import_export.py
- pyproject.toml
- python/grass/script/task.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/simplifiable-if-statement.html
> style: Fix R1703: The if statement can be replaced with 'var = bool(test)' (simplifiable-if-statement)

- gui/wxpython/gui_core/wrap.py
- gui/wxpython/mapdisp/gprint.py
- pyproject.toml
- python/grass/gunittest/reporters.py
- python/grass/pygrass/raster/__init__.py
- python/grass/pygrass/vector/find.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/useless-parent-delegation.html
> style: Fix W0246: Useless parent or super() delegation in method '__init__' (useless-parent-delegation)

- gui/wxpython/mapdisp/frame.py
- gui/wxpython/nviz/mapwindow.py
In preparation for my next PR, this only adds some typing to the lmgr argument, as it was really hard to figure out where it came from and what is allowed to be called with it. I ended up needing to do some runtime inspection. There are two types that I found that this lmgr could be: GMFrame from lmgr.frame (multiple windows), or GMFrame from main_window.frame (single window).
Adding these types here help to resolve **ALOT** of typing checks, since otherwise nothing is known (even by a human reading). I consider this a sort of documentation improvement.
- [gui: Add typing for layer manager lmgr argument](https://github.com/OSGeo/grass/commit/d619a7a9463f180c4c1ae57ce08f254154032019) 
The runtime type is main_window.frame.GMFrame, for both mapdisp.frame.MapPanel and nviz.mapwindow.GLWindow …
> gui: Add types for lmgr constructor argument of GLWindow (3D) and MapPanel (2D)

- gui/wxpython/tplot/frame.py
- pyproject.toml
- python/grass/temporal/temporal_operator.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/unnecessary-negation.html
> style: Fix C0117: Consider changing "not self.optype == 'boolean'" to "self.optype != 'boolean'" (unnecessary-negation)

- gui/wxpython/gcp/manager.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/photo2image/ip2i_manager.py
- pyproject.toml
- python/grass/imaging/images2swf.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/super-init-not-called.html
> style: Fix W0231: __init__ method from base class is not called (super-init-not-called)

- gui/wxpython/core/globalvar.py
- gui/wxpython/gcp/manager.py
- gui/wxpython/image2target/ii2t_manager.py
- gui/wxpython/location_wizard/wizard.py
- gui/wxpython/rlisetup/wizard.py
See https://docs.wxpython.org/wx.adv.WizardEvent.html for the event type, that contains the GetDirections()
I skipped annotating the return type on some event handlers that also returned a string. It is better to only add type hints when it is certain rather than add misleading type hints. (Type checkers try to deduce the types when there are no type hints). It is probably an error of some sort, as handlers shouldn't be returning something. I tried to go back like 15 years ago and still couldn't find the correct solution. (15 years ago that text was in a function returning messages, I didn't investigate to see if it was the correct place now.  Search for "Datum transform is required" in 9228877d8bdfd680e9c7bdfd44a06213585988fe and 8a40775763203d7c546b682de937984cfb096abb)
> gui: Add type hints to bound WizardEvent handlers

- gui/wxpython/lmgr/giface.py
- pyproject.toml
- python/grass/pygrass/gis/__init__.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/unnecessary-comprehension.html
These two occurrences already disabled an equivalent Ruff rule coming from flake8 in #4453, as there was a recursion issue
> style: Ignore R1721: Unnecessary use of a comprehension, use list(self) instead. (unnecessary-comprehension)

- gui/wxpython/animation/anim.py
- gui/wxpython/animation/controller.py
- gui/wxpython/photo2image/ip2i_manager.py
- gui/wxpython/rdigit/dialogs.py
- gui/wxpython/rdigit/toolbars.py
- gui/wxpython/rlisetup/wizard.py
- pyproject.toml
- python/grass/pygrass/vector/geometry.py
Pylint rule: https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/useless-return.html
Some event handlers were surprisingly empty. For these I kept the condition to leave a clue for future edits, but needed to use "pass" in order to keep correct syntax.
For example, the "OnGeoRectDone", introduced in 22f86d9e4645938a2d5d879ebf6f31eb2eefc8d6, was empty there too. However, it seems like a mostly a copy from another active file in the repo, shown below, but the remaining of the function doesn't make sense in the context of the new file.
https://github.com/OSGeo/grass/blob/93a5f04df7bdb13c74eaef63c5a4443133482d46/gui/wxpython/image2target/ii2t_manager.py#L1823-L1839
> style: Fix R1711: Useless return at end of function or method (useless-return)

- python/grass/pydispatch/saferef.py
After stepping through a lot with PDB, I suggest this to fix the hang described in https://github.com/OSGeo/grass/pull/4684#issuecomment-2564316815 and https://github.com/OSGeo/grass/pull/4684#issuecomment-2564383430
It isn't a question of missing `__le__`, `__ge__`, `__ne__` as the replacement of `__cmp__` with all rich comparisons. They don't get called. The current (before #4684) `__cmp__` method isn't called at all in Python 3 (breakpoint isn't hit, while other do).
In #4684, the `__eq__` method gets called by the `list.index` from the receivers.index(receiver) in here:
https://github.com/OSGeo/grass/blob/7f1934ffcd5011d1df1bddb5c13a9f0456233823/python/grass/pydispatch/dispatcher.py#L448-L478
Looking at the locals() available in debugging at various stack levels, I see no real …
> lib: Fix safeRef regression after removing `__cmp__` in #4684

- imagery/i.group/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1207881)
> i.group: Fix Resource Leak issue in main.c

- ps/ps.map/ps_vpoints.c
This pull request fixes issue identified by Coverity Scan (CID : 1207905, 1207907)
Used Vect_destroy_line_struct(), G_free() to fix this issue.
> ps.map: Fix Resource Leak issue in ps_vpoints.c

- gui/wxpython/nviz/wxnviz.py
I have pretty much added typing annotations to all the wxnviz file, reading the doxygen docs and the C library to inject new knowledge and validate the correct usage inside this file.
However, before finishing up assimilating that new info into other files, I extracted the simples changes that don't require any other import, and work correctly (at least for Python 3.9+) without stringified annotations (with the `from __future__ import annotations`.
The remaining will come soon, but I'd like to avoid too much conflicts with different imports.
> gui(nviz.wxnviz): Add simple type hints not needing any imports

- pyproject.toml
- python/grass/gunittest/case.py
- python/grass/gunittest/runner.py
- python/grass/imaging/images2gif.py
- python/grass/jupyter/setup.py
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/utils.py
- python/grass/pygrass/vector/table.py
- python/grass/script/tests/grass_script_setup_test.py
- python/grass/temporal/mapcalc.py
- python/grass/temporal/spatial_topology_dataset_connector.py
- python/grass/temporal/temporal_vector_algebra.py
This PR contains the remaining refactorings selected from a pyrefact run on the python/grass folder (it generated near 300 changed files, some weren't important or relevant, so they were reverted). It took the day to review through this.
These changes are miscellaneous, and not a lot of each kind to merit their own PRs, they are grouped together.
I finish this by removing ruff exclusions that were previously fixed, in this PR _OR_ in other PRs. I commented out everything, and added back until there were no failures, and removed the exclusions that weren't placed back.
> python: Various remaining pyrefact refactorings

- gui/wxpython/core/layerlist.py
The previous code was appending the selected layer whether it was active or not. It doesn't seem expected, as it could be simplified to the following below. These lines were there since the file was introduced like 11 years ago.
A simplified version of the previous code:
```python
def GetSelectedLayers(self, activeOnly=True):
"""Returns list of selected layers.
:param bool activeOnly: return only active layers
"""
layers = []
for layer in self._list:
if layer.IsSelected():
layers.append(layer)
if activeOnly and layer.IsActive():
pass
else:
pass
return layers
```
> gui(core.layerlist): Fix returning active layers in GetSelectedLayers()

- python/grass/imaging/images2gif.py
- python/grass/jupyter/utils.py
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/vector/__init__.py
- python/grass/pygrass/vector/abstract.py
- python/grass/pygrass/vector/geometry.py
- python/grass/pygrass/vector/table.py
- python/grass/script/raster.py
- python/grass/temporal/abstract_dataset.py
- python/grass/temporal/abstract_map_dataset.py
- python/grass/temporal/list_stds.py
- python/grass/temporal/mapcalc.py
- python/grass/temporal/sampling.py
- python/grass/temporal/spatial_extent.py
- python/grass/temporal/spatio_temporal_relationships.py
- python/grass/temporal/stds_import.py
- python/grass/temporal/temporal_raster_base_algebra.py
- python/grass/temporal/temporal_vector_algebra.py
PR containing only typos and formatting changes for docstrings in python/grass
> python: Fix typos and formatting of docstring parameters

- gui/wxpython/history/tree.py
Provide `Copy` command feature on right-click for commands in the GUI History panel.
For reporting bugs it's helpful to copy particular commands from history. Presently, there is just the `Remove` command.
Compiled and executed the Grass application locally. Can observe the new `Copy` command in the History Panel on right-clicking a command.
#4385
> gui: Add Copy command feature on right-click to GUI History panel

- .github/workflows/codeql-analysis.yml
GitHub Actions was recently added to CodeQL https://github.blog/changelog/2024-12-17-find-and-fix-actions-workflows-vulnerabilities-with-codeql-public-preview/
This enables it. I'm already working on some little fixes on default permissions, but nothing stood out here
> CI(CodeQL): Add `actions` language support in CodeQL

- .flake8
- python/grass/temporal/temporal_granularity.py
Add specific exceptions for E722 in `temporal_granularity.py` i.e `ValueError`. Didn't add `TypeError` for `None` objects which seemed less likely to occur via code error.
> temporal: Fixed E722 in temporal_granularity

- .flake8
- python/grass/temporal/datetime_math.py
This PR addresses flake8 E722 warnings by replacing bare `except` clauses with specific exception handling in the datetime_math.py module.
- Replace bare `except` after dateutil import with explicit `(ImportError, ModuleNotFoundError)`
- Replace bare `except` in datetime parsing with explicit `(ValueError, TypeError)`
> temporal: Fix bare except clauses in datetime_math.py

- raster/r.path/main.c
This PR adds support for the power-of-two encoding CW from East (e.g., r.terraflow, ArcGIS).
The default bitmask encoding starts CW from NE, some programs use a 45-degree rotated (one bit shifted) version of the bitmask encoding (e.g. r.terraflow, ArcGIS). The new `-e` (East) flag uses `y=2^((log2(x)+1)%8)` to convert the latter encoding to the default one before tracing.
The PR also adds `-b` flag to avoid breaking lines unnecessarily for single-direction paths.
How to test in the NC sample dataset
```bash
r.terraflow elevation direction=dir -s
r.path dir vec=path scoor=638317.91,220399.94 -be
```
> r.path: Support bitmask encoding CW from East

- .flake8
- python/grass/temporal/spatial_topology_dataset_connector.py
Fix flake8 E722 errors in spatial topology connector
Replace bare 'except' clauses with explicit 'except KeyError' in get_number_of_spatial_relations() method
> temporal: Fixed bare except clauses in spatial_topology_dataset_connector.py

- pyproject.toml
- utils/create_python_init_file.py
- utils/g.html2man/g.html2man.py
- utils/md_isvalid.py
- utils/mkrest.py
- utils/ppmrotate.py
- utils/thumbnails.py
I tried out a tool called pyrefact. While not that safe and stable (hanged on some files if not changed), it still found out some places where context managers could be used and applied these transformations. The changes by pyrefact plus some manual tweaks were enough to unlock existing ruff simplifications afterwards.
I include here some changes that were appropriate for us
> utils: Use context managers for subprocesses and opening files

- gui/wxpython/vdigit/mapwindow.py
Updates exception handling in several methods to catch specific error cases:
1. `AttributeError` in layer access operations (GetLayer().GetName()):
- Occurs when toolbar or layer is None
2. `IndexError`  in undo operation:
- `IndexError`: Occurs when trying to pop from empty polycoords list (e.g., multiple undo attempts)
> wxGUI: Add specific exception handling in vdigit/mapwindow.py

- vector/v.generalize/network.c
This pull request fixes issue identified by Coverity Scan (CID : 1207721,1207722)
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct() to fix this issue.
> v.generalize: Fix Resource Leak issue in network.c

- vector/v.to.rast/do_areas.c
This pull request fixes issue identified by Coverity Scan (CID : 1207750)
Used Vect_destroy_cats_struct() to fix this issue.
> v.to.rast: Fix Resource Leak issue in do_areas.c

- doc/README
- doc/examples/gui/wxpython/frame.py
- doc/examples/gui/wxpython/toolbars.py
- gui/wxpython/animation/toolbars.py
- gui/wxpython/datacatalog/toolbars.py
- gui/wxpython/mapswipe/toolbars.py
We don't have `trunk` anymore since we departed from SVN.
> docs: remove trunk from paths

- lib/vector/Vlib/build_nat.c
This pull request fixes issue identified by Coverity Scan (CID : 1207631)
Used Vect_destroy_cats_struct() to fix this issue.
> lib/vector/Vlib: Fix Resource Leak issue in build_nat.c

- display/d.barscale/draw_scale.c
This pull request fixes issue identified by Coverity Scan (CID : 1415718)
> d.barscale: Fix Resource Leak issue in draw_scale.c

- gui/wxpython/startup/locdownload.py
An error was highlighted mentioning error `module 'wx' has no attribute 'PyDeadObjectError'` in the relevant code. This PR is to update the code with other relevant exceptions to replace that
> wxGUI: Updated exception handling to fix AttributeNotFound error

- .flake8
- gui/wxpython/location_wizard/wizard.py
Replace bare exception handling with specific exception types to prevent masking of unexpected errors and improve error reporting.
Changes:
- Search operations: Add IndexError/ValueError for list unpacking failures
- Datum parameters: Add ValueError for list item removal
- EPSG/IAU searches: Add IndexError/ValueError for search result handling
- Ellipsoid lookups: Add IndexError/ValueError/KeyError for search and dictionary operations
- EPSG code parsing: Add ValueError for integer conversion
> wxGUI: Improve exception handling specificity in location wizard

- lib/raster/json_color_out.c
- raster/r.colors.out/tests/r3_colors_out_test.py
- raster/r.colors.out/tests/r_colors_out_test.py
- vector/v.colors.out/main.c
- vector/v.colors.out/tests/conftest.py
- vector/v.colors.out/tests/v_colors_out_test.py
fixes: #4660 
Used Parson to add JSON output format support to the `v.colors.out` module.
- Added a new `format` option, allowing users to specify the output format:
- `format=plain` for the current output format.
- `format=json` for JSON output.
- Introduced the `color_format` option to specify the color format for JSON output. Supported values for `color_format` include `rgb`, `hex`, `hsv`, and `triplet`.
The JSON output appears as follows:
```json 
[
{"value": 1, "hex": "#00BFBF"},
{"value": 20.8, "hex": "#00FF00"},
{"value": 40.6, "hex": "#FFFF00"},
{"value": 60.4, "hex": "#FF7F00"},
{"value": 80.2, "hex": "#BF7F3F"},
{"value": 100, "hex": "#C8C8C8"},
{"value": "nv", "hex": "#FFFFFF"},
{"value": "default", "hex": "#FFFFFF"},
]
```
> v.colors.out: Add JSON support

- mswindows/osgeo4w/build_osgeo4w.sh
- mswindows/osgeo4w/package.sh
Solves #4990 
(Hopefully)
I quickly applied the patch that changed downstream. I didn’t test it in CI yet, I’m just launching it here quickly.
It seems like Postgres is compiled with a different compiler now, so removing and copying a lib seems necessary. 
I also launched https://github.com/echoix/grass/pull/351
> Windows: Apply OSGeo4W patches for Postgres

- doc/examples/notebooks/parallelization_tutorial.ipynb
- imagery/i.pca/main.c
- raster/r.out.gdal/r.out.gdal.html
- raster/r.resamp.bspline/r.resamp.bspline.html
- vector/vectorintro.html
Similarly to #4401 and #4495, this replaces usage of MASK by mask or raster mask. It removes uppercase MASK when not needed.
> doc: Use lowercase for 2D raster mask

- imagery/i.smap/i.smap.html
The original text is using MASK in all caps out of context and mixes mitigating issues with plain NULLs and 2D raster mask.
This uses lowercase mask in text and names and adds a new expression to handle NULLs in the input as the text promisses.
> i.smap: Add detail to NULL handling

- mswindows/osgeo4w/build_osgeo4w.sh
- mswindows/osgeo4w/package.sh
Backport of #4996 to G84 branch
Co-authored-by: @echoix
> Windows: Apply OSGeo4W patches for Postgres (backport)

- raster/r.watershed/front/r.watershed.html
The original example uses r.mapcalc to directly create MASK and then g.remove to disable it. This now uses r.mask to activate and deactive the mask. NULLs are used in the original expression which is also what r.mask is using by default.
> r.watershed: Use r.mask, not MASK in the example

- lib/gmath/solvers_classic_iter.c
This pull request fixes issue identified by Coverity Scan (CID : 1207773, 1207774 )
> lib/gmath: Fix Resource Leak issue in solvers_classic_iter.c

- raster/r.water.outlet/over_cells.c
This pull request fixes issue identified by Coverity Scan (CID : 1207897)
> r.water.outlet: Fix Resource Leak issue in over_cells.c

- .flake8
- gui/wxpython/mapwin/base.py
- gui/wxpython/mapwin/buffered.py
Defined exceptions under mapwin/ to fix E722
> wxGUI: Fixed bare except in mapwin/

- display/d.mon/render_cmd.py
- pyproject.toml
This PR addresses SIM115 linter warnings by replacing manual file handling with context managers in `d.mon/render_cmd.py`, ensuring proper resource management. 
**Changes**:
- Use `with open(...)` context managers in `update_cmd_file`, `read_stdin`, and temporary file creation.
- Remove redundant `fd is None` checks (Python’s `open()` raises exceptions on failure).
- Simplify temporary file creation with appropriate suffixes and `delete=False` where needed
> d.mon: Fix SIM115 linter warnings by using context managers for file operations

- vector/v.in.dxf/read_dxf.c
This pull request fixes issue identified by Coverity Scan (CID : 1207848)
> v.in.dxf: Fix Resource Leak issue in read_dxf.c

- raster/r.mapcalc/expression.c
This pull request fixes issue identified by Coverity Scan (CID : 1207893)
> r.mapcalc: Fix Resource Leak issue in expression.c

- vector/v.to.db/lines.c
This pull request fixes issue identified by Coverity Scan (CID : 1207675, 1207676, 1207677, 1207678, 1207679)
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct() to fix this issue.
> v.to.db: Fix Resource Leak issue in lines.c

- gui/wxpython/core/globalvar.py
- gui/wxpython/core/render.py
- gui/wxpython/core/settings.py
- gui/wxpython/core/testsuite/test_gcmd.py
- gui/wxpython/core/toolboxes.py
- gui/wxpython/core/utils.py
- gui/wxpython/core/workspace.py
- pyproject.toml
FIxed ruff errors regarding file opening and path iteration
> wxGUI: Fixed PTH208 and SIM115 errors in core/

- vector/v.to.3d/trans3.c
This pull request fixes issue identified by Coverity Scan (CID : 1207711)
Used Vect_destroy_field_info() to fix this issue.
> v.to.3d: Fix Resource Leak issue in trans3.c

- raster/r.resamp.stats/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1207686 , 1207687, 1207688 , 1207689, 1207690, 1207691).
> r.resamp.stats: Fix Resource Leak issue in main.c

- lib/vector/Vlib/open_ogr.c
This pull request fixes issue identified by Coverity Scan (CID : 1588911)
Used fclose() to fix this issue
> lib/vector/Vlib: Fix Resource Leak issue in open_ogr.c

- lib/nviz/exag.c
This pull request fixes issue identified by Coverity Scan (CID : 1207695)
> lib/nviz: Fix Resource Leak issue in exag.c

- display/d.vect.chart/plot.c
This pull request fixes issue identified by Coverity Scan (CID : 1207639, 1207640, 1270285, 1270286).
Used Vect_destroy_line_struct(), Vect_destroy_cats_struct(), Vect_destroy_field_info(), G_free() to fix this issue.
> d.vect.chart: Fix Resource Leak issue in plot.c

- raster/r.sim/r.sim.sediment/main.c
- raster/r.sim/r.sim.water/main.c
The mask test was in a wrong place, so it didn't turn off parallelization when mask was active.
> r.sim: fix turning off parallelization with mask on

- general/g.setproj/g.setproj.html
- raster/r.li/r.li.html
- vector/v.lrs/lrs.html
This PR cleans up remaining HTML headers:
- `g.setproj.html`: remove full header (note that `g.setproj` is deprecated
- `r.li.html` and `lrs.html`: fix meta declarations
Now the `r.li` description is no longer empty:
Addresses #4972
> manual: multi-tools lack short descriptions

- pyproject.toml
- utils/generate_release_notes.py
- utils/gitlog2changelog.py
- utils/thumbnails.py
Fixed multiple ruff errors across all the files in `utils/`
> utils: Fixed ruff errors in utils/

- gui/wxpython/datacatalog/catalog.py
- pyproject.toml
Fixed `PTH208` to use `pathlib.Path.iterdir()`
> wxGUI: Fixed ruff error `PTH208` in datacatalog/

- raster/r.sim/r.sim.sediment/main.c
- raster/r.sim/r.sim.water/main.c
Fixes e495352, which was using new function available only in main.
> r.sim: properly fix turning off parallelization with mask on

- lib/vector/Vlib/net_build.c
This pull request fixes issue identified by coverity scan (CID : 1207632, 1207633, 1207634, 1207635)
Used Vect_destroy_field_info(), db_free_column() to fix this issue.
> lib/vector/Vlib: Fix Resource Leak issue in net_build.c

- imagery/i.gensigset/i.gensigset.html
- imagery/i.landsat.toar/i.landsat.toar.html
- imagery/i.ortho.photo/i.ortho.init/i.ortho.init.html
- imagery/i.ortho.photo/i.ortho.rectify/i.ortho.rectify.html
- imagery/i.pca/i.pca.html
- raster/r.clump/r.clump.html
- raster/r.covar/r.covar.html
- raster/r.fill.stats/r.fill.stats.html
- raster/r.in.xyz/r.in.xyz.html
- raster/r.mapcalc/r.mapcalc.html
- scripts/g.download.project/g.download.project.html
- vector/v.decimate/v.decimate.html
- vector/v.lidar.correction/v.lidar.correction.html
- vector/v.lidar.edgedetection/v.lidar.edgedetection.html
- vector/v.lidar.growing/v.lidar.growing.html
- vector/vectorintro.html
- visualization/ximgview/ximgview.html
Solves couple issues that showed up when building markdown documentation.
* Fix links to addons
* fix i.ortho.rectify name, wximgview
* r.average doesn't exist anymore
* replace v/r.in.lidar with v/r.in.pdal in examples and see also
> doc: fix various issues in html pages in preparation for markdown

- raster/r.geomorphon/r.geomorphon.html
There is only one trailing space in all HTML files, but there is one. This change removes it.
> doc: Remove extra space

- man/build_keywords.py
When a tool links raster or vector as a standard keyword, the link to keyword page does not go anywhere because first keyword (aka class or family) is hidden in the keywords index (overview).
This enables most of the keywords with the exception of general and misc which I assume will not be used by non-general tools as keywords.
Fixes #5049.
In addition, this changes the variable names for better documentation.
> doc: Hide only general and misc keywords in index

- lib/external/parson/test/test_main.c
The first keyword needs to be one of the (recognized) tool categories (families), not a custom keyword. r3.flow and raster3d lib tests are using this style.
> doc: Fix parson lib test first keyword

- raster/r.describe/describe.c
- raster/r.describe/dumplist.c
- raster/r.describe/local_proto.h
- raster/r.describe/main.c
`r.describe`: initialize some variables, which addresses warnings raised by Coverity Scan and scan-build.
In addition:
- add missing static specifier to function definitions
- update copyright year after JSON addition with commit 1c956f7
> r.describe: initialize some variables

- vector/v.distance/distance.c
- vector/v.distance/local_proto.h
- vector/v.distance/main.c
- vector/v.distance/print.c
Addresses issues reported by Coverity Scan and scan-build. Unused variables are only commented out (keep them as reminders just in case).
In addition; a list of macros is converted to enum, for better handling of code by compilers.
> v.distance: initialize variable; remove unused variables

- general/g.proj/datumtrans.c
- general/g.proj/input.c
- general/g.proj/output.c
Fix resource leaks in `g.proj` as reported by Coverity Scan.
> g.proj: fix resource leaks

- vector/v.to.3d/trans3.c
`v.to.3d`: initialize some variables, addressing warnings raised by Coverity Scan.
In addition:
- make sure the bsearch() count argument (ncats) is not negative
- add missing static specifier to function declaration
> v.to.3d: initialize some variables

- .github/workflows/python-code-quality.yml
It seems there was a copy-paste error, it didn't even match my comments and the title of the step, where the first run showing the diff in the CI logs was also the same call as the one that was supposed to actually change the files in order to upload the suggestions for formatting fixes too
> CI: Run ruff format with file fixes for PR suggestions

- lib/raster/quant_io.c
This pull request fixes issue identified by Coverity Scan (CID : 1207809)
> lib/raster: Fix Resource Leak issue in quant_io.c

- pyproject.toml
- python/grass/gunittest/checkers.py
- scripts/db.dropcolumn/db.dropcolumn.py
- scripts/r.rgb/r.rgb.py
- scripts/v.db.dropcolumn/v.db.dropcolumn.py
- scripts/v.in.wfs/v.in.wfs.py
RUF027 Possible f-string without an `f` prefix
Ruff rule: https://docs.astral.sh/ruff/rules/missing-f-string-syntax/
> style: Fix missing-f-string-syntax (RUF027)

- lib/vector/Vlib/remove_areas.c
This pull request fixes issue identified by Coverity Scan (CID : 1207724, 1207725, 1207726, 1207727)
Used Vect_destroy_list(), Vect_destroy_line_struct(), Vect_destroy_cats_struct()
> lib/vector/Vlib: Fix Resource leak issue in remove_areas.c

- raster/r.statistics/o_kurt.c
- raster/r.statistics/o_sdev.c
- raster/r.statistics/o_skew.c
- raster/r.statistics/o_var.c
This pull request fixes issue identified by Coverity Scan (CID : 1207718, 1207719, 1207720)
> raster/r.statistics: Fix Resource Leak issue in o_sdev.c , o_skew.c , o_var.c , o_kurt.c

- man/Makefile
Addressing comment from PR https://github.com/OSGeo/grass/pull/5048.
I've added a command to the Makefile to serve mkdocs locally.
To run make sure to follow the steps from  PR https://github.com/OSGeo/grass/pull/5048 and then you can run:
```sh
cd man
make serve-mkdocs
```
> docs: Added command to serve mkdocs locally

- display/displaydrivers.md
- general/g.findfile/g.findfile.md
- general/g.parser/g.parser.md
- general/g.version/g.version.md
- lib/init/grass.md
- raster/r.category/r.category.md
- raster/r.horizon/r.horizon.md
- raster/r.in.lidar/r.in.lidar.md
- raster/r.info/r.info.md
- raster/r.mask.status/r.mask.status.md
- raster/r.object.geometry/r.object.geometry.md
- raster/r.profile/r.profile.md
- raster/r.report/r.report.md
- raster/r.solute.transport/r.solute.transport.md
- raster/r.sun/r.sun.md
- raster/r.univar/r.univar.md
- scripts/i.band.library/i.band.library.md
- temporal/t.rast.list/t.rast.list.md
- vector/v.db.select/v.db.select.md
- vector/v.distance/v.distance.md
- vector/v.info/v.info.md
- vector/v.univar/v.univar.md
I tried to find places with python or json code snippets, but it was not an exhaustive search, so there may be some places left. Occasionally I fixed some other things I noticed around it.
> docs: fix code snippet languages

- general/g.region/g.region.md
- gui/wxpython/docs/wxGUI.iscatt.md
- imagery/i.gensigset/i.gensigset.md
- raster/r.resamp.filter/r.resamp.filter.md
- raster/r.surf.idw/r.surf.idw.md
- utils/mkdocs.py
- vector/v.label.sa/v.label.sa.md
- vector/v.random/v.random.md
Includes fixing markdown links.
> docs: fix building markdown documentation

- display/d.geodesic/d.geodesic.md
- display/d.grid/d.grid.md
- display/d.histogram/d.histogram.md
- display/d.legend/d.legend.md
- display/d.mon/d.mon.md
- display/d.rast.num/d.rast.num.md
- display/d.rast/d.rast.md
- display/d.rgb/d.rgb.md
- display/d.vect.thematic/d.vect.thematic.md
- imagery/i.atcorr/i.atcorr.md
- imagery/i.ortho.photo/i.ortho.photo/i.ortho.photo.md
- imagery/imageryintro.md
- misc/m.measure/m.measure.md
- ps/ps.map/ps.map.md
- scripts/d.correlate/d.correlate.md
- scripts/d.rast.edit/d.rast.edit.md
- scripts/i.pansharpen/i.pansharpen.md
- scripts/i.tasscap/i.tasscap.md
- scripts/r.blend/r.blend.md
- scripts/r.colors.stddev/r.colors.stddev.md
- scripts/r.drain/r.drain.md
- scripts/r.plane/r.plane.md
- scripts/v.centroids/v.centroids.md
- scripts/v.clip/v.clip.md
Fixing image syntax in tools after automatic conversion (all except raster and vector tools that are in #5092 and #5093).
> docs: fix markdown image syntax in imagery, display, misc, ps tools and scripts

- Dockerfile
- docker/alpine/Dockerfile
- docker/ubuntu/Dockerfile
Pin `gdal-grass` driver to version 1.0.3 and add cmake package to Alpine.
> docker: pin gdal-grass version to 1.0.3; add cmake dep

- lib/vector/Vlib/net_build.c
Fixing a small resource leak in #5038 did not test if there is actually some memory allocated, introducing a segmentation fault. This PR fixes #5038.
> lib/vector/Vlib: fix segfault introduced with #5038

- scripts/r.fillnulls/testsuite/test_r_fillnulls.py
Modifications:
- Added tests for bicubic interpolation.
- Implemented flags like lambda.
- Included tests for r.fillnulls with raster masks.
> r.fillnulls: Modified tests for r.fillnulls module

- pyproject.toml
- temporal/t.list/t.list.py
- vector/v.fill.holes/examples.ipynb
Fixed ruff errors regarding path and context manager
> style: Fix SIM115: Simplify if statement in t.list and PTH201 in v.fill.holes

- docker/alpine/Dockerfile
- docker/alpine/grass_tests.sh
#5111 was not enough to fix the Alpine docker build. `gdal-grass` CMake config uses `grass` for setting paths and requires a working state of grass.
This was not the case because of:
https://github.com/OSGeo/grass/blob/d3993e2852b8ef4d0de1c748aa6376db4db54d26/docker/alpine/Dockerfile#L171
just before the gdal-grass build started.
This moves the gdal-grass build immediately after grass is built, this hopefully will solve this issue.
> docker: build gdal-grass with grass in working condition

- docker/alpine/Dockerfile
- docker/alpine/grass_tests.sh
https://github.com/OSGeo/grass/commit/d657e54da3cdf0a341d6c69e49678fb12db2366b didn't quite work out . The drivers were linked to grass libraries which was later moved. 
```
#23 3.342 ERROR 1: Error loading shared library libgrass_raster.8.5.so: No such file or directory (needed by /usr/lib/gdalplugins/gdal_GRASS.so)
#23 3.342 ERROR 1: Error loading shared library libgrass_raster.8.5.so: No such file or directory (needed by /usr/lib/gdalplugins/gdal_GRASS.so)
#23 3.344 ERROR 1: Error loading shared library libgrass_vector.8.5.so: No such file or directory (needed by /usr/lib/gdalplugins/ogr_GRASS.so)
#23 3.344 ERROR 1: Error loading shared library libgrass_vector.8.5.so: No such file or directory (needed by /usr/lib/gdalplugins/ogr_GRASS.so)
```
Moving the `gdal-grass` building stage to …
> docker: move gdal-grass driver build stage after grass build relocation

- .github/workflows/docker.yml
There was missing a `type=gha` for `cache-from:`.
Also, add scopes to GitHub Actions cache. Otherwise, only one of the images will have the cache available.
This PR is separate from my other work that will enable to run on PRs. I have tested this with a trimmed down version that could run on PRs.
Cache utilization was 19%, 24% and 26% (no info for the failed Alpine image). Times were reduced to about 7 minutes for all three of these jobs, instead of 8-18 minutes. No further optimization of the Dockerfiles to maximize caching was done, yet.
> CI: Fix Docker caching with GitHub Actions

- Dockerfile
- docker/alpine/Dockerfile
- docker/ubuntu/Dockerfile
This PR hardcodes the [gdal-grass 1.0.3](https://github.com/OSGeo/gdal-grass/releases/tag/1.0.3) release in the Alpine and Ubuntu Dockerfile to continue using its `autoconf` support.
This PR may be replaced by a future backport of a `cmake` based solution which is  being worked on in the `main` branch.
The intention of this PR is not to further delay the GRASS 8.4.1 release due to currently broken Dockerfiles.
> docker: gdal-grass autoconf workaround (G84)

- lib/vector/Vlib/net_build.c
I was just about to check #5109 when it was merged. So I figure I'll give my review in this form :).
`Fi` always get set by `Vect_get_field()`, and its result is always checked and is G_fatal_error()'ed if NULL. So we can always expect Fi to be not NULL. Furthermore, `Vect_destroy_field_info()` is safe with a NULL as argument (just like `free()`), but it mustn't be bogus address (it should be initialised to NULL at declaration). Thus, no need to check `if (Fi) Vect_destroy_field_info(Fi);`
`db_get_column()` allocates Column and G_fatal_errors if the call fails. So also here there is no real need for NULL check before `db_free_column()` _if freed at the right place_.
There are several calls to both Vect_get_field() and db_get_column(), which must _each_ be accompanied by freeing up …
> lib/vector/Vlib: free allocated field_info and dbColumn objects (net_build.c)

- .github/workflows/docker.yml
Multiple very small related improvements, that end up being big. It was easier to test all the pieces with the same setup in a common branch, making one final PR, rather than trying to do dozens of PRs. A first set of changes making GitHub Actions Cache work was already merged in #5126.
Main features/changes:
- Allow manually launching a workflow (workflow_dispatch)
- Run workflow on pull requests, but only when a file inside docker/ (except markdown files), or the docker workflow file is changed.
- Support running the workflow on forks. (So someone can test docker builds in a PR or merged on his fork, without having it merged in the main repo)
- Add concurrency group to limit and cancel jobs.
- In a pull request, pushing a new commit will cancel in progress jobs.
- When not in a pull …
> CI(Docker): Docker workflow improvements

- .github/workflows/macos_distribute_app.yml
Add macOS app bundle distribution workflow, which sign, notarise and package to a dmg file.
At this point it "only" creates a GH artefact, which remains available three days.
> CI: add macOS app bundle distribution workflow

- docker/alpine/Dockerfile
Partially reverts 61e38c2, but more importantly hardcodes versioned GISBASE path on Alpine.
> docker: hardcode versioned GISBASE path on Alpine

- gui/wxpython/dbmgr/base.py
- pyproject.toml
Fixed ruff error regarding using context manager to open files
> style: Fixed context opening error in wxGUI/dbmgr

- .markdownlint.yml
- general/g.proj/g.proj.md
- general/g.setproj/g.setproj.md
- gui/wxpython/docs/wxGUI.md
- gui/wxpython/docs/wxGUI.nviz.md
- gui/wxpython/image2target/g.gui.image2target.md
- gui/wxpython/rlisetup/g.gui.rlisetup.md
- imagery/i.atcorr/i.atcorr.md
- imagery/imageryintro.md
- raster/r.in.pdal/r.in.pdal.md
- raster/r.mfilter/r.mfilter.md
- raster/r.neighbors/r.neighbors.md
- raster/r.out.vtk/r.out.vtk.md
- raster/r.proj/r.proj.md
- raster/r.series/r.series.md
- scripts/g.extension/testsuite/data/sample_modules/r.plus.example/r.plus.example.md
- temporal/t.rast.algebra/t.rast.algebra.md
- vector/v.clean/v.clean.md
- vector/v.proj/v.proj.md
Continued cleanup of markdown code.
Items `link-fragments: false` and `no-space-in-links: false` seem to be already solved.
> docs: fix no-emphasis-as-heading in markdown files

- pyproject.toml
- scripts/r.in.srtm/r.in.srtm.py
Fixed multiple linting errors in `r.in.srtm/`
- `SIM115` - Added context manager
- `FURB103` - Added `Path` library to write the file
- `FLY002` - Used `f-strings` where applicable
> r.in.srtm: Fixed SIM115, FURB103, FLY002 by adding context manager, f-strings

- raster/r.cost/r.cost.md
- raster/r.walk/r.walk.md
- vector/v.label/v.label.md
Not sure how, but I missed these cases and now the [CI fails](https://github.com/OSGeo/grass/actions/runs/13416414659/job/37478226857?pr=5105), this should fix it.
> docs: fix missed MD051/link-fragments

- general/g.region/g.region.md
- imagery/i.gensig/i.gensig.md
- imagery/i.gensigset/i.gensigset.md
- ps/ps.map/ps.map.md
- raster/r.li/r.li.dominance/r.li.dominance.md
- raster/r.li/r.li.edgedensity/r.li.edgedensity.md
- raster/r.li/r.li.mpa/r.li.mpa.md
- raster/r.li/r.li.padcv/r.li.padcv.md
- raster/r.li/r.li.padrange/r.li.padrange.md
- raster/r.li/r.li.padsd/r.li.padsd.md
- raster/r.li/r.li.renyi/r.li.renyi.md
- raster/r.li/r.li.shannon/r.li.shannon.md
- raster/r.li/r.li.simpson/r.li.simpson.md
I divided no-inline-html into several PRs, this one removes span, the solution varies depending on the context.
> docs: fix no-inline-html (span tag only)

- configure
- configure.ac
- include/grass/config.h.in
- lib/gis/ls_filter.c
Add support for PCRE, where/when GNU Regex cannot be used.
As this is mainly (perhaps only) needed on Win systems, `--without-pcre` is default. If both Regex and PCRE are available on the system, Regex is used by default.
> lib/gis: add support for PCRE

- .github/workflows/verify-success.yml
Since we observe that macOS and windows jobs are started before other jobs, effectively skipping the queue, running the small 0-second reusable workflow "verify-success" on macOS will prevent having to wait the whole queue a second time when only that is remaining.
We use the "verify-success" reusable workflow to ensure skipped/cancelled jobs aren't considered passes + allowing us to not edit the required checks at each version change in a strategy matrix.
Since it is only plain bash, macOS has no difference compared to Ubuntu runners.
I can confirm it skips the queue on my fork when busy (not immediatly, but when there's a runner change, and we are under our max macOS jobs in parallel), with "older" linux jobs of other PRs that should've run before the newly added success job, and still …
> CI: Run verify-success jobs on macOS

- .github/workflows/macos_dependencies.txt
Use SQLite <3.49.0 on macOS CI runner, attempt for workaround for issue reported at
https://discourse.osgeo.org/t/re-release-planning-grass-gis-8-4-1/112698/18
> CI: use SQLite <3.49.0 on macOS (G84)

- .github/workflows/cmake.yml
I observed that the CMake jobs were cancelled when a new PR was merged. For the time being, when stabilizing CMake, adjust the concurrency groups so that we see that job run on all commits separately.
> CI(CMake): Do not cancel in progress jobs when not in PRs

- macos/files/conda-requirements-dev-arm64.txt
Cherry pick of @nilason's commit on releasebranch_8_4
> CI: use SQLite <3.49.0 on macOS

- .github/labeler.yml
- utils/release.yml
Tuned up the allowed titles regexes.
- Allow CMake prefix
- Allow conda prefix
- Allow chore (possibly a good choice for changing something like the .gitignore: what prefix would it be? config isn't really accurate)
- Section for macOS like Windows
- Allow titles of reverted PRs like the ones made by GitHub's UI.
Also refreshed the paths and labels from the labeler, including:
- Add nix label
- Add cmake label
- Add msvc to windows
- Add more patterns to tests, CI, macOS, markdown
> checks: Add CMake/conda/macOS titles prefixes and labels, and allow revert PR titles

- vector/v.extract/extract.c
This pull request fixes issue identified by Coverity Scan (CID : 1207858, 1415586)
Used  `Vect_destroy_cats_struct(), Vect_destroy_field_info()` to fix this issue.
> v.extract: Fix Resource Leak Issue in extract.c

- raster/r.watershed/seg/do_cum.c
This pull request fixes issue identified by Coverity Scan (CID : 1207844).
> r.watershed/seg: Fix Resource Leak Issue in do_cum.c

- lib/vector/Vlib/cindex.c
This pull request fixes issue identified by Coverity Scan (CID : 1208155, 1588938)
Used fclose(), G_free() to fix this issue
> lib/vector/Vlib: Fix Resource Leak Issue in cindex.c

- raster/r.surf.idw/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1208158)
> r.surf.idw: Fix Resource Leak Issue in main.c

- include/config.h.cmake.in
- msvc/dirent.h
- msvc/fcntl.h
- msvc/stdio.h
- msvc/stdlib.h
- msvc/string.h
- msvc/strings.h
- msvc/sys/stat.h
- msvc/unistd.h
- raster/r.coin/format.c
This PR introduces additional wrapper header files for MSVC:
* msvc/stdlib.h
* msvc/string.h
* msvc/sys/stat.h
It also `#define`s necessary constants, macros, and data types (e.g., `ssize_t`) to align with their definitions in Linux headers. The objective is to avoid `#ifdef _MSC_VER` in C files as much as possible by providing compatibility through these files.
With this PR, `cmake .. -DWITH_OPENGL=OFF` + `msbuild grass.sln` compiles without errors.
> Windows: Wrapper header files for MSVC

- vector/v.vol.rst/user1.c
- vector/v.vol.rst/user2.c
This pull request fixes issue identified by Coverity Scan (CID : 1207917, 1589006)
Used `db_CatValArray_free(), db_close_database_shutdown_driver()` to fix this issue.
> vector/v.vol.rst: Fix Resource Leak Issue

- man/mkdocs/mkdocs.yml
- man/mkdocs/requirements.txt
Added support for social meta tags for each page in mkdocs addressing part of issue https://github.com/OSGeo/grass/issues/5162 .
docs: https://squidfunk.github.io/mkdocs-material/plugins/social/
```html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Overland flow hydrologic simulation using path sampling method (SIMWE).">
<link rel="canonical" href="http://0.0.0.0:8000/grass-stable/manuals/r.sim.water.html">
<link rel="icon" href="[favicon.ico](http://127.0.0.1:8000/grass-stable/manuals/favicon.ico)">
<meta name="generator" content="mkdocs-1.6.1, mkdocs-material-9.6.2">
<title>r.sim.water - GRASS GIS 8.5.0dev Reference Manual</title>
<meta  property="og:type"  content="website" >
<meta  property="og:title" …
```
> docs: Add mkdocs social meta tags

- macos/files/conda-requirements-dev-arm64.txt
- temporal/t.unregister/testsuite/test_unregister.py
- vector/v.db.select/testsuite/test_v_db_select_json_csv.py
Use correct type of quotes for SQLite 3.49.0+.
Fixes #5197.
> pytest: use correct type of quotes for conda's SQLite 3.49.0+ (SQLITE_DQS=0)

- vector/v.overlay/area_area.c
- vector/v.overlay/line_area.c
This pull request fixes issues identified by Coverity Scan (CID : 1207775, 1270302, 1270303, 1270305)
Used Vect_destroy_cats_struct(), Vect_destroy_line_struct() to fix this issue
> v.overlay: Fix Resource Leak Issue in line_area.c

- lib/ogsf/gp3.c
Addresses regression caused by bf53e3a3608f7fddcea15190b86d3c232a2518fd.
(cc @ShubhamDesai, to avoid potential double work).
> lib/ogsf: free linked list of geopoint objects in gp3.c

- .gitignore
By default, CMake in Visual Studio creates its build directory in out/build/. Visual Studio also creates multiple files, not intended to be shared, in a .vs folder.
Ignore both of these in .gitignore, like Kitware uses in its own CMake repo
https://github.com/Kitware/CMake/blob/ce1f8420559f408aef642bbcc9c4049b4e790e46/.gitignore#L34-L37
They also have different patterns for CLion, but I don't use it, so I can't tell if it is appropriate for us here, they could be added if needed. 
https://github.com/Kitware/CMake/blob/ce1f8420559f408aef642bbcc9c4049b4e790e46/.gitignore#L22-L25
> chore: Update .gitignore for cmake in Visual Studio

- .github/workflows/documentation.yml
This mainly adds numpy which is an import-time dependency for many addons. The custom Python setup does not use the apt dependencies which otherwise work in plain Ubuntu workflows.
> CI: Install Python deps with pip in doc workflow

- visualization/ximgview/main.c
This pull request fixes issue identified by Coverity Scan ( CID : 1501249)
If the return value == -1 then G_fatal_error
> wxGUI: Fix Unchecked return value in main.c

- man/mkdocs/scripts/hook_list_scripts.py
The mkdocs link to edit docs for addons contained a double slash. I've updated the code to remove trailing slashes if they are found.
> docs: Removed trailing slash from mkdocs github edit and view urls for addons

- raster/r.topmodel/file_io.c
This PR corrects the handling of `\r\n` and ensures empty lines are properly skipped. `fscanf(fp, " %[^\r\n] ", buffer)` will skip any empty lines (e.g., at the beginning of a file) (1st white space in the format), read a non-empty line into `buffer` (`%[^\r\n]`), and skip any amount of white spaces (2nd white space) until the next non-empty line.
Without this PR, `r.topmodel` would fail to skip empty lines in an LF-EOL input files and fail to stop reading a no-EOL file.
A small program for fixing this issue is provided at https://github.com/HuidaeCho/fix_rtopmodel until this PR is merged and released.
> r.topmodel: Handle CRLF and empty lines properly

- .github/workflows/macos_distribute_app.yml
Avoid attempts to run _macOS distribute app_ workflow on forks.
> CI(macOS): only run 'macOS distribute app' on OSGeo repo

- cmake/ctypesgen.cmake
- gui/wxpython/CMakeLists.txt
- lib/CMakeLists.txt
- python/libgrass_interface_generator/CMakeLists.txt
This addresses incomplete generation of python.lib.[vector|proj|vedit].py files, and fixes most of the failing tests.
In addition some minor, not directly related, fixes:
- add libparson test
- copy wxpython/README.md
> cmake: add missing include paths to ctypesgen

- utils/mkdocs.py
- utils/mkhtml.py
- utils/mkmarkdown.py
The initial port of HTML code to Markdown didn't include GRASS_PROXY support for the build. This moves the proxy function out of HTML to the common code and calls that function the Markdown build script.
It also fixes typo in a docstring.
> docs: Add proxy settings to Markdown build

- temporal/t.rast.accdetect/t.rast.accdetect.py
- temporal/t.rast.algebra/t.rast.algebra.py
- temporal/t.rast.contour/t.rast.contour.py
- temporal/t.rast.list/t.rast.list.html
- temporal/t.rast.list/t.rast.list.md
- temporal/t.rast.to.rast3/t.rast.to.rast3.md
- temporal/t.rast.to.vect/t.rast.to.vect.py
- temporal/t.rast3d.algebra/t.rast3d.algebra.py
- temporal/t.register/t.register.html
- temporal/t.register/t.register.md
- temporal/t.select/t.select.py
- temporal/t.vect.algebra/t.vect.algebra.py
Fix user-facing and non-user-facing typos
Found via `codespell -q 3 -S "*.po,*.pot,*.ps,*.raw,*.svg,./contributors_extra.csv,./translators.csv,./mswindows/external,./lib/external,./utils/fix_typos.sh" -L aline,alle,alog,anull,apoints,asnd,attch,bufer,buffr,bui,buildin,build-in,bund,clen,co-ordinate,co-ordinates,datas,delt,doubleclick,dout,dudo,dum,dyin,enew,entrys,eto,fle,flor,fpr,fromm,greif,huld,ihs,indx,ine,ines,infex,infp,inout,inpt,ist,linke,linz,lsat,makin,mapp,mis,modul,nam,nams,nd,neast,ned,nin,numer,observ,offsetp,oint,ons,ontext,parm,parms,partialy,redner,re-use,re-used,rin,selectin,sistem,siz,strin,strng,tht,vas,vizual`
> temporal: fix typos

- db/databaseintro.html
- db/databaseintro.md
- db/db.columns/db.columns.html
- db/db.columns/db.columns.md
- db/db.describe/db.describe.html
- db/db.describe/db.describe.md
- db/db.tables/db.tables.html
- db/db.tables/db.tables.md
Found via `codespell -q 3 -S "*.po,*.pot,*.ps,*.raw,*.svg,./contributors_extra.csv,./translators.csv,./mswindows/external,./lib/external,./utils/fix_typos.sh" -L aline,alle,alog,anull,apoints,asnd,attch,bufer,buffr,bui,buildin,build-in,bund,clen,co-ordinate,co-ordinates,datas,delt,doubleclick,dout,dudo,dum,dyin,enew,entrys,eto,fle,flor,fpr,fromm,greif,huld,ihs,indx,ine,ines,infex,infp,inout,inpt,ist,linke,linz,lsat,makin,mapp,mis,modul,nam,nams,nd,neast,ned,nin,numer,observ,offsetp,oint,ons,ontext,parm,parms,partialy,redner,re-use,re-used,rin,selectin,sistem,siz,strin,strng,tht,vas,vizual`
> db: fix typos

- man/build_md.py
- man/parser_standard_options.py
This changes representation of the generated documentation of the standard parser options (parameters). The table did not work great in the original HTML documentation, but it was not useable in the new mkdoc-rendered documentation.
The options (parameters) are now represented as individual sections (level 3 headings). The individual key-value pairs for the defaults are represented as rows in a small table for each option. Examples are included to demonstrate basic Python usage and allow copy-pasting.
The page now starts with a short introduction and links to g.parser for more context.
The C code parsing is now strictly split between the line ingesting and value cleanup. The cleanup is now done with regular expressions. This fixes several truncated values when parentheses were present. …
> docs: Replace table by sections for standard parser options

- man/build_manual_gallery.py
This fixes build of header and footer by avoiding YAML syntax issue in title (colon) and writing of HTML footer. It also does multiline matching for the image capture which results in capturing (presumably) all images in the Markdown docs.
> build: Fix basic gallery build issues for Markdown

- imagery/i.landsat.toar/landsat_met.c
This pull request fixes issue identified by Coverity Scan (CID : 1208229)
fread does not automatically null-terminate the buffer, leading to undefined behavior in string functions.
Solution:
- Reads up to METADATA_SIZE - 1 bytes to leave space for \0
- Checks for read errors and stops execution if necessary
- Ensures null termination to prevent undefined behavior
> i.landsat.toar: Fix string not null terminated issue

- python/grass/gunittest/main.py
- python/grass/gunittest/reporters.py
Making gunittest accept floating points for `--min-success` was a one word change, and already worked correctly.
I just followed up by making the percentage displayed with a decimal point, and extracting the repeated nested function as noted in a todo note; they were exactly the same and didn't use anything from the outer context, both were "[pure functions](https://en.wikipedia.org/wiki/Pure_function)", and could've been static functions in other languages.
I tried it out on the vector folder, making sure I didn't compile with some required libraries so some tests would fail (for example, no pdal, so v.in.lidar and v.in.pdal would fail)
For 19/31=0.6129032258064516, using 66.7 fails:
```
grass --tmp-project XY --exec     python3 -m grass.gunittest.main     --grassdata $HOME --location …
```
> grass.gunittest: Allow floating point for `--min-success` argument

- CMakeLists.txt
- cmake/modules/CheckDependentLibraries.cmake
- general/CMakeLists.txt
- lib/CMakeLists.txt
- raster/CMakeLists.txt
Use the imported PNG::PNG target from CMake's FindPNG.
> cmake: use imported PNG::PNG target

- vector/v.colors/write_rgb.c
This pull request fixes issue identified by Coverity Scan (CID : 1207647,1207649)
Used Vect_destroy_field_info(), G_free() to fix this issue.
> v.colors: Fix Resource Leak issue in write_rgb.c

- raster/rasterintro.md
Some links still pointed to HTML, not Markdown after manual conversion from HTML.
> docs: Fix r.mask Markdown links

- python/grass/gunittest/main.py
This is an old bit of work that I’m carrying on since the last 2024 community meeting in Prague.
I’ve made some progress on the matter, that is running gunittest-based tests with pytest, so it is time to file some preparatory work.
Pytest will respect this attribute and not consider that function to be a test (which fails and duplicates the tests, it is supposed to be used if the scripts are run directly, but when it is imported, pytest sees it.). See the end of https://docs.pytest.org/en/latest/example/pythoncollection.html#customizing-test-collection
It shouldn’t be impacting doctest too, even if it is mentioned here: https://docs.python.org/3/library/doctest.html#doctest.testmod
> tests: Ignore gunittest.main.test() when collecting with pytest

- .github/workflows/documentation.yml
Get all the history when cloning Git repos to have all commits when asking about the lastest change for the Source code section in the doc.
See #5323
> CI: Fetch all Git history for building docs

- utils/mkmarkdown.py
While #3849 added link to the specific commit, the URL was always main repo. This rewrites the code to get pure repo URL in a variable and then uses that to link to the specific commit in the appropriate repo. It limits the use of urlparse.urljoin because that is not required to join URLs and brings additional complexity with the need to add trailing slashes.
> docs: Link to addons repo for addons

- gui/wxpython/timeline/g.gui.timeline.py
- gui/wxpython/tplot/g.gui.tplot.py
- lib/gis/parser_md.c
- man/build_keywords.py
- man/mkdocs/mkdocs.yml
- man/mkdocs/tags.md
To use the keywords directly in MkDocs, keywords property needs to be proper YAML list, not a plain comma-separated list as a string. The keywords are now generated like that, and the custom keyword parsing now accepts both version (with and without []).
This does not include any keywords entered manually to Markdown because there are none in this repo, but they are in grass-addons repo which will break the MkDocs reading of the tags from the keywords property (for r.pi, r.green). Addons are addressed in https://github.com/OSGeo/grass-addons/pull/1357.
This includes cleanup of keywords tool metadata syntax which is supposed to use multiple keyword keys now rather than keywords (for a single keyword).
For the tags page generated by MkDocs, this adds an exclude of keyword 'unit test' which …
> docs: Use YAML list for keywords in front matter

- raster/r.null/testsuite/test_null.py
- raster/r.null/testsuite/test_r_null.py
This PR introduces tests for the `r.null` module to validate its functionality. The tests cover:
Basic Functionality: Verifies that `r.null` correctly adds null values in the raster map using `setnull` parameter.
Float Maps: Tests the `-f` flag for adding null values in the float map.
Fill Nulls: Tests `null` parameter to replace null values
The tests use temporary regions and custom raster maps.
> r.null: added test cases the module

- .github/workflows/python-code-quality.yml
Remove Sphinx Python doc build from Python quality check CI workflow. It is now build in the Documentation workflow.
> CI: Remove Sphinx build from Python QC

- pyproject.toml
- scripts/i.spectral/i.spectral.py
- scripts/r.fillnulls/r.fillnulls.py
- scripts/r.tileset/r.tileset.py
- scripts/wxpyimgview/wxpyimgview_gui.py
This PR fixes SIM115 linting errors across several modules by replacing direct file operations with proper context managers (with statements)
> style: Fix SIM115 linting errors using context managers for file operationsadding context managers in `scripts/`

- utils/mkmarkdown.py
Fixes merging markdown header with the rest. Before:
```markdown
**units**=*string*  
&nbsp;&nbsp;&nbsp;&nbsp;Elevation units (overrides scale factor)  
&nbsp;&nbsp;&nbsp;&nbsp;Options: *intl, survey*  
&nbsp;&nbsp;&nbsp;&nbsp;**intl**: international feet  
&nbsp;&nbsp;&nbsp;&nbsp;**survey**: survey feet
*r.relief* creates a raster shaded relief map based on current
resolution settings and on sun altitude, azimuth, and z-exaggeration
values entered by the user.
```
After:
```markdown
**units**=*string*  
&nbsp;&nbsp;&nbsp;&nbsp;Elevation units (overrides scale factor)  
&nbsp;&nbsp;&nbsp;&nbsp;Options: *intl, survey*  
&nbsp;&nbsp;&nbsp;&nbsp;**intl**: international feet  
&nbsp;&nbsp;&nbsp;&nbsp;**survey**: survey feet
*r.relief* creates a raster shaded relief map based on current …
```
> doc: add missing newline between generated synopsis and description heading

- scripts/conftest.py
- scripts/db.univar/db.univar.py
- scripts/v.db.univar/tests/conftest.py
Closes #3778
I cherry picked some changes I had queued up that fixed some errors that appeared in normal pytest when running with random order (plugin pytest-randomly), similar to what I reported in https://github.com/OSGeo/grass/issues/4480. Since then, I had found a workaround that was used in 
https://github.com/OSGeo/grass/blob/582d100897c67807399e318bce10cfc4f70c4b73/python/grass/script/tests/test_script_task.py#L9-L19
So, with this, most of the test problems I know of are addressed. Plus, tests pass on Windows locally. It will also unblock failing tests on Windows that depended on db.univar.
> db.univar: Use python sort fallback on Windows

- .github/workflows/macos_gunittest.cfg
- .github/workflows/osgeo4w_gunittest.cfg
- .gunittest.cfg
- vector/v.what/testsuite/test_vwhat_layers.py
- vector/v.what/testsuite/test_vwhat_ncspm.py
- vector/v.what/what.c
A part of the failures of v.what that I suppose was the reason that they got disabled, was because the output had an extra whitespace after the map name. 
I want to know if it is safe to do this change, as I don’t know the repercussions of changing that.
It’s been like this since at least the welcome to grass 7.0 SVN commit 17 years ago. https://github.com/OSGeo/grass/blame/b659313166fc5f26fb12b94898dfcefd59ce23a3/vector/v.what/what.c#L76C36-L77C41
This PR contains #5342, but could replace #5342 of it is ok. That other PR was to show the tests working. 
Closes #5342
> v.what: Fix test failures from trailing space after map name

- scripts/g.download.project/g.download.project.py
When trying to test locally for #5338, I stumbled across an error on Windows, but couldn't see it. The translated string contained both named placeholders and empty placeholder, but used keyword arguments. I don't know why I never noticed on Linux, but on Windows, there was no indication of what was happening.
```
d:\repos\grass_repo\grass\vector\v.univar>grass85 --tmp-project XY --exec g.download.project url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz path=%USERPROFILE%
WARNING: Concurrent mapset locking is not supported on Windows
File "C:\OSGeo4W\apps\grass\grass85/scripts/g.download.project.py", line 153, in <module>
main(*gs.parser())
File "C:\OSGeo4W\apps\grass\grass85/scripts/g.download.project.py", line 107, in …
```
> g.download.project: Fix string formatting error when download already exists

- .github/workflows/cmake.yml
- CMakeLists.txt
Increase required CMake version to 3.22 (Nov 2021), replacing current version 3.16 (Nov 2019).
That version would be supported out-of-the-box with, e.g.:
- Debian 12 Bookworm (current stable)
- Fedora 36 (EOL)
- Slackware 15.0 (current stable)
- Ubuntu 22.04 (Jammy Jellyfish, EOL in Apr 2027)
See further platforms: https://repology.org/project/cmake/versions 
Otherwise it may be installed through pip.
Version 3.22 comes with a number of useful improvements, among others for Apple ARM platform support, FindGDAL and FindPostgreSQL. See links below for news posts for each upgrade:
https://cmake.org/cmake/help/latest/release/3.17.html
https://cmake.org/cmake/help/latest/release/3.18.html
https://cmake.org/cmake/help/latest/release/3.19.html …
> cmake: increase required version to 3.22

- .github/workflows/cmake.yml
- cmake/modules/CheckDependentLibraries.cmake
- lib/gis/CMakeLists.txt
- locale/CMakeLists.txt
Fix Native Language Support (NLS) support with CMake builds.
~~This is another reason to increase CMake required version to 3.22 (#5269). The version of FindIntl from 3.16 is not particularly good and we'll have to use a custom one if staying with 3.16.
I included here the version of 3.22, for "proof of concept".~~
> cmake: fix Native Language Support (NLS) support

- cmake/modules/CheckDependentLibraries.cmake
- general/CMakeLists.txt
- lib/CMakeLists.txt
- vector/CMakeLists.txt
> cmake: use of imported Freetype target

- vector/v.build/testsuite/v.build_test.py
This PR introduces tests for the `v.build` module for various options including `build, dump, sdump, cdump, fdump`.
The additional text file is used to validate the output.
> v.build: added tests for v.build module

- .github/workflows/documentation.yml
- man/Makefile
- man/build_full_index.py
- man/build_md.py
This builds addon index (for `addons` subdirectory) in CI using the tooling from core, specifically the script to build full tool index. The intro text is different for addons and for the core. The addons version is derived from the current addon index page.
> docs: Build Markdown addon index using core index tooling

- flake.nix
Update cachix public key for Nix after recreation of cache.
Following instructions at https://github.com/OSGeo/grass/pull/3906#issuecomment-2188589331
> CI: update cachix public key for Nix

- scripts/db.dropcolumn/db.dropcolumn.py
- scripts/db.droptable/db.droptable.py
- scripts/i.in.spotvgt/i.in.spotvgt.py
I don’t really expect this to be merged as is, but I wanted to provoke some discussions.
In the scope of enhancing our tests with pytest (I’m close to 100 commits ahead on that work), some tests were failing because the backing c library doesn’t support receiving an empty value for a required argument, message. It happens in our repo three times, but more in grass-addons.
Since the problem might be in the python wrapping functions, that don’t play well with empty strings (I didn’t try in C directly), the other way to solve the problem is by not causing it. That is what this PR is doing.
If there’s a better solution for this, please update this PR or create a new one ;)
> python: `gs.message` doesn't support an empty string

- man/mkdocs/mkdocs.yml
We have a long list of pages we are linking from other pages, but currently not including from the menu. For all or most of these, we have a high confidence we are linking all, so we just silence the MkDocs warning about these pages missing in the nav.
Fixes #5215
> docs: Tell MkDocs about pages linked from other pages

- python/grass/gunittest/checkers.py
This error popped up post updating `ruff` to latest version
> pythonlib: Add missing docstring summary lines to fix D402 errors

- display/d.vect.thematic/plot1.c
This pull request fixes issue identified by coverity scan (CID : 1207610, 1207611, 1207612, 1207613, 1207614)
Used `Vect_destroy_cats_struct(), Vect_destroy_line_struct(), G_free()` to fix this issue.
> d.vect.thematic: Fix Resource Leak issue in plot1.c

- raster/r.in.gdal/main.c
- raster/r.in.gdal/proj.c
This pull request fixes issue identified by coverity scan (CID : 1248588)
Used `G_free()` to fix this issue.
> r.in.gdal: Fix Resource Leak Issue in main.c

- lib/vector/Vlib/array.c
This pull request fixes issue identified by Coverity Scan (CID : 1207956, 1207957, 1207958, 1207959)
Used `Vect_destroy_cats_struct(), Vect_destroy_field_info(), G_free()` to fix this issue.
> lib/vector/Vlib: Fix Resource Leak Issue in array.c

- vector/v.voronoi/skeleton.c
This pull request fixes issue identified by coverity scan (CID : 1207960, 1207961, 1207962, 1207963, 1207964)
Vect_destroy_line_struct(), Vect_destroy_list(), Vect_destroy_cats_struct(), G_free() to fix this issue
> v.voronoi: Fix resource leak issue in skeleton.c

- lib/gis/datum.c
This pull request fixes issue identified by coverity scan (CID : 1207999)
Used fclose() to fix this issue.
> lib/gis: Fix Resource Leak issue in datum.c

- cmake/modules/CheckDependentLibraries.cmake
- raster/CMakeLists.txt
- vector/CMakeLists.txt
Use imported PDAL target(s) from find_package in config mode.
A workaround is needed for PDAL pre-2.6, which exports two targets.
> cmake: use of imported PDAL target

- raster/r.covar/tests/test_r_covar.py
This PR adds pytest-based tests for the `r.covar` module, covering:
- Basic covariance calculation with multiple raster inputs
- Correlation matrix generation using the `-r` flag
- Edge case handling (e.g., identical maps, null values)
> r.covar: added test cases for the module

- lib/gis/compress.c
- lib/gis/copy_dir.c
Addresses issues of type [CWE-190](https://cwe.mitre.org/data/definitions/190.html): Integer Overflow or Wraparound, reported by Coverity Scan.
> lib/gis: fix potential integer overflow issues

- lib/gis/color_str.c
- lib/gis/commas.c
- lib/gis/env.c
- lib/gis/file_name.c
- lib/gis/get_ellipse.c
- lib/gis/get_window.c
- lib/gis/parser.c
- lib/gis/parser_help.c
Addresses issues of type [CWE-120](https://cwe.mitre.org/data/definitions/120.html): _Buffer Copy without Checking Size of Input_, reported by Coverity Scan.
> lib/gis: fix potential buffer overflow issues

- raster/r.out.ascii/formspecific.c
This pull request fixes issue identified by Coverity Scan (CID : 1207940, 1207941, 1207942)
> r.out.ascii: Fix Resource Leak Issue in formspecific.c

- raster/r.viewshed/grass.cpp
This pull request fixes issue identified by Coverity Scan (CID: 1208132, 1208133, 1208134, 1208135, 1415592)
> r.viewshed: Fix Resource Leak Issue in grass.cpp

- lib/gis/area.c
- lib/gis/datum.table
- lib/gis/distance.c
- lib/gis/env.c
- lib/gis/gislib.dox
- lib/gis/parser_wps.c
- lib/gis/timestamp.c
- lib/gis/wind_overlap.c
Found via codespell
Also contains the same issue as https://github.com/OSGeo/grass/pull/5346#pullrequestreview-2669452703
> lib/gis: fix typos

- lib/vector/Vlib/header_finfo.c
This pull request fixes issue identified by coverity scan (CID : 1207950, 1207951)
Used `G_free()` to fix this issue.
> lib/vector/Vlib: Fix Resource Leak issue in header_finfo.c

- lib/vector/Vlib/close.c
This pull request fixes issue identified by Coverity Scan ( CID : 1207965)
> lib/vector/Vlib: Fix Resource Leak issue in close.c

- raster/r.fill.dir/ppupdate.c
This pull request fixes issue identified by Coverity Scan (CID : 1208481, 1208482)
Initialized to `NULL` to fix this issue.
> r.fill.dir: Fix uninitialized pointer

- CMakeLists.txt
- vector/CMakeLists.txt
Remove OpenDWG related unused CMake code.
`v.in.dwg` was removed with 7dc46cdadd53399c566cf0a496632c80ea03db81.
> cmake: remove OpenDWG related unused code

- man/mkdocs/overrides/partials/footer.html
This is removing the series of links in the footer of the new documentation which go to the various index pages. These links to index pages served as a menu in the custom HTML documentation, but don't have much use in the new documentation which is using MkDocs navigation with a top bar menu being the main navigation place. In very special cases, the bottom bar contained extra link to GUI and the link to tool category would be generated dynamically. This has a limited use as menus are not expected to be changing, instead you expect to find things in the same place there. (So this is something which the new MkDocs menus don't have, but it is not a problem.) In the future, if anything from this footer links should be linked from menu, it should be added to the new menu. The full index …
> docs: Remove old footer links from MkDocs site

- .github/workflows/documentation.yml
- man/Makefile
- man/build_keywords.py
- man/build_topics.py
- man/mkdocs/keywords.md
- man/mkdocs/mkdocs.yml
- man/mkdocs/overrides/fragments/tags/default/listing.html
This removes custom keywords index and replaces the keywords.html page by a MkDocs tags listing.
The default MkDocs tag anchor contains tag: prefix to help distinguishing tag headings from others, but we likely won't have a heading of the same name on the same page. However, we were using anchors without any prefix, so this will make most of the anchor links work (if there are any external ones anywhere). It also makes the anchor little simple to read and write if managed manually for any reason.
The check for anchor existence is done by MkDocs before the tags page is generated. This creates false positive for the Keywords section (to be removed) and for topics. To avoid this warning for topics, and perhaps to be little more helpful, instead of linking to the keyword, this new code uses …
> docs: Replace keywords index by MkDocs tags

- display/d.barscale/draw_scale.c
This pull request fixes issue identified by Coverity Scan (CID : 1208451, 1208454)
initialized variables with 0.0
> d.barscale: Fix uninitialized Variable in draw_scale.c

- raster3d/r3.out.vtk/writeVTKData.c
This pull request fixes issue identified by Coverity Scan (CID : 1208000, 1208001)
> r3.out.vtk: Fix Resource Leak Issue in writeVTKData.c

- man/build.py
- man/build_class.py
- man/build_class_graphical.py
- man/build_full_index.py
- man/build_md.py
- man/mkdocs/index.md
- man/mkdocs/mkdocs.yml
Use tool instead of command, use tools instead of processing tools, and use sentence case instead of title case.
Also fix heading levels and remove backlinks to index in tool category pages.
> docs: Unify tool index wording

- man/build_class_graphical.py
- man/build_graphical_index.py
- man/build_md.py
The generated Markdown for index was broken and the the individual pages were missing the default image. The page title for index was too long. This is making the pages legible.
...even if may remove it in the future, let's evaluate it in the best possible light:
> docs: Fix basic graphical index issues in Markdown

- man/build_topics.py
- man/mkdocs/mkdocs.yml
The additional change in #5446 adding tag listing for topic pages turned out to be harmful as it makes the tags (aka keywords) on top of pages link to the tag heading in the topic pages if the listing exists. While this sort of looks like the original custom HTML behavior of second keyword being a tag, this creates inconsistency with an seemingly arbitrary keyword (not just the second or 'topic' keyword) linking to a different page than the list of keywords, but not even to the topic page itself, but to a heading inside the page because instead of a a topic, the link goes to the keyword (tag) in the listing.
This preserves the additional list of tools for topic pages introduced in #5446 by creating another instance of the material tags plugin in MkDocs using the same front matter metadata …
> docs: Separate topics from keywords by 2nd tags plugin

- docker/ubuntu_wxgui/Dockerfile
See issue:
https://github.com/OSGeo/grass/issues/5458
Gui did not run from docker ubuntu gui image.
After adding this package, gui starts again without error message.
By the way, needs this PR also be applied on release branch 8.4? Same problem.
I don't know the policies about fixing release branches. And which..
> docker: add package to docker image to be able to run gui

- Dockerfile
- docker/alpine/Dockerfile
- docker/debian/Dockerfile
- docker/ubuntu/Dockerfile
- docker/ubuntu_wxgui/Dockerfile
Fixes
- "Legacy key/value format with whitespace separator should not be used"
- "The 'as' keyword should match the case of the 'from' keyword"
> docker: fix various syntax warnings

- lib/init/grass.py
There was a function called `f()` that was only used inside this file. It ended up often getting shadowed in other functions when using a file description variable named `f`. This caused a Pylint warning W0621.
This function was adjusting fixed width strings, and used 4 times.
I simply renamed it as there would be way more changes to rename all the variables elsewhere in the file. `fw` for fixed-width still makes sense and is still short enough like the previous intention, not causing formatting changes.
> init: Rename often shadowed internal helper function `f()` to `fw()`

- vector/v.external/proj.c
> v.external: Fix Resource Leak Issue in proj.c

- lib/raster/range.c
This pull request fixes issue identified by Coverity Scan (CID : 1208145, 1208146, 1415666, 1415672)
Used G_free(), fclose() to fix this issue.
> lib/raster: Fix Resource Leak Issue in range.c

- gui/wxpython/icons/grass_icons.py
- pyproject.toml
PR addresses the PTH208 linting error in gui/wxpython/icons/grass_icons.py by replacing os.listdir and os.path.splitext with their pathlib equivalents.
- Imports Path from pathlib.
- Converts the iconPath string to a Path object.
- Uses Path.iterdir() to iterate over directory contents.
- Uses Path.stem and Path.suffix to get the filename components.
- Uses Path.name to get the full filename for storage in iconSet
> wxGUI: Fix PTH208 use pathlib Path instead of os module

- imagery/i.aster.toar/main.c
- imagery/i.eb.hsebal01/main.c
- temporal/t.rast.accdetect/t.rast.accdetect.py
- temporal/t.rast.accumulate/t.rast.accumulate.py
- temporal/t.rast.aggregate.ds/t.rast.aggregate.ds.py
- temporal/t.rast.aggregate/t.rast.aggregate.py
- temporal/t.rast.extract/t.rast.extract.py
- temporal/t.rast.gapfill/t.rast.gapfill.py
- temporal/t.rast.import/t.rast.import.py
- temporal/t.rast.neighbors/t.rast.neighbors.py
- temporal/t.rast3d.mapcalc/t.rast3d.mapcalc.py
- temporal/t.vect.extract/t.vect.extract.py
- vector/v.label.sa/main.c
Remove misused gisprompt option, which is expected to be a [comma separated three part value](https://grass.osgeo.org/programming8/gislib_cmdline_parsing.html#gisprompt_Member).
> CQ: remove misused gisprompt options

- lib/vector/Vlib/box.c
This pull request fixes issue identified by Coverity Scan (CID : 1415696)
> lib/vector/Vlib: Fix Resource Leak Issue in box.c

- raster/r.fill.dir/ppupdate.c
This most likely addresses a false positive static analyser issue, which was raised after merge of 9fdce5ae068d245ee78d3422ae4f216054409be3.
But it doesn't hurt to add this simple check either.
```
*** CID 1593959:  Null pointer dereferences  (FORWARD_NULL)
/raster/r.fill.dir/ppupdate.c: 165 in ppupdate()
159     
160             n = list[i].next;
161             if (list[n].next == i) {
162                 /* we have a pair */
163                 /* find out how large the elevation difference would be for a change
164                  * in each basin */
CID 1593959:  Null pointer dereferences  (FORWARD_NULL)
Passing null pointer "that_elev" to "memcpy", which dereferences it.
165                 memcpy(that_elev, list[n].pp_alt, bpe());
166                 diff(that_elev, list[n].pp); …
```
> r.fill.dir: avoid null pointer dereferences

- raster/r.series/main.c
At least some of ASCII symbols are better described by a word than just by showing the symbol itself. This way it is clear that what the symbol is while also being able to copy the symbol. When pipe is a parameter, we allow, even promote, using the word rather than the symbol itself.
> r.series: Say pipe in addition to showing the symbol

- raster/r.slope.aspect/main.c
This replaces a custom code in r.slope.aspect by a function call. The message is similar, but this way the information is available to interface generators parser (namely XML and Markdown).
> r.slope.aspect: Use parser function to specify required parameters

- lib/init/grass.py
This is the last of my PRs for the init file, that I had some work done.
It ends up by adding typing annotations where I could fully reason the usages and the types (it's like a sudoku, you start with what you know and more and more gets possible to fill out).
The `StrPath` for string-based paths or Paths that are accepted from os.path functions, is from typeshed, always available when using type checkers tools (they have to bundle their own copy), and follows the recommended usage like shown here: https://github.com/python/typeshed/tree/0104531422353e89d55fe0488ad28556296771fc/stdlib/_typeshed
The places where I didn't fill out more was because it wasn't clear yet.
Because of the previous PRs, there are no code changes mixed in with these, so they should be fast and easy to review. They …
> init: Add typing annotations where appropriate

- raster/r.out.vtk/writeascii.c
This pull request fixes issue identified by Coverity Scan (CID : 1208084, 1208085, 1208086, 1208087, 1208088, 1208089, 1208090,1208091, 1208092)
> r.out.vtk: Fix Resource Leak Issue in writeascii.c

- db/drivers/sqlite/select.c
This pull request fixes issue identified by Coverity Scan (CID : 1415582)
> db.drivers: Fix Resource Leak Issue in select.c

- .github/workflows/additional_checks.yml
- mswindows/external/rbatch/el.js
I thought I had already made this PR, but it might have stayed unpushed on my phone. Oh well, doing it now.
I've been bitten a few times where we don't see any signs of differences of pre-commit fixes in CI when a version or config file changes, but doesn't affect the .pre-commit.yaml file. The latest one is that a fix for super-linter had some more changes from pre-commit. I'm fixing them here, as it should have been made in #5241
> CI: Run pre-commit in CI when config files or workflows change

- .github/workflows/documentation.yml
- doc/grass_database.md
- doc/projectionintro.md
- gui/wxpython/docs/wxgui_sphinx/conf.py
- lib/init/helptext.md
- man/Makefile
- man/build_graphical_index.py
- man/build_md.py
- man/build_topics.py
- mswindows/GRASS-Installer.nsi.tmpl
- python/grass/docs/conf.py
Use simpler Documentation instead of loaded Reference Manual. We call it both doc and ref man and using doc in the doc itself should lead to just one name although a less specific one. Doc is also just one work so it avoids title case versus sentence case inconsistencies.
This shuffles things around in a couple of the See also sections which were linking the index page which now is simply linked from the navigation, mainly it moves EPSG links from helptext aka quick start aka GUI intro) into projectionintro page.
> docs: Use Documentation instead of Reference Manual

- imagery/i.smap/testsuite/test_i_smap.py
This PR fixes the test file which failed occasionally due to ambiguity in the arithmetic expression.
**Issue:**  
The `i.smap` regression test was exhibiting flaky behavior due to an ambiguity in the arithmetic expression used to compute `synth_map3` during test setup. The problematic line:
```python
20 * exp(-((row() - 50)^2 + (col() - 50)^2) / 500)
```
was incorrectly evaluated due to operator precedence. The exponentiation applied only to the numerator, and the division by 500 happened *after* `exp`, resulting in much smaller values than intended. This led to inconsistent behavior in `i.gensigset` and subsequent variation in `i.smap` classification, especially affecting the `goodness` map.
**Fix:**  
The arithmetic expression was corrected by adding parentheses to ensure the division …
> i.smap: bug fix

- gui/wxpython/tools/update_menudata.py
- pyproject.toml
Ensure writeData() uses a with‐statement for appending the trailing newline
> wxGUI: use context manager for file append in writeData() (SIM115)

- lib/imagery/testsuite/test_imagery_signature_management.py
- pyproject.toml
Replace all `open(...)`/`write(...)`/`close()` sequences in test_imagery_signature_management.py with `with open(...) as f:` to satisfy Ruff’s SIM115.
> lib/imagery: use context manager for file writes in tests (SIM115)

- gui/wxpython/web_services/dialogs.py
- pyproject.toml
Replace manual `open()`/`close()` with a `with`‑statement in `_setRevertCapFiles()` for proper resource handling.
> wxGUI: use context manager for deleting file content in _setRevertCapFiles (SIM115)

- vector/v.info/level1.c
- vector/v.info/print.c
This pull request fixes issue identified by Coverity Scan (CID : 1415719)
> v.info: Fix Resource Leak Issues

- python/grass/pygrass/modules/interface/module.py
Ruff rule: https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/
Since #4032 has essentially been stalled for 9 months now, I'm extracting only one of the changes as I encountered a situation that justifies it sooner than waiting for the existing PR to get back to life, if ever.
With this PR, a traceback that looked before like:
Now looks like:
<details><summary>Text version:</summary>
<p>
Before:
```
____________________________________________________________________ TestGdalImportFails.test_error_handling_2 ____________________________________________________________________
/usr/local/grass85/etc/python/grass/pygrass/modules/interface/module.py:554: in __init__
get_cmd_xml = Popen([cmd, "--interface-description"], stdout=PIPE) …
```
> style: Fix raise-without-from-inside-except (B904) for pygrass Module

- python/grass/script/testsuite/test_names.py
In the same spirit of the changes made for https://github.com/OSGeo/grass/issues/4838 with ScriptError, there's a CalledModuleError that doesn't (and shouldn't) come from grass.script, but from grass.exceptions.
This PR adjusts the import so it is not an unknown attribute of grass.script.
Other instances that exists, but I couldn't verify them (I was only in the tests side of things today, didn't manage to trigger on a GUI):
https://github.com/OSGeo/grass/blob/d850a9fd8c7b9c9181aa5a09e9b07bf601b7e8ad/gui/wxpython/psmap/frame.py#L1247
https://github.com/OSGeo/grass/blob/d850a9fd8c7b9c9181aa5a09e9b07bf601b7e8ad/gui/wxpython/psmap/utils.py#L244
Will be fixed in #5526
https://github.com/OSGeo/grass/blob/d850a9fd8c7b9c9181aa5a09e9b07bf601b7e8ad/man/mkdocs/docs/python_intro.md#L771-L779
In …
> tests: Import CalledModuleError from grass.exceptions in test_names.py

- python/grass/script/testsuite/test_script_raster.py
- raster/r.his/testsuite/test_r_his.py
- scripts/r.blend/testsuite/test_r_blend_quoting.py
- scripts/r.grow/testsuite/test_r_grow_quoting.py
- temporal/t.connect/testsuite/test_distr_tgis_db_raster.py
- temporal/t.connect/testsuite/test_distr_tgis_db_raster3d.py
- temporal/t.connect/testsuite/test_distr_tgis_db_vector.py
- temporal/t.rast.export/testsuite/test_rast_export.py
Some test files do some actions, like set up steps outside the set up functions. So, simply importing them for collection, even with pure unittest `python -m unittest discover`, would have side effects and possibly fail.
With the following change in pyproject.toml for allowing to discover gunittest tests with pytest:
```diff
-python_files = "*/tests/*_test.py */tests/test_*.py"
+python_files = """
+    */tests/*_test.py
+    */tests/test_*.py
+    **/testsuite/*test*.py
+"""
```
These errors are now pointed out.
This PR fixes these collection errors, so at least pytest, if configured correctly to be able to find and import grass from python, doesn't fail anymore.
> tests: Fix collection errors when importing tests have side effects

- man/build_manual_gallery.py
Image from pillow supports using context managers, but wasn't used yet.
Solves more than 100 ResourceWarning at least for macOS builds (log search returns 100 results)
Errors looked like:
```
GISBASE="/Users/runner/work/grass/grass/dist.aarch64-apple-darwin20.0.0" ARCH="aarch64-apple-darwin20.0.0" ARCH_DISTDIR="/Users/runner/work/grass/grass/dist.aarch64-apple-darwin20.0.0" MDDIR="/Users/runner/work/grass/grass/dist.aarch64-apple-darwin20.0.0/docs/mkdocs" VERSION_NUMBER=8.5.0dev VERSION_DATE=2025 python3 ./build_class.py m miscellaneous
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/runner/work/grass/grass/man/./build_manual_gallery.py:107: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/runner/work/grass/grass/dist.aarch64-apple-darwin20. …
```
> man: Use context manager when opening image file

- imagery/i.evapo.pt/testsuite/test_i_evapo_pt.py
This PR adds a comprehensive regression test suite for the `i.evapo.pt` module, which implements the Priestley-Taylor evapotranspiration model.
The test suite includes:
- **Default model validation**: Verifies output against theoretical Priestley-Taylor ET values using generated input rasters.
- **`-z` flag behavior**: Confirms that negative ET values are correctly clamped to zero.
- **Energy scaling test**: Checks that doubling net radiation and soil heat flux results in proportionally scaled ET output.
- **Zero ET validation**: Ensures that ET output is zero when net radiation equals soil heat flux (i.e., no available energy for evaporation).
| Platform | Runtime |
|----------|---------|
| Windows  | 1.512s  |
| Ubuntu   | 1.130s  |
| macOS    | 0.904s  |
This PR improves the test …
> i.evapo.pt: add test file

- vector/v.delaunay/testsuite/v_delaunay_test.py
This pull request introduces a comprehensive test suite for the v.delaunay module in GRASS GIS. It verifies the correctness of Delaunay triangulation under various scenarios, including standard random point inputs, collinear points (which should produce no areas), the minimum valid number of points (three), and inputs with duplicate coordinates (ensuring deduplication). Additionally, it tests the behavior of the -r and -l flags to confirm expected changes in topology, such as region-limited triangulation and line-only output.
> vector: Adding test cases for the module V.delaunay

- imagery/i.evapo.time/testsuite/test_i_evapo_time.py
This PR introduces a regression test suite for the i.evapo.time module in GRASS GIS, focusing on correctness of cumulative evapotranspiration (ET) calculations under different input conditions.
**Key Updates in this PR include:**
**Functionality:**
- Validates that cumulative ET increases when the analysis time period is extended.
- Confirms linear scaling of ET output when ETo values are proportionally increased (with constant ETrF).
**Test Case Additions:**
- Cumulative Statistics Test: Checks that the output raster matches expected summary statistics like mean, min, and max.
- Time Range Sensitivity Test: Ensures ET increases when the simulation period is lengthened.
- Linearity with ETo Scaling: Verifies that doubling or tripling ETo results in a corresponding increase in cumulative …
> i.evapo.time: Add test file

- imagery/i.maxlik/testsuite/test_i_maxlik.py
- lib/gis/testsuite/test_gis_lib_getl.py
- lib/imagery/testsuite/test_imagery_sigfile.py
- lib/imagery/testsuite/test_imagery_sigsetfile.py
Fixes some expected failures, and removes the decorator to not have unexpected successes.
"libc" just doesn't make sense on Windows. The functionality comes from msvc. As stated in the Python docs, and some old threads, we shouldn't use CDLL to get the library on Windows, as a really old version would be returned, and not the one Python would be compiled with. This PR uses a suggested approach, that works.
> tests: Load "msvcrt" instead of "c" ctypes library on Windows

- raster3d/r3.mkdspf/r3_find.c
This pull request fixes issue identified by Coverity scan (CID : 1208251)
Used G_strlcpy() to fix this issue
> r3.mkdspf: Fix copy into fixed buffer size issue in r3_find.c

- raster/r.watershed/seg/cseg_open.c
This pull request fixes issue identified by Coverity Scan (CID : 1207993)
> r.watershed: Fix Resource Leak issue in cseg_open.c

- display/d.mon/list.c
- display/d.mon/select.c
- display/d.mon/start.c
- display/d.mon/stop.c
This pull request fixes issue identified by Coverity Scan (CID : 1415593, 1270312, 1270310, 1270309)
Used G_free(), close() to fix this issue.
> d.mon: Fix Resource Leak Issues

- display/d.vect.thematic/main.c
- include/grass/defs/arraystats.h
- lib/arraystats/basic.c
- lib/arraystats/class.c
- vector/v.class/main.c
Addresses heap buffer overflow in previously disabled 'Discont' algorithm.
The immediate cause was too small allocation of variable `num` in `AS_class_discont()`, which was fixed by an increase of its size (broadly mirroring the original Fortran code).
This fix was complemented by some code related improvements:
- Code clean up and restructure of `AS_class_discont()`
- Re-enable "dis" algorithm in v.class and d.vect.thematic
- Pass `classbreaks` array by pointer to pointer to enable in- and output.
For this PR I had the original Fortran code at my disposal.
See: https://lists.osgeo.org/pipermail/grass-dev/2008-July/038951.html
Fixes: https://github.com/OSGeo/grass/issues/5486
> lib/arraystats: re-enable "Discont" algorithm

- python/grass/script/utils.py
The decode function from utils raises TypeError when the type is not bytes or str. This also makes it include the type of the passed object in the message. Practically, this will be often NoneType (you use decode, but you don't have Popen configured properly).
> grass.script: Reveal the failed type passed to decode

- raster/r.sim/simlib/hydro.c
The `iterout` variable can be zero in some cases causing crash. When cell size (xstep, ystep) is large and average velocity is low, deltap can get larger than the input iterout.
```c
setup->deltap =
0.25 * sqrt(geometry->stepx * geometry->stepy) /
(setup->vmean > EPS ? setup->vmean : EPS); /*time step for water */
...
setup->iterout =
(int)(settings->iterout /
(setup->deltap * setup->timec)); /* number of cells to pass for
time series output */
```
And then it's used in division.
> r.sim: fix division by zero

- python/grass/app/data.py
- python/grass/script/setup.py
- python/grass/script/tests/grass_script_setup_test.py
The function _gs.setup.init_ can now optionally lock the mapset and unlock when exiting the context or with call to finish (both free function or bound method). This keeps the current state of not locking as a default, i.e., the locking is opt-in, so multiple session are responsibility of the user just like running multiple processes within one mapset.
Importantly, this brings feature parity with the grass command to Python, and makes it possible for users to use the mapset locking from Python.
The PID used is the the current process ID which is already used for variable GIS_LOCK in init. The underlying locking (but not unlocking) functionality is the same one as used for the main _grass_ command thanks to a previous refactoring of locking from lib/init/grass.py to _grass.app.data_.
The …
> grass.script: Add locking to init

- gui/wxpython/core/gconsole.py
> wxGUI/gconsole: avoid infinite GUI-in-GUI loops when running python scripts with no required params

- scripts/r.plane/r.plane.py
As the option does not contain a comma separated three part string, this causes heap buffer overflow. This is probably the cause of some random CI failures with `r.plane`.
Follow-up to #5493.
> r.plane: remove misused gisprompt option

- raster/r.li/r.li.cwed/cwed.c
- raster/r.li/r.li.daemon/avl.c
- raster/r.li/r.li.daemon/avlID.c
- raster/r.li/r.li.daemon/daemon.c
- raster/r.li/r.li.daemon/worker.c
- raster/r.li/r.li.dominance/dominance.c
- raster/r.li/r.li.edgedensity/edgedensity.c
- raster/r.li/r.li.mpa/mpa.c
- raster/r.li/r.li.mps/mps.c
- raster/r.li/r.li.padcv/padcv.c
- raster/r.li/r.li.padrange/padrange.c
- raster/r.li/r.li.padsd/padsd.c
- raster/r.li/r.li.patchdensity/main.c
- raster/r.li/r.li.patchnum/main.c
- raster/r.li/r.li.pielou/pielou.c
- raster/r.li/r.li.renyi/renyi.c
- raster/r.li/r.li.richness/richness.c
- raster/r.li/r.li.shannon/shannon.c
- raster/r.li/r.li.shape/main.c
- raster/r.li/r.li.simpson/simpson.c
Fix resource leak issues in `r.li[.*]` modules. In addition remove return after G_fatal_error().
This may look like a lot of changes in one PR, but the code in `r.li` is very repetitive (which even Coverity Scan have problem to handle).
(This module group could probably gain a lot by major refactoring and re-use of repetitive code).
> r.li: fix resource leak issues

- python/grass/app/Makefile
- python/grass/app/__main__.py
- python/grass/app/cli.py
- python/grass/app/tests/grass_app_cli_test.py
This adds a CLI to grass.app subpackage using `__main__.py` and Python argparse with subcommands. At this point, this is meant as internal and experimental. The original motivation for this is testing locking in #5443. The subcommands add a lot of flexibility in what can done with argparse supporting directly several use cases and being quite stable and standardized.
Just as an example (to have this separate from #5443 while functional), this adds two subcommands, help and man, which both end up calling _g.manual_. The result looks like this:
```bash
python -m grass.app help g.region
python -m grass.app man g.region
```
Assumes:
```bash
export PYTHONPATH=$(grass --config python-path)
```
Notably, `python -m grass.app help g.region` is not a replacement for calling `g.manual g.region` …
> grass.app: Add internal CLI with argparse subcommands

- imagery/i.evapo.mh/mh_eto.c
- imagery/i.evapo.mh/mh_original.c
- imagery/i.evapo.mh/mh_samani.c
This PR fixes an incorrect radiation conversion applied in the evapotranspiration calculations of the `i.evapo.mh` module.
Previously, the radiation input (`ra`) was multiplied by `86.4`, incorrectly boosting the energy input and resulting in overestimated evapotranspiration values.
This PR corrects the unit conversion:
- Changes `ra = ra * (24.0 * 60.0 * 60.0 / 1000.0);`  to  `ra = ra * (24.0 * 60.0 * 60.0 / 1000000.0);`
- This matches the correct SI conversion where 1 W/m² = 0.0864 MJ/m²/day
The correction is applied consistently across the following functions:
- `mh_eto()`
- `mh_original()`
- `mh_samani()`
Fixes https://github.com/OSGeo/grass/issues/5520
> i.evapo.mh: fix radiation conversion factor

- raster/r.li/r.li.daemon/worker.c
- raster/r.li/r.li.edgedensity/edgedensity.c
Fix two new and one old issue in `r.li` closing potentially un-opened files.
> r.li: only close files that are opened

- .github/codeql/codeql-config.yml
- .github/labeler.yml
- .github/workflows/additional_checks.yml
- .github/workflows/cmake.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/gcc.yml
- .github/workflows/macos_distribute_app.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/pytest.yml
- .github/workflows/test-nix.yml
- .github/workflows/ubuntu.yml
- .markdownlint.yml
- .yamllint
- man/mkdocs/mkdocs.yml
- utils/release.yml
Simple changes that I've been continuously reverting for over a year each time I format the file with my IDE (for workflow files).
The formatting has its roots with the yaml language server, that uses "prettier" for actual parsing and formatting.
I've then applied to other yaml files.
The cmake workflow was using 4 spaces instead of 2 like our other workflows, so the changes seem bigger for this file.
> chore: Format yaml and workflow files

- general/g.region/main.c
- include/grass/defs/raster.h
- include/grass/defs/vector.h
- include/grass/gis.h
- lib/gis/mapset_msc.c
- lib/gis/parser_md_python.c
- lib/raster/mask_info.c
- lib/raster/raster_metadata.c
- lib/rst/interp_float/init2d.c
- raster/r.horizon/main.c
- raster/r.kappa/print_json.c
- raster/r.mask.status/main.c
- raster/r.out.gdal/attr.c
- raster/r.series/main.c
- raster/r.slope.aspect/main.c
- raster/r.sun/main.c
- raster/r.sun/sunradstruct.h
- raster/r.thin/thin_lines.c
- raster/r.volume/main.c
- vector/v.db.select/main.c
- vector/v.fill.holes/main.c
- vector/v.hull/chull.c
- vector/v.surf.rst/main.c
Always `#include <stdbool.h>` where `bool` is used.
For the same reason, revert (part of 1e0c11f526f64755f877957ce6c14b2159c3823f) definition of `TRUE` and `FALSE` (in gis.h) to `1` and `0`, in order to avoid the inclusion everywhere it may/should have been needed. In addition, starting with C23 `bool` is not an int, but a type of its own, making it not interchangeable with int.
Fixes #5585
> CQ: always include stdbool.h if bool is used in C code

- python/libgrass_interface_generator/README.md
- python/libgrass_interface_generator/ctypesgen/ctypedescs.py
This change is needed for C23 support, where _Bool is not necessarily defined by default.
See e.g., [GCC](https://gcc.gnu.org/onlinedocs/gcc/Boolean-Type.html):
> C23 added bool as the preferred name of the boolean type, but _Bool also remains a standard keyword in the language and is supported as such by GCC with -std=c23.
GCC 15 now [defaults](https://gcc.gnu.org/gcc-15/changes.html#c) to C23.
This patch is submitted upstream (https://github.com/ctypesgen/ctypesgen/pull/225).
> ctypesgen: Add 'bool' to ctypes type map, needed for C23

- man/mkdocs/grassdocs.css
The nav footer font color was set incorrectly to white when it should have been set as the secondary color (blue).
The change made the previous and next text visible.
> docs: Fixed mkdocs fg-footer color

- raster/r.latlong/tests/test_r_latlong.py
**Test Details for r.latlong**
Basic Latitude Test (test_latlong_lat):
- Checks that the output ASCII grid includes correct header details for north, south, east, west, rows, and columns.
- Ensures the generated grid represents proper latitude values derived from the row numbers (i.e., a 3x3 grid with values decreasing from north to south as 3, 2, 1).
Longitude Output Test (test_l_flag):
- Validates that using the -l flag properly instructs r.latlong to generate longitude-based values.
- Confirms that the header information remains accurate and that the grid data is correctly formatted, showing a increase in longitude values (0 to 2) across columns for each row.
> r.latlong: Add tests

- vector/v.cluster/testsuite/cluster_test.py
This PR introduces comprehensive testing for the v.cluster module after refining my initial approach. I've implemented robust validation for DBSCAN clustering, including parameter sensitivity tests for distance and min_points, 2D/3D handling with the -2 flag, and edge cases like minimal clusters and noise points. The tests now feature proper cleanup routines and resolve previous CI issues (like CRLF line endings)
> v.cluster: Add tests

- lib/vector/Vlib/snap.c
This pull request fixes issue identified by Coverity Scan (CID : 1262568, 1262569, 1262571, 1588935)
Used Vect_destroy_list(), G_free().
> lib/vector/Vlib: Fix Resource Leak Issue in snap.c

- python/grass/temporal/core.py
The problem is caused by #4805, where the psycopg2.Error is used, even when the package is not available.
I also removed try except for sqlite3 since it has been part of standard Python package since Python 2.5.
> grass.temporal: fix error handling

- general/g.region/main.c
Adjust the region before saving it. Before, setting rows= and cols= had no effect on the saved region.
Fixes #5625.
> g.region: fix save option behavior

- .github/workflows/documentation.yml
This allows to see the changes made in the PR even when on a fork. Otherwise, it is using the default branch without the changes (except for the workflow file itself).
> CI(docs): Remove repository input when checking-out grass core

- man/build.py
- man/parser_standard_options.py
There was another ResourceWarning error in manual generation that I solved after #5560. The unclosed files were defined in the argparse arguments with FileType type.
The argparse FileType argument type will be deprecated in Python 3.14. It does not properly close files if a subsequent error in another FileType argument occurs when parsing. The suggestion is to use context managers after parsing the arguments. The implementation of the changes is inspired by [a PR](https://github.com/python/cpython/pull/113649) doing the same in the CPython repo.
Other small changes included in (wasn't worth a separate PR):
- Removing `urlopen()`'s proxies argument. It was for the old interface. Default proxy handling is used now. It allowed correct type checking.
- Invalid None assignment to nothing in …
> man: Remove FileType argument types in parser standard options arguments

- raster/r.resamp.filter/main.c
In line 498:
_WARNING: Parallel processing disabled due to active make._
should be:
_WARNING: Parallel processing disabled due to active mask._
> r.resamp.filter: correct typo in warning message

- general/g.region/main.c
Follow up on #5627. temp_window is still used elsewhere, so it should not be removed completely.
> g.region: remove unnecessary temp_window variable

- include/Make/Doxyfile_arch_html.in
- include/Make/Doxyfile_arch_latex.in
- include/grass/gis.h
- include/grass/iostream/embuffer.h
- include/grass/iostream/imbuffer.h
- include/grass/vect/dig_macros.h
- include/grass/vect/dig_structs.h
> docs: fix typos in include

- lib/gis/parser_md.c
Some tools (modules) have defined `label` instead of `description` (eg. https://github.com/OSGeo/grass/blob/main/raster/r.relief/main.c#L109). Currently `G__usage_markdown() ` doesn't handle metadata correctly in this case:
```
r.relief --md-description | grep description
description: (null)
```
This bug also affects mkdocs-generated manual pages:
This PR solves it:
```
r.relief --md-description | grep description
description: Creates shaded relief map from an elevation map (DEM).
```
> libgis: G__usage_markdown() include tool label in metadata if defined

- gui/wxpython/gui_core/forms.py
The same was done at the end of both `if-else` condition branches. Running it just once reduces the places where we need to fix it if something goes wrong.
> CQ: gui_core.forms: avoid code duplicity of GrassGUIApp(task).MainLoop()

- raster/r.in.pdal/grasslidarfilter.h
- raster/r.in.pdal/r.in.pdal.html
- raster/r.in.pdal/r.in.pdal.md
- raster/r.in.xyz/r.in.xyz.html
- raster/r.in.xyz/r.in.xyz.md
- raster/r.mapcalc/r.mapcalc.html
- raster/r.mapcalc/r.mapcalc.md
- raster/r.mapcalc/r3.mapcalc.html
- raster/r.mapcalc/r3.mapcalc.md
- raster/r.mfilter/r.mfilter.html
- raster/r.neighbors/r.neighbors.html
- raster/r.neighbors/r.neighbors.md
- raster/r.out.gdal/main.c
- raster/r.out.png/r.out.png.html
- raster/r.out.png/r.out.png.md
- raster/r.out.vtk/writeascii.c
- raster/r.patch/r.patch.html
- raster/r.patch/r.patch.md
- raster/r.proj/r.proj.html
- raster/r.proj/r.proj.md
- raster/r.resamp.filter/r.resamp.filter.html
- raster/r.resamp.filter/r.resamp.filter.md
- raster/r.series/graphics_for_description.ipynb
- raster/r.series/r.series.html
- raster/r.series/r.series.md
References to GRASS GIS changed to GRASS for html and md files. for r.series, r.in.pdal, r.in.xyz,r.mfilter, r.out.png, r.patch, r.proj, r.resamp.filter.  r.out.gdal main.c had a reference to GRASS GIS instead of GRASS in he metadata written out.  r.out.vtk also had a reference to GRASS GIS writing out to the ascii file.
> doc: remove GIS from several raster tools' documentation

- vector/v.select/main.c
- vector/v.select/testsuite/test_v_select.py
Currently `v.select` doesn't create output vector map when no features found. This behaviour is not consistent with other GRASS tools as eg. `v.extract`. 
`v.extract` creates output regardless how many features found:
```
v.extract in=schools out=extract cat=0
v.info -t extract | grep point
points=0
```
Current behaviour -> no output vector map created:
```
v.select ainput=schools binput=roadsmajor out=select_output
v.info -t select_output | grep point
ERROR: Vector map <select_output> not found
```
New behaviour introduced by this PR is consistent with `v.extract` (output is created also when no features found):
```
v.select ainput=schools binput=roadsmajor out=select_output
v.info -t select_output | grep point
points=0
```
> v.select: create output also when no features found 

- vector/v.surf.rst/main.c
- vector/v.surf.rst/v.surf.rst.html
- vector/v.surf.rst/v.surf.rst.md
I've corrected the default parameters for smoothing and dmin to match the code and updated the documentation.
> v.surf.rst: Corrected defaults parameters and documentation

- gui/wxpython/gmodeler/model.py
- python/grass/script/task.py
This PR fixes regression caused by 3f98304d0d7bbc71727d07f3530370bcd7cdbbde:
Steps to reproduce:
1. create model with parameterized option (see attached [model.zip](https://github.com/user-attachments/files/20354205/model.zip))
2. run model
It fails with:
```py
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gmodeler/panels.py", line 966, in OnRunModel
self.model.Run(self._gconsole, self.OnModelDone, parent=self)
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gmodeler/model.py", line 668, in Run
GError(parent=parent, message="\n".join(err))
~~~~~~~~~^^^^^
TypeError: sequence item 0: expected str instance, list found
```
> wxGUI: avoid creating nested list of errors (Graphical modeler)

- cmake/find_scripts/FindLAPACKE.cmake
- msvc/lapacke.h
This PR defines a wrapper `lapacke.h` to define custom complex types for MSVC. Without it, `FindLAPACKE` fails.
See https://github.com/Reference-LAPACK/lapack/issues/683#issuecomment-1179338751
> CMake: Define custom complex types for MSVC LAPACKE

- locale/CMakeLists.txt
- man/CMakeLists.txt
Small quality of life PR here.
IDEs can make use of a folder structure when displaying cmake projects. Interfaces that don't support it keeps working normally.
See the short docs for the FOLDER property here: https://cmake.org/cmake/help/latest/prop_tgt/FOLDER.html
The same pattern was already used for other folders like lib, gui, scripts. I added them for locale and man, so that the targets aren't at the top level, like ALL_VECTOR_MODULES. See how it looks like in my VSCode extension
Extracted from #5643
> cmake: Group locale and man into folders for IDEs

- man/mkdocs/grassdocs.css
Addressing issue #5718 
I've added the grass mono font to the `md-code-font-family` variable correcting code block displays.
> docs: Added GRASS mono font to md-code-font-family

- general/g.proj/testsuite/test_g_proj.py
- gui/wxpython/location_wizard/wizard.py
- gui/wxpython/mapdisp/statusbar.py
- python/grass/jupyter/utils.py
- python/grass/temporal/stds_export.py
- python/grass/temporal/stds_import.py
- scripts/m.proj/m.proj.py
- scripts/r.buffer.lowmem/r.buffer.lowmem.py
- scripts/r.in.aster/r.in.aster.py
- scripts/r.in.srtm/r.in.srtm.py
- scripts/r.in.wms/wms_base.py
- scripts/r.tileset/r.tileset.py
- scripts/v.in.geonames/v.in.geonames.py
This PR gets rid of the warning (initially found when using the Jupyter Notebook) when in the g.proj module the 'j' is deprecated and will be removed in a future release. Instead, the format=proj4 style is used.
The change was applied in the whole GRASS repository, the occurrences were found using 
`grep -Irni 'flags="[^"]*j[^"]*"'`
The info about deprecation can be found here: https://grass.osgeo.org/grass-devel/manuals/g.proj.html .
> g.proj: upgrade to format=proj4 style text output

- general/g.proj/testsuite/test_g_proj.py
- gui/wxpython/gui_core/gselect.py
- gui/wxpython/timeline/frame.py
- python/grass/script/tests/grass_script_core_location_test.py
- scripts/r.import/r.import.py
- scripts/r.in.wms/wms_base.py
- scripts/r.reclass.area/r.reclass.area.py
- scripts/v.import/v.import.py
This PR gets rid of the warning when in the g.proj module the 'g' is deprecated and will be removed in a future release. Instead, the format=shell style is used.
The change was applied in the whole GRASS repository, the occurrences were replaced by
find . -type f -name ".py" -exec sed -i 's/"g.proj", flags="g"/"g.proj", flags="p", format="shell"/g' {} +
The info about deprecation can be found here: https://grass.osgeo.org/grass-devel/manuals/g.proj.html .
>  g.proj: upgrade to format=shell style text output

- general/g.proj/main.c
it does not mean the conventional GRASS format anymore; it is just the flag that is needed to print the info in the format specified by the format option
> docs: g.proj - update the meaning of -p

- general/g.proj/testsuite/test_g_proj.py
- gui/wxpython/core/ws.py
- scripts/r.in.wms/wms_drv.py
This PR gets rid of the warning when in the g.proj module the 'w' is deprecated and will be removed in a future release. Instead, the format=wkt style is used.
The change was applied in the whole GRASS repository, the occurrences were replaced by 
find . -type f -name "*.py" -exec sed -i 's/"g.proj", flags="wf"/"g.proj", flags="fp", format="wkt"/g' {} +
find . -type f -name "*.py" -exec sed -i 's/"g.proj", flags="w"/"g.proj", flags="p", format="wkt"/g' {} +
The info about deprecation can be found here: https://grass.osgeo.org/grass-devel/manuals/g.proj.html .
> g.proj: upgrade to format=wkt style text output

- raster/r.relief/main.c
`r.relief` is the only module in the main repo which doesn't have `description` defined.
> r.relief: module label changed to description

- python/libgrass_interface_generator/ctypesgen/libraryloader.py
This PR fixes:
```
CMake Error at C:/Users/hcho/usr/grass/grass/cmake/ctypesgen.cmake:72 (message):
C:/Users/hcho/usr/grass/grass/python/libgrass_interface_generator/run.py:
File "C:\Users\hcho\usr\grass\grass\python\libgrass_interface_generator\run.py", line 10, in <module>
import ctypesgen.main  # noqa: E402
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hcho\usr\grass\grass\python\libgrass_interface_generator\ctypesgen\__init__.py", line 57, in <module>
from . import processor
File "C:\Users\hcho\usr\grass\grass\python\libgrass_interface_generator\ctypesgen\processor\__init__.py", line 10, in <module> 
from .pipeline import process
File "C:\Users\hcho\usr\grass\grass\python\libgrass_interface_generator\ctypesgen\processor\pipeline.py", line 40, in <module> …
```
> CMake: Fix the parameter is incorrect: . error for MSVC

- gui/wxpython/gui_core/forms.py
Previously defined value for `where` option is not propageted.
Steps to reproduce:
1. Create model which contains a tool with a `where` option (see attached model [select.gxm.zip](https://github.com/user-attachments/files/20401553/select.gxm.zip))
2. Define `where` option
3. Close dialog
4. Re--open dialog
A `where` option is empty
The PR solves this bug:
> GUI: propagate previously defined where option value

- raster/r.univar/testsuite/test_r_univar.py
The precision used for testing was 6, which is very high. It is changed to 1e-10.
Some reference values are wrong in testing.
1.  Line 182: the number of cells is 8100 (from r.info).
2. Line 247, Line 248: mean = sum / n, 39204 / 162 = 242
> r.univar: Correct testing

- python/grass/temporal/c_libraries_interface.py
- python/grass/temporal/core.py
- python/grass/temporal/testsuite/test_mapset_change.py
This introduces the possibility of using the temporal framework and switching mapset within the same session.
This should address issue #629.
I created a specific test for this feature, and ran the other tgis tests locally.
> grass.temporal: allow change of mapset in a single script

- man/build_full_index.py
Currently miscellaneous tools  are missing in full index:
This PR adds this tools:
> docs: add miscellaneous tools to full index (markdown)

- utils/release.yml
Follow-up from https://github.com/OSGeo/grass/pull/5762.
After discussion, `locale:` should be an accepted title prefix recognized for classification in the changelog.
> checks: Allow "locale:" title prefix

- include/grass/gis.h
This PR fixes `M_PI_4` redefinition warnings for MSVC by using the same value as the system macro:
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math_defines.h(30,9): warning C4005: 'M_PI_4': macro redefinition [C:\Users\hcho\usr\grass\grass\build21\display\d.grid.vcxproj]
```
> MSVC: Use the same M_PI_4 value to avoid redefinition warnings

- raster/r.univar/r.univar_main.c
Fix an issue reported by valgrind.
> r.univar: OpenMP private variables must be initialized

- general/g.version/main.c
- include/grass/iostream/ami_stream.h
- raster/r.univar/stats.c
This PR fixes warnings about using `%lu` instead of `%zu` for `size_t` in `*printf`.
> build: Fix %lu *printf format string to %zu for size_t

- gui/wxpython/gui_core/forms.py
- gui/wxpython/gui_core/gselect.py
Currently when `map/input` option is changed than also all depending widgets (`layer`, `columns`, `where`) are updated. It includes also setting value to an empty string.
1. Launch ` v.db.select map=schools where="TAG = '001'" --ui`
2. Change `map` option
-> `where` option is removed
https://github.com/user-attachments/assets/456adaab-ebb1-4277-97dc-da9b2322b021
This PR changes current behaviour 
-> `where` option is kept
https://github.com/user-attachments/assets/dd5795b1-c990-45a0-bff1-ca508a91fe44
- keep decision to remove or update eg. `where` option on the user
- user may have multiple maps with the same column. When switching between maps, a `where` statement must be set again from the scratch (which is not desired in this case)
- solves #5759
> GUI: do not remove parameter value on dialog update event

- gui/wxpython/nviz/wxnviz.py
- python/grass/pygrass/vector/geometry.py
- python/grass/script/core.py
- python/grass/script/utils.py
- python/grass/temporal/core.py
I fixed all invalid admonitions (warning/notes boxes) in the docstrings. I searched for all instances where there were two dots followed by a letter, missing a space. I also found some in addons, I will report them too.
Note that it might not be enough to have all the syntax rendered correctly in the files python/grass/temporal/spatio_temporal_relationships.py (function: create_temporal_relation_sql_where_statement) and python/grass/temporal/core.py (function: init). However the rest of the changes are kinda big, as it is unindenting by one space, and other docstrings might need the same attentions. Keeping it for another time.
> docs: Fix reStructuredText admonitions syntax (notes, warnings, error boxes)

- general/CMakeLists.txt
- general/g.mapset/Makefile
- general/g.mapset/g.mapset.md
- general/g.mapset/main.c
- general/g.mapset/tests/conftest.py
- general/g.mapset/tests/g_mapset_test.py
Fixes: #5518 
This PR adds JSON support to the `g.mapset` module. The JSON output looks like:
1. `g.mapset -p format=json`
```json
{
"project": "nc_spm_08_grass7",
"mapset": "user1"
}
````
2. `g.mapset -l format=json`
```json
{
"project": "nc_spm_08_grass7",
"mapsets": ["landsat", "new", "PERMANENT", "user1"]
}
````
This PR includes the following changes:
1. Adds JSON support to `g.mapset` by introducing the `format` option to specify either `plain` or `json` output.
2. Adds corresponding tests for the change.
3. Updates the documentation to include a JSON output example and a Python example demonstrating JSON parsing.
> g.mapset: Add JSON support

- python/grass/jupyter/utils.py
- python/grass/script/db.py
- python/grass/temporal/abstract_dataset.py
- python/grass/temporal/abstract_map_dataset.py
- python/grass/temporal/abstract_space_time_dataset.py
- python/grass/temporal/base.py
- python/grass/temporal/core.py
- python/grass/temporal/metadata.py
- python/grass/temporal/space_time_datasets.py
- python/grass/temporal/spatial_extent.py
- python/grass/temporal/temporal_algebra.py
- python/grass/temporal/temporal_extent.py
With only this, the number of warnings down to 407 warnings (from 415).
The number of actual issues fixed is way more.
Before:
After:
I have lots and lots more to file later, my combined branch has 47 commits for now: https://github.com/echoix/grass/tree/docstrings-fix-syntax-1
> docs: Fix docstring syntax for return values

- doc/development/style_guide.md
- doc/examples/notebooks/parallelization_tutorial.ipynb
- python/grass/script/__init__.py
- python/grass/script/raster.py
- python/grass/script/tests/grass_script_raster_region_test.py
Similarly to MaskManager, this adds a context manager for temporary changes of computational region.
Example with explicit region parameters:
```python
>>> with gs.RegionManager(n=226000, s=222000, w=634000, e=638000):
...     gs.parse_command("r.univar", map="elevation", format="json")
```
Example matching a raster map's region:
```python
>>> with gs.RegionManager(raster="elevation"):
...     gs.run_command("r.slope.aspect", elevation="elevation", slope="slope")
```
Example using g.region:
```python
>>> with gs.RegionManager():
...     gs.run_command("g.region", n=226000, s=222000, w=634000, e=638000)
...     gs.parse_command("r.univar", map="elevation", format="json")
```
Example using set_region():
```python
>>> with gs.RegionManager() as manager:
...     manager.set_region(n=226000, …
```
> grass.script: new RegionManager context manager

- python/grass/gunittest/case.py
- python/grass/pydispatch/dispatcher.py
- python/grass/pygrass/gis/region.py
- python/grass/pygrass/messages/__init__.py
- python/grass/pygrass/modules/interface/module.py
- python/grass/pygrass/raster/segment.py
- python/grass/pygrass/vector/geometry.py
- python/grass/pygrass/vector/table.py
- python/grass/script/db.py
- python/grass/temporal/c_libraries_interface.py
- scripts/g.extension/g.extension.py
Makes use of admonitions for notes and warnings. I searched "note" and "warning" in .py files for candidates to better displaying the notes. I didn't find other candidates for "caution", "warn", "info",
The number of warnings does not change here.
This does not include the note admonition changes in pydispatch.saferef that is made in #5819, so it is independent of that PR.
Example before:
Example after:
Upgraded note to warning following the context and severity of the message conveyed
> docs: Convert docstrings to use note and warning admonitions

- python/grass/docs/Makefile
- python/grass/pydispatch/saferef.py
Since there were a couple of issues with the saferef docstrings, and really didn't look that great and the docstrings before wasn't rendered using the rich semantic features to convey meaning of the parts of code, I tuned this one a fair bit to practice myself. It was a nice challenge since the attributes to describe were dynamic and not collected by normal introspection (even static parsing would have had a hard time).
Now, it even renders anchors for these attributes, shows up in TOC, can be referenced with links (and used in other docstrings of the file), so the meaning is well conveyed. I also tried it out if some special members (like `__call__()`) were ever rendered if changing the settings. I needed to make sure the note was rendered correctly anyways.
Take note that the …
> docs: Adapt docstrings of pydispatch.saferef for good-looking Sphinx rendering

- doc/python_intro.md
- python/grass/docs/conf.py
- python/grass/docs/src/temporal_framework.rst
- python/grass/pygrass/modules/interface/module.py
- python/grass/pygrass/vector/__init__.py
- python/grass/pygrass/vector/find.py
- python/grass/pygrass/vector/geometry.py
- python/grass/script/core.py
- Enable rendering of TODO boxes (admonitions). Usually they are stripped out, but they seem to be part of the content more often then not, having them removed makes the docs not complete
- Other code blocks I had already fixed
- Using references to methods of a same class
- Use double backticks for parts of code that were interpreted as labels to something in reStructuredText, but didn't exist, so causing warnings (the underscores at the end have a meaning in reST). => Reducing warnings
I don't have much "real" other fixes queued up for docs after that. The rest isn't worth it for now
> docs: Render todo boxes, other code blocks formatting and label syntax

- general/g.region/g.region.md
- raster3d/raster3dintro.md
Add information in the docs about the differences between the 2D and 3D resolution.
See issue #5801.
I also took the opportunity to rename GRASS GIS to GRASS.
> doc: be more explicit about 2D vs 3D region resolution

- python/grass/exceptions/__init__.py
- python/grass/jupyter/interactivemap.py
- python/grass/jupyter/map.py
- python/grass/jupyter/map3d.py
- python/grass/jupyter/seriesmap.py
- python/grass/jupyter/timeseriesmap.py
- python/grass/pygrass/gis/region.py
- python/grass/pygrass/messages/__init__.py
- python/grass/pygrass/modules/interface/module.py
- python/grass/script/core.py
- python/grass/script/db.py
- python/grass/script/imagery.py
- python/grass/script/raster.py
- python/grass/script/raster3d.py
- python/grass/script/setup.py
- python/grass/script/utils.py
- python/grass/script/vector.py
- python/grass/temporal/abstract_dataset.py
- python/grass/temporal/gui_support.py
- python/grass/temporal/spatio_temporal_relationships.py
This is another round of making the formatting of code blocks either valid, better, or semantically better represented in example sections headers (that is, indented, but also represented inside the field list element in the HTML render, not just underneath).
It will probably be boring to review, not much interesting things to highlight with screenshots in this.
One place, `Region.get_bbox()` (in python/grass/pygrass/gis/region.py), I created more docstring contents (for the return description and return type), to align with the rest around it.
> docs: Adjust more code-blocks syntax and inside example sections in docstrings

- lib/gis/parser_md_python.c
In the generated Python examples the type was leaking to the code, but does not make sense syntactically. For strings, we simply say string in quotes by default (if key description is not available), but for ints and floats, there is no such value (we don't have an example value), so this generates zero in the example. This will be likely wrong value for many cases, but it isvalid and also something the user will likely change (and it is easy to change).
Generated r.buffer example:
```python
gs.run_command("r.buffer", input="name", output="name", distances=0.0)
```
> doc: Generate zero, not type in Python examples

- python/grass/app/data.py
- python/grass/docs/conf.py
- python/grass/script/core.py
- python/grass/script/raster.py
- python/grass/script/setup.py
By enabling the widely used intersphinx functionality, Sphinx is able to resolve types, exceptions, etc. and allows us to create cross-references to the docs of an external project, like the Python standard library.
For example, a `:raises OSError: ...` or `:raises ValueError: ...` in the docstrings are magically linked to the Python docs:
Before:
After, when hovering over the link:
Same thing for the base classes that come from NumPy:
Before:
After, when hovering over the link:
When using cross-refs, I opted to be explicit by using `:external:` followed by the domain and role, so looking like: ``:external:py:func:`sys.exit` ``. It then makes it easier to search for `:external:`, and there's less a surprise that Sphinx links to the python docs when not knowing about it. This comes in as …
> docs: Configure intersphinx to reference Python's and NumPy's docs

- gui/wxpython/iscatt/dialogs.py
- python/grass/grassdb/history.py
- python/grass/jupyter/interactivemap.py
- python/grass/pygrass/gis/region.py
- python/grass/pygrass/modules/grid/grid.py
- python/grass/pygrass/raster/__init__.py
- python/grass/pygrass/vector/basic.py
- python/grass/pygrass/vector/find.py
- python/grass/pygrass/vector/geometry.py
- python/grass/script/core.py
- python/grass/script/raster.py
- python/grass/script/raster3d.py
- python/grass/script/utils.py
- python/grass/temporal/base.py
- python/grass/temporal/core.py
- python/grass/temporal/stds_export.py
- python/grass/temporal/temporal_algebra.py
- python/grass/temporal/temporal_raster_base_algebra.py
I've batched here some queued commits that addresses various small warnings, or just to continue aligning the docstrings with other places.
Some of the fixes here seemed to have originated from copy-paste errors, and a few are real typos too.
Using admonitions (boxes) for "Attention: " rendered quite nice and colourful, so I kept it.
Escaping a trailing underscore in the parameter list is necessary as it was interpreted as a label, so then the parameters weren't matching the signature, when using some stricter warnings. And the backslash needs to be escaped too, as one is for python to keep the backslash, the second one to pass to sphinx/docutils.  So, `:param xxxx_: bla bla bla` into `:param xxxx\\_: bla bla bla`
When finding issues, I was doing searches on the repo to find other cases. …
> docs: Various docstring fixes related to parameter markup

- python/grass/pygrass/gis/region.py
- python/grass/pygrass/raster/__init__.py
- python/grass/pygrass/vector/basic.py
- python/grass/pygrass/vector/find.py
- python/grass/script/core.py
- python/grass/script/raster.py
- python/grass/script/raster3d.py
This PR changes some function names, class names, etc. to use cross-references when applicable. Mostly centered around grass.script.core (the main topic, I reviewed that file completely), but includes related changes when searching for other instances to apply the same changes.
This does not include cross-references to exceptions, as it will be bundled separately, there's some original work (new text) created in these, so I didn't want to mix them up.
> docs: Use more crossrefs in grass.script.core

- lib/gis/parser_md_python.c
The Python example counts on format option being there, so we need to add that even if it is not required.
This allows for empty and not required format in v.info in #5844.
> docs: Add format to example even when not required

- display/d.vect/d.vect.html
- display/d.vect/d.vect.md
In the Examples section of the documentation, there's an example where random elevation points are sampled with `r.random` to create a 3D vector layer. The example uses:
```
r.random input=elevation.10m n=5000 vector=random3d -d
```
It should use the `-z` flag, as per the [r.random](https://grass.osgeo.org/grass-devel/manuals/r.random.html) documentation. There is no option for the a "-d" flag so the current example ends with an error.
> d.vect: Fix typo in documentation example 

- general/g.mapset/g.mapset.md
- general/g.mapset/main.c
- general/g.mapset/tests/g_mapset_test.py
- general/g.mapsets/g.mapsets.md
- general/g.mapsets/main.c
- general/g.mapsets/tests/g_mapsets_list_format_test.py
The current outputs are marked as plain and may possibly change in the future. For now, only with major release for backwards compatibility reasons, but in the future, any release can change the plain outputs. Implementing a separate, stable, shell-script-style output is a bigger endeavor, so the documentation now recommends JSON only.
This also changes the description of the tools to clarify what they do, and improves descriptions of the tests.
> g.mapset, g.mapsets: Specify stability of the outputs

- vector/v.distance/main.c
- vector/v.distance/print.c
- vector/v.distance/testsuite/test_v_distance.py
- vector/v.distance/v.distance.md
Fixes: #5846 
This PR updates the JSON output format of `v.distance` module. The new format looks like:
```json
[
{
"from_cat": 1,
"to_cat": 112,
"dist": 0.1428123184481199,
"to_attr": "8,A"
},
{
"from_cat": 2,
"to_cat": 44,
"dist": 0.10232660032693719,
"to_attr": "9,A"
}
]
```
It also includes minor improvements to error handling and adds a pandas example for `v.distance`.
> v.distance: Update JSON format

- imagery/i.ortho.photo/i.ortho.init/testsuite/test_i_ortho_init.py
This PR adds a regression test suite for the `i.ortho.init` module, which is responsible for initializing or updating the camera exposure station file for ortho-rectification. These tests aim to ensure robust behavior of the module across input configurations.
- `test_create_camera_model_with_use_flag`: Validates full initialization of the camera model using all primary and standard deviation parameters, with the `-r` (use) flag. The test confirms that the module correctly creates a usable ortho camera model and stores all parameters with the expected precision, ensuring data consistency for subsequent ortho-rectification steps.
- `test_partial_update_of_parameters`: Checks the module's ability to partially update selected parameters without overwriting unrelated values. This ensures the …
> i.ortho.init: add test file

- imagery/CMakeLists.txt
- imagery/i.group/Makefile
- imagery/i.group/i.group.md
- imagery/i.group/main.c
- imagery/i.group/testsuite/test_i_group.py
Fixes: #5815 
This PR adds JSON output support to the `i.group` module.
1. Adds a `format` option with `plain`, `shell`, and `json` modes for output formatting.
2. Adds tests covering each of the new formats.
3. Updates the documentation with a JSON output example and a Python example demonstrating JSON parsing.
**With `-l` flag:**
```json
[
"lsat7_2000_10@PERMANENT",
"lsat7_2000_20@PERMANENT",
"lsat7_2000_30@PERMANENT"
]
```
**With `-s` flag:**
```json
[
"vis_bands"
]
```
> i.group: Add JSON support

- raster/r.stats/raw_stats.c
Ref: https://github.com/OSGeo/grass/pull/5892#issuecomment-2977188565
This fixes the issue of the uninitialized `window` variable by ensuring it is set and used only when `with_coordinates` is enabled, and not when `format == JSON`.
> r.stats: fix uninitialised window value

- python/grass/script/core.py
A certain situation on Windows described in #5717 produces 'OSError: Cannot find the executable g.message' which is missing the original message. While such message is an indication of a deeper issue, the traceback misses the original message. This fallback approach show the message as the function was asked to do even when the subprocess had issues. It attaches the exception which may be confusing, but also may be quite helpful to understand the overall situation (which may not be related to the message itself).
> grass.script: Fallback to print when g.message fails

- imagery/i.gensigset/testsuite/test_i_gensigset.py
This PR introduces a regression test suite for the `i.gensigset` module, designed to validate the statistical structure of the generated `.sig` files and verify the behavior of the `maxsig` parameter under different configurations.
* **`test_basic_signature_generation`**
Ensures that a `.sig` file is correctly generated for a synthetic training map and that each signature includes well-formed mean vectors and statistically sound values.
* **`test_maxsig_parameter`**
Verifies that increasing the `maxsig` parameter results in an equal or greater number of detected classes and subsignatures. Confirms the expected behavior of the Gaussian mixture model’s flexibility.
* **`test_minimal_maxsig`**
Evaluates module behavior when `maxsig=1`, enforcing at most one subsignature per class. Ensures …
> i.gensigset: add test file

- python/grass/script/core.py
Changing the current working directory to create the files might have been inherited from a shell workflow, but it is not needed to create the files, and it just complicates the code. Using pathlib for everything, not a mix of os.mkdir and Path.mkdir.
> grass.script: Do not change dir to create XY project

- general/g.list/tests/conftest.py
- python/grass/script/core.py
To get a debug level Python code calls debug_level function which in turn needs to call g.gisenv because the debug level is stored in GRASS gisenv variable (and not as a system environment variable). For call to g.gisenv, one needs to have a session (GISRC) set up, so env is needed when it is only a local one (and not os.environ).
Experimentally, this also removes the monkeypatch fixture from the recently added test for g.list which, without the monkeypatch, failed on Windows with GISRC missing from g.gisenv indicating that os.environ was set up with the runtime (PATH etc.), but didn't have an active session (GISRC etc.). This should pass the correct local environment through env all the way to g.gisenv. (Additionally, the fixture scope is changed to module, so that it is created only …
> grass.script: Pass env to debug_level

- man/mkdocs/grassdocs.css
- man/mkdocs/mkdocs.yml
Improved styling of the search suggestions. The default style used an offset on the suggested text that made the suggestion harder to read, so I reduced the offset to improve the readability of the suggested text.
I also added in the ability to share a search by clicking the share button in the search box. Look at the **New Styling** example to see the implementation (top right corner next to the X).
> docs: Improved styling of search suggestion and added search sharing

- vector/v.to.db/report.c
- vector/v.to.db/testsuite/test_v_to_db.py
- vector/v.to.db/v.to.db.md
Fixes: #5711 
This PR updates the JSON output format of the `v.to.db` module. The new format looks like this:
```json
{
"units":{
"length":"meters"
},
"totals":{
"length":10426.657857419743
},
"records":[
{
"category":1,
"length":4554.943058982206
},
{
"category":2,
"length":5871.714798437538
}
]
}
```
Other changes include:
- The totals and units keys will appear every time. However, they’ll be equal to `{}` if they don’t apply.
- Updated tests for the change.
- Added a Python example in the documentation for parsing JSON output.
> v.to.db: Update JSON format

- python/grass/script/tests/grass_script_run_command_test.py
This should fix currently failing CI, because 21e8ebb got merged but used outdated g.region json that got merged just before it.
> tests: Fix tests after changing g.region json

- imagery/i.rectify/testsuite/test_i_rectify.py
This PR introduces a comprehensive regression test suite for the `i.rectify` module in GRASS. The tests cover the core rectification workflows, including affine and polynomial transformations, flag-specific behaviors, and region/resolution control. 
- **`test_affine_rectification`**
* Verifies a first-order (affine) polynomial transformation using `cubic` interpolation.
* Ensures that spatial transformation and pixel values remain consistent with expected statistics.
- **`test_polynomial_order2_rectification`**
* Validates 2nd-order polynomial transformation using `linear` interpolation.
* Tests numerical stability and interpolation accuracy when extending beyond affine geometry.
- **`test_polynomial_order3_rectification`**
* Verifies 3rd-order polynomial transformation with `lanczos` …
> i.rectify: add test file

- imagery/i.eb.soilheatflux/testsuite/test_i_eb_soilheatflux.py
This PR introduces regression test suite for the `i.eb.soilheatflux` module. The suite validates both numerical consistency and functional correctness across different operating conditions.
- `test_module_statistics`: It verifies that the output from `i.eb.soilheatflux` matches expected statistical properties. This catches unintentional changes in the computational logic due to internal formula changes or numerical instability.
- `test_heatflux_decreases_with_high_ndvi`: Test ensures that soil heat flux decreases with higher NDVI, which simulates vegetated surfaces. It validates the theoretical relationship in the model and confirms its responsiveness to input vegetation conditions.
- `test_heatflux_increases_with_time`: Test checks that soil heat flux is higher at solar noon compared to …
> i.eb.soilheatflux: add test file

- general/g.mapset/tests/conftest.py
- general/g.mapset/tests/g_mapset_test.py
- general/g.mapsets/tests/conftest.py
- general/g.mapsets/tests/g_mapsets_list_format_test.py
- python/grass/script/setup.py
- python/grass/script/tests/grass_script_core_get_commands.py
In clear cases, pass a copy of os.environ to grass.script.setup.init instead of modifying the os.environ (and modifying it for all following tests).
There are couple complex cases which are not covered here (global/subprocess tests of grass.script.init, GridModule, grass.jupyter).
> tests: Use more env for session isolation

- imagery/i.eb.eta/testsuite/test_i_eb_eta.py
- imagery/i.eb.netrad/testsuite/test_i_eb_netrad.py
- imagery/i.evapo.mh/testsuite/test_i_evapo_mh.py
- imagery/i.evapo.pm/testsuite/test_i_evapo_pm.py
- imagery/i.evapo.pt/testsuite/test_i_evapo_pt.py
- imagery/i.evapo.time/testsuite/test_i_evapo_time.py
- raster/r.univar/globals.h
- raster/r.univar/r.univar.md
- raster/r.univar/r.univar_main.c
- raster/r.univar/r3.univar_main.c
- raster/r.univar/stats.c
- raster/r.univar/testsuite/test_r_univar.py
Fixes: #5824 
This PR includes the following changes:
* Adds `format = shell` option; the `-g` flag is now deprecated.
* Adds `format = csv` option; the `-t` flag is now deprecated.
* The default separator for all formats is `| (pipe)`, unless `format=csv` is specified in that case, it will be a `comma`.
* Added tests and updated the documentation.
> r.univar: Add shell and CSV format

- raster/r.mapcalc/r.mapcalc.html
- raster/r.mapcalc/r.mapcalc.md
This pull request address issue #5975 by replacing flag -r with flag -s in [r.mapcalc's](https://grass.osgeo.org/grass-stable/manuals/r.mapcalc.html) manual page. Edited both html and markdown manual pages.
> r.mapcalc: fixed flag typo

- msvc/fcntl.h
This PR fixes a comment about non-existing files (merged into `msvc/fcntl.c` previously).
> MSVC: Fix comment in msvc/fcntl.h

- raster/r.mapcalc/r.mapcalc.md
- raster/r.mapcalc/r3.mapcalc.md
The automated transition to MkDocs rendered the operators, functions, and data types sections as shell code blocks, but they better suited as Markdown tables. I've updated the docs for r.mapcalc and r3.mapcalc. 
```sh
Operator   Meaning                    Type        Precedence
--------------------------------------------------------------
-          negation                   Arithmetic  12
~          one's complement           Bitwise     12
!          not                        Logical     12
^          exponentiation             Arithmetic  11
%          modulus                    Arithmetic  10
/          division                   Arithmetic  10
*          multiplication             Arithmetic  10
+          addition                   Arithmetic   9
-          subtraction …
```
> docs: Converted mapcalc operators, functions, and data types references to tables

- raster/r.regression.line/testsuite/test_rregression_line.py
ref: #5950 
This PR adds a regression test suite for the `r.regression.line` module. These tests are intended to serve as regression checks for upcoming PRs that add JSON support to `r.regression.line`.
> r.regression.line: Add test file

- lib/vector/Vlib/simple_features.c
This pull request fixes issue identified by Coverity Scan (CID : 1208109)
> lib/vector/Vlib: Fix Resource Leak Issue in simple_features.c

- imagery/i.eb.hsebal01/main.c
This PR fixes issues mentioned in #6003 that prevent the module from working properly when manual wet/dry pixels are specified:
- **Missing initialization of raster arrays:**
- In manual mode, `d_t0dem`, `d_z0m`, and `d_eact` arrays were never populated before iteration loops. This caused all pixel values to remain zero, leading to invalid `d_rah_dry` and `d_roh_dry`, `NaN` results, and premature failure with `Delta T Convergence failed`.
- Fix: Added this loop after raster input buffers are allocated:
```c
/* Always read t0dem, z0m, and eact into the arrays */
for (row = 0; row < nrows; row++) {
Rast_get_d_row(infd_t0dem, inrast_t0dem, row);
Rast_get_d_row(infd_z0m, inrast_z0m, row);
Rast_get_d_row(infd_eact, inrast_eact, row);
for (col = 0; col < ncols; col++) {
d_t0dem[row][col] = …
```
> i.eb.hsebal01: fix manual pixel handling

- raster/r.out.ppm/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1208236)
Used G_strlcpy() and G_strlcat() to fix this issue.
For G_strlcat(), added a return value check with G_fatal_error() instead of silencing it with (void) (not sure whether it would fit within 1000 characters), even though the buffer ofile is 1000 bytes wide.
> r.out.ppm: Fix buffer issues in main.c

- raster/CMakeLists.txt
- raster/r.stats.quantile/Makefile
- raster/r.stats.quantile/main.c
- raster/r.stats.quantile/r.stats.quantile.md
- raster/r.stats.quantile/testsuite/test_r_stats_quantile.py
Fixes: #5951 
This PR adds JSON support to the `r.stats.quantile` module. The JSON output looks like:
```json
[
{
"category": 27511,
"percentiles": [
{
"percentile": 50,
"value": 139.62598419189453
}
]
},
{
"category": 27513,
"percentiles": [
{
"percentile": 50,
"value": 143.7049102783203
}
]
},
{
"category": 27518,
"percentiles": [
{
"percentile": 50,
"value": 122.53437805175781
}
]
}
]
```
This PR includes the following changes:
1. Adds a `format` option with `plain`, `csv`, and `json` modes for output formatting.
2. Adds `format = csv` option; the `-t` flag is now deprecated.
3. If no separator is specified, the default is `:`; If the format is `CSV`, the separator is a `comma`.
4. Adds tests covering each of the new formats.
5. Adds a Python example to the documentation for parsing …
> r.stats.quantile: Add JSON support

- raster/r.kappa/stats.c
This pull request fixes issue identified by Coverity Scan ( CID : 1207210)
The warning was caused by an unchecked return value from the remove() function, which may fail and return a non-zero error code. In this fix, the return value of remove() is explicitly checked, and a warning is logged if the file removal fails. This follows a more defensive programming approach.
An alternative fix would have been to suppress the warning using a (void) cast, since the program exits immediately afterward via G_fatal_error().
> r.kappa: Fix unchecked return value from library in stats.c

- db/drivers/dbf/dbfexe.c
- db/drivers/dbf/table.c
This pull request fixes issue identified by Coverity Scan (CID : 1208551, 1208571, 1208572, 1208573, 1208574, 1208575, 1208577)
> db.drivers/dbf: Fix uninitialized scalar variable

- general/g.findfile/main.c
- general/g.findfile/tests/test_g_findfile.py
- python/grass/script/core.py
g.findfile didn't take raster/raster_3d/region, even though g.findfile -l lists them. This PR fixes that.
Also adds a new -t flag similarly to r.mask.status to get the error code without printing the results. In the future, without -t it should always return success.
> g.findfile: use element aliases

- vector/v.label.sa/font.c
- vector/v.label.sa/labels.c
This pull request fixes issue identified by Coverity Scan(CID : 1415681, 1415703, 1415745, 1415754)
Used Vect_destroy_field_info(), G_free(), Vect_destroy_list() to fix this issue
> v.label.sa: Fix Resource Leak issue

- lib/vector/Vlib/read.c
This Pull Request fixes issue identified by Coverity Scan (CID : 1208043, 1208044)
Used G_free() to fix this issue
> lib/vector/Vlib: Fix Resource Leak Issue in read.c

- scripts/i.colors.enhance/testsuite/test_i_colors_enhance.py
This PR introduces a regression and property-based test suite for the `i.colors.enhance` module in GRASS. The tests are designed to validate the correctness and reproducibility of color enhancement operations under various input scenarios and to enforce key behavioral constraints documented for this module.
* **`test_default_enhancement_applies_new_colors`**: Verifies that the default enhancement workflow replaces the initial `grey255` color table, confirming that color rules are applied as expected.
* **`test_full_range_flag_sets_grey`**: Checks that using the `-f` (full-range) flag produces a standard grey gradient ranging from black (`0:0:0`) to white (`255:255:255`), enforcing correct fallback behavior.
* **`test_reset_flag_restores_grey255`**: Confirms that the `-r` (reset) flag …
> i.colors.enhance: add test file

- general/g.ppmtopng/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1207235)
added a check to fgetc()
> g.ppmtopng: Fix unchecked return value in main.c

- db/db.connect/testsuite/test_db_connect.py
ref: #6009 
This PR adds a regression test suite for the `db.connect` module. These tests are intended to serve as regression checks for upcoming PRs that add JSON support to `db.connect`.
> db.connect: Add test file

- raster/r.volume/main.c
- raster/r.volume/r.volume.md
This addresses a problem with the new p flag of r.volume - it renders incorrectly (https://grass.osgeo.org/grass-devel/manuals/r.volume.html).
It also removes a fatal error, currently that condition will never happen and I don't think we need to enforce that condition anyway.
Also fixes documentation by adding the -p flag.
> r.volume: fix -p flag behavior

- scripts/i.tasscap/testsuite/test_i_tasscap.py
This PR introduces a regression test suite for the `i.tasscap` GRASS module. The tests are designed to validate the correctness of Tasseled Cap transformations across multiple supported satellite sensors under synthetic and predictable conditions.
**Tests Included:**
* **`test_landsat5_tm`**: Validates output for Landsat 5 TM using constant-value rasters. Confirms that all four Tasseled Cap components (Brightness, Greenness, Wetness, and Haze) are computed correctly, including use of the additive constant in the coefficients.
* **`test_modis`**: Tests the MODIS 7-band configuration, which omits the additive constant. Ensures that the transformation logic for `calc1bands7` is correctly implemented and produces mathematically expected output values.
* **`test_sentinel2`**: Verifies the …
> i.tasscap: add test file

- .gitignore
After comparing the .gitignore files from the main grass repo and the addons repo, I carried over some relevant exclusions here, notably the *.tmp.html exclusions, the whole point of this PR.
It is related to https://github.com/OSGeo/grass-addons/pull/1441, but in the other direction
> chore: Update .gitignore to include some changes from grass-addons

- .gitignore
Follow-up from https://github.com/OSGeo/grass/pull/6090, analogous to https://github.com/OSGeo/grass-addons/pull/1442.
I noticed when building that there are now (since a couple of months) `*.tmp.md` files used when generating markdown docs, just like html docs were doing before.
This PR adds this pattern too to the .gitignore file.
> chore: Add *.tmp.md to .gitignore to exclude temporary markdown files

- python/grass/temporal/ply/lex.py
Since #5942 was last updated, we have changed the Additionnal Checks workflow, and the vendored copy of ply hadn't run with these new checks. There's one line with remaining trailing whitespace, so I'm just trimming it out here. So, this will clear the errors we see on main for all other PRs.
> CQ: Trim one trailing whitespace in python/grass/temporal/ply/lex.py

- include/Make/Doxyfile_arch_html.in
- include/Make/Doxyfile_arch_latex.in
Upgrades the doxygen configuration files to doxygen 1.9.1, the version currently used in the server that publishes the programming8 manual.
From https://www.doxygen.nl/manual/doxygen_usage.html:
> If you have a configuration file generated with an older version of Doxygen, you can upgrade it to the current version by running Doxygen with the -u option.
> ```shell
> doxygen -u <config_file>
> ```
> All configuration settings in the original configuration file will be copied to the new configuration file. Any new options will have their default value. Note that comments that you may have added in the original configuration file will be lost.
Here are  the messages logged in the console during the conversion:
```console
$ doxygen -u include/Make/Doxyfile_arch_html.in
warning: Tag 'TCL_SUBST' …
```
> man: Upgrade Doxyfile config files with doxygen 1.9.1

- lib/calc/xmedian.c
- lib/calc/xmode.c
- lib/calc/xnmedian.c
- lib/calc/xnmode.c
- raster/r.mapcalc/testsuite/test_median_mode.py
This is an attempt to get rid of static variables from the r.mapcalc functions for mode and median. The static variables were there I assume to not allocate for every row, but it complicates parallelization, see #5742. Since the size of the array is typically very small (the number of arguments of the median() or mode() function, can be raster or number), it will use array on stack and allocate only for larger sizes. 
I am not a C expert, but hopefully this makes sense.
> r.mapcalc: remove static variables from mode and median to fix parallelization

- .github/workflows/documentation.yml
After having explored Doxygen a bit last week for potential improvements and upgrades, I asked @neteler last week to send me a snapshot of the doxygen-generated docs that are set up and published on the server. I wanted to have a true baseline of what the documentation workflow on the server was doing, in order to safely compare any improvements, such as upgrading the doxygen version to benefit from the numerous improvements in the past years, which aren't available in a distro's repos, especially an LTS version.
This PR does exactly this: Builds the doxygen docs in CI (previously never built in CI), and uploads an artifact that can be inspected and compared. The configure flags were changed to disable features with `--with-FEATURE=no` instead of `--without-FEATURE` or removing the line …
> CI(docs): Generate Programmer's Manual with Doxygen in CI

- python/grass/app/runtime.py
Use the same practice as elsewhere and hide os.environ inside the function using None as the default value in the function signature.
Fixes leaking of env vars into doc.
Fixes #6089
> grass.app: Use None as default value, hide os.environ

- lib/vector/Vlib/dbcolumns.c
This pull request fixes issue identified by coverity scan (CID : 1207742, 1207743, 1207745, 1207746, 1207748, 1207749)
Used `Vect_destroy_field_info( ); db_close_database_shutdown_driver( );` to fix this issue.
> lib/vector/Vlib: Fix Resource Leak Issue in dbcolumns.c

- imagery/i.cca/main.c
- imagery/i.cca/stats.c
- imagery/i.cca/testsuite/test_i_cca.py
- imagery/i.cca/transform.c
This PR resolves a segmentation fault and memory misalignment in the `i.cca` module. (https://github.com/OSGeo/grass/issues/5947)
- Corrected all loops and array accesses to use zero-based indexing.
- Replaced incorrect memory allocations sized by `nclass` with allocations correctly sized by `bands`.
- Fixed off-by-one output raster naming to preserve the original `<prefix>.1`, `<prefix>.2`, etc.
- Ensured symmetric covariance matrices by correctly including diagonal elements in the computation.
The changes were tested using the same reproduction steps outlined in the linked issue. The module now runs successfully and produces canonical component outputs without error. This fix brings `i.cca` in line with standard C indexing practices, preventing both runtime crashes and silent memory …
> i.cca: fix indexing, buffer size issues and matrix computation

- .github/workflows/label.yml
I noticed when using my second fork of grass (through an organisation), that the labeler workflow doesn't work anymore.
The error shown in the CI logs is:
```
Error: HttpError: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
Error: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
```
The `pull-requests: write` permission doesn't seem to allow creating labels anymore, the `issues: write` is also needed.
As discussed in https://github.com/googleapis/release-please-action/issues/1105#issuecomment-2780292262 and https://github.com/googleapis/release-please-action/issues/1105#issuecomment-2850640688, there seems to be a change and …
> CI: Fix labeler permissions to create labels

- python/grass/gunittest/case.py
Since the lines were introduced, it always had that unexistant function. I made a search in the git log, and there's only one commit where the count of `_compute_xor_vectors` occurences change. So I assume it was meant to be `_compute_vector_xor`, in the same file.
The function `assertVectorsNoAreaDifference()` has no tests, and its declaration is the only occurrence. It seems to be there to match the other types of `assert*No*Difference()` functions.
> grass.gunittest: Fix typo in function `TestCase.assertVectorsNoAreaDifference()` for `_compute_vector_xor`

- python/grass/tools/session_tools.py
This avoids conflict with name parameter passed in kwargs. Alternative name would be arg, but going with a more descriptive name.
I got a Pylint warning in #5878:
```text
python/grass/tools/session_tools.py:205:12: W1117: 'name' will be included in '**kwargs' since a positional-only parameter with this name already exists (kwarg-superseded-by-positional-arg)
```
It was triggered by:
```python
self.call(
"g.remove",
type="raster",
name=object_parameter_handler.temporary_rasters,
flags="f",
)
```
I tried to recreate the issue I got with a test, but I was not able to.
```python
def test_json_with_tool_name_and_tool_name_parameter(xy_dataset_session):
"""Check that using a tool name and a tool name parameter works
This tests for the case we decide to rename first parameter to *name*
which …
```
> grass.tools: Rename tool name parameter

- raster3d/r3.gwflow/testsuite/test_r3_gwflow.py
This PR introduces a regression test suite for the `r3.gwflow` module in GRASS, designed to validate numerical consistency, solver equivalence, and sensitivity to boundary and conductivity conditions.
* **`test_gwflow_default_solver`**
Validates the expected statistical output for a simple setup using the default `cg` solver. It ensures numerical stability and correctness of the default solver path, acting as a baseline.
* **`test_full_matrix_matches_sparse_close`**
Verifies that the sparse matrix (`cg`) and full matrix (`cholesky`, `-f`) solvers yield nearly identical numerical results. This protects against changes in underlying numerical behavior.
* **`test_gwflow_mixed_boundary_conditions`**
Tests the handling of mixed boundary statuses (`0`, `1`, and `2`) and ensures that results …
> r3.gwflow: add test file

- .github/workflows/documentation.yml
Follow-up of #6092.
I thought I had created the PR, but no, it was only on my fork.
This enables extra features in the configure step, so more parts of the code can be documented. The goal is to have as much optional features enabled, so that the possible values for example, what db drivers are allowed, can represent the full set of features in the docs.
In #6092, the goal was to have a baseline that matched what was on the server.
If the packages are not installed on the server that independently generates the docs, only the artifact in CI will have these extra function blocks and extra text. Soon it'll be needed to publish the artifact so we can use newer doxygen versions, but now it is still kept at 1.9.1 as the server.
> CI(docs): Enable bzlib, openmp, pthread, and readline support in build for doxygen docs

- lib/imagery/iscatt_core.c
This pull request fixes issue identified by Coverity Scan ( CID : 1208098, 1208099, 1208100, 1543965, 1543972, 1543985, 1543987, 1543988, 1543989)
> lib/imagery: Fix Resource Leak Issue in iscatt_core.c

- gui/wxpython/startup/locdownload.py
Update outdated URL to `gismentors.zip` project data.
Source: https://www.training.gismentors.cz/geodata/grass/
> wxGUI: fix URL of gismentors.zip data file

- lib/vector/Vlib/dangles.c
This pull request fixes issue identified by Coverity Scan (CID : 1207790, 1207791, 1207792)
Used Vect_destroy_line_struct(), Vect_destroy_list(), Vect_destroy_cats_struct() to fix this issue.
> lib/vector/Vlib: Fix Resource Leak Issue in dangles.c

- lib/vector/Vlib/buffer2.c
This pull request fixes issue identified by Coverity Scan (CID : 1208640, 1208641, 1208642, 1208645, 1208646)
> lib/vector/Vlib: Fix Uninitialized Variable issue in buffer2.c

- python/grass/script/core.py
The note at the end of [`sys.stdout`'s docs](https://docs.python.org/3/library/sys.html#sys.stdout) mentions that writing binary data to the standard streams should use the underlying binary buffer object. However, that file might be replaced by a file-like object that doesn't support the buffer attribute.
So, inspired by [the code example for `sys.displayhook`](https://docs.python.org/3.13/library/sys.html#sys.displayhook), use the binary buffer object if available or simply write the encoded text otherwise.
This solves multiple ResourceWarnings found in tests that could be traced back to this when enabling python tracemalloc as written in the warning messages. One of the ways is to set the env var `PYTHONTRACEMALLOC` to the number of frames to keep. So, `export PYTHONTRACEMALLOC=15` is …
> grass.gunittest: Solve ResourceWarning in gs.parser() coming from sys.stdout

- python/grass/script/core.py
Similar to #6198 and #6197, add a context manager for a very simple `call()` wrapper. The `Popen` instance was already not available for use anywhere else.
> grass.script.core: Use context manager for Popen call in call() function

- vector/v.class/main.c
- vector/v.class/tests/test_v_class.py
- vector/v.class/v.class.md
ref: #6136
This PR adds one more test case for the `v.class` module to cover all scenarios, ensuring that future changes, particularly the upcoming addition of JSON support, do not break existing behavior.
It also includes a fix for an out-of-bounds bug mentioned here: https://github.com/OSGeo/grass/issues/6136#issuecomment-3148203451
The fix sets the range for `nbclasses` to a minimum of 2 using a parser option.
Additionally, it contains a minor typo fix in the documentation.
> v.class: Add more test cases and fix out-of-bounds bug

- python/grass/gunittest/gmodules.py
- python/grass/gunittest/reporters.py
- python/grass/script/core.py
Similar to #6197, and another yet-to-file PR, context managers can, _and should_, be used with Popen.
This PR addresses the similar instances in gunittest code, the code I was working on closely today.
Maybe in the near future, we would get rid of the svn calls when doing tests, but I'm not finished investigating the impacts of it.
> grass.gunittest: Use context manager for Popen calls in gunittest

- python/grass/gunittest/invoker.py
- python/grass/gunittest/multirunner.py
The option `-t`, documented here: https://docs.python.org/2.7/using/cmdline.html#cmdoption-t, was used to issue a warning when spaces and tabs were used in a same file, in a way that makes it depend on the worth of a tab expressed in spaces. With `-tt`, it was an error instead.
This doesn't exist since Python 3, as it was always an error.
The comment also mentioned a Python 2-only `-Qwarn`, documented here: https://docs.python.org/2.7/using/cmdline.html#cmdoption-q, that was used to choose the type of division:
"warn: old division semantics with a warning for int/int and long/long"
This also doesn't make sense since Python 3 and that interpreter option doesn't exist in Python 3.
> grass.gunittest: Remove Python2-only `-tt` interpreter option

- python/grass/gunittest/Makefile
- python/grass/gunittest/case.py
- python/grass/gunittest/main.py
- python/grass/gunittest/result.py
- python/grass/gunittest/runner.py
- python/grass/gunittest/utils.py
Prepare classes from gunittest to use multiple inheritance and be able to subclass from unittest, that would allow removing any code that we don't override. But before this, sync the code with Python 3.9's unittest implementation's, so the code is more similar and easier to compare. There will be less diff to review, and allows us to see that some newer unittest code effectively still works well with our codebase.
So, apart from copying over code that was copied some time ago, some code that is in a file named "result.py" was moved there, to follow the unittest implementation:
https://github.com/python/cpython/blob/06fc882eac0e59220a7b8b127a1e7babe0055d45/Lib/unittest/result.py#L24-L39
Other useful code to see is:
https://github.com/python/cpython/blob/06fc882eac0e59220a7b8b127a1e7babe0055 …
> grass.gunittest: Sync with unittest from Python 3.9

- raster/r.mapcalc/evaluate.c
MSVC build fails with OpenMP error:
```
"C:\opt\grass\build\grass.sln" (default target) (1) ->
"C:\opt\grass\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\opt\grass\build\raster\ALL_RASTER_MODULES.vcxproj.metaproj" (default target) (306) ->
"C:\opt\grass\build\raster\r.mapcalc\r.mapcalc.vcxproj.metaproj" (default target) (391) ->
"C:\opt\grass\build\raster\r.mapcalc\r.mapcalc.vcxproj" (default target) (394) ->
(ClCompile target) -> 
C:\opt\grass\raster\r.mapcalc\evaluate.c(463,18): error C3015: initialization in OpenMP 'for' statement has improper form [C:\opt\grass\build\raster\r.mapcalc\r.mapcalc.vcxproj]
```
Moved variable declaration outside the OpenMP pragma directive to comply with OpenMP standards.
- Declared `int row;` before the `#pragma omp parallel for` …
> r.mapcalc: Fix OpenMP C3015 error in evaluate.c on MSVC

- lib/gis/error.c
This pull request fixes issue identified by Coverity Scan (CID : 1501254)
> lib/gis: Fix Uninitialized Variable Issue in error.c

- raster3d/r3.gwflow/main.c
This PR resolves a segmentation fault in the `r3.gwflow` module that occurs when the optional `sink` parameter is not provided. The issue was caused by unconditional dereferencing of `param.q->answer` and use of `data->q`, even when the `q` array was never allocated.
* **Memory Allocation**:
* Changed:
```c
N_alloc_gwflow_data3d(cols, rows, depths, 0, 0);
```
to:
```c
N_alloc_gwflow_data3d(cols, rows, depths, 1, 0);
```
to ensure `data->q` is always allocated.
* **Runtime Check**:
* Replaced the sink reading line:
```c
N_read_rast3d_to_array_3d(param.q->answer, data->q, param.mask->answer);
```
with:
```c
if (param.q->answer != NULL) {
N_read_rast3d_to_array_3d(param.q->answer, data->q, param.mask->answer);
N_convert_array_3d_null_to_zero(data->q);
} else {
G_message(_("No sink map …
```
> r3.gwflow: fix segmentation fault

- vector/v.category/main.c
- vector/v.category/testsuite/test_v_category.py
This simplifies v.category format=json option=layers from:
```json
{
"layers": [
1
]
}
```
to
```json
[
1
]
```
which is more consistent with the other options.
> v.category: return json array for layers option

- lib/vector/Vlib/color_read.c
Added a clause in the logic for choosing the color table. Now, if mapset is not current mapset, but the local vcolr2 table is not defined, GRASS will resort to using the color table in the original mapset.
Addresses #6225
> v.colors: fix colors returning to default when using another mapset

- raster/r.external/proj.c
- raster/r.in.gdal/proj.c
- scripts/r.in.wms/wms_base.py
- vector/v.external/proj.c
- vector/v.in.ogr/proj.c
We use both CRS and SRS in the documentation. There is more CRS than SRS, so this replaces the few occurences of SRS with CRS. In case of WMS, also mention SRS because the SRS/srs parameter is explicitly mentioned. In general, we can't avoid SRS because it is used a lot in the code, in GDAL, and at this point in tool parameters as well. This does not touch the cases where 'projection' is used to refer to CRS.
> doc: Use CRS instead of SRS

- python/grass/gunittest/case.py
- python/grass/gunittest/result.py
- python/grass/gunittest/runner.py
Python is one of the few languages that allows multiple inheritance. That means that even we override two classes, one of which is is the base class of another, and we want the second class to use both our overridden class and overridden base class: it is possible. That is the case in our gunittest code.
Python uses a MRO (method resolution order) to know from which class call the function in this case. This order ignores duplicate classes if it happens. Python will handle at runtime an error when instantiating the class if there is a cycle in the base classes that can’t exist (this isn’t our case here). The `super()` call is where it makes the sense the most in Python, in multiple inheritance situations.
This PR is a follow up of some of my previous PRs (like #6200) that synced some …
> grass.gunittest: Inherit more from unittest classes

- gui/wxpython/vdigit/dialogs.py
Fixing the following issue when editing categories in GUI digitizer:
```
File "/home/akratoc/dev/grass/grass_main/dist.x86_64-pc-
linux-gnu/gui/wxpython/vdigit/dialogs.py", line 461, in OnOK
self.OnApply(event)
File "/home/akratoc/dev/grass/grass_main/dist.x86_64-pc-
linux-gnu/gui/wxpython/vdigit/dialogs.py", line 404, in
OnApply
for fid in self.cats.keys():
RuntimeError
:
dictionary keys changed during iteration
```
> gui: fix editing categories in vdigit

- python/grass/script/raster.py
- python/grass/script/tests/grass_script_raster_mask_test.py
- python/grass/script/tests/grass_script_raster_region_test.py
Add methods to explicitly call activate/deactivate on Regionmanager, RegionManagerEnv and MaskManager:
```python
>>> manager = gs.RegionManager(raster="elevation")
>>> manager.activate()
>>> try:
...     gs.run_command("r.slope.aspect", elevation="elevation", slope="slope")
... finally:
...     manager.deactivate()
```
> grass.script: add Activate and Deactivate methods to RegionManager and MaskManager

- python/grass/exceptions/__init__.py
Add a __reduce__ method to CalledModuleError so that instances can be pickled and unpickled correctly. Without this, multiprocessing fails when trying to reconstruct the exception, raising:
```
TypeError: CalledModuleError.__init__() missing 3 required positional arguments
```
> grass.exceptions: make CalledModuleError pickleable for multiprocessing

- .github/workflows/additional_checks.yml
- .github/workflows/cmake.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverity.yml
- .github/workflows/create_release_draft.yml
- .github/workflows/docker.yml
- .github/workflows/documentation.yml
- .github/workflows/gcc.yml
- .github/workflows/macos.yml
- .github/workflows/macos_distribute_app.yml
- .github/workflows/osgeo4w.yml
- .github/workflows/periodic_update.yml
- .github/workflows/pytest.yml
- .github/workflows/python-code-quality.yml
- .github/workflows/super-linter.yml
- .github/workflows/test-nix.yml
- .github/workflows/titles.yml
- .github/workflows/ubuntu.yml
Analogous to https://github.com/OSGeo/grass-addons/pull/1473
Fixes zizmor warnings that are now included by default in super-linter (but not enabled here yet).
Persisting credentials is not needed, as we don't need to push commits made inside any of the workflows.
The only places where we actually do a commit and push, we do it though an action which seems to use the GITHUB_TOKEN instead.
> CI: Do not persist credentials on checkout when not needed

- vector/v.external.out/list.c
This pull request fixes issue identified by Coverity Scan (CID : 1207810)
> v.external.out: Fix Resource Leak Issue in list.c

- lib/gis/parser_md_cli.c
- lib/gis/parser_md_python.c
Some tools explicitly declare no default value (here v.out.ogr), messing up markdown:
Before:
After:
Now the "Default:" is not shown at all.
> docs: fix testing default value in parser

- vector/v.what/main.c
The description attribute was repeated, but it was supposed to be label. Introduced in #6252. Found by Coverity Scan.
> v.what: Fix label for -j with deprecated

- vector/v.out.ogr/export_areas_fast.c
- vector/v.out.ogr/testsuite/test_v_out_ogr.py
When exporting vector with no attribute table linked, v.out.ogr was crashing, there was a missing check when the new fast method was implemented. I didn't look too much into the code, I fixed it based on the `export_areas_multi` function.
Added test, it fails without this change.
> v.out.ogr: fix fast method with no attributes

- lib/vector/Vlib/ascii.c
- python/grass/gunittest/case.py
- python/grass/gunittest/testsuite/test_assertions_vect.py
This attempts to fix comparison of vector ascii files in testing. Currently r.centroids has been failing with:
```
FAIL: test_output (__main__.TestCentroids.test_output)
2025-08-25T17:20:36.8321804Z Test that centroids are expected output
2025-08-25T17:20:36.8322918Z ----------------------------------------------------------------------
2025-08-25T17:20:36.8323842Z Traceback (most recent call last):
2025-08-25T17:20:36.8324992Z   File "raster/r.centroids/testsuite/test_r_centroids.py", line 57, in test_output
2025-08-25T17:20:36.8325959Z     self.assertVectorEqualsAscii(
2025-08-25T17:20:36.8327064Z   File "etc/python/grass/gunittest/case.py", line 1208, in assertVectorEqualsAscii
2025-08-25T17:20:36.8328352Z     self.assertVectorAsciiEqualsVectorAscii(
2025-08-25T17:20:36.8329835Z   File …
```
> lib/vector: remove writing trailing spaces in ASCII format

- python/grass/jupyter/map.py
- python/grass/jupyter/tests/conftest.py
- python/grass/jupyter/tests/grass_jupyter_map_numpy_test.py
- python/grass/jupyter/tests/grass_jupyter_map_test.py
- python/grass/jupyter/testsuite/map_test.py
- python/grass/jupyter/utils.py
- python/grass/tools/support.py
- python/grass/tools/tests/grass_tools_tool_function_wrap_test.py
Uses Tools from grass.tools to run the underlying display tool. This allows NumPy arrays to be passed to display tools when used with grass.jupyter.Map. Small adjustments to automatic region handling were needed so that the arrays are ignored (and only raster names, i.e., strings, are used).
The Map objects already allow syntax similar to Tools in terms of access to tools as attributes. This migrates the attribute access handling to use the functionality from grass.tools.support and overall syncs the code to Tools. As a result, Map provides the same error messages and attribute completion as Tools. To achieve expected results with the limit for display tools only, the underlying class now supports an allowed prefix parameter which limits the tools to only those with the allowed prefix …
> grass.jupyter: Use grass.tools for running and attributes in Map

- python/grass/tools/support.py
- python/grass/tools/tests/grass_tools_session_tools_test.py
Previously, you needed to do:
```python
pd.DataFrame(tools.run("g.region", flags="p", format="json").json)
```
otherwise you get an error. Now this works:
```python
pd.DataFrame(tools.run("g.region", flags="p", format="json"))
```
Pandas looks for __iter__:
https://github.com/pandas-dev/pandas/blob/1feacde3b686f9fea02c440528fee1d8fb907da8/pandas/_libs/lib.pyx#L1299
> grass.tools: add __iter__ to result object to streamline reading into pandas dataframe

- mswindows/osgeo4w/setup.hint.tmpl
This PR updates the GRASS setup.hint.tmpl template to include dependencies for running Jupyter notebooks inside GRASS.
It adds the following packages to requires: section:
- python3-jupyterlab – provides the JupyterLab interface.
- python3-jupyter-server – the backend server for Jupyter notebooks.
- python3-ipykernel – allows Python code execution in notebooks.
- python3-ipython – interactive Python shell for notebook execution.
- python3-ipywidgets – supports interactive widgets in notebooks.
**Next steps:**
Once tested in daily builds, these dependencies will also need to be added to the official OSGeo4W build: https://github.com/jef-n/OSGeo4W/blob/master/src/grass/osgeo4w/package.sh
> Windows: Add Jupyter dependencies to GRASS daily builds

- gui/wxpython/main_window/frame.py
When closing workspace action is triggered via main window menu File -> Workspace -> Close. Fixes #6386.
> wxGUI/main_window: fix displaying save workspace dialog before close workspace action

- raster/r.gwflow/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1270269, 1270272, 1270275, 1270276, 1270278, 1270279)
CID : 1270269 is false positive i think because it is checked as NULL in the function before returning and G_fatal_error is used but still to silence the warning i used G_fatal_error again to check the return value. Ideally it won't reach the G_fatal_error where return value is checked but it will silence the warning.
> r.gwflow: Fix Dereference before Null Check issue in main.c

- vector/v.surf.idw/main.c
- vector/v.surf.idw/read_sites.c
This PR adds two messages to inform the user about
- which column is used for interpolation, and
- in case, which column lacks the required numeric type.
(in addition, a confusing code comment is updated)
> v.surf.idw: improve user messages

- raster/r.distance/report.c
This pull request fixes issue identified by Coverity Scan (CID : 1220034)
> r.distance: Fix Resource Leak Issue in report.c

- vector/v.segment/main.c
This pull request fixes issue identified by Coverity Scan (CID : 1207846)
Used Vect_destroy_cats_struct() to fix this issue.
> v.segment: Fix Resource Leak Issue in main.c

- lib/vector/Vlib/cats.c
This pull request fixes issue identified by Coverity Scan (CID : 1208157)
> lib/vector/Vlib: Fix Resource Leak issue

- .flake8
- .github/workflows/additional_checks.yml
- .pre-commit-config.yaml
- raster/r.geomorphon/r.geomorphon.html
This PR is a minimalistic flake8 settings backport to re-enable pre-commit and CI in relbranch84.
> CI: minimalistic flake8 backport to re-enable pre-commit and CI

- raster/r.fill.dir/dopolys.c
- raster/r.fill.dir/filldir.c
This pull request fixes issue identified by Coverity Scan (CID : 1207781, 1207920, 1207921)
For CID : 1207781  i don't think we need G_malloc as min is just holding the address, no need for buffer allocation.
> r.fill.dir: Fix Resource Leak Issue in dopolys.c and filldir.c

- vector/v.overlay/main.c
back [then](https://github.com/OSGeo/grass/commit/ee9579d97f51058afc28c8c5be99f65fd41d1404) support for SQL type text (unlimited varchar) was added to `v.overlay` and for reasons of backwards compatibility with dbf, columns of type "text" were converted to type "varchar(250)" which is not the same. The db drivers automatically convert text to varchar if text is not supported.
This should be regarded as a bug because column types should not be changed by modules when copying columns.
> v.overlay: preserve SQL type text

- include/grass/defs/raster.h
- lib/raster/mask_info.c
- lib/raster/reclass.c
Always pass stack-based buffers to Rast_mask_status and Rast_is_reclass.
This allows for consistency in resource handling.
Alternative solution to #6146.
> lib/raster: always pass stack-based buffers

- raster3d/r3.out.ascii/main.c
- raster3d/r3.out.v5d/main.c
r3.out.ascii/r3.out.v5d fail to compile with GCC-17. This PR attempts to fix the issue.
> r3.out.ascii/r3.out.v5d: Adjust for GCC-17

- raster/r.kappa/mask.c
- raster/r.reclass/reclass.c
- raster/r.report/header.c
- raster/r.report/maskinfo.c
- raster/r.report/prt_json.c
Address resource leaks in `r.kappa`, `r.reclass` and `r.report`, most of which were discovered in latest run of CoverityScan.
> r.kappa,r.reclass,r.report: address resource leaks

- .github/workflows/osgeo4w.yml
libtre-git is no longer available, so the build in CI fails, but libtre is, so using it should make the CI build work again.
Fixes #6463
> CI: Use released libtre, not libtre-git

- python/grass/script/task.py
The dialog for importing included input and output fields, even though they are explicitely blacklisted in the code. It was working on linux, but on windows the name included .py extension so it never passed the test:
Thanks @latb for bringing this to my attention.
> GUI: fix hiding input/output fields from import dialogs on Windows

- gui/wxpython/datacatalog/tree.py
This change is specifically done for Tangible Landscape [plugin](https://github.com/tangible-landscape/grass-tangible-landscape), I need to programatically disable processing watchdog events and restart again. It could be done in different places, this approach only removes the bindings, watchdog itself is still running. I didn't expose this anywhere in the GUI itself, I was not sure how useful that would be. If we want that, maybe an option in the context menu might be the least intrusive.
> GUI: add functions for disabling processing events about mapset content changes in datacatalog
